### ISSUE TITLE
Gemfile with source 'http://rubygems.org' cannot work

### ISSUE THREAD

**Issue by StanleyShen** [bundler/bundler#4648] opened 2016-06-06 03:38 UTC
hello, all

It seems recently gemfile with source "http://rubygems.org" cannot work any more?
If I change it to "https://rubygems.org" then it works well.

Does "http://rubygems.org" still support? Or we must to update gemfile to use "https://rubygems.org"?

```
source "http://rubygems.org"
gem "rspec"
```

Above is my gemfile, it works well before, but right now, it doesn't work and reports error
```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    URI::InvalidURIError: the scheme https does not accept registry part: app_servers (or bad hostname?)
      /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize'
      /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/http.rb:84:in `initialize'
      /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/common.rb:214:in `new'
      /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/common.rb:214:in `parse'
      /home/ubuntu/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/fetcher/downloader.rb:20:in `fetch'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/fetcher/dependency.rb:8:in `api_available?'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/fetcher.rb:143:in `block in use_api'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/fetcher.rb:143:in `reject!'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/fetcher.rb:143:in `use_api'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:330:in `select'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:330:in `api_fetchers'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:335:in `block in remote_specs'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/index.rb:9:in `build'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:334:in `remote_specs'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/source/rubygems.rb:81:in `specs'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/spec_set.rb:90:in `block in materialize'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `load'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global/bin/bundle:23:in `<main>'
source "https://rubygems.org"
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
      /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.3
    Ruby      1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
    GEM_HOME  /home/ubuntu/.rvm/gems/ruby-1.9.3-p551
    GEM_PATH  /home/ubuntu/.rvm/gems/ruby-1.9.3-p551:/home/ubuntu/.rvm/gems/ruby-1.9.3-p551@global
    RVM       1.26.11 (master)
source "http://rubygems.org"
    Git       1.7.9.5
    rubygems-bundler (1.4.4)
--- TEMPLATE END ----------------------------------------------------------------
```

**Comment by GGD** [comment] 2016-06-06 03:53
I had same issue as you and solved it by changing `source` from
```
source "http://rubygems.org"
```
to
```
source "https://rubygems.org"
```

**Comment by colby-swandale** [comment] 2016-06-06 04:24
Hi! This behavior has been fixed in a newer release, can you please update bundler to the latest version and report back if you have any troubles.

**Comment by StanleyShen** [comment] 2016-06-06 04:41
OK, thanks for information.
The strange thing is this version still works well last week or before, it just stops working today.

**Comment by brent-clintel** [comment] 2016-06-06 05:26
I can second this problem.  We are receive the exact same error message and this only started happening with the last few hours.  It was working fine at the start of the day.  No gems have been changed or been updated.

<pre>
Environment
    Bundler   1.9.9
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
    GEM_HOME  /rails_app/vendor/ruby/2.1.0
    GEM_PATH  
    Git       2.8.3

Bundler settings
    path
      Set for your local app (/rails_app/.bundle/config): "vendor"
    disable_shared_gems
      Set for your local app (/rails_app/.bundle/config): "1"
<pre>

**Comment by PixelTom** [comment] 2016-06-06 05:32
Switching from "http://rubygems.org" to "https://rubygems.org" is working for me until I update bundler.

**Comment by segiddins** [comment] 2016-06-06 05:32
@dwradcliffe could this be caused by recent infra changes?

**Comment by segiddins** [comment] 2016-06-06 05:32
@dwradcliffe could this be caused by recent infra changes?

**Comment by arnav90** [comment] 2016-06-06 05:58
As pointed out in [this tweet](https://twitter.com/ishiokakeiichi/status/739677723518328832), the problem appears to be with http://bundler.rubygems.org/api/v1/dependencies being redirected to https://app_server/api/v1/dependencies

https://bundler.rubygems.org/api/v1/dependencies works fine.

**Comment by kavinkr** [comment] 2016-06-06 06:45
Changing http://rubygems.org to https://rubygems.org fixed the issue for me too.

**Comment by paultung** [comment] 2016-06-06 09:08
I have some reason so I can't update the 'bundle' version, is there other way to reach 'http://rubygems.org'?

**Comment by vs4vijay** [comment] 2016-06-06 09:26
Same error, Switched to **https**. But is should work without **https**. Any changes on rubygems site?

**Comment by spalakaluri** [comment] 2016-06-06 10:12
I can't update the 'bundle' version and change to 'https', is there other way to reach 'http://rubygems.org'? Please suggest, I got struck-up in creating some customer releases.

**Comment by dwradcliffe** [comment] 2016-06-06 11:22
Yes this was caused by infrastructure changes/problems. It should be fixed now. Is there are reason any of you are using http? We strongly suggest you only use https.

**Closed** 2016-06-06 13:46 UTC
Labels: bug report

**Comment by paultung** [comment] 2016-06-07 02:28
When we access from China mainland to 'https' will encounter terrible slow speed even failed, if we change to 'http', it is no problem.

**Comment by allenzhao** [comment] 2016-06-07 02:29
@paultung You should consider some mirror service in China, such as [RubyChina's RubyGems Mirror](https://gems.ruby-china.org/)

**Comment by dwradcliffe** [comment] 2016-06-07 02:31
Ah yes I've heard that. 😞
