### ISSUE TITLE
Installation instructions are incorrect

### ISSUE THREAD

**Issue by aragnon** [bundler/bundler#4434] opened 2016-04-12 20:33 UTC
The instructions on your website are not valid. 

You claim the following:
```
Getting started with bundler is easy! Open a terminal window and run this command:

$ gem install bundler

```

However, reality disagrees with you:

```
gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
```

Annoying if reality doesn't match your fantasy, isn't it? 

I don't particularly care about some random person suggesting something; I just want you to fix the website, such that the instructions are actually correct. 

Alternatively, you can also state that bundler is abandonware and has no maintainers.

**Comment by indirect** [comment] 2016-04-12 20:35
This is a duplicate of #4433.

**Closed by indirect** 2016-04-12 20:35 UTC
