### ISSUE TITLE
loaderror cannot load such file 2.3/pg_ext

### ISSUE THREAD

**Issue by santey12** [bundler/bundler#4675] opened 2016-06-16 18:17 UTC
loaderror cannot load such file 2.3/pg_ext
![pg](https://cloud.githubusercontent.com/assets/18305464/16128028/0b94cd7a-3410-11e6-9dfe-9573e2e6ef10.jpg)

**Comment by colby-swandale** [comment] 2016-06-17 00:09
Hi! it looks like you're missing the Postgresql libraries needed for the gem to be installed on your machine and not an issue with Bundler itself. @indirect @segiddins @LynnCo can we close this?

**Closed** 2016-06-17 00:44 UTC

**Comment by santey12** [comment] 2016-06-17 04:45
Hey. And how to do it? I reinstalled using the "gem install --pg".

**Comment by colby-swandale** [comment] 2016-06-17 04:57
I don't use windows myself, so i have no experience but I suggest following the supplied [README-windows](https://bitbucket.org/ged/ruby-pg/src/e61a06f1f5ed1006563b731ee3dc1e10f426d6cf/README-Windows.rdoc?at=default&fileviewer=file-view-default)

**Comment by kaiomagalhaes** [comment] 2017-01-11 09:06
I am also facing this issue on ruby 2.3

/share/vendor/bundle/ruby/2.3.0/gems/pg-0.19.0/lib/pg.rb:4:in `require': libruby.so.2.3: cannot open shared object file: No such file or directory - /share/vendor/bundle/ruby/2.3.0/gems/pg-0.19.0/lib/pg_ext.so (LoadError)

**Comment by colby-swandale** [comment] 2017-01-11 09:26
@kaiomagalhaes it appears you're are missing the PostgreSQL headers. Make sure that the PostgreSQL headers are installed and if required use `bundle config` to set the correct location of `pg_exst.so`

**Comment by kaiomagalhaes** [comment] 2017-01-11 14:16
@colby-swandale the problem is that I'm using it inside a docker container and the error only appears on prod. So my container doesn't start because of it and I have no way to enter into it =/

**Comment by hasanen** [comment] 2017-01-11 18:16
> it inside a docker container and the error only appears on prod

You're using same docker image in development and production, right? Check that the image has the headers for postgres like @colby-swandale said. Those needs to be installed with the platform's package manager, not with bundler/rubygems.
