### ISSUE TITLE
Wrong 'lower' version of gem resolved

### ISSUE THREAD

**Issue by Confusion** [bundler/bundler#4766] opened 2016-07-07 07:43 UTC
What you're trying to accomplish: update a gem in the bundle, after a new gem was available on the gemserver 
The command you ran: `bundle update`
What you expected to happen: the gem is upgraded to the new version
What actually happened: the gem was downgraded to an older version
Bundle-env gist: https://gist.github.com/Confusion/94aba43cafef678012da581d537ad415

Short version: 
I'm seeing a case where bundler essentially comes up with gem version 1.2.3, even though the Gemfile.lock was at 1.2.4 and the only change is that 1.2.5 has become available. 

Complete version:
We have an internal gemserver where gems are versioned using major.minor.date.time, so gems are named e.g. `our-gem-1.3.20160415.170325`.

We have a Gemfile with a declaration

```
  gem 'our-gem', '~> 1.3'
```

For purposes of this issue report, I've stripped all other dependencies: this is the only remaining dependency. 

Initially the project depended on `our-gem-1.3.20160620.115531`. A new gem was made available to our gemserver, named `our-gem-1.3.20160706.171350`.

To my surprise, running `bundle update` resulted in

```
  Installing our-gem 1.3.20160415.170325 (was 1.3.20160620.115531)
```

Some experimentation results in the following additional observations: if I change the dependency to

```
  gem 'our-gem', '>= 1.3.20160701'
```

and rerun `bundle update` then `our-gem-1.3.20160706.171350` is used.

If I then change the Gemfile to

```
  gem 'our-gem', '~> 1.3.20160701'
```

and rerun `bundle update`, then that gem stays used. If I change it back to

```
  gem 'our-gem', '~> 1.3'
```

then I once again get

```
  Using our-gem 1.3.20160415.170325 (was 1.3.20160706.171350)
```

This is using Ruby 2.2.3p173, rubygems 2.6.6, bundler 1.12.5.

**Comment by segiddins** [comment] 2016-07-07 11:39
Thanks for the bug report! If you can boil this down to a script we can run to reproduce the issue, it'll probably be easier to diagnose what's going on.  Thanks!

**Comment by Confusion** [comment] 2016-07-08 06:37
I've tried to create a concise reproduction, but so far no luck. It's not simply a matter of setting up a gemserver with only gems with these three versions and having a project with Gemfile with just this single reference. Possibly the dependencies of the gem are essential to the reproduction, or the presence of a score of other versions on the gemserver is, or some other detail.

**Comment by chrismo** [comment] 2016-07-08 15:08
Can you re-run with DEBUG and DEBUG_RESOLVER env vars set and post the output to a gist? Might be able to deduce something from that.

**Comment by Confusion** [comment] 2016-07-09 07:26
[Done](https://gist.githubusercontent.com/Confusion/95837919f3bbea91d93d9ddac256ed28/raw/b5cf45a06333b2f5f78e9d230d032ba956f158f8/gistfile1.txt) (~5 MB file). 

This file show the output when you run `bundle update` in the situation where the gem is at the 'newest' version (1.3.20160706.171350). It then downgrades the gem to the 'oldest' version (1.3.20160415.170325)

Two things that may be of note:
* Removing all versions of `our-gem` from the locally available gems doesn't make a difference
* the command is pretty slow. I thought the slowness was a separate issue, but perhaps they are related. In the output you can see that it downloads all .rz files present on `gems.our-company.com/external`, where we store all 3rd party gems we use. That doesn't seem necessary?

**Comment by Confusion** [comment] 2016-07-11 12:16
Something I found out:
* the `gems.our-company.com/external` gemserver has existed for quite a while and the gems are served directly by Apache, without `gem server` or `geminabox`. So no API available.
* the `build-gems.our-company.com` is newer and uses geminabox and has the API available.

Perhaps the client first queries `build-gems.our-company.com`, concludes it can use the API, then queries `gems.our-company.com/external`, doesn't get a response to API calls and falls back to some behaviour of last resort where it just downloads all the .rz files? From a quick look at the code it is not obvious to me whether this is possible.

**Comment by segiddins** [comment] 2016-07-11 12:46
@Confusion yup, that's what it has to do when no sort of API is available

**Comment by Confusion** [comment] 2016-08-04 14:18
I've done some more digging. I've reduced the set of gems on the gemserver to the minimum possible to still show the problem. Here's another [gist](https://gist.github.com/Confusion/182721304154071552e72923761a5612), where each part is only ~350 lines. One file shows a correct resolution and one an incorrect resolution.

Things of note:
* if I use Apache to serve the gems and fallback to 'fetch all .rz files', the wrong gem version is resolved
* if I use `gem server` on the same gem repo and use that to serve the gems, the right gem version is resolved
* if I remove cucumber-1.3.20, cucumber-rails-1.3.0, gherkin-2.12.2 or mime-types-1.25.1 from the gem server, the right gem version is resolved (as the alternative solution is no longer possible). These are also the only gems of which multiple versions are available on the server at this point.

So I think this suggests that if you're using the fallback method, an 'inferior' solution may be achieved by the resolver.

**Comment by segiddins** [comment] 2016-09-21 16:43
This _might_ be fixed in the 2-0 branch

**Comment by Confusion** [comment] 2016-10-11 08:07
It turns out the whole 'using Apache and falling back to fetching all .rz files' was a red herring. We switched all our gem servers to using the API's and at that moment it made the problem go away, but a few days ago the problem reappeared, even though we are not using the 'fallback behavior' anywhere anymore.

Will try with a bundler based on the 2-0 branch.

**Comment by segiddins** [comment] 2017-09-06 16:18
Closing because there's no Gemfile to test this against, but both master (in 2.0 mode) and 1.16.0.pre.1 have major resolver improvements.

**Closed by segiddins** 2017-09-06 16:18 UTC
Labels: status: triage
