### ISSUE TITLE
1.13.0.rc.1 has problems parsing git version on Mac OS - 2.7.4 (Apple Git-66)

### ISSUE THREAD

**Issue by jcoleman** [bundler/bundler#4911] opened 2016-08-24 13:14 UTC
LM-CHI-21000962:activerecord jamecoleman$ gem install bundler
Successfully installed bundler-1.12.5
1 gem installed
LM-CHI-21000962:activerecord jamecoleman$ bundle install                                                                                                                            
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/jamecoleman/.rbenv/versions/2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to install gems

- What happened instead?

  Instead, what happened was...

Error details

    ArgumentError: Malformed version number string 2.7.4 (Apple Git-66)
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/version.rb:207:in `initialize'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/version.rb:199:in `new'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/version.rb:190:in `create'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/source/git/git_proxy.rb:128:in `block in copy_to'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/shared_helpers.rb:54:in `chdir'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/shared_helpers.rb:54:in `block in chdir'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/shared_helpers.rb:53:in `chdir'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/source/git/git_proxy.rb:122:in `copy_to'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/source/git.rb:156:in `specs'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:235:in `block (2 levels) in index'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:233:in `each'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:233:in `block in index'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/index.rb:10:in `build'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:230:in `index'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:224:in `resolve'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:148:in `specs'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/definition.rb:136:in `resolve_remotely!'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/installer.rb:214:in `resolve_if_need'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/installer.rb:70:in `run'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/installer.rb:22:in `install'
      /usr/local/Cellar/rbenv/1.0.0/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli/install.rb:64:in `run'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli.rb:182:in `install'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/cli.rb:11:in `start'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/exe/bundle:34:in `block in <top (required)>'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.0.rc.1/exe/bundle:26:in `<top (required)>'
      /Users/jamecoleman/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
      /Users/jamecoleman/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.0.rc.1
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  GEM_HOME  /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0
  GEM_PATH  /Users/jamecoleman/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0:/Users/jamecoleman/.gem/ruby/2.3.0
  Git       2.7.4 (Apple Git-66)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/Users/jamecoleman/.rbenv/versions/2.3.0/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/jamecoleman/.rbenv/shims:/Users/jamecoleman/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jamecoleman/.rbenv/shims:/Users/jamecoleman/bin:/Applications/Postgres.app/Contents/Versions/latest/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by segiddins** [comment] 2016-08-24 13:40
Thanks, I think I know what caused this 😔

**Comment by segiddins** [comment] 2016-08-26 21:06
Never mind, I cannot reproduce this. What's the output of `git --version` for you?

**Comment by segiddins** [comment] 2016-08-26 21:07
This actually should be fixed in rc.2 by https://github.com/bundler/bundler/pull/4810

**Closed by segiddins** 2016-08-26 21:07 UTC
Labels: type: bug report
