### ISSUE TITLE
Proposal: Add feature to install gem using bundle CLI command (like npm)

### ISSUE THREAD

**Issue by mrdivyansh** [bundler/bundler#5020] opened 2016-09-26 13:29 UTC
Can we have  command like `bundle install devise --save` to install gem and add to gemfile ?

Now, we open gemfile and write name of gem and then run `bundle install`. I guess, this is little complicated.

What do you guys think ?

**Comment by chrismo** [comment] 2016-09-26 14:29
Is this what you want? http://bundler.io/v1.13/bundle_inject.html

**Comment by lynnco** [comment] 2016-09-27 23:24
`inject` does exactly what they described, although I noticed `inject` isn't listed in `bundle help`? I'll create a new issue for that

**Comment by indirect** [comment] 2016-09-27 23:30
@lynnco `inject` was designed to have a UI for platform implementors (like Heroku or Engine Yard) who need to add e.g. Puma to a Gemfile. It requires both a name and an exact version. The idea was that we would get around to building a user-facing `add` command later, and we haven't done it yet. There's an open issue about the `add` command, though: https://github.com/bundler/bundler/issues/4901

**Comment by segiddins** [comment] 2017-01-15 01:03
Closing as a duplicate of https://github.com/bundler/bundler/issues/4901.

**Closed by segiddins** 2017-01-15 01:03 UTC
Labels: contribution: unclaimed, status: ready, type: feature-request
