### ISSUE TITLE
`BUNDLE_GEMFILE` does not override `.bundle/config` path to Gemfile

### ISSUE THREAD

**Issue by joelvh** [bundler/bundler#6270] opened 2018-01-24 02:56 UTC
It's possible to specify a development version of the Gemfile in `.bundle/config` (such as `Gemfile.dev`). However, when running something like `BUNDLE_GEMFILE=Gemfile bundle exec rake` will still use `Gemfile.dev`.

Shouldn't the environment variable override what's specified in `.bundle/config`?

**Comment by joelvh** [comment] 2018-01-24 02:57
Would love to submit a PR for this, but spent a lot of time trying to track down where the Gemfile path is determined and haven't been able to identify the proper fix yet....

**Comment by colby-swandale** [comment] 2018-01-24 10:12
This seems like a bug, thanks for the report! A PR would be awesome! I suggest looking at [SharedHelpers](https://github.com/bundler/bundler/blob/master/lib/bundler/shared_helpers.rb#L240) as you'll find most of the logic around finding the Gemfile there.

**Comment by joelvh** [comment] 2018-01-24 15:42
My finding at the moment is that running `BUNDLE_GEMFILE=Gemfile JOEL=yes bundle exec rails c` brings up the Rails console, and `ENV` has the proper value for `JOEL` but `BUNDLE_GEMFILE` contains the value of what's specified in `.bundle/config`. (In this case, it's reset to "Gemfile.dev" instead of "Gemfile" specified in the command.)

@colby-swandale do you know if/why `BUNDLE_GEMFILE` is overwritten with what's in `.bundle/config`?

**Comment by joelvh** [comment] 2018-01-24 15:43
@colby-swandale I see there's an "environment preserver" here, but still digging into things.

https://github.com/bundler/bundler/blob/2c059142d17df414ab6f06842cfbfd7321a3e33e/lib/bundler.rb#L21

**Comment by joelvh** [comment] 2018-01-24 15:59
@colby-swandale If I don't use `bundle exec` it works as expected. Maybe there's a conflict between `bundle exec` and Rails loading bundler internally?

**Comment by joelvh** [comment] 2018-01-24 16:01
Alright, so I've tested `bundle exec irb` and I see in `ENV` that the value I want to override what's specified in `.bundle/config` is overwritten and the value I want to use is in `BUNDLER_ORIG_BUNDLE_GEMFILE`

**Comment by joelvh** [comment] 2018-01-24 16:23
The real issue I have right now is `BUNDLE_GEMFILE=Gemfile bundle update` uses `Gemfile.dev` from `.bundle/config`. I'm not sure why the existing environment variables get backed up and replaced @colby-swandale ?

**Comment by joelvh** [comment] 2018-01-24 16:36
It looks like the culprit is this line, which either takes a CLI option `--gemfile` or pulls from settings. I think environment variables should be merged into settings. (My specific issue is trying to specify `BUNDLE_GEMFILE` with `bundle update`, so adding the `--gemfile` option for `bundle update` could suffice... I don't know why it's not already an option for that command. However, it's not intuitive that the environment variables don't override settings.)

https://github.com/bundler/bundler/blob/master/lib/bundler/cli.rb#L36

**Comment by joelvh** [comment] 2018-01-31 00:05
@colby-swandale this is my original issue which identified that environment variables do not override `.bundle/config` settings because it seems the environment variables are "backed up" and replaced with default values before settings are loaded.

Rather than trying to run `BUNDLER_GEMFILE=Gemfile bundle update` when `.bundle/config` specifies `Gemfile.dev` as the default Gemfile, I opted to implement the `--gemfile` option to mimic `bundle install --gemfile` in https://github.com/bundler/bundler/pull/6273.

Any interest in keeping this issue open to fix the root cause which prevents environment variables from overriding `.bundle/config`?

**Comment by colby-swandale** [comment] 2018-01-31 00:12
👍 this issue needs to also be fixed as well.

**Comment by colby-swandale** [comment] 2018-03-09 13:48
So looking into this issue further, this is actually intended behavior of Bundler (to my surprise). The [local configuration](https://github.com/bundler/bundler/blob/master/lib/bundler/settings.rb#L93) takes precedent over `ENV`. I'm going to open a new issue on working to provide better information on the order that Bundler looks at settings. Apologies for not picking this up sooner.

I'm going to close this issue.

**Closed by colby-swandale** 2018-03-09 13:48 UTC
Labels: type: bug report
