### ISSUE TITLE
Invoking sudo without consent

### ISSUE THREAD

**Issue by orangecms** [bundler/bundler#5113] opened 2016-10-22 15:47 UTC
I just forked a project from GitHub and it is built with Jekyll, having a Gemfile to install dependencies. So I used my system's package manager to install Bundler first, which implied sudo, and thus sudo wouldn't ask me for authentication again within the next minutes.
Then I ran `bundle install` as documented in the project's README, and apparently it installed the gems to a system directory (`/usr/lib/ruby/gems/2.3.0/gems/`), so it seems that it just invokes sudo without the user's consent. Otherwise the user would not have been able to write to this directory. This is very bad for the system's integrity, because the package manager cannot track it. It would be very nice if Bundler would at least warn first-time users about this, and even better, not do it, please.

**Comment by segiddins** [comment] 2016-10-22 16:00
This behavior should already be changed on `master`! See https://github.com/bundler/bundler/pull/4956, which hasn't quite shipped yet

**Comment by orangecms** [comment] 2016-10-22 16:28
Cool, thank you for the quick reply!

**Comment by orangecms** [comment] 2016-10-22 20:05
Okay, I just checked the version I have installed, that is `1.13.6`. I then looked into https://github.com/bundler/bundler/pull/4956/commits/5a20eb0ef14121c23b3464d99836cd6e0ab85b4a, which covers #4956, but that is a different thing. What I mean is related to what is also described in https://github.com/bundler/bundler/issues/2565#issuecomment-87125407 - it just took me quite a while to find this, I'm sorry.

So the thing is, when you just ran another command through sudo, you are still authenticated for a while, so when you invoke `bundler install` just then, you won't see the warning.

I have read through the docs, specifically http://bundler.io/v1.2/bundle_install.html, but I'm not sure how to figure out where bundler put which files now. Usually all files in `/usr/lib/` are tracked by my package manager, and since bundler put other files there, now some are not. I can remove the whole Ruby directory and simply reinstall the packages involving Ruby, but that feels uncomfortable as I might forget something. So I just removed `/usr/lib/ruby/gems/2.3.0/gems/` and reinstalled Bundler, hoping that everything is consistent again. The more tedious part is to find what now resides in `/usr/bin`.
Are there any other locations Bundler writes to? And is there a utility to clean up what Bundler installed? I couldn't find much information through Google or the docs. I only see [`bundle clean`](http://bundler.io/v1.1/bundle_clean.html), but I don't know how it determines what is "unused" or what that really means, since the dependencies I installed came from a project, but were installed system-wide.

**Comment by segiddins** [comment] 2016-10-22 23:08
This hasn't been fixed in a release yet -- did you try running on master?

**Comment by lynnco** [comment] 2016-10-26 04:55
@orangecms

> This hasn't been fixed in a release yet -- did you try running on master?

(although that doesn't address your comment about https://github.com/bundler/bundler/pull/4956 vs https://github.com/bundler/bundler/issues/2565#issuecomment-87125407)

**Comment by orangecms** [comment] 2016-12-03 15:57
I'm sorry, I have already abandoned bundler because of this issue.

**Closed** 2016-12-03 16:45 UTC
Labels: status: triage

**Comment by orangecms** [comment] 2016-12-04 11:57
@segiddins I'm working on another Ruby project by chance now, so I gave it another shot, and to answer your question now, I did try it on master this time. However, I  have Rails and Bundler installed globally, and I don't know if that has implications. Anyway, I cloned this repo, and ran the `exe/bundle` from it. It still invokes sudo.

**Comment by segiddins** [comment] 2016-12-04 16:41
Can you share the output of `bundle env` and the output from running the install? Also, are you sure the cloned repos `lib` was in your load path?

**Comment by orangecms** [comment] 2016-12-04 19:13
Sure. I tried to follow your suggested and included the local lib directory in the load path, which didn't help. So I ran `LOAD_PATH="~/opensource/bundler/lib/" ~/opensource/bundler/exe/bundle env` (in bash), and that yields:

```
Environment

    Bundler   1.13.6
    Rubygems  2.5.2
    Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
    Git       2.10.2

Gemfile

    source 'https://rubygems.org'
    
    gem 'rails', '4.0.10'
    
    # Bundle edge Rails instead:
    # gem 'rails', :git => 'git://github.com/rails/rails.git'
    
    gem 'pg'
    
    gem 'json'
    
    # Gems used only for assets and not required
    # in production environments by default.
    group :assets do
    # gem 'sass-rails',   '~> 3.2.3'
    # gem 'coffee-rails', '~> 3.2.1'
    
      # See https://github.com/sstephenson/execjs#readme for more supported runtimes
      # gem 'therubyracer'
    
    # gem 'uglifier', '>= 1.0.3'
    end
    
    gem 'jquery-rails'
    
    # To use ActiveModel has_secure_password
    # gem 'bcrypt-ruby', '~> 3.0.0'
    
    # To use Jbuilder templates for JSON
    # gem 'jbuilder'
    
    # Deploy with Capistrano
    # gem 'capistrano'
    
    # To use debugger
    # gem 'ruby-debug'
    
    # gem 'clearance'
    gem 'devise_ichain_authenticatable'
    gem 'declarative_authorization'
    gem 'bootstrap_forms'
    gem 'postgres_ext'
    
    gem 'rfc822'
    gem 'geoip'
    
    # add these gems to help with the transition:
    # gem 'protected_attributes'
    gem 'rails-observers'
    gem 'actionpack-page_caching'
    gem 'actionpack-action_caching'
    gem 'cancan'
    
    local_gemfile = File.join(File.dirname(__FILE__), "Gemfile.local")
    if File.exists?(local_gemfile)
      puts "Loading Gemfile.local ..." if $DEBUG # `ruby -d` or `bundle -v`
      instance_eval File.read(local_gemfile)
    end

Gemfile.lock

    <No /home/shopco/opensource/mirrorpinky2/Gemfile.lock found>
```

And `LOAD_PATH="~/opensource/bundler/lib/" ~/opensource/bundler/exe/bundle install`:
```
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...

Your user account isn't allowed to install to the system Rubygems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to Rubygems using sudo.

  Password:
```

I'm on commit `1f10c7f07fdbe5b664272d54657b5687bc881810`.

**Comment by segiddins** [comment] 2016-12-04 20:31
The `LOAD_PATH` env var doesn't map to `$LOAD_PATH` in ruby, but it appears bundler asked for your password before running sudo, which is exactly the intended behavior

**Comment by orangecms** [comment] 2016-12-04 20:49
That is actually fine. My issue was that it didn't in the first place when I had already run another command via sudo, so I was still authenticated. I'm sorry that I failed to make that clear.
Please don't feel offended now, this is just some feedback. I care a lot about isolation, consistency, and integrity. So I don't get why you would write to a system directory anyway instead of the project directory like e.g. Node.js does or the home directory. I have just started working with Ruby, and so far the experience was, say, not very pleasant. I'm slowly getting along now. Through lots of blog posts and trial-error I have figured out how to use the tools in a somewhat sane way without messing up my system. When I understand everything, I'll share my notes to make it more beginner-friendly. :)

**Comment by indirect** [comment] 2016-12-04 21:13
@orangecms We install into system directories because that is long-standing (like, 10 years' worth of) expected behavior. The default for `bundle install` is going to be to write gems into `./.bundle` in 2.0, which we are actively working on.
