### ISSUE TITLE
jruby + pry + ffi bundles but does not exec

### ISSUE THREAD

**Issue by kenichi** [bundler/bundler#5356] opened 2017-01-24 01:05 UTC
investigating why all of our jruby CI suddenly failed, we discovered that the latest version of bundler seems to have a problem with gemspec pry dependency. it seems that bundling, creating the Gemfile.lock, all seems to work - but actually running something like `bundle exec ruby`, does not. sorry, i've not had more time to drill deeper but this is what i've found:

* jruby 9.1.6.0
* Gemfile must specify `gemspec`
* gemspec specifies pry ~> 0.9.12
* bundler 1.14.2

```
 $ wr
/Users/knakamura/.rubies/jruby-9.1.6.0/bin/ruby
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 +jit [darwin-x86_64]

$ cat Gemfile
source "https://rubygems.org"
gemspec

$ cat foo.gemspec
Gem::Specification.new do |s|
  s.name = "foo"
  s.version = "0.0.1"
  s.authors = [ "Kenichi Nakamura" ]
  s.homepage = "https://example.com"
  s.summary = "foo"
  s.add_development_dependency "pry", "~> 0.9.12"
end

$ rm Gemfile.lock

$ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using coderay 1.1.1
Using ffi 1.9.17 (java)
Using foo 0.0.1 from source at `.`
Using method_source 0.8.2
Using slop 3.6.0
Using bundler 1.14.2
Using spoon 0.0.6
Using pry 0.9.12.6 (java)
Bundle complete! 2 Gemfile dependencies, 8 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle exec irb
Bundler could not find compatible versions for gem "ffi":
  In snapshot (Gemfile.lock):
    ffi (= 1.9.17) java

  In Gemfile:
    pry (~> 0.9.12) java was resolved to 0.9.12.6, which depends on
      spoon (~> 0.0) java was resolved to 0.0.6, which depends on
        ffi java

    pry (~> 0.9.12) java was resolved to 0.9.12.6, which depends on
      spoon (~> 0.0) java was resolved to 0.0.6, which depends on
        ffi

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

$ gem uninstall bundler
Remove executables:
        bundle, bundler

in addition to the gem? [Yn]
Removing bundle
Removing bundler
Successfully uninstalled bundler-1.14.2

$ gem install --no-rdoc --no-ri -v 1.13.7 bundler
Fetching: bundler-1.13.7.gem (100%)
Successfully installed bundler-1.13.7
1 gem installed

$ bundle exec irb
irb(main):001:0> puts "ruh roh"
```

note: if this pry is in the Gemfile, and gemspec is not, things seem to work. please let me know if there's more info i can provide or anything else i can do to help. thanks.

**Comment by segiddins** [comment] 2017-01-24 01:12
This looks like a duplicate of https://github.com/bundler/bundler/issues/5349 to me

**Comment by segiddins** [comment] 2017-01-24 02:08
Can you see if https://github.com/bundler/bundler/issues/5355 fixes this for you?

**Closed** 2017-01-24 17:35 UTC

**Comment by kenichi** [comment] 2017-01-24 17:50
hi @segiddins sorry for the dupe - i just got to work, got configured to run bundler from a checkout, pulled latest master, and was able to run irb without any other changes to the above env. thanks 👍

**Comment by segiddins** [comment] 2017-01-24 17:52
as soon as I get the time to make a release

**Comment by kenichi** [comment] 2017-01-24 17:53
no worries, thanks for fixing the problem so quickly, much appreciated!
