### ISSUE TITLE
BUNDLED WITH causing git problems

### ISSUE THREAD

**Issue by mferrier** [bundler/bundler#3706] opened 2015-06-02 21:07 UTC
The addition of the `BUNDLED WITH` line to the `Gemfile.lock` causes a problem when a large dev team is working on a project with the `Gemfile.lock` added to source control.

A dev will check with `bundle check` and if their version of bundler doesn't match the version the `Gemfile.lock` was `BUNDLED WITH`, the `BUNDLED WITH` line gets updated in the `Gemfile.lock` and marks the file as dirty. 

It then has to be checked in or reset by hand every time.

How about an environment variable or a config directive that prevents that line from getting added?

**Comment by segiddins** [comment] 2015-06-02 21:09
This is a duplicate of https://github.com/bundler/bundler/issues/3697.

**Closed by segiddins** 2015-06-02 21:09 UTC
