### ISSUE TITLE
Bundler 1.16.3 results in load error

### ISSUE THREAD

**Issue by oliverguenther** [bundler/bundler#6629] opened 2018-07-17 09:08 UTC
Our travis environment started failing this morning after the release of 1.16.3. It is connected to `parallel_test` trying to execute in a bundle context despite bundler already loaded.

```
bundle exec parallel_test --type cucumber -o ' -p rerun -r /home/travis/build/opf/openproject/features' -n 1 --only-group 1 features
/home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
rake aborted!
Command failed with status (1): [bundle exec parallel_test --type cucumber ...]
/home/travis/build/opf/openproject/lib/tasks/parallel_testing.rake:132:in `block (2 levels) in <top (required)>'
/home/travis/build/opf/openproject/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load'
/home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => parallel:cucumber
(See full trace by running task with --trace)
``` 

This PR rolling back to 1.16.2 results in correct execution:

https://travis-ci.org/opf/openproject/jobs/404795702 (Change behind that is https://github.com/opf/openproject/pull/6432).

vs. it breaking with 1.16.3

https://travis-ci.org/opf/openproject/jobs/404746397

Please let me know if and how I can provide further insight in that failure from our side. Is it a regression? has a change in 1.16.3 affected something? shouldn't this have worked in the first place?

**Comment by colby-swandale** [comment] 2018-07-17 10:07
I have a feeling that this may the same issue as #6537. I suggest fixing your version of Bundler to  1.16.2 for the time being

**Comment by oliverguenther** [comment] 2018-07-17 11:10
Yes, that does help indeed. It also only occurs in that nested bundle context, the other jobs are working fine.

**Comment by bastelfreak** [comment] 2018-07-17 16:11
Hey everybody. I think the Vox Pupuli org (https://travis-ci.org/voxpupuli/puppet-archive) got his by this as well. We see this error on ruby2.1.9, 2.4.4 and 2.5.1 under certain constraints that I did not yet discovered.

**Comment by LithiumSR** [comment] 2018-07-18 14:13
Same problem for me with ruby 2.5.1

**Comment by graywolf** [comment] 2018-07-29 20:17
I'm not sure if I'm supposed to +1 on github but I've encountered this issue
too, for me it's locally, not in travis.

```
/home/wolf/.gem/ruby/2.5.0/bin/bundle:23:in `load': cannot load such file -- /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle (LoadError)
	from /home/wolf/.gem/ruby/2.5.0/bin/bundle:23:in `<main>'
```

I'm not sure why it's even trying to load the file from that location,
bundle 1.16.3 is installed in user folder:

```
   $ ls -al .gem/ruby/2.5.0/gems/ | grep bundler
drwxr-xr-x 1 wolf wolf 110 Jul 29 22:14 bundler-1.16.3
```

```
   $ ls -al /usr/lib/ruby/gems/2.5.0/gems/
total 0
drwxr-xr-x 1 root root 160 Jul  2 06:27 .
drwxr-xr-x 1 root root  92 Feb 17 23:51 ..
drwxr-xr-x 1 root root   6 Feb 17 23:53 bundler-1.16.1
drwxr-xr-x 1 root root   6 May 19 20:09 bundler-1.16.2
drwxr-xr-x 1 root root 416 Jul  2 06:27 rdoc-6.0.4
drwxr-xr-x 1 root root 550 Feb 17 23:52 rubygems-update-2.7.6
drwxr-xr-x 1 root root 550 May 19 20:08 rubygems-update-2.7.7
```

Reverting to `1.16.2` fixes the issue for me (probably since it's in the 
system folder).

**Comment by pboling** [comment] 2018-08-13 09:18
I am having this issue on RubyGems 2.7.7 and bundler 1.16.3.  I initially reported to Rubygems, but I think the issue is in bundler.
https://github.com/rubygems/rubygems/issues/2377

**Comment by pboling** [comment] 2018-08-29 09:54
I am still getting the same error on new bundler `1.16.4`

**Comment by colby-swandale** [comment] 2018-08-29 12:41
Yes, this problem will continue to exist in new releases of Bundler until we can fix this issue.

**Comment by colby-swandale** [comment] 2018-09-18 22:19
This issue has been fixed in the newest release of Bundler.

**Closed by colby-swandale** 2018-09-18 22:19 UTC
Labels: type: bug report
