### ISSUE TITLE
Middleman init throws bundle error

### ISSUE THREAD

**Issue by COLTstreet** [bundler/bundler#6263] opened 2018-01-18 20:51 UTC
I installed Ruby, and then installed Middleman just as the Middleman getting started video said. 

What did you do?
I ran middleman init speed_digital

What did you expect to happen?
It to build out the starting files

What happened instead?
It failed halfway though throwing an error.

Here is the backtrace:

## Backtrace

```
RuntimeError: Unable to find a spec satisfying tzinfo-data (>= 0) in the set. Perhaps the lockfile is corrupted?
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:40:in `block in for'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:25:in `loop'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:25:in `for'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:80:in `materialize'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:158:in `resolve_remotely!'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/installer.rb:279:in `resolve_if_needed'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/installer.rb:83:in `block in run'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:12:in `block in lock'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `open'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/process_lock.rb:9:in `lock'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/installer.rb:72:in `run'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/installer.rb:25:in `install'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/install.rb:65:in `run'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:224:in `block in install'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/settings.rb:136:in `temporary'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:223:in `install'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  C:/Ruby24-x64/bin/bundle:23:in `load'
  C:/Ruby24-x64/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       1.16.1
  Platforms   ruby, x64-mingw32
Ruby          2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
  Full Path   C:/Ruby24-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      2.6.14
  Gem Home    C:/Ruby24-x64/lib/ruby/gems/2.4.0
  Gem Path    C:/Ruby24-x64/lib/ruby/gems/2.4.0;C:/Users/cstreet/.gem/ruby/2.4.0
  User Path   C:/Users/cstreet/.gem/ruby/2.4.0
  Bin Dir     C:/Ruby24-x64/bin
OpenSSL
  Compiled    OpenSSL 1.0.2n  7 Dec 2017
  Loaded      OpenSSL 1.0.2n  7 Dec 2017
  Cert File   C:/Ruby24-x64/ssl/cert.pem
  Cert Dir    C:/Ruby24-x64/ssl/certs
Tools
  Git         2.14.2.windows.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
```

### Gemfile.lock

```
<No C:/Users/cstreet/speed_digital/Gemfile.lock found>

**Comment by colby-swandale** [comment] 2018-01-20 05:55
This is a duplicate of #6141

**Closed by colby-swandale** 2018-01-20 05:55 UTC
