### ISSUE TITLE
You must use Bundler 2 or greater error 

### ISSUE THREAD

**Issue by reshadf** [bundler/bundler#7097] opened 2019-04-04 11:47 UTC
ruby version: 2.6.0
ubuntu: 18.04
bundler: 2.0.1

I am not sure wether this is a replica of #6784 or #6937 but it happens for me on the above setup. Weird thing is that when I retry a dozen times, it succeeds but fails again later in another run. This only happens through the CI ( gitlab ). 

If I ssh into the server and manually run bundle install.  everything is fine

```
$ bundle install
You must use Bundler 2 or greater with this lockfile.
```

**Comment by deivid-rodriguez** [comment] 2019-04-04 13:21
Can you try upgrading to ruby 2.6.2 and report back?

**Comment by reshadf** [comment] 2019-04-05 09:23
with 2.6.2 it still happens. The error message looks different but it is still the same

```
/usr/share/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /home/gitlab-runner/builds/jZR2y_qx/0/proactive-mobile/android/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
	from /usr/share/rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
	from /usr/share/rvm/rubies/ruby-2.6.2/bin/bundle:23:in `<main>'
	from /usr/share/rvm/rubies/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	from /usr/share/rvm/rubies/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by deivid-rodriguez** [comment] 2019-04-05 09:27
Ok, thanks.

And you definitely have bundler 2 installed there, right?

**Comment by reshadf** [comment] 2019-04-05 09:56
yes I have, this is the output of gem list bundler 

```
bundler (2.0.1, default: 1.17.2)
bundler-unload (1.0.2)
rubygems-bundler (1.4.5)
```

**Comment by deivid-rodriguez** [comment] 2019-04-05 10:14
:+1:. And you just can't reproduce it consistently, right?

It'd be great if you could try reproduce this on bundler's master. You would need to lock your lockfile to 2.1.0.pre.1, and make sure you have that installed in your CI (`bin/rake install:local` from a bundler checkout should do the trick, once #7104 is merged :sweat_smile:).

**Comment by reshadf** [comment] 2019-04-05 11:22
I actually fixed it just now by deleting the local Gemfile.lock and pushing it to the CI again. It recreated the Gemfile and runs fine so far.

**Comment by deivid-rodriguez** [comment] 2019-04-05 11:23
Did something change in the lock file?

**Comment by reshadf** [comment] 2019-04-05 11:29
I think the ruby version. Not sure though..

**Comment by deivid-rodriguez** [comment] 2019-04-05 11:40
> I think the ruby version. 

Interesting...

> Not sure though..

I guess that means you don't commit your lockfile?

**Comment by reshadf** [comment] 2019-04-05 11:57
I do commit it.. but I think that is why it didn't regenerate it maybe after changing ruby versions?

**Comment by deivid-rodriguez** [comment] 2019-04-05 12:42
Oh ok, I figured, since you were not sure about what changed, that you didn't keep that file under version control. Anyways, please report back if this happens again. I'd really like to be able to reproduce this.

**Comment by reshadf** [comment] 2019-04-05 13:41
sure! will do.

**Closed** 2019-04-29 09:51 UTC
