### ISSUE TITLE
Bundler installs gems from wrong source

### ISSUE THREAD

**Issue by cshada** [bundler/bundler#4290] opened 2016-02-09 23:28 UTC
I've run into a bit of an issue with gems being installed from the wrong sources.

Given a Gemfile of:
```
source 'https://rubygems.org'
ruby '2.2.3'
gem 'mono_logger'
gem 'custom-gem', '~> 0.0.2', source: 'http://gems.company.com/'
```

On an initial `bundle install` with no Gemfile.lock, everything will install as expected. However if the gem `mono_logger` is uninstalled, and then `bundle install` is run again, I get the following output:

```
Fetching gem metadata from http://gems.company.com/..
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from http://gems.company.com/.
Fetching version metadata from https://rubygems.org/.
Fetching gem metadata from http://gems.company.com/..
Fetching version metadata from http://gems.company.com/.
Installing mono_logger 1.1.0
Using custom-gem 0.0.2
Using bundler 1.11.2
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Warning: the gem 'mono_logger' was found in multiple sources.
Installed from: http://gems.company.com/
Also found in:
  * https://rubygems.org/
You should add a source requirement to restrict this gem to your preferred source.
For example:
    gem 'mono_logger', :source => 'http://gems.company.com/'
Then uninstall the gem 'mono_logger' (or delete all bundled gems) and then install again.
```

Why is it mono_logger was installed from gems.company.com when it should have come from rubygems and gems.company.com was defined as the source for only one gem?

**Comment by segiddins** [comment] 2016-02-16 02:23
I believe this is actually a know issue caused by backwards compatibility concerns with the lock file :(

\c @TimMoore

**Comment by indirect** [comment] 2016-02-16 03:20
I think the actual bug here is that we should show that warning even when installing from rubygems.org. It's supposed to be a hard error in 2.0 or install a gem that's available from multiple sources without explicitly tying it to a single source.

**Comment by TimMoore** [comment] 2016-02-16 08:33
Yeah I think this could be related to #3671, which I had no success in fixing without breaking everything else. The problem is with the way it reconciles the set of sources in the Gemfile with those in the lock... it's a complicated process that I can't quite wrap my head around. There should be a way to resolve it, even without breaking backward compatibility, but it's non-trivial.

@indirect I don't think it ought to warn in this case, as it shouldn't be checking for `mono_logger` in the private gem server at all.

**Comment by LynnCo** [comment] 2016-06-12 07:48
(clarifying) this issue is likely the same as https://github.com/bundler/bundler/issues/3671, that one will have to be resolved first

**Comment by segiddins** [comment] 2016-09-07 13:15
Given #3696 has been fixed on 2-0-dev, can we close this?

**Closed** 2016-09-21 07:13 UTC
Labels: status: working, type: bug report
