### ISSUE TITLE
bundle outdated incorrectly says "Bundle up to date!"

### ISSUE THREAD

**Issue by roberts1000** [bundler/bundler#5157] opened 2016-11-06 05:15 UTC
Running 'bundle outdated' with bundler 1.13.6 **always** generates

```
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...

Bundle up to date!
```

I also deleted my `Gemfile.lock` and ran `bundle`.  This caused a bunch of new gems to be installed which suggested bundler wasn't telling the truth.  I downgraded bundler to 1.12.5 and ran `bundle outdated` again.  It generated a totally different response this time:

```
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies........

Outdated gems included in the bundle:
  * actionview-encoded_mail_to (newest 1.0.8, installed 1.0.7, requested = 1.0.7) in group "default"
  * ancestry (newest 2.2.2, installed 2.1.0, requested = 2.1.0) in group "default"
  * bullet (newest 5.4.2, installed 5.3.0, requested ~> 5.3.0) in group "development"
  * capistrano (newest 3.6.1, installed 3.5.0, requested = 3.5.0) in group "development"
  * capistrano-rails (newest 1.2.0, installed 1.1.8, requested ~> 1.1.6) in group "development"
  * capybara (newest 2.10.1, installed 2.8.1, requested ~> 2.8.0) in group "test"
  * mysql2 (newest 0.4.5, installed 0.4.4, requested = 0.4.4) in group "default"
  * rails_config (newest 0.99.0, installed 0.4.2, requested = 0.4.2) in group "default"
  * selenium-webdriver (newest 3.0.0, installed 2.53.4, requested ~> 2.53.0) in group "test"
  * sitemap_generator (newest 5.2.0, installed 5.1.0, requested ~> 5.1.0) in group "default"
  * web-console (newest 3.4.0, installed 3.3.1, requested ~> 3.3.1) in group "development"
  * json (newest 2.0.2, installed 1.8.3)
  * libv8 (newest 5.3.332.38.1, installed 3.16.14.15)
  * rdoc (newest 5.0.0, installed 4.3.0)
  * slop (newest 4.4.1, installed 3.6.0)
  * yajl-ruby (newest 1.3.0, installed 1.2.1)
```

I uninstalled bundler 1.12.5 and tried going back to 1.13.0.  I got the same `Bundle up to date!` message.

I'm using Ubuntu 16.04.1 in a Virtualbox VM, Ruby 2.3.1, gem 2.6.8, rvm 1.27.0.

Oddly enough, I'm not seeing this problem on my work machine which is using the exact same versions as above.

**Comment by vandrijevik** [comment] 2016-11-07 10:26
I am seeing the same behavior on macOS 10.12.1. With this bundle environment:

```
$ bundle env
Environment

    Bundler   1.13.6
    Rubygems  2.6.8
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    Git       2.10.2

Bundler settings
```

and the following `Gemfile`:

```
$ cat Gemfile
source 'https://rubygems.org'

gem "aws-sdk"
gem "bugsnag"
gem "mixpanel-ruby"
gem "poseidon_cluster"

group :development do
  gem "bundler"
  gem "byebug"
  gem "foreman"
  gem "minitest"
  gem "mocha"
  gem "pry"
  gem "rake"
end
```

`bundle outdated` gives this incorrect output:

```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...

Bundle up to date!
```

However, running `bundle update` behaves very differently and (correctly) updates a bunch of outdated gems:

```
$ bundle update
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing jmespath 1.3.1 (was 1.1.3)
Using bundler 1.13.6
Installing bugsnag 5.0.1 (was 2.8.12)
Installing rake 11.3.0 (was 10.4.2)
Using thor 0.19.1
Using metaclass 0.0.4
Using method_source 0.8.2
Installing byebug 9.0.6 (was 6.0.2) with native extensions
Installing coderay 1.1.1 (was 1.1.0)
Installing minitest 5.9.1 (was 5.8.1)
Using mixpanel-ruby 2.2.0
Using poseidon 0.0.5
Using zookeeper 1.4.11
Using slop 3.6.0
Installing foreman 0.82.0 (was 0.78.0)
Installing mocha 1.2.1 (was 1.1.0)
Using zk 1.9.6
Installing aws-sdk-core 2.6.18 (was 2.1.29)
Using poseidon_cluster 0.3.3
Installing pry 0.10.4 (was 0.10.2)
Installing aws-sdk-resources 2.6.18 (was 2.1.29)
Installing aws-sdk 2.6.18 (was 2.1.29)
Bundle updated!
```

**Comment by chrismo** [comment] 2016-11-07 15:23
This appears to be a duplicate of #4979 (PR #5105). If y'all agree I can close this one.

**Comment by vandrijevik** [comment] 2016-11-07 16:19
@chrisimo That issue suggests that 1.13.0 does not show all outdated gems. However, in my case 1.13.6 does not show **any** gems as outdated, but 1.13.5 correctly lists as outdated all gems that are updated when `bundle update` runs, so I don’t think it is the same issue?!

**Comment by roberts1000** [comment] 2016-11-07 23:52
@chrismo I just uninstalled bundler from my system, cloned the fork/branch used in PR #5105, built the gem and installed it locally.  The output for `bundle outdated` now matches the output when I'm using bundler `1.12.5`.  I agree with @vandrijevik that the two issues are different, but it looks like PR #5105 fixes both.  I vote for closing the issue; we can reopen if needed.

**Closed** 2016-11-12 06:11 UTC
