### ISSUE TITLE
Explicit source option acts like a global source

### ISSUE THREAD

**Issue by etehtsea** [bundler/bundler#4529] opened 2016-05-06 10:55 UTC
```ruby
$ cat Gemfile
gem 'activesupport', source: 'https://rubygems.org/'
gem 'activemodel'
```

```
$ cat Gemfile.lock                        
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    builder (3.2.2)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.8.4)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activemodel
  activesupport!

BUNDLED WITH
   1.12.2
```

Expected behaviour:

```
Could not find gem 'activemodel' in any of the gem sources listed in your Gemfile or available on this machine.
```

Real life case:

I want to set explicit source to private repo for forked/internal gems. But once passed option to private repo implicitly affects all another that don't have it.

**Comment by segiddins** [comment] 2016-05-06 13:19
Are you sure you don't just have `activemodel` already installed locally?

**Comment by etehtsea** [comment] 2016-05-07 08:46
I'm pretty sure.

```
/tmp  ⚡ gem list --no-version | grep -v -E "test-unit|rdoc|racc|rake|psych|power_assert|net-telnet|jruby-openssl|jar-dependencies|minitest|json|io-console|bigdecimal|bundler" | xargs gem uninstall --force
Successfully uninstalled activemodel-4.2.6
Successfully uninstalled builder-3.2.2
Successfully uninstalled activesupport-4.2.6
Successfully uninstalled tzinfo-1.2.2
Successfully uninstalled thread_safe-0.3.5
Successfully uninstalled i18n-0.7.0
/tmp  ⚡ bundle install     
/tmp  ⚡ cat Gemfile      
gem 'activesupport'
gem 'activemodel', source: 'https://rubygems.org/'
/tmp  ⚡ bundle install    
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Using bundler 1.12.3
Using minitest 5.8.4
Using json 1.8.3
Installing builder 3.2.2
Installing i18n 0.7.0
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.6
Installing activemodel 4.2.6
Bundle complete! 2 Gemfile dependencies, 9 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by ojab** [comment] 2016-07-14 14:37
Actually not only `source`, but also `git`/`github`/etc are affected: something like
```
gem 'foo', github: 'ojab/foobar'
gem 'bar'
```
installs both gems if both gemspecs are available in repo.

**Comment by segiddins** [comment] 2016-07-14 14:55
This should be fixed now for Bundler 2

**Comment by ojab** [comment] 2016-07-14 15:10
Yep, cannot reproduce w/ bundler from 2-0-dev.
Is there any roadmap & timeline for Bundler 2?

**Closed** 2016-07-17 23:55 UTC
Labels: status: triage

**Comment by LynnCo** [comment] 2016-07-21 11:20
@ojab there isn't any "Bundler 2.0 will be released in `$MONTH`, `$YEAR`" timeline, the only thing I can point to is the number of issues open for the [2.0 milestone](https://github.com/bundler/bundler/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+--+Breaking+Changes%22), which is more or less how I measure nearness to release.
