### ISSUE TITLE
Permission denied when running Bundle Install.

### ISSUE THREAD

**Issue by markorapaic** [bundler/bundler#5211] opened 2016-11-28 06:50 UTC
Getting the following error when trying to run 'bundle install'

`Permission denied - /Users/markorapaic/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20161128-94505-wd9pqd`

**Comment by markorapaic** [comment] 2016-11-28 06:51
Also tried this with sudo and no luck.

**Comment by colby-swandale** [comment] 2016-11-28 07:08
Check to make sure that Bundler has permission to write to `/Users/markorapaic/.bundle` and `/Users/markorapaic`.

Also check to make sure that everything inside `/Users/markorapaic/.bundle` (if any) is owned by the same user that Bundler is being run as.

**Comment by byReham** [comment] 2016-11-29 10:39
it worked after i did ...

sudo chmod 1777 -R /home/<my_name>/.bundle/cache/compact_index

and

sudo chmod 1777 -R /tmp

**Comment by colby-swandale** [comment] 2016-11-29 10:43
@byReham You're setting everything in `/home/<my_name>/.bundle/cache/compact_index` and `/tmp` to be readable, writeable and executable for any user/group of the system, which is something I strongly advise against.

**Comment by byReham** [comment] 2016-11-29 10:58
Yea, I agree with you. It was just temporary solution.

**Comment by lynnco** [comment] 2016-12-01 08:00
(pre-written response)

Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) `Permission denied` issues. A suite of permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14. Until 1.14 releases, the team doesn't have the capacity to deal with, or deploy more fixes for, the quantity of permissions errors we receive.

I'm sorry you are experiencing issues and I hope you can get them resolved!!! Feel free to continue commenting on this issue in the meantime.

**Closed by lynnco** 2016-12-01 08:00 UTC

**Comment by FractalJim** [comment] 2018-01-12 03:37
Ran across this page trying to solve the same error.  I believe it was caused when I used sudo to run bundle install. I resolved the error by doing chown -R user:user .bundle in my home directory (where user is the name of your user).

**Comment by clr2107** [comment] 2018-02-11 02:07
@FractalJim This totally worked for me!! Thanks!

**Comment by touseefbutt321** [comment] 2018-06-20 18:18
I had the same issue, that's how i fixed mine.

If you are using **ZSH** then goto 

> profile -> command

 and check "Run command as a login shell" and close the terminal.
Fire up your terminal and initiate `bundle install` command.

**Comment by mcndubuisi** [comment] 2018-08-23 20:36
`sudo bundle install`

**Comment by cruelmelody** [comment] 2018-10-22 23:47
> Ran across this page trying to solve the same error. I believe it was caused when I used sudo to run bundle install. I resolved the error by doing chown -R user:user .bundle in my home directory (where user is the name of your user).

Just to chime in on this. If changing the permissions doesn't work, sudo remove the `/.bundle` directory from your home folder and then reinstall bundler as a non-sudoer. This resolved all write permission errors for me.

**Comment by tinosam** [comment] 2019-01-23 09:13
verify your rails version rails -v 
1 - update it with " gem install raiils -v 5.2.2" if it ask for persmission add Sudo 

2- Delete your gemfile.lock

3- Bundle install , it's work for me

**Comment by kingsj0405** [comment] 2019-03-11 05:35
In my case, `sudo apt-get install ruby-dev` was solution

**Comment by ngocsangyem** [comment] 2019-04-21 04:41
@FractalJim Thank you. It's work perfectly.

Noted: If you have this issues

```
chown: user: illegal group name

```
Try: sudo chown -R user: ~/.bundle

**Comment by Sphinxs** [comment] 2019-04-28 23:09
Is there a 'final' solution ?

**Comment by Klowar** [comment] 2019-07-07 09:08
On macOs u need to change group name to staff
so command is : `chown -R $(whoami):staff directory_path`

**Comment by danielsunarjo** [comment] 2020-01-09 09:35
Go rry `rm -rf /Users/yourusername/.bundle/cache/`  and bundle instale again
