### ISSUE TITLE
upgrading rails 4.2.8 -> 5.0.2, can't resolve dependencies for sprockets-rails / rack

### ISSUE THREAD

**Issue by joemsak** [bundler/bundler#5569] opened 2017-04-07 19:11 UTC
I decided to see if I could upgrade my rails install today, and it hasn't gone very well with bundler :(

Check this error I am getting from bundler when trying to run `bundle update`

```
rails (~> 5.0.2) was resolved to 5.0.2, which depends on
      actionpack (= 5.0.2) was resolved to 5.0.2, which depends on
        rack (~> 2.0)
        
rails (~> 5.0.2) was resolved to 5.0.2, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 2.0.0, which depends on
        sprockets (~> 2.8) was resolved to 2.8.0, which depends on
          rack (~> 1.0)
```

And a thread between me and @tenderlove on twitter where he says he can reproduce it and isn't sure what the issue is, told me to open a ticket (also shows a screenshot of bundler resolving dependencies for a very long time)

https://twitter.com/joemsak/status/850403632512208897

Finally, my gemfile with some notes commented at the top

https://gist.github.com/joemsak/9e82361806fdcbb065626cabee822c70

For what it's worth, I use pessimize regularly to ensure my gem versions are kept in order to prevent accidental over-updates.

**Comment by segiddins** [comment] 2017-04-07 20:39
Can you check if this is fixed on bundler `master`? There are improvements to `bundle update` that haven't been released yet

**Comment by tenderlove** [comment] 2017-04-08 19:22
Same error as of cdae66803a527067fd80686301551c4e7aa7fad9:

```
[aaron@TC bundler (master)]$ git show
commit cdae66803a527067fd80686301551c4e7aa7fad9
Merge: 32fb83273 261afb919
Author: The Bundler Bot <bot@bundler.io>
Date:   Sat Apr 8 16:25:28 2017 +0000

    Auto merge of #5559 - colby-swandale:gem-branch-exception, r=segiddins
    
    print an error message when a non-git gem is given a `branch` option
    
    When the user supplies the `branch` option to a non-git gem an error message should be printed.
    
    Relates to #5530.

[aaron@TC bundler (master)]$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
[aaron@TC bundler (master)]$ cd ../bundle-issue
[aaron@TC bundle-issue]$ time ruby -I ~/git/bundler/lib ~/git/bundler/exe/bundle
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 5.0.2) was resolved to 5.0.2, which depends on
      actionpack (= 5.0.2) was resolved to 5.0.2, which depends on
        rack (~> 2.0)

    rails (~> 5.0.2) was resolved to 5.0.2, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 2.0.0, which depends on
        sprockets (~> 2.8) was resolved to 2.8.0, which depends on
          rack (~> 1.0)

real	5m15.538s
user	5m9.152s
sys	0m2.527s
[aaron@TC bundle-issue]$
```

It's not clear from the error message why Bundler chose sprockets-rails 2.0.0 for it's solution and failed.  Hope that helps!

**Comment by segiddins** [comment] 2017-04-08 19:34
Yup, looks like a resolver bug 😞

**Comment by segiddins** [comment] 2017-04-08 19:41
> It's not clear from the error message why Bundler chose sprockets-rails 2.0.0 for it's solution and failed. 
That would just be the last version of `sprockets-rails` it tried, implying that it couldn't find _any_ that worked

**Comment by segiddins** [comment] 2017-04-08 19:50
This seems related to https://github.com/CocoaPods/Resolver-Integration-Specs/pull/10

**Comment by joemsak** [comment] 2017-04-09 15:49
Hi everyone, thank you so much for your help and input. @tenderlove told me via twitter that the problem seemed to originate with `country_state_select` so I came back to this by starting with removing the restraint on that gem and trying a bundle update.

Through a few rounds of trial and error, removing and re-adding gems once the updates were possible, I finally have a working Gemfile, seen here:

https://gist.github.com/joemsak/fe969aa71aa66f8ac2e6aa30215dd0e7

The only problem is now capybara-webkit (resolving to 1.14.0) won't build on my machine. But removing that gem for now gives me a working gemfile.

Gems I had to remove and then re-add (just removing the constraint didn't help the resolver)

* country_state_select

Gems that the resolver previously reported issues for, that are now installing okay:

* sass-rails
* sinatra

Other gems I had to remove entirely (or so it seemed):

* vanilla-ujs (rails 5.1 rails-ujs will use vanilla js anyway)
* quiet_assets (I think rails 5.* logs handle asset logging better now?)

I hope this information is helpful, and thank you again to everyone here.

**Comment by segiddins** [comment] 2017-04-09 21:27
I have to be honest, I can't promise I'll get around to fixing this issue in Molinillo soon, but thanks so much for following up and providing so much detail

**Comment by joemsak** [comment] 2017-04-09 22:34
The resolver problem comes back when I try to upgrade Country State Select from 2.0 to 3.0 

The working gemfile shows that 2.0 installed fine. But I previously had version 3.0, and I needed that specifically in my app. Their gemspec doesn't specify a version of rails for dependencies.

However, it does rely on compass-rails 2.0.4 which relies on sprockets < 2.13, and 2.12.14 is 4 years old

So I will link country-state-select to this issue, as well.

**Comment by joemsak** [comment] 2017-04-09 22:38
Y'all might find it interesting to see someone had a similar problem, and I found the existing issue and commented on it, yet his bundle install notes lead him in the right direction

https://github.com/arvindvyas/Country-State-Select/issues/47#issuecomment-291905626

**Comment by greysteil** [comment] 2017-07-11 09:14
I'm seeing a similar resolution problem for a bundle update. I've pruned down the `Gemfile` and `Gemfile.lock` to the minimal example to reproduce.

**Command:** `bundle update rails`

**Gemfile:**
```
source "https://rubygems.org"

ruby "2.4.1"

gem "devise"
gem "failbot_rails"
gem "rails"

gem "spring"
gem "web-console"
gem "codecov", require: false

```

**Gemfile.lock:**
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.2)
      actionpack (= 5.0.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.2)
      actionview (= 5.0.2)
      activesupport (= 5.0.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.2)
      activesupport (= 5.0.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.2)
      activesupport (= 5.0.2)
      globalid (>= 0.3.6)
    activemodel (5.0.2)
      activesupport (= 5.0.2)
    activerecord (5.0.2)
      activemodel (= 5.0.2)
      activesupport (= 5.0.2)
      arel (~> 7.0)
    activesupport (5.0.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.1.4)
    bcrypt (3.1.11)
    bindex (0.5.0)
    builder (3.2.3)
    codecov (0.1.10)
      json
      simplecov
      url
    concurrent-ruby (1.0.5)
    devise (4.2.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    docile (1.1.5)
    erubis (2.7.0)
    failbot (2.0.1)
    failbot_rails (0.5.0)
      failbot (>= 0.9.2, < 3)
      rails (>= 4)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    i18n (0.8.1)
    json (2.1.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    nio4r (2.0.0)
    nokogiri (1.7.1)
      mini_portile2 (~> 2.1.0)
    orm_adapter (0.5.0)
    rack (2.0.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.2)
      actioncable (= 5.0.2)
      actionmailer (= 5.0.2)
      actionpack (= 5.0.2)
      actionview (= 5.0.2)
      activejob (= 5.0.2)
      activemodel (= 5.0.2)
      activerecord (= 5.0.2)
      activesupport (= 5.0.2)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.2)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.0.2)
      actionpack (= 5.0.2)
      activesupport (= 5.0.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    simplecov (0.14.1)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.1)
    spring (2.0.1)
      activesupport (>= 4.2)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.4)
    thread_safe (0.3.6)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    url (0.3.2)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.5.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  codecov
  devise
  failbot_rails
  rails
  spring
  web-console

RUBY VERSION
   ruby 2.4.1p111

BUNDLED WITH
   1.15.1
```

Going to have a dig into what's going on, but thought I'd post this here in the meantime, in case there's any context I don't have.

**Comment by greysteil** [comment] 2017-09-15 19:45
This has been fixed by https://github.com/CocoaPods/Molinillo/pull/72 and can be closed.

**Closed** 2017-09-16 05:38 UTC
Labels: type: bug report

**Comment by rulingcom-debug** [comment] 2019-08-24 10:00
In fact, I met the similar issue with sass-rails.
"
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (~> 4.1.0) ruby depends on
      railties (= 4.1.0) ruby depends on
        actionpack (= 4.1.0) ruby depends on
          rack (~> 1.5.2) ruby

    sass-rails (~> 4.0.2) ruby depends on
      sprockets (<= 2.11.0, ~> 2.8) ruby depends on
        rack (1.0.0)
"
Bundler version 1.7.2
Any one can give me some advices? Thank you.
