### ISSUE TITLE
single line Gemfile; much older version of gem installed if version unspecified

### ISSUE THREAD

**Issue by mccalluc** [bundler/bundler#5154] opened 2016-11-04 23:59 UTC
I have read #3089, so I don't think this is really a bug, but the behavior surprised me, and perhaps this will be useful to you as an edge case to improve. (I had not been pinning version numbers because what really matters is the version github.io uses, and I didn't want to suggest we had control over that, but going forward I will, and that will fix everything for us.)

```
source 'https://rubygems.org'
gem 'github-pages'
```
produces "Using github-pages 39"

```
source 'https://rubygems.org'
gem 'github-pages', '104'
```
produces "Using github-pages 104"

Looking at the debug logs, I can see that in the first case it begins with 104, but then falls all the way back to 39, rather than falling to back to an earlier version of an underlying dependency. 

- [log-unspecified.txt](https://github.com/bundler/bundler/files/572866/log-unspecified.txt)
- [log-104.txt](https://github.com/bundler/bundler/files/572867/log-104.txt)

**Comment by segiddins** [comment] 2016-11-05 00:19
What's the output of `bundle env`?

**Comment by mccalluc** [comment] 2016-11-05 16:55
```
$ bundle env
Environment

    Bundler   1.13.6
    Rubygems  2.4.8
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    GEM_HOME  /Users/chuck/.rvm/gems/ruby-2.2.2
    GEM_PATH  /Users/chuck/.rvm/gems/ruby-2.2.2:/Users/chuck/.rvm/gems/ruby-2.2.2@global
    RVM       1.27.0 (latest)
    Git       2.7.4 (Apple Git-66)
    rubygems-bundler (1.4.4)

Gemfile

    source 'https://rubygems.org'
    gem 'github-pages'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        RedCloth (4.2.9)
        activesupport (5.0.0.1)
          concurrent-ruby (~> 1.0, >= 1.0.2)
          i18n (~> 0.7)
          minitest (~> 5.1)
          tzinfo (~> 1.1)
        addressable (2.4.0)
        blankslate (2.1.2.4)
        classifier-reborn (2.0.4)
          fast-stemmer (~> 1.0)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.10.0)
        colorator (0.1)
        concurrent-ruby (1.0.2)
        ethon (0.9.1)
          ffi (>= 1.3.0)
        execjs (2.7.0)
        faraday (0.9.2)
          multipart-post (>= 1.2, < 3)
        fast-stemmer (1.0.2)
        ffi (1.9.14)
        gemoji (2.1.0)
        github-pages (39)
          RedCloth (= 4.2.9)
          github-pages-health-check (~> 0.2)
          jekyll (= 2.4.0)
          jekyll-coffeescript (= 1.0.1)
          jekyll-feed (= 0.3.1)
          jekyll-mentions (= 0.2.1)
          jekyll-redirect-from (= 0.8.0)
          jekyll-sass-converter (= 1.3.0)
          jekyll-sitemap (= 0.8.1)
          jemoji (= 0.5.0)
          kramdown (= 1.5.0)
          liquid (= 2.6.2)
          maruku (= 0.7.0)
          mercenary (~> 0.3)
          pygments.rb (= 0.6.3)
          rdiscount (= 2.1.7)
          redcarpet (= 3.3.2)
          terminal-table (~> 1.4)
        github-pages-health-check (0.3.2)
          net-dns (~> 0.6)
          public_suffix (~> 1.4)
          typhoeus (~> 0.7)
        html-pipeline (1.9.0)
          activesupport (>= 2)
          nokogiri (~> 1.4)
        i18n (0.7.0)
        jekyll (2.4.0)
          classifier-reborn (~> 2.0)
          colorator (~> 0.1)
          jekyll-coffeescript (~> 1.0)
          jekyll-gist (~> 1.0)
          jekyll-paginate (~> 1.0)
          jekyll-sass-converter (~> 1.0)
          jekyll-watch (~> 1.1)
          kramdown (~> 1.3)
          liquid (~> 2.6.1)
          mercenary (~> 0.3.3)
          pygments.rb (~> 0.6.0)
          redcarpet (~> 3.1)
          safe_yaml (~> 1.0)
          toml (~> 0.1.0)
        jekyll-coffeescript (1.0.1)
          coffee-script (~> 2.2)
        jekyll-feed (0.3.1)
        jekyll-gist (1.4.0)
          octokit (~> 4.2)
        jekyll-mentions (0.2.1)
          html-pipeline (~> 1.9.0)
          jekyll (~> 2.0)
        jekyll-paginate (1.1.0)
        jekyll-redirect-from (0.8.0)
          jekyll (>= 2.0)
        jekyll-sass-converter (1.3.0)
          sass (~> 3.2)
        jekyll-sitemap (0.8.1)
        jekyll-watch (1.5.0)
          listen (~> 3.0, < 3.1)
        jemoji (0.5.0)
          gemoji (~> 2.0)
          html-pipeline (~> 1.9)
          jekyll (>= 2.0)
        kramdown (1.5.0)
        liquid (2.6.2)
        listen (3.0.8)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
        maruku (0.7.0)
        mercenary (0.3.6)
        mini_portile2 (2.1.0)
        minitest (5.9.1)
        multipart-post (2.0.0)
        net-dns (0.8.0)
        nokogiri (1.6.8.1)
          mini_portile2 (~> 2.1.0)
        octokit (4.4.1)
          sawyer (~> 0.7.0, >= 0.5.3)
        parslet (1.5.0)
          blankslate (~> 2.0)
        posix-spawn (0.3.12)
        public_suffix (1.5.3)
        pygments.rb (0.6.3)
          posix-spawn (~> 0.3.6)
          yajl-ruby (~> 1.2.0)
        rb-fsevent (0.9.8)
        rb-inotify (0.9.7)
          ffi (>= 0.5.0)
        rdiscount (2.1.7)
        redcarpet (3.3.2)
        safe_yaml (1.0.4)
        sass (3.4.22)
        sawyer (0.7.0)
          addressable (>= 2.3.5, < 2.5)
          faraday (~> 0.8, < 0.10)
        terminal-table (1.7.3)
          unicode-display_width (~> 1.1.1)
        thread_safe (0.3.5)
        toml (0.1.2)
          parslet (~> 1.5.0)
        typhoeus (0.8.0)
          ethon (>= 0.8.0)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        unicode-display_width (1.1.1)
        yajl-ruby (1.2.1)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      github-pages
    
    BUNDLED WITH
       1.13.6
```

**Comment by segiddins** [comment] 2016-11-05 17:02
Thanks! Looks like a bug in the backjumping, for some reason molinillo is going straight back to the root dependency instead of unwinding to consider an older version of addressable

**Comment by segiddins** [comment] 2016-11-05 19:58
I have a potential fix for this in Molinillo, thanks for the great bug report!

**Comment by nickmccurdy** [comment] 2016-11-09 18:41
Is there anything we can do to help?

**Comment by segiddins** [comment] 2016-11-09 20:40
Not really, just have to land https://github.com/CocoaPods/Molinillo/issues/54

**Closed** 2016-11-13 21:24 UTC
Labels: status: confirmed, type: bug report

**Comment by falsandtru** [comment] 2016-12-06 00:47
@segiddins When can we get the patched version?

**Comment by segiddins** [comment] 2016-12-06 01:11
When we release 1.14

**Comment by falsandtru** [comment] 2016-12-06 01:22
When will it be released?

**Comment by segiddins** [comment] 2016-12-06 03:38
We don't have a date set yet

**Comment by falsandtru** [comment] 2016-12-06 03:41
I see, thanks.

**Comment by christophevg** [comment] 2017-09-27 11:45
I have the impression that this problem has resurfaced: when doing a `bundle update` today I see the github-pages gem being downgraded again:

```
...
Using github-pages 75 (was 161)
Bundle updated!
```

Tested with bundler 1.15.4.

Trying to upgrade to the current prerelease (1.16.0.pre.2) using `gem install bundler --pre`, dependency resolution takes a very long time, as in, it takes too long to wait for ;-)

Current work-around, as shown above: I'm locking version `161`.

**Comment by nickmccurdy** [comment] 2018-01-13 03:26
Please reopen. Confirmed on bundler 1.16.1, it's installing github-pages 39 again, even after wiping Gemfile.lock with `bundle install` or `bundle update`. I also seem like I can't install a different version of bundler with `--pre` (it installs the same version), so I'll specify the minimum version in my Gemfile again.

**Comment by nickmccurdy** [comment] 2018-01-13 03:40
Currently, my Gemfile locks `github-pages` to 39 if I'm also depending on `html-proofer`. Is this accurate or is it another regression in bundler's version resolution? If I force a more recent version of `github-pages` or remove the `html-proofer` gem, my Gemfile depends on the latest version of `github-pages`.
