### ISSUE TITLE
`require 'bundler/setup'` fails on 2.5.1 if bundler is located in symlinked directory

### ISSUE THREAD

**Issue by ojab** [bundler/bundler#6465] opened 2018-03-29 15:58 UTC
I don't really know if the root cause is symlinked directory, but it's my best shot (and I think [this change](https://bugs.ruby-lang.org/issues/14557) can be somehow related).
ruby-2.5.1 installed via rvm, rvm directory with all gems located in directory under symlink (i. e. `/symlinked_directory/ -> /real_directory/`, rvm is placed in `/real_directory/.rvm`, but `$LOAD_PATH` contains `/symlinked_directory/.rvm/…`)

`require 'bundler/setup'` in any project with `Gemfile.lock` fails with various `LoadError`s.

In empty project:
```
$ mkdir testapp && cd testapp && bundle init && irb
Writing new Gemfile to /tmp/testapp/Gemfile
2.5.1 :001 > require 'bundler/setup'
Traceback (most recent call last):
       16: from (irb):1
       15: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
       14: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
       13: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
       12: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
       11: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
       10: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
        9: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        8: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
        7: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
        6: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
        5: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:256:in `resolve'
        4: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:70:in `ui'
        3: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        2: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        1: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
LoadError (cannot load such file -- bundler/ui)
2.5.1 :002 > Gem::VERSION
 => "2.7.6"
2.5.1 :003 > Bundler::VERSION
 => "1.16.1"
```

<details>
 <summary>In rails project (this time `bundler/dep_proxy`)</summary>

```
$ irb
2.5.1 :001 > require 'bundler/setup'
Traceback (most recent call last):
       16: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
       15: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
       14: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
       13: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
       12: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
       11: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
       10: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
        9: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
        8: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
        7: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
        6: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
        5: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
        4: from /real_directory/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
        3: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        2: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        1: from /real_directory/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
LoadError (cannot load such file -- bundler/dep_proxy)
2.5.1 :002 > Gem::VERSION
 => "2.7.6"
2.5.1 :003 > Bundler::VERSION
 => "1.16.1"
```
</details>

2.5.0 in the same directories with bundler in symlinked directory works fine:
```
$ irb
2.5.0 :001 > require 'bundler/setup'
 => true
2.5.0 :002 > Gem::VERSION
 => "2.7.6"
2.5.0 :003 > Bundler::VERSION
 => "1.16.1"
```

**Comment by ojab** [comment] 2018-03-29 16:28
but simple test like
```
$ ln -svf ~ /tmp/home
‘/tmp/home/ojab’ -> ‘/home/ojab’
$ irb
2.5.1 :001 > $LOAD_PATH.map { |path| path.sub(%r{^/home/ojab/}, '/tmp/home/') }.map { |path| "-I '#{path}'" }.join(' ')
 => "-I '/tmp/home/.rvm/gems/ruby-2.5.1@global/gems/did_you_mean-1.2.0/lib' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/x86_64-linux' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/vendor_ruby/2.5.0' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/vendor_ruby/2.5.0/x86_64-linux' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/vendor_ruby' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0' -I '/tmp/home/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/x86_64-linux'"
2.5.1 :002 > require 'bundler/setup'
 => true
```
doesn't reproduce it, unfortunately. Will try to create some kind of reproducer.

**Comment by indirect** [comment] 2018-03-29 20:29
@hsbt do you know of a change in 2.5.1 that would break require through symlinks like this?

**Comment by watsonian** [comment] 2018-03-29 20:35
`lib/rubygems.rb` also updated from 2.7.3 to 2.7.6. I remember seeing some reports of this issue when on 2.7.3 that were fixed by upgrading to 2.7.4. Maybe there's a regression there? https://github.com/ruby/ruby/compare/v2_5_0...v2_5_1#diff-e2bd4eb9bbb8b25862825c636e55bd6dL13

**Comment by ojab** [comment] 2018-03-29 22:37
And I cannot reproduce it w/ ruby build from source manually (i. e. `./configure && make && make install`). Looks like rvm issue, but still trying to isolate it.

**Comment by watsonian** [comment] 2018-03-30 00:29
Yeah, could very well be an rvm issue. I'm not able to reproduce the issue locally on my end either, but it happens consistently on Travis CI (which uses rvm).

**Comment by ralf-berger** [comment] 2018-04-04 13:42
Ruby 2.5.1 via RVM (head):

```sh
% bundle
Traceback (most recent call last):
 6: from [...]/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
 5: from [...]/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
 4: from [...]/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
 3: from [...]/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load'
 2: from [...]/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:10:in `<top (required)>'
 1: from [...]/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
[...]/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```

```sh
Traceback (most recent call last):
 4: from bin/rails:3:in `<main>'
 3: from bin/rails:3:in `require_relative'
 2: from [...]/[...]]/config/boot.rb:3:in `<top (required)>'
 1: from [...]/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
[...]/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
```

**Comment by colby-swandale** [comment] 2018-04-05 10:36
is there any update to this issue?

**Comment by ojab** [comment] 2018-04-05 11:40
Sorry for delay, so far I can reproduce the issue with symlink `/home/testuser` -> `/tmp/testuser`, ruby-2.5.1 compiled w/ ` ./configure --prefix=/home/testuser/ruby --disable-install-doc` and then
```
$ PATH="/home/testuser/ruby/bin:${PATH}" GEM_PATH=/home/testuser/ruby/lib/ruby/gems/2.5.0/ irb
irb(main):001:0> require 'bundler/setup'
Traceback (most recent call last):
       16: from (irb):1
       15: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
       14: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
       13: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
       12: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
       11: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
       10: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
        9: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        8: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
        7: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
        6: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
        5: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:252:in `resolve'
        4: from /tmp/testuser/ruby/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:70:in `ui'
        3: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        2: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        1: from /tmp/testuser/ruby/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
LoadError (cannot load such file -- bundler/ui)
```
without rvm involved. Unfortunately hasn't found time to bisect it yet.

Basically `GEM_PATH` is similar to rvm's one and rvm works fine if `unset GEM_PATH` is run before interacting with ruby.

**Comment by ojab** [comment] 2018-04-05 12:46
…and bisecting is actually impossible: ruby v2_5_0 from git fails with the same error, while ruby-2.5.0 from tarball works fine, looks like local `autoreconf -i` doing something different from `autoreconf` which was run for tarball creation :/

**Comment by hsbt** [comment] 2018-04-06 00:32
7825e8363d4b2ccad8e2d3f5eeba9e26f6656911 is not related this problem.

**Comment by ojab** [comment] 2018-04-06 11:16
Nevertheless commit just before bundler merge (https://github.com/ruby/ruby/commit/f2e04b77aa8a363d7e36ce5a9cdb60714a537a3c) works (even after `gem update --system`/with rubygems-2.7.6), so offending commit should be here https://github.com/ruby/ruby/compare/f2e04b77aa8a363d7e36ce5a9cdb60714a537a3c...7825e8363d4b2ccad8e2d3f5eeba9e26f6656911 or it's caused not by ruby/rubygems/bundler. I can't see anything related in the range above.

**Comment by marcthe12** [comment] 2018-04-07 14:12
It failed with comunized-gem installed on rbenv. When I removed the plugin and reinstalled ruby with all settings intact, it works. So the problem in definately something to do with symlinks.

**Comment by michaelrigart** [comment] 2018-04-13 08:39
Hi,
I'm running into a similar problem using docker passenger image, which in turn uses rvm.

```
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.5.1
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.5.1/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.5.1
     - /usr/local/rvm/gems/ruby-2.5.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.5.1/bin
     - /usr/local/rvm/gems/ruby-2.5.1@global/bin
     - /usr/local/rvm/rubies/ruby-2.5.1/bin
     - /usr/local/rvm/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```
Commands run through the rails binstubs seem to fail, but running those commands directly through ```bundle exec``` work fine.

```
Traceback (most recent call last):
	33: from bin/rails:5:in `<main>'
	32: from bin/rails:5:in `load'
	31: from /home/app/bin/spring:16:in `<top (required)>'
	30: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	29: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	28: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	27: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	26: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	25: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	24: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	23: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	22: from /usr/local/rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	21: from /home/app/bin/rails:12:in `<top (required)>'
	20: from /home/app/bin/rails:12:in `require_relative'
	19: from /home/app/config/boot.rb:5:in `<top (required)>'
	18: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	16: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
	15: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	14: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	13: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	12: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	11: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	10: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	 9: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
	 8: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
	 7: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
	 6: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
	 5: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
	 4: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
	 3: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
	 2: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 1: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- bundler/dep_proxy (LoadError)
```

**Comment by chewi** [comment] 2018-04-13 11:46
Just come here from another issue and I can confirm the symlink aspect of it. If I replace the global gemset symlink with a bind mount then it works.

**Comment by chrisokamoto** [comment] 2018-04-17 16:09
Any update on this issue?

**Comment by DamienRobert** [comment] 2018-04-17 16:50
I can confirm this bugs happen with ruby 2.5.1p57, gem 2.7.6 and bundler 1.16.1. In fact for me this happens when my GEM_HOME path contains a symlink too. If I call bundler via GEM_PATH=/path/to/gems/without/symlinks it works (but strangely not when I do the same with GEM_HOME rather than GEM_PATH).

**Comment by michaelrigart** [comment] 2018-04-20 06:55
After some testing, I've noticed that when you uninstall the already provided bundler install from rvm and just reinstall it ( tested with version 1.16.0 and 1.16.1), the error won't appear anymore.

**Comment by indirect** [comment] 2018-04-20 07:14
I can confirm that [adding `before_install: gem install bundler`](https://github.com/rubytogether/rubytogether.org/commit/de3dda5a62d1d38f50634ffc9f884bbd143fb666) fixed this issue for me on Travis.

If reinstalling Bundler fixes the issue, maybe this is a problem with however RVM is packaging Bundler?

/cc @watsonian

**Comment by ojab** [comment] 2018-04-20 08:02
hmm, but `bundler` is not installed by default during `rvm install`. 
<details>
<summary>`gem list` after `rvm install 2.5.1`</summary>
```
bigdecimal (default: 1.3.4)
bundler-unload (1.0.2)
cmath (default: 1.0.0)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
etc (default: 1.0.0)
executable-hooks (1.4.2)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.10.3)
net-telnet (0.1.1)
openssl (default: 2.1.0)
power_assert (1.1.1)
psych (default: 3.0.2)
rake (12.3.0)
rdoc (default: 6.0.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```
</details>
what exactly is meant by `uninstall the already provided bundler install from rvm and just reinstall it`?

**Comment by ojab** [comment] 2018-04-20 08:42
```
$ docker run -it --rm --entrypoint sh phusion/passenger-ruby25
# ls -larth /usr/local/rvm/gems/ruby-2.5.1@global
lrwxrwxrwx. 1 root rvm 52 Apr  6 13:36 /usr/local/rvm/gems/ruby-2.5.1@global -> /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0
```
so AFAIU reinstallation basically moves `bundler` from symlinked directory to non-symlinked one and it just workarounds the issue.

**Comment by chewi** [comment] 2018-04-20 08:51
RVM used to preinstall Bundler but hasn't done for quite a while now. I was under the impression it is now included with Ruby itself?

**Comment by michaelrigart** [comment] 2018-04-20 08:57
@ojab , 

indeed, it's being re-installed in a non-symlinked directory.

Installing it back into the symlinked directory throws up the error again:

```
gem install -i /usr/local/rvm/gems/ruby-2.5.1@global bundler
```
So installing bundler in the non-symlinked directory is indeed a workaround.

**Comment by ralf-berger** [comment] 2018-04-20 09:38
@chewi IIRC that was planned for 2.6, but reverted last minute.

**Comment by ojab** [comment] 2018-04-23 12:51
Ok, so I've found time to dig it (instead of procrasinating), see https://github.com/bundler/bundler/pull/6502. It fixes issue here w/ ruby-2.5.1.
PR is based on 1.16-stable branch, has no tests etc, I'll fix it if it's proper fix and can be merged in theory.

**Comment by d-schloss-mvg** [comment] 2018-05-02 09:41
I am seeing this error too, while upgrading a Rails project to ruby-2.5.1.

The workaround for me was to downgrade to rubygems-2.7.5
`
$> rvm rubygems 2.7.5
`

**Comment by ojab** [comment] 2018-05-03 11:09
So after some debugging I've found that default rvm's ruby-2.5.0 installation has bundled `/home/ojab/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler{,.rb}` and missing files (i. e. `bundler/ui`) are required from there instead of installed gem.
Since ruby converts `$LOAD_PATH` entries to realpaths, the issue is not reproducible in that case.
rvm's ruby-2.5.1 doesn't install that `bundler{,.rb}`, so the issue is reproducible there.

**Comment by aalbagarcia** [comment] 2018-05-09 13:55
Hi,

I stepped into this issue today when upgrading a rails 5.2 application to ruby 2.5.1. 

In my case, I'm using chruby and ruby-install instead of RVM. We first upgraded our docker containers for development and everything was Ok. 

Then we tried to upgrade our test server (no docker, just a simple centos virtual machine) and the jenkins builds started to fail with the error `cannot load such file -- bundler/dep_proxy (LoadError)`. 

This is what I did and how I solved it:

- Install the latest ruby version using ruby-install as root
- log-in with the jenkins user `su - jenkins`
- run `chruby ruby-2.5.1 && gem install bundler`
- run our jenkins builds
- piss off our chuck norris plugin with failed builds
- cd into the jenkins workspace of the proyect to see if we could open a rails console
- try to run `RAILS_ENV=test bin/rails c` which raised the error `cannot load such file -- bundler/dep_proxy (LoadError)`
- ...Google about the error for a while until I read this issue

Since everything was working fine on ruby 2.5.0, y compared the path of the `bundle` executable for both ruby 2.5.0 and 2.5.1:

>ruby-2.5.1 -> ~/.gem/ruby/2.5.1/bin/bundler
>ruby-2.5.0 -> /opt/rubies/ruby-2.5.0/bin/bundler

So this is what I did:
- log-in with the jenkins user `su - jenkins`
- uninstall bundler as user jenkins `gem uninstall bundler`
- log-in again as root
- globally install bundler as root for ruby 2.5.1: `chruby ruby-2.5.1 && gem bundler install`
- log-in as jenkins again
- cd again into the jenkins workspace and run `bundle install`
- run `RAILS_ENV=test bin/rails c` and it worked
- jenkins build is back to green

I'm not sure if this is related to this issue. I write it down here just in case. Hope it helps somebody else.

**Comment by SunbeamRapier** [comment] 2018-06-23 15:12
I did:

gem install bundler
bundle install

It loads a pile of stuff and...

... it works!

**Closed** 2018-07-10 06:51 UTC
