### ISSUE TITLE
multiplatform Gemfile?

### ISSUE THREAD

**Issue by ahorek** [bundler/bundler#7168] opened 2019-05-09 13:43 UTC
I have a project and I want to support both mri and jruby. My Gemfile looks like this

```
gem "activerecord-jdbcmysql-adapter", platforms: [:jruby]
gem "mysql2", platforms: [:mri, :mingw, :x64_mingw]
```

in both cases bundler complains about unused dependencies
```
The dependency xxx (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
```

to get rid of them I have to run
`bundle lock --add-platform java`

but as an MRI user, why should I have to add "java"? This seems wrong.

as a project maintainer, the only way how to silence it is this ugly hack.
```
if RUBY_PLATFORM.match?('java')
  gem "activerecord-jdbcmysql-adapter", platforms: [:jruby]
else
  gem "mysql2", platforms: [:mri, :mingw, :x64_mingw]
end
```
is there a good way how to create a Gemfile, that will support more than one platform? I think it's a valid use case.

I saw many complains about this warning, people think it's an error, that the software maintainer should fix. Even if the warning doesn't break anything, it's confusing.

the same problem is with windows specific gems like 'tzinfo-data'. My options are
1/ remove the gem and I'll break windows compatibility
2/ force linux users to run `bundle lock --add-platform x86-mingw32` (I don't think it should be their responsibility)
3/ Gemfile generator or multiple Gemfiles (hacks)

even worse, PRs like this https://github.com/rails/rails/pull/36174 will make generated Gemfiles locked on a platform for which it was generated just to silence the warning.

It would be nice to have a way to silence these warnings as a project maintainer for projects that are suppose to support multiple platforms. Maybe add a magic comment to the Gemfile? I'm open for discussion and ideas, thanks!

**Comment by deivid-rodriguez** [comment] 2019-05-09 14:45
I'm aware of a problem with this warning. It's unavoidable when you run `bundle install` of a fresh Gemfile with gems specific for different platforms and no lockfile. In my opinion, `bundle install` without a lockfile should do the following by default: resolve and lock gems for all platforms, no warnings given, and install gems for the running platform. I'll see if I can fix this in the future.

That said, I don't understand your motivations. You want to support multiple platforms in your Gemfile by using the `:platforms` DSL, but refuse the lock the dependencies for those platforms by using the provided CLI command. To me that's like saying, "I want to support multiple platforms, but want to do it poorly".

> even worse, PRs like this rails/rails#36174 will make generated Gemfiles locked on a platform for which it was generated just to silence the warning.

This confirms that I failed to explain what my PR to Rails does... :disappointed:. Anyways, I won't push that PR further, it's no big deal. I'll try to improve this in `bundler` instead!

By the way, I just had a quick look at the source code, and there's apparently the `BUNDLE_DISABLE_PLATFORM_WARNINGS` environment variable to do just what you want. :smiley: 

Closing this since the request is actually implemented :)

**Closed by deivid-rodriguez** 2019-05-09 14:45 UTC

**Comment by ahorek** [comment] 2019-05-09 16:27
> resolve and lock gems for all platforms, no warnings given, and install gems for the running platform. I'll see if I can fix this in the future.

yes, that'll be the most elegant solution!

> You want to support multiple platforms in your Gemfile by using the :platforms DSL, but refuse the lock the dependencies for those platforms by using the provided CLI command. 

so you're saying that I should distribute `Gemfile.lock` in the source code? I thought it's a bad practice, because it's platform specific. Instead of letting bundler to decide if there's a valid combination for the current platform, I'll just lock them. I understand there are cases when you want it this way, but it shouldn't be a requirement.

> This confirms that I failed to explain what my PR to Rails does... 

sorry, your PR is ok, I should read more carefully. But I still don't consider this code as DRY.
```
if RUBY_PLATFORM.match(/bccwin|cygwin|emx|mingw|mswin|wince|java/)
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
end
```

**Comment by deivid-rodriguez** [comment] 2019-05-09 17:33
Yeah, it's generally accepted as a best practice to commit your Gemfile.lock to source control. By doing that, you make sure all contributors and all your environments always use the same set of dependencies. That's a good thing, everything is more reproducible and leads to less surprises.

**Comment by ahorek** [comment] 2019-05-09 17:41
@deivid-rodriguez make sense, thanks
