### ISSUE TITLE
Dependency resolution behavior change/regression in 1.13.0

### ISSUE THREAD

**Issue by fungi** [bundler/bundler#4961] opened 2016-09-09 22:53 UTC
On switching from bundler 1.12.5 to 1.13.0 today, a Gem we use for declaring a shared dependency set across a lot of our Puppet modules suddenly became uninstallable citing unresolvable dependencies. If you install http://git.openstack.org/openstack-infra/puppet-openstack_infra_spec_helper along with puppet-lint-empty_string-check (no version constraint) under 1.13.0 you end up with the following failure:
```
Fetching https://git.openstack.org/openstack-infra/puppet-openstack_infra_spec_helper
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies.........
Bundler could not find compatible versions for gem "puppet-lint":
  In Gemfile:
    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-absolute_template_path was resolved to 1.0.1, which depends on
        puppet-lint (< 3.0, >= 1.1)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (< 3.0, >= 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppet-lint-unquoted_string-check was resolved to 0.1.0, which depends on
        puppet-lint (~> 1.0)

    puppet-openstack_infra_spec_helper was resolved to 0.0.1, which depends on
      puppetlabs_spec_helper was resolved to 1.2.2, which depends on
        puppet-lint (~> 2.0)
```

With 1.12.5 it's able successfully to compute a set of versions for the requested dependencies.

**Comment by mwhahaha** [comment] 2016-09-09 23:14
Here's the Gemfile where it fails, https://github.com/openstack-infra/puppet-mediawiki/blob/master/Gemfile

It should be noted that without gem 'puppet-lint-empty_string-check' in that Gemfile it works fine.

**Comment by coderanger** [comment] 2016-09-09 23:18
Seeing this too, with a pretty minimal repro:

```ruby
# frozen_string_literal: true
source "https://rubygems.org"
gem 'chef', '~> 12.1.2'
```

**Comment by coderanger** [comment] 2016-09-09 23:28
The output from bundler on that Gemfile:

```
Bundler could not find compatible versions for gem "ffi-yajl":
  In Gemfile:
    chef (~> 12.1.2) was resolved to 12.1.2, which depends on
      ffi-yajl (~> 1.2)

    chef (~> 12.1.2) was resolved to 12.1.2, which depends on
      chef-zero (~> 4.0) was resolved to 4.0, which depends on
        ffi-yajl (~> 2.2)

    chef (~> 12.1.2) was resolved to 12.1.2, which depends on
      chef-zero (~> 4.0) was resolved to 4.0, which depends on
        ffi-yajl (~> 1.1)
```

chef-zero 4.0 does not depend on `ffi-yajl (~> 2.2)`, it depends on `~> 1.1`. I'm not sure where that second chunk is coming from, it seems like deps are getting mixed up between versions.

**Comment by coderanger** [comment] 2016-09-10 01:19
Continuing to try and sort out that minimal case, the solver tries to activate ohai 8.20.0, but when things fail it never tries earlier versions of the ohai gem (which is required to find a solution). That seems like a bug? Is there something I can do to see why no other versions were tried there?

**Comment by segiddins** [comment] 2016-09-11 12:33
I can confirm the regression, it's likely caused by the bump to Molinillo 0.5.0

**Comment by segiddins** [comment] 2016-09-11 12:56
This seems to be caused by https://github.com/bundler/bundler/commit/5751e7015e06dba641c55b643c82d5c00e3e59f4#diff-9fb56cc2c5baf698bd4a969e44119293L220, I'm still investigating

**Comment by segiddins** [comment] 2016-09-11 14:36
This will be fixed by https://github.com/CocoaPods/Molinillo/pull/43

**Closed** 2016-09-12 21:36 UTC
Labels: type: bug report

**Comment by fungi** [comment] 2016-09-15 19:09
Looks like this made it into 1.13.1. Thanks!
