### ISSUE TITLE
Parallel installer uses wrong build settings due to thread-safety bug

### ISSUE THREAD

**Issue by FooBarWidget** [bundler/bundler#3660] opened 2015-05-17 19:02 UTC
If the user has configured build settings (e.g. `bundle config build.nokogiri --use-system-libraries`), and at the same time uses the parallel installer (e.g. `bundle install -j 2`), then Bundler can pass the build settings to the wrong gem.

This is because `install_gem_from_spec` temporarily saves the settings using `Bundler.rubygems.with_build_args [settings]`, which in turn temporarily saves the settings into `Gem::Command.build_args`. This is a global variable, so there is a thread-safety bug here.

It appears that Gem::Installer accepts a `:build_args` option, though I'm not sure which version introduced it. You can use that instead of using `Gem::Command.build_args`.

Tested on Bundler 1.9.9, Ruby 2.1.6, RubyGems 2.2.3, Linux x86.

**Comment by segiddins** [comment] 2015-05-17 19:23
I believe with build args has a mutex to prevent exactly this scenario.

**Comment by indirect** [comment] 2015-05-17 19:24
It's possible that you missed this, but [with_build_args](https://github.com/bundler/bundler/blob/master/lib/bundler/rubygems_integration.rb#L182) explicitly uses  a Monitor and synchronizes access to the global variable. In the future, I would like to use the `:build_args` option, but it will require more work, since we need to continue to support versions of RubyGems that do not include it.

Do you have an example of a time the Monitor is failing to provide thread-safety while building gems?

**Comment by FooBarWidget** [comment] 2015-05-18 16:00
I'll try to setup a small test case that reproduces the problem.

**Comment by agis-** [comment] 2015-10-22 07:39
@FooBarWidget Closing this until a test case and/or reproduction steps are provided.

**Closed by agis-** 2015-10-22 07:39 UTC
Labels: more-information-needed
