### ISSUE TITLE
Failure to upgrade gem if a yanked gem is required by an unrelated gem in Gemfile

### ISSUE THREAD

**Issue by pnomolos** [bundler/bundler#3265] opened 2014-11-20 18:26 UTC
As far as I can tell, that's what is happening here.  Here's the output of `bundle update -V`

```
Updating git://github.com/hyperoslo/capistrano-foreman.git
Updating https://github.com/bryanrite/carrierwave-sequel
Updating https://github.com/pnomolos/bamfcsv
HTTP GET https://bundler.rubygems.org/api/v1/dependencies
HTTP 200 OK
Fetching gem metadata from https://rubygems.org/
Query List: ["bundler", "rake", "oj", "unicorn", "flowdock", "grit", "clockwork", "capistrano", "cape", "foreman", "sinatra", "pg", "sinatra-sequel", "sequel", "upsert", "activesupport", "sentry-raven", "carrierwave", "fog", "rest-client", "resque", "resque-batched-job", "redis-lock", "uuidtools", "rubyzip", "zippy", "rabl", "mail", "mime-types", "padrino-core", "padrino-mailer", "padrino-helpers", "php-serialize", "nokogiri", "bill-parser", "carrier-scraper", "tux", "ruby-prof", "pry", "pry-byebug", "fixture_dependencies", "rspec", "webmock", "vcr", "fuubar", "rake-compiler", "sqlite3", "capistrano-bundler"]
Query Gemcutter Dependency Endpoint API: bundler,rake,oj,unicorn,flowdock,grit,clockwork,capistrano,cape,foreman,sinatra,pg,sinatra-sequel,sequel,upsert,activesupport,sentry-raven,carrierwave,fog,rest-client,resque,resque-batched-job,redis-lock,uuidtools,rubyzip,zippy,rabl,mail,mime-types,padrino-core,padrino-mailer,padrino-helpers,php-serialize,nokogiri,bill-parser,carrier-scraper,tux,ruby-prof,pry,pry-byebug,fixture_dependencies,rspec,webmock,vcr,fuubar,rake-compiler,sqlite3,capistrano-bundler
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=bundler,rake,oj,unicorn,flowdock,grit,clockwork,capistrano,cape,foreman,sinatra,pg,sinatra-sequel,sequel,upsert,activesupport,sentry-raven,carrierwave,fog,rest-client,resque,resque-batched-job,redis-lock,uuidtools,rubyzip,zippy,rabl,mail,mime-types,padrino-core,padrino-mailer,padrino-helpers,php-serialize,nokogiri,bill-parser,carrier-scraper,tux,ruby-prof,pry,pry-byebug,fixture_dependencies,rspec,webmock,vcr,fuubar,rake-compiler,sqlite3,capistrano-bundler
HTTP 200 OK
Query List: ["ruby-progressbar", "chalofa_ruby-progressbar", "rspec-instafail", "progressbar", "ripl", "ripl-rack", "ripl-multi_line", "redis", "archive-tar-minitar", "rcov", "hoe", "multi_json", "httparty", "win32console", "method_source", "slop", "coderay", "spoon", "ruby_parser", "yard", "tzinfo", "ffi", "tlsmail", "treetop", "i18n", "rack", "tilt", "mongrel", "shotgun", "rack-test", "rack-protection", "backports", "rspec-mocks", "rspec-expectations", "rspec-core", "cucumber", "diff-lcs", "syntax", "spicycode-rcov", "kgio", "raindrops", "padrino-support", "dotenv", "thor", "term-ansicolor", "posix-spawn", "json", "crack", "addressable", "tmail", "launchy", "redis-namespace", "vegas", "json_pure", "mono_logger", "http_router", "usher", "rdoc", "netrc", "mini_portile", "racc", "tenderlove-frex", "rexical", "weakling", "bacon", "highline", "net-ssh", "net-sftp", "net-scp", "net-ssh-gateway", "echoe", "sshkit", "fakeweb", "opennebula", "fog-terremark", "fog-vmfusion", "fog-voxel", "fog-profitbricks", "fog-radosgw", "fog-sakuracloud", "fog-softlayer", "fog-brightbox", "ipaddress", "fog-xml", "fog-json", "fog-core", "builder", "excon", "formatador", "ruby-hmac", "named-parameters", "google-api-client", "unicode", "thread_safe", "minitest", "memcache-client", "activemodel", "metaid", "ParseTree", "ruby2ruby", "sequel_core", "sequel_model", "assistance", "RubyInline", "faraday", "yajl-ruby", "hashie", "byebug"]
Query Gemcutter Dependency Endpoint API: ruby-progressbar,chalofa_ruby-progressbar,rspec-instafail,progressbar,ripl,ripl-rack,ripl-multi_line,redis,archive-tar-minitar,rcov,hoe,multi_json,httparty,win32console,method_source,slop,coderay,spoon,ruby_parser,yard,tzinfo,ffi,tlsmail,treetop,i18n,rack,tilt,mongrel,shotgun,rack-test,rack-protection,backports,rspec-mocks,rspec-expectations,rspec-core,cucumber,diff-lcs,syntax,spicycode-rcov,kgio,raindrops,padrino-support,dotenv,thor,term-ansicolor,posix-spawn,json,crack,addressable,tmail,launchy,redis-namespace,vegas,json_pure,mono_logger,http_router,usher,rdoc,netrc,mini_portile,racc,tenderlove-frex,rexical,weakling,bacon,highline,net-ssh,net-sftp,net-scp,net-ssh-gateway,echoe,sshkit,fakeweb,opennebula,fog-terremark,fog-vmfusion,fog-voxel,fog-profitbricks,fog-radosgw,fog-sakuracloud,fog-softlayer,fog-brightbox,ipaddress,fog-xml,fog-json,fog-core,builder,excon,formatador,ruby-hmac,named-parameters,google-api-client,unicode,thread_safe,minitest,memcache-client,activemodel,metaid,ParseTree,ruby2ruby,sequel_core,sequel_model,assistance,RubyInline,faraday,yajl-ruby,hashie,byebug
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=ruby-progressbar,chalofa_ruby-progressbar,rspec-instafail,progressbar,ripl,ripl-rack,ripl-multi_line,redis,archive-tar-minitar,rcov,hoe,multi_json,httparty,win32console,method_source,slop,coderay,spoon,ruby_parser,yard,tzinfo,ffi,tlsmail,treetop,i18n,rack,tilt,mongrel,shotgun,rack-test,rack-protection,backports,rspec-mocks,rspec-expectations,rspec-core,cucumber,diff-lcs,syntax,spicycode-rcov,kgio,raindrops,padrino-support,dotenv,thor,term-ansicolor,posix-spawn,json,crack,addressable,tmail,launchy,redis-namespace,vegas,json_pure,mono_logger,http_router,usher,rdoc,netrc,mini_portile,racc,tenderlove-frex,rexical,weakling,bacon,highline,net-ssh,net-sftp,net-scp,net-ssh-gateway,echoe,sshkit,fakeweb,opennebula,fog-terremark,fog-vmfusion,fog-voxel,fog-profitbricks,fog-radosgw,fog-sakuracloud,fog-softlayer,fog-brightbox,ipaddress,fog-xml,fog-json,fog-core,builder,excon,formatador,ruby-hmac,named-parameters,google-api-client,unicode,thread_safe,minitest,memcache-client,activemodel,metaid,ParseTree,ruby2ruby,sequel_core,sequel_model,assistance,RubyInline,faraday,yajl-ruby,hashie,byebug
HTTP 200 OK
Query List: ["sexp_processor", "SexpProcessor", "ZenTest", "bond", "termios", "multi_xml", "jnunemaker-crack", "mocha", "newgem", "signet", "httpadapter", "extlib", "liquid", "autoparse", "jwt", "retriable", "rspec-support", "multipart-post", "daemons", "fastthread", "gem_plugin", "cgi_multipart_eof_fix", "safe_yaml", "multi_test", "gherkin", "cucumber-core", "polyglot", "configuration", "tins", "test-spec", "camping", "fcgi", "ruby-openid", "thin", "spruz", "erubis", "rubyforge", "gemcutter", "allison", "facets", "escape_utils", "fuzzyhash", "bones", "needle", "jruby-pageant", "bcrypt-ruby", "url_mount", "validatable", "atomic", "rbvmomi", "dotenv-deployment", "colorize", "debugger-linecache", "columnize", "pry-debugger", "inflecto", "fission"]
Query Gemcutter Dependency Endpoint API: sexp_processor,SexpProcessor,ZenTest,bond,termios,multi_xml,jnunemaker-crack,mocha,newgem,signet,httpadapter,extlib,liquid,autoparse,jwt,retriable,rspec-support,multipart-post,daemons,fastthread,gem_plugin,cgi_multipart_eof_fix,safe_yaml,multi_test,gherkin,cucumber-core,polyglot,configuration,tins,test-spec,camping,fcgi,ruby-openid,thin,spruz,erubis,rubyforge,gemcutter,allison,facets,escape_utils,fuzzyhash,bones,needle,jruby-pageant,bcrypt-ruby,url_mount,validatable,atomic,rbvmomi,dotenv-deployment,colorize,debugger-linecache,columnize,pry-debugger,inflecto,fission
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=sexp_processor,SexpProcessor,ZenTest,bond,termios,multi_xml,jnunemaker-crack,mocha,newgem,signet,httpadapter,extlib,liquid,autoparse,jwt,retriable,rspec-support,multipart-post,daemons,fastthread,gem_plugin,cgi_multipart_eof_fix,safe_yaml,multi_test,gherkin,cucumber-core,polyglot,configuration,tins,test-spec,camping,fcgi,ruby-openid,thin,spruz,erubis,rubyforge,gemcutter,allison,facets,escape_utils,fuzzyhash,bones,needle,jruby-pageant,bcrypt-ruby,url_mount,validatable,atomic,rbvmomi,dotenv-deployment,colorize,debugger-linecache,columnize,pry-debugger,inflecto,fission
HTTP 200 OK
Query List: ["CFPropertyList", "trollop", "cdb-full", "tokyocabinet", "metaclass", "english", "RedCloth", "rubigen", "bcrypt", "ruby-yadis", "flexmock", "abstract", "activerecord", "markaby", "mab", "eventmachine", "eventmachine-le", "http_parser.rb", "preforker", "little-plugger", "loquacious", "bones-git", "bones-extras", "debugger-ruby_core_source", "ruby_core_source", "debugger", "psych"]
Query Gemcutter Dependency Endpoint API: CFPropertyList,trollop,cdb-full,tokyocabinet,metaclass,english,RedCloth,rubigen,bcrypt,ruby-yadis,flexmock,abstract,activerecord,markaby,mab,eventmachine,eventmachine-le,http_parser.rb,preforker,little-plugger,loquacious,bones-git,bones-extras,debugger-ruby_core_source,ruby_core_source,debugger,psych
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=CFPropertyList,trollop,cdb-full,tokyocabinet,metaclass,english,RedCloth,rubigen,bcrypt,ruby-yadis,flexmock,abstract,activerecord,markaby,mab,eventmachine,eventmachine-le,http_parser.rb,preforker,little-plugger,loquacious,bones-git,bones-extras,debugger-ruby_core_source,ruby_core_source,debugger,psych
HTTP 200 OK
Query List: ["git", "libxml-ruby", "thoughtbot-shoulda", "language", "bones-rcov", "bones-rubyforge", "bones-rspec", "bones-zentest", "arel", "activerecord-deprecated_finders"]
Query Gemcutter Dependency Endpoint API: git,libxml-ruby,thoughtbot-shoulda,language,bones-rcov,bones-rubyforge,bones-rspec,bones-zentest,arel,activerecord-deprecated_finders
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=git,libxml-ruby,thoughtbot-shoulda,language,bones-rcov,bones-rubyforge,bones-rspec,bones-zentest,arel,activerecord-deprecated_finders
HTTP 200 OK
Query List: []
Fetching additional metadata from https://rubygems.org/
Query List: ["chalofa_ruby-progressbar"]
Query Gemcutter Dependency Endpoint API: chalofa_ruby-progressbar
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=chalofa_ruby-progressbar
HTTP 200 OK
Query List: []
HTTP GET https://privategemserver/api/v1/dependencies
HTTP 200 OK
HTTP GET https://bundler.rubygems.org/api/v1/dependencies
HTTP 200 OK
Fetching gem metadata from https://fd937aa9b1989f4d2fdf33aa86a92e98.simplexmobility.com/
Query List: ["chalofa_ruby-progressbar"]
Query Gemcutter Dependency Endpoint API: chalofa_ruby-progressbar
HTTP GET https://privategemserver/api/v1/dependencies?gems=chalofa_ruby-progressbar
HTTP 200 OK
Query List: []
Fetching gem metadata from https://rubygems.org/
Query List: ["chalofa_ruby-progressbar"]
Query Gemcutter Dependency Endpoint API: chalofa_ruby-progressbar
HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=chalofa_ruby-progressbar
HTTP 200 OK
Query List: []
Resolving dependencies...
Could not find gem 'carrier-scraper (~> 0.19.3) ruby' in the gems available on this machine.
```

It appears that because `chalofa_ruby-progressbar` has been yanked, bundler goes on a chase down the rabbit-hole trying to find it, then gives up.

Note that `bundle update -V carrier-scraper` also produces a similar result.

**Comment by pnomolos** [comment] 2015-01-26 19:22
@indirect @TimMoore Just wondering if you guys had any luck figuring out what's causing this?  Thanks! :)

**Comment by TimMoore** [comment] 2015-01-27 10:54
Sorry, haven't looked into it yet.

**Comment by TimMoore** [comment] 2015-02-07 00:21
Finally getting to this... sorry that it's taken so long @pnomolos.

I think it's triggered by the use of rubygems.org as both a top-level source and attached to a specific gem. This `Gemfile` works fine, for example:

```ruby
source 'https://XCKRzWDSo1r7Xk8SYrSp@gem.fury.io/pnomolos/'
#source 'https://rubygems.org'

gem 'rake', '10.2.2', source: 'https://rubygems.org/'
gem 'rack', source: 'https://rubygems.org/'
```

This is definitely an unintended bug, and I'll work on a fix, but it's also not the way the feature was really intended to be used. If you're using a source for specific gems, you shouldn't also put it a the top level. You can probably work around the bug by changing your `Gemfile` to have one top-level source, and use source blocks around any gems that are supposed to come from an alternate gem server.

**Comment by pnomolos** [comment] 2015-02-07 00:26
@TimMoore I would have to see if I can replicate it, but right now in my gem file I am using source blocks for both the private gem server and for rubygems and that still triggers the error - should I try a source block for only the private gem server and leave rubygems at the top level?

**Comment by TimMoore** [comment] 2015-02-07 00:29
@pnomolos do you have any gems outside of source blocks?

**Comment by pnomolos** [comment] 2015-02-07 00:30
@TimMoore Nope, all of them are inside of the source blocks.  The private gemserver source block comes first, if that would make any difference.

**Comment by TimMoore** [comment] 2015-02-07 00:33
@indirect looks like you were right... this change seems to cause the problem: 1eb62f21d24e32029d5df1a279cecd957764f827

Commenting out `s.specs.each { |spec| dependency_names.delete(spec.name) }` fixes it for me.

**Comment by TimMoore** [comment] 2015-02-07 01:03
@indirect I'm going to revert that change and disable the test introduced in that commit for now. I agree that it is probably causing a few of the recent issues. I'll add a test to reproduce this issue, too.

That means that it will go back to querying gem servers for path gems and gemspecs, which isn't ideal but AFAIK isn't too harmful either. We'll need to find another solution for that. Really, path gems (and git gems/gemspecs, which are both special cases of path gems) shouldn't ever go into the list of dependencies to query remotely in the first place, but right now the code doesn't distinguish between them internally.

/cc @dubek, @grosser

**Comment by grosser** [comment] 2015-02-07 01:08
The original issue was no showstopper / just a bad implementation detail,
so I think it's fine to revert as long as we come up with a solution that
does what as described ("shouldn't ever go into the list of dependencies to
query remotely in the first place")

**Comment by TimMoore** [comment] 2015-02-07 03:14
Related: #3368

**Comment by indirect** [comment] 2015-02-07 03:20
I just finished a fix for this, and a test to prevent a regression, while on the bus to the animal sanctuary... I'll push in a few hours. :)

**Comment by TimMoore** [comment] 2015-02-07 03:25
Oh whoops!

**Comment by TimMoore** [comment] 2015-02-09 09:19
This should be fixed in 1.7.13. Please try upgrading and let us know if you still have any problems.

**Closed by TimMoore** 2015-02-09 09:19 UTC

**Comment by pnomolos** [comment] 2015-02-11 04:00
@TimMoore  yep it appears to be fixed.  Thanks so much!

**Comment by ccencho** [comment] 2016-04-06 22:48
Hello everyone I'm installing ubuntu 14.04 LTS bigbluebutton and I get the following error, agradecere your help:

Gem files will remain installed in /var/lib/gems/1.9.1/gems/nokogiri-1.4.4 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/nokogiri-1.4.4/ext/nokogiri/gem_make.out
Your Gemfile.lock is corrupt. The following gems are missing from the DEPENDENCIES section: 'archive-tar-minitar' 'hoe'
'rcov'
dpkg: error processing package bbb-record-core (--configure):
subprocess installed post-installation script returned error exit status 20
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
bbb-playback-presentation depends on bbb-record-core; however:
Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
bbb-config depends on bbb-web; however:
Package bbb-web is not configured yet.
bbb-config depends on bbb-playback-presentation; however:
Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
bigbluebutton depends on bbb-config; however:
Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Errors were encountered while processing:
bbb-web
bbb-record-core
bbb-playback-presentation
bbb-config
bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
