### ISSUE TITLE
Changes in how bundler does update with gems in path

### ISSUE THREAD

**Issue by vipulnsward** [bundler/bundler#4493] opened 2016-04-30 16:24 UTC
From: https://github.com/bundler/bundler/pull/4485#issuecomment-215975746

On 1.11.2 : https://gist.github.com/vipulnsward/3cccba09cbc6a1dab00f65361eff94ed
On 1.12.1 : https://gist.github.com/vipulnsward/c54ea4b376d1c30434fa329b51557986
### Steps to reproduce
- git clone git@github.com:rails/rails.git
- bundle update

**Comment by segiddins** [comment] 2016-04-30 16:29
What's the output of `gem env`?

**Comment by vipulnsward** [comment] 2016-04-30 16:31
https://gist.github.com/vipulnsward/e69dfd8775e44597ecccf4a84ce5e1f7

**Comment by chrismo** [comment] 2016-06-22 17:08
I tried re-creating with 1.12.5 and the latest master of rails and it resolved both the same:

```
[chrismo@momac rails (master)]$ diff Gemfile.lock ../../12/rails/Gemfile.lock
402c402
<    1.11.2
---
>    1.12.5
```

1.12.5 diff: https://gist.github.com/chrismo/c69afbe99e9d0259a062ec37deb0ce6e

fwiw

**Comment by segiddins** [comment] 2017-06-04 19:35
Closing because chris couldn't reproduce the issue.

**Closed by segiddins** 2017-06-04 19:35 UTC
Labels: status: triage
