### ISSUE TITLE
Error: “Your Gemfile.lock is corrupt”

### ISSUE THREAD

**Issue by ddfreyne** [bundler/bundler#5048] opened 2016-10-04 21:37 UTC
(Also see: #4467, #5006, #5008, #5044)

Bundler 1.13.2 fails with `bundle install` with the error: “Your Gemfile.lock is corrupt”.

Steps to reproduce:
1.  Create a Gemfile with the following contents:
   
   ``` ruby
   source 'https://rubygems.org'
   
   gem 'rainpress'
   ```
2. Run `bundle`. The following `Gemfile.lock` will be generated:
   
   ```
   GEM
     remote: https://rubygems.org/
     specs:
       rainpress (1.0)
   
   PLATFORMS
     ruby
   
   DEPENDENCIES
     rainpress
   
   BUNDLED WITH
      1.13.2
   ```
3.  Run `bundle install --jobs=3 --retry=3 --deployment`. Bundler will spit out this error:
   
   ```
   Fetching gem metadata from https://rubygems.org/.............
   Fetching version metadata from https://rubygems.org/.
   Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'echoe'
   ```

Setup:
- RubyGems 2.5.1
- Bundler 1.13.2
- ruby 2.3.1p112
- rvm 1.26.10

I have neither `rubygems-bundler` nor `open_gem`.

**Comment by ddfreyne** [comment] 2016-10-04 21:44
I’ll attempt to construct the smallest Gemfile/Gemfile.lock for which it still fails. Will get back to you.

**Comment by ddfreyne** [comment] 2016-10-04 21:54
`rainpress`’s gemspec is a little odd. An excerpt:

```ruby
Gem::Specification.new do |s|
  # … snip …

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<echoe>, [">= 0"])
    else
      s.add_dependency(%q<echoe>, [">= 0"])
    end
  else
    s.add_dependency(%q<echoe>, [">= 0"])
  end
end
```

**Comment by segiddins** [comment] 2016-10-04 22:11
This is a bug with rubygems.org incorrectly listing the development dependency as a runtime dependency, see https://rubygems.org/gems/rainpress/versions/1.0

\c @dwradcliffe

**Comment by ddfreyne** [comment] 2016-10-04 22:21
@segiddins Do you believe this a problem that can be handled within Bundler, or is it an issue with RubyGems (or its web site)?

**Comment by segiddins** [comment] 2016-10-04 22:28
My personal belief is that it's an issue with the RubyGems.org service, but I know the rest of the team does not agree with me

**Comment by indirect** [comment] 2016-10-04 23:17
@ddfreyne you _should_ be able to work around this for now by running `bundle install --full-index --deployment`. We're working on the rest.

**Comment by chrismo** [comment] 2016-10-05 02:59
fwiw, i couldn't recreate with RubyGems 2.6.6, but could recreate with 2.5.1. The lock file created in step 2 of [this comment](https://github.com/bundler/bundler/issues/5048#issue-181011547) should have all dependencies in it, not just `rainpress`.

**Comment by indirect** [comment] 2016-10-05 04:16
whoa, it did not even occur to me that this could be a RubyGems version issue. thanks for testing that, @chrismo!

**Comment by ddfreyne** [comment] 2016-10-05 06:41
I can make it fail with RubyGems 2.6.7 as well:

```
% gem --version
2.6.7

% cat Gemfile
source 'https://rubygems.org'

gem 'rainpress'

% bundle
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rainpress 1.0
Using bundler 1.13.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

% cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    rainpress (1.0)

PLATFORMS
  ruby

DEPENDENCIES
  rainpress

BUNDLED WITH
   1.13.2
```

**Comment by chrismo** [comment] 2016-10-05 15:17
Well, I just recreated with 2.6.7 and 2.6.6 - must be something else unrelated, and inconsistent. I'll yield back to @segiddins idea. ;)

**Comment by chrismo** [comment] 2016-10-05 16:22
I can recreate if `rainpress` is already installed in system gems. If I uninstall the gem from system gems first, then it works fine. 

This could still mean the issue is triggered by RubyGems.org listing echoe as both runtime and dev dependency, I haven't dug into any code.

**Comment by segiddins** [comment] 2016-10-05 17:20
@chrismo that was my conclusion as well

**Comment by gpakosz** [comment] 2016-11-02 11:43
I'm facing this issue with `rainpress` as well. Using `bundle install --full-index --deployment` as suggested by @indirect worked.

Still, it seems that people are hitting this exact problem with many different gems. As per @ddfreyne first post.

For the record, from a clean Debian Jessie. Ruby install with `ruby-install`:

```
# ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

Bundler being the only gem installed globally:

```
# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.13.6)
io-console (0.4.5)
json (1.8.3)
psych (2.0.17)
rdoc (4.2.1)
```

```
# cat Gemfile
source 'https://rubygems.org'

gem 'rainpress'
```

```
# cat Gemfile
source 'https://rubygems.org'

gem 'rainpress'
root@sdkb044:/tmp# cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    rainpress (1.0)

PLATFORMS
  ruby

DEPENDENCIES
  rainpress

BUNDLED WITH
   1.13.6
```

```
# bundle install --deployment
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/.
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'echoe'
```

**Comment by henning-koch** [comment] 2016-12-19 17:45
I wrote a guide outlining several options for dealing with this issue:
https://makandracards.com/makandra/43292-bundler-gemfile-lock-is-corrupt-gems-are-missing-from-the-dependencies-section

**Comment by segiddins** [comment] 2017-01-15 01:22
Fixed by https://github.com/bundler/bundler/pull/5267 which is in 1.14.

**Closed by segiddins** 2017-01-15 01:22 UTC
Labels: status: triage, type: bug report
