### ISSUE TITLE
Package command updates lock file when using a "path" gem

### ISSUE THREAD

**Issue by PChambino** [bundler/bundler#4739] opened 2016-06-30 17:36 UTC
#### What you're trying to accomplish

I am using `bundle package --all` to package the gems of a project which contains a "path" gem. 

Example Gemfile:

``` ruby
source 'https://rubygems.org'
gem 'my-gem', path: '../path/to/my-gem'
```
#### The command you ran

`bundle package --all`
#### What you expected to happen

For the gems to be packaged at `vendor/cache` and the `Gemfile.lock` to remain the same.
#### What actually happened

The `Gemfile.lock` was updated, the `remote` path of `my-gem` was updated to `vendor/cache/my-gem`.

Everything still seems to work, but it is annoying to keep the lock file in a version control system.

I am not sure if this is the intended behaviour, but it seems strange that `package` updates the lock file and to revert it you need to delete `vendor/cache` and run `bundle install`.

**Comment by segiddins** [comment] 2016-07-01 11:48
it is the intended behavior, otherwise path gems could not be used in a frozen bundle

**Comment by LynnCo** [comment] 2016-07-06 08:50
@PChambino I figure

> it is the intended behavior, otherwise path gems could not be used in a frozen bundle

is a reasonable explanation for the behavior? If so we can close this

**Comment by PChambino** [comment] 2016-07-06 12:43
After some trial and error to solve the problem that explanation actually makes less sense or I am not understanding @segiddins comment and the concept of package and frozen bundle. 😕 

Let me try to better explain what I am trying to achieve and how I solved the problem, then you tell me if this is the intended behaviour.

I want to package a project in a `.deb` with all its dependencies to achieve that I do `bundle package --all` and create my `.deb`. My `.deb` has a `postinst` script that runs `bundle install --deployment --local --without development:test` which fails because `bundle package --all` changed my `.lock` file.

I was able to solve the problem by running `bundle package --all --frozen` which keeps my `.lock` file intact and allows `bundle install --deployment --local --without development:test` to run correctly.

So, is this the intended behaviour?

Using `--frozen` when packaging is probably safer so I am happy with the solution. Nevertheless, in my opinion, `bundle package --all` should never change the remote of a "path" gem in the `.lock` file. Maybe I am missing something. In what situation would such change be desirable?

If this is not worth pursuing, we can close this issue, but I felt confused when `bundle package --all` changed the remote of the "path" gem.

**Comment by segiddins** [comment] 2017-06-04 20:10
@indirect thoughts?

**Comment by indirect** [comment] 2017-06-04 20:24
@segiddins I was under the impression that we solved this by not copying path gems into vendor/cache, and telling users that they need to handle their own vendoring if they have a path gem outside the application directory.

**Comment by segiddins** [comment] 2017-06-04 20:28
👍 we've indeed done that. Closing.

**Closed by segiddins** 2017-06-04 20:28 UTC
Labels: status: triage
