### ISSUE TITLE
Regression in deployment mode in Bundler 1.8.3

### ISSUE THREAD

**Issue by indirect** [bundler/bundler#5037] opened 2016-10-01 00:28 UTC
When running in deployment/frozen mode, Bundler should be able to install a previously-locked bundle without evaluating the gemspecs of gems that are not going to be installed.

In Bundler <= 1.8.2, this was true. In Bundler >= 1.8.3, this is no longer true. Sadface.

A minimal reproduction case can be checked out here:
https://gist.github.com/indirect/1cc86d686f40a40d68b895834ab11cf6

**Comment by segiddins** [comment] 2016-12-05 23:55
I have absolutely no idea how to fix this

**Comment by segiddins** [comment] 2017-06-04 20:19
I'm tempted to close this as wontfix/behaving as intended. We can't tell if things have changed and the lockfile is valid or not unless we can read in all gemspecs

**Comment by indirect** [comment] 2017-06-04 20:28
Are you saying you think it's a bugfix (correctly raising when frozen is being violated) that caused this regression, and therefore it's impossible to get back the old behavior?

It seems like at a minimum we can allow this if there are no path gems? If the Gemfile matches the lock in frozen mode, gems in excluded groups seem like they should be irrelevant to being able to install.

**Comment by segiddins** [comment] 2017-06-04 20:40
> Are you saying you think it's a bugfix (correctly raising when frozen is being violated) that caused this regression, and therefore it's impossible to get back the old behavior?

Correct.

> It seems like at a minimum we can allow this if there are no path gems? If the Gemfile matches the lock in frozen mode, gems in excluded groups seem like they should be irrelevant to being able to install.

But in the general case they can have dependencies that can change the resolution.
You're free to try and make this part work, but I seem to recall sinking a bunch of time into this issue 2 finals weeks ago and making no progress, so I don't think I'll try again.

**Comment by indirect** [comment] 2017-06-04 21:04
Thanks for the explanation. This is something that I personally would like, so I'll try to spend some time on it myself. Don't worry about solving it. 👍

**Comment by segiddins** [comment] 2017-08-02 16:21
This appears to be fixed on master.

**Closed by segiddins** 2017-08-02 16:21 UTC
Labels: status: ready, type: bug report
