### ISSUE TITLE
Confusing logic when processing BUNDLE_PATH setting

### ISSUE THREAD

**Issue by eyusupov** [bundler/bundler#5310] opened 2017-01-08 10:06 UTC
If I have it in `~/.bundle/config` set as
```
BUNDLE_PATH: "tmp/bundles"
```
Then my gems will be installed in `tmp/bundles/gems` directory.
However, if I copy `~/.bundle/config` to `.bundle/config (keeping the same path value), my gems will be installed in `tmp/bundles/ruby/<RUBY_VERSION>/gems/`.

From what I can tell, this is a regression when introducing a local config file. Before that, the logic was that environment variable value was not scoped with Ruby version and the setting from a config file _was_.

Now, the logic is that the env variable and value from the global config are not scoped with Ruby version and the value from the local config is scoped. Is there a reason for that or is that a bug?

This difference in the behavior breaks tag files support in `vim-bundler` plugin with my configuration.

**Comment by eyusupov** [comment] 2017-01-08 10:08
(For the record - `vim-bundler` thinks that the Ruby version needs to be added to the path whenever `BUNDLE_DISABLE_SHARED_GEMS` option is present).

**Comment by segiddins** [comment] 2017-01-14 23:07
This seems to be intentional behavior -- only the local config is suppose to have the ruby scope appended to the provided path. (see https://github.com/bundler/bundler/blob/5bd4e729ee801298e914702cd5038c3afb046e9e/lib/bundler/settings.rb#L193)

Given the code in question hasn't changed in several years, what version of Bundler are you seeing this as a regression from?

**Comment by colby-swandale** [comment] 2017-02-20 03:55
ping @eyusupov

**Comment by colby-swandale** [comment] 2017-02-21 04:08
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Closed by colby-swandale** 2017-02-21 04:08 UTC
Labels: status: user feedback required
