### ISSUE TITLE
metasploit bundel install error

### ISSUE THREAD

**Issue by lutti-it** [bundler/bundler#4658] opened 2016-06-09 10:57 UTC
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/home/user/.rvm/gems/ruby-2.1.6/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::EACCES: Permission denied @ dir_s_mkdir - /home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160609-19949-13xskca
      /home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `mkdir'
      /home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `block in mktmpdir'
      /home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/tmpdir.rb:142:in `create'
      /home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/tmpdir.rb:85:in `mktmpdir'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /home/user/.rvm/gems/ruby-2.1.6/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /home/user/.rvm/gems/ruby-2.1.6/bin/bundle:23:in `load'
      /home/user/.rvm/gems/ruby-2.1.6/bin/bundle:23:in `<main>'
      /home/user/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
      /home/user/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.12.5
  Rubygems  2.4.8
  Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
  GEM_HOME  /home/user/.rvm/gems/ruby-2.1.6
  GEM_PATH  /home/user/.rvm/gems/ruby-2.1.6:/home/user/.rvm/gems/ruby-2.1.6@global
  RVM       1.27.0 (latest)
  Git       2.8.4
  rubygems-bundler (1.4.4)
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/user/.rvm/gems/ruby-2.1.6/bin:/home/user/.rvm/gems/ruby-2.1.6@global/bin:/home/user/.rvm/rubies/ruby-2.1.6/bin:/home/user/.rvm/bin:/home/user/.rbenv/plugins/ruby-build/bin:/home/user/.rbenv/shims:/home/user/.rbenv/bin:/home/user/.local/share/umake/bin:/home/user/.npm-global/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/user/.rvm/gems/ruby-2.1.6:/home/user/.rvm/gems/ruby-2.1.6@global"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by segiddins** [comment] 2016-06-09 15:40
Do you have write permission for the `/home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/` directory?

**Comment by lutti-it** [comment] 2016-06-09 15:58
This are my permission for the 
/home/user/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/ 
directory:

drwxr-xr-x 2 root root    12288 Jun  8 15:33 info
-rw-r--r-- 1 root root 12569003 Jun  8 15:33 versions

**Comment by segiddins** [comment] 2016-06-09 16:12
But what about the permissions on the directory itself?

**Comment by lutti-it** [comment] 2016-06-09 17:06
The permissions of the metasploit directory:

drwxrwxrwx 4 user root 4096 Jun 8 15:30 app

-rwxrwxrwx 1 user root 2504 Jun 8 15:30 CODE_OF_CONDUCT.md

drwxrwxrwx 3 user root 4096 Jun 8 15:40 config

-rwxrwxrwx 1 user root 5587 Jun 8 15:30 CONTRIBUTING.md

-rwxrwxrwx 1 user root 1858 Jun 8 15:30 COPYING

drwxrwxrwx 23 user root 4096 Jun 8 15:30 data

drwxrwxrwx 3 user root 4096 Jun 8 15:30 db

drwxrwxrwx 3 user root 4096 Jun 8 15:30 documentation

drwxrwxrwx 6 user root 4096 Jun 8 15:30 external

drwxrwxrwx 7 user root 4096 Jun 8 15:30 features

-rwxrwxrwx 1 user root 1467 Jun 8 15:30 Gemfile

-rwxrwxrwx 1 user root 1319 Jun 8 15:30 Gemfile.local.example

-rwxrwxrwx 1 user root 6354 Jun 8 15:30 Gemfile.lock

-rwxrwxrwx 1 user root 1143 Jun 8 15:30 HACKING

drwxrwxrwx 20 user root 4096 Jun 8 15:30 lib

-rwxrwxrwx 1 user root 41263 Jun 8 15:30 LICENSE

-rwxrwxrwx 1 user root 4690 Jun 8 15:30 metasploit-framework.gemspec

drwxrwxrwx 8 user root 4096 Jun 8 15:30 modules

-rwxrwxrwx 1 user root 7484 Jun 8 15:30 msfbinscan

-rwxrwxrwx 1 user root 1140 Jun 8 15:30 msfconsole

-rwxrwxrwx 1 user root 2796 Jun 8 15:30 msfd

-rwxrwxrwx 1 user root 2921 Jun 8 15:30 msfelfscan

-rwxrwxrwx 1 user root 2481 Jun 8 15:30 msfmachscan

-rwxrwxrwx 1 user root 4505 Jun 8 15:30 msfpescan

-rwxrwxrwx 1 user root 4301 Jun 8 15:30 msfrop

-rwxrwxrwx 1 user root 2214 Jun 8 15:30 msfrpc

-rwxrwxrwx 1 user root 3175 Jun 8 15:30 msfrpcd

-rwxrwxrwx 1 user root 9816 Jun 8 15:30 msfupdate

-rwxrwxrwx 1 user root 9827 Jun 8 15:30 msfvenom

drwxrwxrwx 2 user root 4096 Jun 8 15:30 plugins

-rwxrwxrwx 1 user root 697 Jun 8 15:30 Rakefile

-rwxrwxrwx 1 user root 2329 Jun 8 15:30 README.md

drwxrwxrwx 2 user root 4096 Jun 8 15:30 script

drwxrwxrwx 6 user root 4096 Jun 8 15:30 scripts

drwxrwxrwx 9 user root 4096 Jun 8 15:30 spec

drwxrwxrwx 8 user root 4096 Jun 8 15:30 test

drwxrwxrwx 9 user root 4096 Jun 8 15:30 tools

**Comment by lynnco** [comment] 2016-10-09 01:19
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93) `Permission denied @ dir_s_mkdir` issues. Permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14

**Closed by lynnco** 2016-10-09 01:19 UTC
Labels: status: triage
