### ISSUE TITLE
Error when running bundler install - Permissions denied

### ISSUE THREAD

**Issue by mdigga39** [bundler/bundler#5153] opened 2016-11-04 17:33 UTC
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to update to a different version of activesupport (4.2.7.1) that hasn't been removed in order to install.

- What happened instead?

  Instead, what happened was:

fatal: Not a git repository (or any of the parent directories): .git
Fetching gem metadata from https://rubygems.org/.
Retrying fetcher due to error (2/4): Errno::EACCES Permission denied - (/var/folders/0j/gq25lpk16872gsdk7r7r0vy40000gn/T/bundler-compact-index-20161104-35169-axsqj4/rex-random_identifier, /Users/DiGregorio/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/rex-random_identifier).
Retrying fetcher due to error (3/4): Errno::EACCES Permission denied - (/var/folders/0j/gq25lpk16872gsdk7r7r0vy40000gn/T/bundler-compact-index-20161104-35169-19vxglc/rex-powershell, /Users/DiGregorio/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/rex-powershell).
Retrying fetcher due to error (4/4): Errno::EACCES Permission denied - (/var/folders/0j/gq25lpk16872gsdk7r7r0vy40000gn/T/bundler-compact-index-20161104-35169-1ktos6g/rex-arch, /Users/DiGregorio/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/rex-arch)

Error details

    Errno::EACCES: Permission denied - (/var/folders/0j/gq25lpk16872gsdk7r7r0vy40000gn/T/bundler-compact-index-20161104-35169-p81k0a/windows_error, /Users/DiGregorio/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/windows_error)
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `block in dependencies'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `block (3 levels) in compact_index_client'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `call'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `block in process_queue'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `loop'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
      /Library/Ruby/Gems/2.0.0/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `block (2 levels) in initialize'

Environment
      
  Bundler   1.13.6
  Rubygems  2.0.14.1
  Ruby      2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  GEM_HOME  /Library/Ruby/Gems/2.0.0
  GEM_PATH  /Library/Ruby/Gems/2.0.0:/Users/DiGregorio/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  Git       2.9.3 (Apple Git-75)

Error when checking the site was as follows:

Permission denied - (/var/folders/0j/gq25lpk16872gsdk7r7r0vy40000gn/T/bundler-compact-index-20161104-35169-p81k0a/windows_error, /Users/DiGregorio/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/windows_error)

**Comment by marcus-crane** [comment] 2016-11-06 14:27
I was having similar permissions issues as well.

You can try installing an earlier version which works for me and my coworker like so:

`gem install bundler:1.13`

It was claimed that the issue was fixed in a pull request and is going to be released in 1.14 but I built the repo post-PR merge and I still had no luck

*shrug* Maybe I was just doing it wrong, haha

Hopefully that fixes your issue in the meantime.

**Comment by lynnco** [comment] 2016-11-12 05:58
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93) `Permission denied @ dir_s_mkdir` issues. Permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14

---

@marcus-crane truthfully 1.14 will only fix a subset of permissions errors, but we won't know which ones are still around until it releases. 1.14 will be out soon ™, then we'll work on another round of permissions error fixes

**Closed by lynnco** 2016-11-12 05:58 UTC
