### ISSUE TITLE
Bundler complains about Gemfile.lock for no apparent reason

### ISSUE THREAD

**Issue by Overbryd** [bundler/bundler#5390] opened 2017-02-01 16:00 UTC
I don't get it. Sorry for this minimal "issue" but this stops my work right now, for no obvious reason.

I am using a specific Gemfile named `Gemfile.jruby` and configured with `BUNDLE_GEMFILE=Gemfile.jruby`. Locally I ran `bundle install` and checked the resulting `Gemfile.jruby.lock` into version control.

Remotely on the CI (using the same `BUNDLE_GEMFILE`) bundler tries to install gems for deployment:

```
bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
```

That results in the following error. **Note: none of the gems have changed in `Gemfile.jruby.lock`, only the order of appearance**.

```console
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.jruby.lock to version control.
You have added to the Gemfile:
* annotate (>= 2.6.5, ~> 2.6)
* rspec-rails (>= 3.4.2, ~> 3.4)
* simplecov (>= 0.12.0, ~> 0.12)
* shoulda-matchers (>= 2.8.0, ~> 2.8)

You have deleted from the Gemfile:
* annotate (>= 2.6.5, ~> 2.6)
* rspec-rails (>= 3.4.2, ~> 3.4)
* shoulda-matchers (>= 2.8.0, ~> 2.8)
* simplecov (>= 0.12.0, ~> 0.12)
```

**Comment by segiddins** [comment] 2017-02-01 16:21
This is a bug -- please share the output of `bundle env` so we can look into it

**Comment by Overbryd** [comment] 2017-02-02 13:58
Here is the output of `bundle env`: https://gist.github.com/Overbryd/02d2beecddacc8bffc325a3dd32e6d29

**Comment by segiddins** [comment] 2017-06-04 20:38
I can't reproduce this on either Bundler 1.15.1 nor Bundler 1.14.3

**Comment by segiddins** [comment] 2017-08-02 16:25
Closing because we could never reproduce.

**Closed by segiddins** 2017-08-02 16:25 UTC
Labels: status: ready, type: bug report

**Comment by faucct** [comment] 2018-07-04 08:28
I have faced the same issue and managed to localize it:

```bash
bundle init
echo "gem 'yard', '>= 0.9', '>= 0.9.0'" >> Gemfile
bundle
bundle --frozen
```

I guess this is the problem:

```ruby
Gem::Version.new("0.9.0") <=> Gem::Version.new("0.9")
# => 0
```
