### ISSUE TITLE
No such file or directory - git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet

### ISSUE THREAD

**Issue by zezima0** [bundler/bundler#4365] opened 2016-03-14 13:16 UTC
Here is the error I get, do you know how to solve this?

C:\Ruby22-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby22-x64\bin/bundle install
Fetching https://github.com/jejacks0n/mercury.git
Retrying git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet due to error (2/4): Errno::ENOENT No such file or directory - git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet
Retrying git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet due to error (3/4): Errno::ENOENT No such file or directory - git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet
Retrying git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet due to error (4/4): Errno::ENOENT No such file or directory - git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `C:\Ruby22-x64\bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    Errno::ENOENT: No such file or directory - git clone "https://github.com/jejacks0n/mercury.git" "C:/Ruby22-x64/lib/ruby/gems/2.2.0/cache/bundler/git/mercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a" --bare --no-hardlinks --quiet
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in ``'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in `block in git'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:71:in `call'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:71:in `with_clean_git_env'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:133:in `git'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:127:in `block in git_retry'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/retry.rb:38:in `call'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/retry.rb:38:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/retry.rb:28:in `attempt'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:126:in `git_retry'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git/git_proxy.rb:82:in `checkout'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git.rb:153:in `specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:541:in `block in converge_locked_specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:530:in `each'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:530:in `converge_locked_specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:192:in `resolve'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      C:/Ruby22-x64/bin/bundle:23:in `load'
      C:/Ruby22-x64/bin/bundle:23:in `<top (required)>'
      -e:1:in `load'
      -e:1:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
    GEM_HOME  C:/Ruby22-x64/lib/ruby/gems/2.2.0
    GEM_PATH  C:/Ruby22-x64/lib/ruby/gems/2.2.0;C:/Users/zezima/.gem/ruby/2.2.0
    Git       not installed
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=No+such+file+or+directory+-+git+clone+%22https%3A%2F%2Fgithub.com%2Fjejacks0n%2Fmercury.git%22+%22C%3A%2FRuby22-x64%2Flib%2Fruby%2Fgems%2F2.2.0%2Fcache%2Fbundler%2Fgit%2Fmercury-cda6f0a977e67f14dc7f94bde1bcb92f180ba37a%22+--bare+--no-hardlinks+--quiet&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

Process finished with exit code 1

**Comment by segiddins** [comment] 2016-03-14 15:55
The issue is that you don't have `git` available on your `PATH`

**Comment by zezima0** [comment] 2016-03-14 17:00
@segiddins Ok, but how to do that? Sorry I'm newbie here...

**Comment by segiddins** [comment] 2016-03-14 17:01
Well, if you want to use `git` dependencies in your Gemfile, you need to install Git (https://www.git-scm.com)

**Comment by zezima0** [comment] 2016-03-14 17:04
@segiddins I have already installed this :) Is there any tutorial how to add git to path?

**Comment by zezima0** [comment] 2016-03-14 18:01
@segiddins Ok, I have git im my PATH, but I still get this:

"C:\Program Files (x86)\JetBrains\RubyMine 8.0.3\bin\runnerw.exe" C:\Ruby22-x64\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/zezima/Projects/backup/script/rails server -b 127.0.0.1 -p 3000 -e production
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git.rb:191:in `rescue in load_spec_files': git://github.com/jejacks0n/mercury.git (at master@fee3bf2) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git.rb:188:in `load_spec_files'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/path.rb:92:in `local_specs'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/source/git.rb:159:in `specs'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:209:in `block (2 levels) in index'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:207:in `each'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:207:in `block in index'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/index.rb:9:in `build'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:204:in `index'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in `resolve'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
	from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/Users/zezima/Projects/backup/config/boot.rb:6:in `<top (required)>'
	from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/zezima/Projects/backup/script/rails:5:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1


How to solve it?

**Comment by allenzhao** [comment] 2016-03-15 06:55
@zezima0 Try this http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/
And you should close this issue if there's nothing wrong with bundler itself - as far as I could tell, no.

**Comment by allenzhao** [comment] 2016-03-24 13:06
@zezima0 Is this still valid? If not, can you close this?

**Closed** 2016-04-19 15:23 UTC
