### ISSUE TITLE
Source block resolution difficulty

### ISSUE THREAD

**Issue by garrypolley** [bundler/bundler#3537] opened 2015-03-31 17:54 UTC
I'm not sure if the following is a bug or not.  I'll describe my team's situation and see what everyone thinks. 

We have a Gemfile that looks like: 

```rb
source 'https://rubygems.org'

# Internal Gems
source 'http://in-house-url.com/rubygems/' do
  gem 'in-house-gem', '~> 1.0.0'
end
```

Where the `in-house-gem` is an in-house gem that has dependencies that are available on normal RubyGems.org.  The issue we are having is a resolution problem.  We do not mirror all of rubygems.org we only put our in-house gems in our gem repo. 

Whenever we run `bundle` we get an error about resolution.  It seems it expects all dependencies of the  gem to be at the `source` location.  

This is the error: 

```sh
Resolving dependencies...
Bundler could not find compatible versions for gem "whenever":
  In Gemfile:
    in-house-gem (~> 1.0) ruby depends on
      whenever (~> 0.8.4) ruby
Could not find gem 'whenever (~> 0.8.4) ruby', which is required by gem
'in-house-gem (~> 1.0) ruby', in any of the sources.
```

We can get this working by doing two different things: 

1. Specifying more than one top level gem repo (which leads to warnings and then we do not get to use `source` blocks).
2. Specifying all the dependencies outside of the `source` block that our gem depends on. 

In our ideal world the `source` block would look their first for the dependencies and then use the top level gem repository for ones it could not find at the `source` gem repo.  

I'm running Bundler version `1.9.2` and Ruby version `2.2.1` and I'm using a mac.

**Comment by indirect** [comment] 2015-03-31 19:55
I believe the desired behavior you're describing is how we would expect it to work. Thanks for the bug report, and we'll look into this!

**Comment by garrypolley** [comment] 2015-03-31 20:19
Thanks for looking into this issue. I believe we are using [Geminabox version](https://github.com/geminabox/geminabox/tree/0.5.2) `0.5.2` as our gem server.  It has not been updated in a long time.

**Comment by Strech** [comment] 2015-05-17 11:38
@indirect @garrypolley  So, I try to reproduce this bug locally. And what I get:

At lastest `geminabox`
```
Fetching gem metadata from http://geminabox.dev:9999/...
Fetching version metadata from http://geminabox.dev:9999/..
Fetching dependency metadata from http://geminabox.dev:9999/..
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing i18n 0.7.0
Installing json 1.8.2
Installing minitest 5.6.1
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.1
Installing chronic 0.10.2
Installing whenever 0.8.4
Installing dummy 0.0.1
Using bundler 1.9.2
Bundle complete! 1 Gemfile dependency, 10 gems now installed.
Bundled gems are installed into ./gems.
```

At `geminabox = 0.5.2`
```
Fetching source index from http://geminabox.dev:9999/
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "whenever":
  In Gemfile:
    dummy (~> 0.0.1) ruby depends on
      whenever (= 0.8.4) ruby
Could not find gem 'whenever (= 0.8.4) ruby', which is required by gem 'dummy (~> 0.0.1) ruby', in any of the sources.
```

When i start digging, i see that bundler (in any version, even HEAD) doesn't receive `whenever` spec at all (for `geminabox = 0.5.2`).

Looks like it's not bundler bug, it's just older rubygems server.
So, the easiest way is to update geminabox server (i had no problem with update)

**Comment by DmitryBochkarev** [comment] 2015-05-19 04:55
I have same bug. After run `bundle update` in my Gemfile.lock sources swap lines like this

Gemfile:

```
source 'https://example.com/'
source 'https://rubygems.org/'
```

Gemfile.lock:

```
GEM
  - remote: https://example.com/
    remote: https://rubygems.org/
 + remote: https://example.com/
```

**Comment by TimMoore** [comment] 2015-05-19 05:04
@Strech / @garrypolley I think this _is_ a Bundler bug, that may be triggered by the older version of geminabox. I'll try to give this a look soon.

@DmitryBochkarev your comment sounds like a different problem. Could you follow the instructions in https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems for creating a new issue with all of the information we need to troubleshoot it?

**Comment by DmitryBochkarev** [comment] 2015-05-19 05:08
Actually, maybe this is different bug, but only thing that changed was swapped lines in Gemfile.lock and gem versions.

**Comment by segiddins** [comment] 2015-05-19 05:16
In that case, please do open an issue so we can stop that from happening!

**Comment by Strech** [comment] 2015-05-19 09:16
@TimMoore Ok, i'll try to digg deeper :laughing:

**Comment by TimMoore** [comment] 2015-05-19 10:32
@Strech here is one clue in the output:

```
Fetching gem metadata from http://geminabox.dev:9999/...
Fetching version metadata from http://geminabox.dev:9999/..
Fetching dependency metadata from http://geminabox.dev:9999/..
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
```

vs.

```
Fetching source index from http://geminabox.dev:9999/
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
```

This means that it is using the dependency API with the new version of geminabox, but downloading the full index of all gems from the old version. This might be because dependency API support was added in a later version. When a source does not support the dependency API, Bundler falls back to downloading the full source index, but this should not change its resolution behaviour.

**Comment by TimMoore** [comment] 2015-05-19 10:33
If the whenever gem is actually not present in the geminabox server (or whatever source block the parent gem comes from), it should always fall back to finding it from rubygems.org.

**Comment by Strech** [comment] 2015-05-19 11:00
@TimMoore oh, got it. I'll try to check fallback in bundler

**Comment by Strech** [comment] 2015-05-20 09:55
@TimMoore So, what i get new:

The process looks like this

I have geminabox gem-server that doesn't support dependency api at all. At this server i've got 1 gem named `specific-name-donut` (strange name just to avoid existing on rubygems)

So this is a debug trace:
```
1. HTTP GET http://geminabox.dev:9999/api/v1/dependencies
   HTTP 404 Not Found
2. Fetching source index from http://geminabox.dev:9999/
   HTTP GET https://bundler.rubygems.org/api/v1/dependencies
   HTTP 200 OK
3. Fetching gem metadata from https://rubygems.org/
   Query List: ["specific-name-donut"]
   Query Gemcutter Dependency Endpoint API: specific-name-donut
   HTTP GET https://bundler.rubygems.org/api/v1/dependencies?gems=specific-name-donut
   HTTP 200 OK
   Query List: []
4. Fetching version metadata from https://rubygems.org/
   Query List: []
5. HTTP GET http://geminabox.dev:9999/quick/Marshal.4.8/specific-name-donut-0.0.1.gemspec.rz
   HTTP 200 OK
6. Resolving dependencies...

--- Result
Bundler could not find compatible versions for gem "whenever":
  In Gemfile:
    specific-name-donnut (~> 0.0.1) ruby depends on
      whenever (= 0.8.4) ruby
Could not find gem 'whenever (= 0.8.4) ruby', which is required by gem 'specific-name-donnut (~> 0.0.1) ruby', in any of the sources.
```

1. Bundler try to examine gem-server on dependency api – result is fail
2. Bundler try to load whole index from gem-server – result is success
  2.1 In loaded index bundler see 1 gem `specific-name-donut` without any dependency
3. Bundler try to find rubygems for `specific-name-donut` dependencies – result success
  3.1 Dependencies are empty list
4. Bundler try to load version metadata for empty dependency list – result success
  4.1 Versions are empty list

So at the beginning of resolve process i've got 2 index

1. geminabox with installed gems from `<ruby gems>/specifications/default` folder + `specific-name-donut` gem
2. rubyges with installed gems from `<ruby gems>/specifications/default` folder

So, when bundler start resolving dependencies for `specific-name-donut`, it try to find [dependency specific-name-donut](https://github.com/bundler/bundler/blob/1-10-stable/lib/bundler/resolver.rb#L249) and the step 5 occurs, but [without any pros](https://github.com/bundler/bundler/blob/1-10-stable/lib/bundler/resolver.rb#L274) because of `each`

**Comment by Strech** [comment] 2015-05-20 10:00
@TimMoore I don't know the right behavior for bundler, when at the beginning of resolving process, we don't know anything about gem dependency, and load them later, when try to resolve it.

What should we do if only full index available? I think in this case, if we load gem dependencies for this kind of source earlier, we could add them to dependency list and search for them before resolving process.

What do you think?

**Comment by agis-** [comment] 2015-05-21 10:24
I believe we are running into the same issue: We keep our forked gems in our private gem server (rubygems.xxx.com) and for the rest of them we use rubygems.org.

Here is how I managed to reproduce this:

1. We create a new folder with the following Gemfile (none of the gems are installed on my system):
    ```shell
    agis:bundler-bug $ cat Gemfile
    source 'https://rubygems.org'

    gem "rack-openid", '1.3.1' # rubygems.org

    source 'https://rubygems.example.com' do
      gem "ruby-openid", '2.1.8.1.example'
    end
    ```

2. Bundle:
   ```shell
   agis:bundler-bug $ bundle
   Fetching source index from https://rubygems.foobar.com/
   Fetching gem metadata from https://rubygems.org/...........
   Fetching version metadata from https://rubygems.org/..
   Resolving dependencies...
   Installing rack 1.6.1
   Installing ruby-openid 2.1.8.1.foobar
   Installing rack-openid 1.3.1
   Using bundler 1.9.9
   Bundle complete! 2 Gemfile dependencies, 4 gems now installed.
   Bundled gems are installed into ./vendor.
   ```

   The resulting Gemfile.lock is the following:

   ```shell
   agis:bundler-bug $ cat Gemfile.lock
   GEM
     remote: https://rubygems.org/
     remote: https://rubygems.foobar.com/
     specs:
       rack (1.6.1)
       rack-openid (1.3.1)
         rack (>= 1.1.0)
         ruby-openid (>= 2.1.8)
       ruby-openid (2.1.8.1.foobar)

   PLATFORMS
     ruby

   DEPENDENCIES
     rack-openid (= 1.3.1)
     ruby-openid (= 2.1.8.1.foobar)!
   ```

3. Add a new gem from rubygems.org. The updated Gemfile is this:

   ```ruby
   source 'https://rubygems.org'

   gem "rack-openid", '1.3.1'

   source 'https://rubygems.foobar.com' do
     gem "ruby-openid", '2.1.8.1.foobar'
   end

   gem "hashie" # new gem, from rubygems.org
   ```

4. Try to bundle:

   ```shell
   agis:bundler-bug $ bundle
   Fetching source index from https://rubygems.foobar.com/
   Fetching source index from https://rubygems.foobar.com/
   Fetching gem metadata from https://rubygems.org/...........
   Fetching version metadata from https://rubygems.org/..........
   Fetching version metadata from https://rubygems.org/...
   Fetching dependency metadata from https://rubygems.org/..
   Resolving dependencies...
   Bundler could not find compatible versions for gem "ruby-openid":
     In snapshot (Gemfile.lock):
       ruby-openid (= 2.1.8.1.foobar)

     In Gemfile:
       rack-openid (= 1.3.1) ruby depends on
         ruby-openid (>= 2.1.8) ruby

       ruby-openid (= 2.1.8.1.foobar) ruby

   Running `bundle update` will rebuild your snapshot from scratch, using only
   the gems in your Gemfile, which may resolve the conflict.
   ```


I noticed that if if I remove `Gemfile.lock` after the final step and do a
`$ bundle` again, everything works fine. But if after this I add repeat step
3 (with yet another gem), the exact same error message pops up.

Our gem server is a geminabox 0.6.1 and I'm on ruby 1.9.3 (although the same
applies to 2.1.5) and bundler 1.9.9 (tested with 1.9.6 too).

**Comment by Strech** [comment] 2015-05-21 19:26
@agis- What in your `.bundle/config` file?

**Comment by agis-** [comment] 2015-05-22 09:45
@Strech These are the relevant parts:

```
$ cat ~/.bundle/config
---
BUNDLE_BUILD__THRIFT: --with-cppflags=-D_FORTIFY_SOURCE=0
```

The project doesn't contain any project-specific bundle settings.

**Comment by agis-** [comment] 2015-05-22 13:32
Update: The actual Gemfile is ofcourse way bigger than the one in the demonstration, but the error report is actually the same (ie. `rack-openid` & `ruby-openid` are reported).

In addition to the last comment, another observation is that the bundle fails only if *both* of the following are true:

1. The `Gemfile.lock` is not outdated, meaning that bundler would update it if `$ bundle install` actually succeeded (ie. the case when you're adding a new gem)
2. The newly-added gem is not present in my system (also mentioned this before but for the shake of completeness)

**Comment by miah** [comment] 2015-06-02 19:03
This seems very much like a SOURCE PRIORITY issue; http://bundler.io/v1.9/man/gemfile.5.html#SOURCE-PRIORITY

"For implicit gems (dependencies of explicit gems), any source, git, or path repository declared on the parent. This results in bundler prioritizing the ActiveSupport gem from the Rails git repository over ones from rubygems.org"

**Comment by xaviershay** [comment] 2015-09-23 15:54
I think this is the same case as presented above:

```
Fetching source index from https://nexus-hosted-internal-gems/
Fetching gem metadata from https://internal-mirror/.......
Fetching version metadata from https://internal-mirror/..
Resolving dependencies...
Bundler could not find compatible versions for gem "stickler":
  In Gemfile:
    our_private_gem (~> 1.0) ruby depends on
      stickler (>= 0) ruby
Could not find gem 'stickler (>= 0) ruby', which is required by gem
'our_private_gem (~> 1.0) ruby', in any of the sources.Bundler could not find
compatible versions for gem "nexus":
  In Gemfile:
    our_private_gem (~> 1.0) ruby depends on
      nexus (>= 0) ruby
Could not find gem 'nexus (>= 0) ruby', which is required by gem 'our_private_gem
(~> 1.0) ruby', in any of the sources.
```

We are running nexus hosted rubygems: https://github.com/sonatype/nexus-ruby-support/wiki/Rubygems-setup Possibly same issue with not supporting latest index format?

Also note a small UI bug, a newline is missing: "any of the sources.Bundler could not find"

**Comment by normelton** [comment] 2015-09-29 14:14
Seems I'm having the same issue, but with an old-fashioned private gem repository (not gem-in-a-box):

    source 'https://rubygems.org'
    
    source 'http://repo.example.com/gems' do
      gem "my_custom_gem"
    end

I'm getting...

    Fetching source index from http://repo.example.com/gems/
    Fetching gem metadata from https://rubygems.org/..
    Fetching version metadata from https://rubygems.org/.
    Resolving dependencies..................
    Bundler could not find compatible versions for gem "redis":
      In Gemfile:
        my_custom_gem (>= 0) ruby depends on
          redis (>= 0) ruby
    Could not find gem 'redis (>= 0) ruby', which is required by gem 'my_custom_gem (>= 0) ruby', in any of the sources.

The docs seem to indicate that implicit gems (dependencies of explicit gems) should be fetched from any global repo source. Is this a bug or just a documentation error?

**Comment by pabloh** [comment] 2015-10-27 05:07
@Strech , I think I just run into this, do you is it feasible to make bundler fall-back to retrieving all the private source's gems and dependencies together when the API isn't available?.
BTW: Are you still considering this problem a bundler a issue or the server's (since this is still open...)?

**Comment by Strech** [comment] 2015-10-27 11:41
@pabloh Right now I'm stuck with this issue. It's not so easy to understand fetching internals. I point to the problem and ask for some help, but as you can see, nothing happened

**Comment by segiddins** [comment] 2015-10-27 14:37
We have a failing test that reproduces the bug, but given the difficulty in fixing it, it hasn't been a top priority for any of the team

**Comment by LynnCo** [comment] 2016-04-27 12:40
The test @segiddins mentioned is here #3696

**Comment by segiddins** [comment] 2016-08-08 19:54
This should now be fixed on the 2-0-dev branch.

**Closed by segiddins** 2016-08-08 19:54 UTC
Labels: status: working / ready, type: bug report
