### ISSUE TITLE
bundle clean extensions

### ISSUE THREAD

**Issue by dylanahsmith** [bundler/bundler#5596] opened 2017-04-18 20:56 UTC
Install any gem with an extension through bundler then try to remove it with `bundle clean --force` and the extension will still be in the file system.

For example, create a Gemfile

```
source "https://rubygems.org"
gem "cityhash"
```

then install and uninstall the gem using bundler

```
$ bundle install
...
Installing cityhash 0.8.1 with native extensions
...
$ find $GEM_HOME/extensions -name '*.bundle'
/Users/dylansmith/.gem/ruby/2.3.3/extensions/x86_64-darwin-15/2.3.0/cityhash-0.8.1/cityhash/cityhash.bundle
$ echo '' > Gemfile
$ bundle clean --force
Resolving dependencies...
Removing cityhash (0.8.1)
$ find $GEM_HOME/extensions -name '*.bundle'
/Users/dylansmith/.gem/ruby/2.3.3/extensions/x86_64-darwin-15/2.3.0/cityhash-0.8.1/cityhash/cityhash.bundle
```

but the extension wasn't cleaned.

A workaround would be to remove the `$GEM_HOME` path and re-installing bundler.

Note that my actual use case was that I want to uninstall a gem installed through bundler from a git source, where `gem uninstall` can't be used.

**Comment by segiddins** [comment] 2017-04-18 22:57
This seems intentional, according to https://github.com/bundler/bundler/pull/4030

**Comment by colby-swandale** [comment] 2017-05-16 11:06
@segiddins is there any action for this issue?

**Comment by segiddins** [comment] 2017-05-16 13:57
I don't know, the behavior reported seems to be intentional

**Comment by dylanahsmith** [comment] 2017-05-16 14:17
It looks like #4030 was about git gems having their extensions being removed **when they were still used**.

This issue is about gems that have been removed from the Gemfile.  Notice in the PR description that I do this by simply emptying the Gemfile with the following line

> $ echo '' > Gemfile

in my example, `bundle clean --force` does in fact remove the cityhash gem, so I don't see why the extension for the removed gem shouldn't also get removed.

**Comment by segiddins** [comment] 2017-06-21 23:12
In that case, a PR changing the behavior would be 💯

**Comment by indirect** [comment] 2017-06-22 16:25
I can confirm that not removing the extension is an accident, leftover from when extensions were moved outside of the directory containing the gem's other files. A PR to fix this would be great. 👍🏻

**Comment by colby-swandale** [comment] 2018-02-17 14:03
A PR to fix this issue has been merged and will be part of the next Bundler release.

**Closed by colby-swandale** 2018-02-17 14:03 UTC
Labels: contribution: unclaimed, type: bug report
