### ISSUE TITLE
Permission denied @ rb_file_s_rename

### ISSUE THREAD

**Issue by jmils** [bundler/bundler#5161] opened 2016-11-10 15:52 UTC
I can't run `bundle install` without doing `sudo bundle install` which worked but it says you shouldn't do this. Please let me know how I can fix this.

-
- What did you do?

  I ran the command `/Users/jamie/.rvm/gems/ruby-2.3.0/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/pk/3m7m_w8d551gwd3xzs7tzf200000gn/T/bundler-compact-index-20161110-34228-1rcxs9j/versions, /Users/jamie/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /Users/jamie/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/lazy_specification.rb:61:in `__materialize__'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:91:in `block in materialize'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/jamie/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/jamie/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
      /Users/jamie/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
      /Users/jamie/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      /Users/jamie/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
  GEM_HOME  /Users/jamie/.rvm/gems/ruby-2.3.0
  GEM_PATH  /Users/jamie/.rvm/gems/ruby-2.3.0:/Users/jamie/.rvm/gems/ruby-2.3.0@global
  RVM       1.27.0 (latest)
  Git       2.5.4 (Apple Git-61)
  rubygems-bundler (1.4.4)

**Comment by lynnco** [comment] 2016-11-12 06:02
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) `Permission denied` issues. A suite of permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14. Until 1.14 releases, the team doesn't have the capacity to deal with, or deploy more fixes for, the quantity of permissions errors we receive.

I'm sorry you are experiencing issues and I hope you can get them resolved!!!

**Closed by lynnco** 2016-11-12 06:02 UTC

**Comment by dilippanwar1** [comment] 2016-11-19 22:11
It was working fine for me but after some repetitive install of ruby and gems it is failing now.
I have a scenario where on one machine it is working and on another one, I am also facing same issue.
Can you suggest if any other version could work or any other workaround
