### ISSUE TITLE
bundle update --stdout (bundle update dry-run)

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4547] opened 2016-05-09 21:23 UTC
_From @sanemat on October 8, 2013 1:8_

This is not actual update, but this can easily compare with old one! If you have `Gemfile.lock` under version control(=not gem), then you can compare easily with git, but if you ignore `Gemfile.lock`(like gem), then you cant compare with old one.

Use case:

``` bash
$ diff Gemfile.lock <(bundle update --stdout)
4,9c4,5
<     addressable (2.3.5)
<     faraday (0.8.7)
<       multipart-post (~> 1.1)
<     faraday_middleware (0.9.0)
<       faraday (>= 0.7.4, < 0.9)
<     hashie (2.0.5)

---
>     faraday (0.8.8)
>       multipart-post (~> 1.2.0)
11d6
<     multi_json (1.7.7)
13,20c8,9
<     netrc (0.7.7)
<     octokit (1.25.0)
<       addressable (~> 2.2)
<       faraday (~> 0.8)
<       faraday_middleware (~> 0.9)
<       hashie (~> 2.0)
<       multi_json (~> 1.3)
<       netrc (~> 0.7.7)

---
>     octokit (2.1.1)
>       sawyer (~> 0.3.0)
23,24c12,16
<     safe_yaml (0.9.4)
<     tachikoma (3.0.5)

---
>     safe_yaml (0.9.5)
>     sawyer (0.3.0)
>       faraday (~> 0.8, < 0.10)
>       uri_template (~> 0.5.0)
>     tachikoma (3.0.7)
28a21
>     uri_template (0.5.3)
```

My implementation:

Not `bundle update --stdout` but `bundle-update_stdout update_stdout`.
http://rubygems.org/gems/bundler-update_stdout
https://github.com/sanemat/bundler-update_stdout

_Copied from original issue: bundler/bundler-features#30_

**Comment by LynnCo** [comment] 2016-05-09 21:23
_From @indirect on October 8, 2013 12:21_

I believe it would be more useful to have `bundle update --dry-run` that would print the gems that would be updated, but not actually update them. Would that work for you as well?

**Comment by LynnCo** [comment] 2016-05-09 21:23
_From @sheerun on October 17, 2013 12:51_

Duplicate of #2

**Comment by LynnCo** [comment] 2016-05-09 21:23
_From @sanemat on October 22, 2013 16:46_

I agree `bundle update --dry-run`, my concern is what output format is diff friendly, command friendly, pipe friendly. One example(in perl case), [cpan-outdated](http://search.cpan.org/dist/App-cpanoutdated/bin/cpan-outdated) provides `$ cpan-outdated |cpanm`, I feel this is beautiful.

`Gemfile.lock` format is useful, I think.

**Comment by segiddins** [comment] 2017-09-06 21:59
`bundle outdated --strict` already have this functionality

**Closed by segiddins** 2017-09-06 21:59 UTC
Labels: type: feature-request
