### ISSUE TITLE
Bundler 2 is already installed, still getting "You must use Bundler 2 or greater with this lockfile" error

### ISSUE THREAD

**Issue by stuartweir** [bundler/bundler#6937] opened 2019-01-30 21:57 UTC
After installing Bundler following the steps from this [page](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html), I cannot seem to run a test in rails.

The Gemfile.lock states at the bottom:
```
BUNDLED WITH
   2.0.1
```
Bundler Version:
```bash
$ bundler -v
Bundler version 2.0.1
```
**Rails Test failing even though Bundler 2 is installed**
```bash
$ bundle exec bin/rails test test/lib/my_rails_test_test.rb
You must use Bundler 2 or greater with this lockfile.
```

I have tried uninstalling and reinstalling Bundler:
```bash
$ gem uninstall bundler && gem install bundler
Successfully uninstalled bundler-2.0.1
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
Done installing documentation for bundler after 5 seconds
1 gem installed
```

Ruby version:
```bash
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
```

I'm really not sure what seems to be the issue here, or why it's failing. Any help appreciated.

**Comment by stuartweir** [comment] 2019-01-30 22:01
Looks like it might be somehow falling back on an old bundler?
```bash
$ gem list bundler

*** LOCAL GEMS ***

bundler (2.0.1, default: 1.17.3, 1.7.3)
capistrano-bundler (1.5.0, 1.3.0, 1.2.0)```

not sure how to set/force bundler to use 2.0.1

**Comment by hewrin** [comment] 2019-02-03 07:00
I am seeing a similar issue as well, if I delete Gemfile.lock and run bundle again, it says 
```
BUNDLED WITH
   1.16.0
```
Which is my old version of bundler

**Comment by morgoth** [comment] 2019-02-04 10:15
I have the same issue when using Rails and `bin/*` scripts in app.

Using bundler 2.0.1 with "2.0" mode on Rails 5.2.2 on Ruby 2.6.1

**Comment by deivid-rodriguez** [comment] 2019-02-04 11:19
Hello! I tried reproducing this with a fresh Rails app and could, can someone provide reproduction steps? Thanks!

**Comment by deivid-rodriguez** [comment] 2019-02-04 12:07
Reproduced now! Thanks! I'll look into it!

**Comment by deivid-rodriguez** [comment] 2019-02-04 12:22
Generating a bundler binstub with `bundle binstubs bundler` fixes the problem. @segiddins @indirect Is this expected?

If it is, I think we need to at least generate a bundler binstub together with any other binstub if it doesn't exist? :thinking:. And in any case, we should probably downgrade this error to a warning for now?

**Comment by connorshea** [comment] 2019-02-04 16:14
Yup, I had the same problem when using `bin/webpack-dev-server` provided by webpacker.

**Comment by mbell697** [comment] 2019-02-04 20:34
I don't think this is limited to a binstub issue, in an empty directory with no non-default gems installed:

```
❯ ruby --version
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
❯ gem list
*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
....
❯ gem install bundler
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
Done installing documentation for bundler after 2 seconds
1 gem installed
❯ gem list
*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (2.0.1, default: 1.17.2)
...
❯ ruby -rbundler -e 'puts Bundler::VERSION'
2.0.1
❯ ruby -rbundler/setup -e 'puts Bundler::VERSION'
1.17.2
```

Why is `bundler/setup` switching versions?

Adding a gemfile:

```
❯ echo "source 'https://rubygems.org'" > Gemfile
❯ bundle install
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
❯ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   2.0.1
 ❯ ruby -rbundler -e 'puts Bundler::VERSION'
2.0.1
❯ ruby -rbundler/setup -e 'puts Bundler::VERSION'                                                                                                                                               You must use Bundler 2 or greater with this lockfile.
```

Did something change about how `bundler/setup` is supposed to be used?

**Comment by mbell697** [comment] 2019-02-04 20:49
Strangely, requiring `bundler` before `bundler/setup` works correctly:

```
❯ ruby -r bundler -r bundler/setup -e 'puts Bundler::VERSION'
2.0.1
```

**Comment by deivid-rodriguez** [comment] 2019-02-04 21:33
Thanks for your investigations, I'll have another look tomorrow!

**Comment by stuartweir** [comment] 2019-02-04 21:54
So, an update at least for my purpose, which doesn't _actually_ solve the problem, but solved it for me.

Steps I took, in exact order:

1. Uninstall bundler
2. Uninstall ruby using rbenv
3. Uninstall rbenv (so, essentially, going bac to MacOS's base installed Ruby. 2.3.x
4. Re-install rbenv
5. Re-install ruby 2.4.1 using rbenv
6. Re-install bundler
7. `bundle install`

**Comment by mbell697** [comment] 2019-02-04 22:57
This seems like a wonky issue so I'm unsure how to open a PR but here is what I believe the issue / fix is:

Rubygems keeps a map of files from default gems and detects them to allow overriding with a normal gem, see: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/core_ext/kernel_require.rb#L39 and
https://github.com/rubygems/rubygems/blob/master/lib/rubygems.rb#L1240

This map is built from the `files` entry in the gemspec, and bundler is missing an entry for `bundler/setup`. In 1.17.2 it look likes this: `s.files = ["bundler.rb".freeze, "exe/bundle".freeze, "exe/bundler".freeze]` adding `bundler/setup` to the list locally resolves this issue but an actual fix for this, at least as I understand it, means updating the spec file that is shipped with Ruby so likely requires a 1.17.x bundler release that would need to be included in a Ruby 2.6.x release.

In the shorter term this may break a lot of stuff but at least the workaround is rather simple in that you just need to add `require 'bundler'` prior to `require 'bundler/setup'`.

**Comment by deivid-rodriguez** [comment] 2019-02-05 20:12
Thanks so much @mbell697, your diagnosis is perfect! I making some checks now to try figure out the best way to fix this :+1:.

**Comment by deivid-rodriguez** [comment] 2019-02-06 10:06
Just some heads up here. I have confirmed this is not a bundler nor a rubygems issue, but a ruby-core issue. Issue is fixed on master. I'll now run a bisection to find the culprit and request a backport.

**Comment by mbell697** [comment] 2019-02-06 14:28
Looks like it was fixed here: https://bugs.ruby-lang.org/issues/15582

**Comment by stuartweir** [comment] 2019-02-06 18:02
@deivid-rodriguez for those who are not on ruby 2.6.x, what would be the workaround aside from what I already did?

**Comment by connorshea** [comment] 2019-02-08 02:47
@deivid-rodriguez based on your comment from #6948, 2.6.0 doesn't have this issue but 2.6.1 does?

**Comment by deivid-rodriguez** [comment] 2019-02-08 09:42
Yes, that's what I observed on fresh `rbenv` installations of both versions. I don't know the reason though since the fix for this issue present in ruby-core's 2-6-stable reverts some installer changes made way before 2.6.0, and I didn't notice any relevant changes between 2.6.0 and 2.6.1. Maybe @hsbt has more insights.

**Comment by deivid-rodriguez** [comment] 2019-02-08 09:48
@stuartweir I don't think yours is the same issue because 2.6.0 is the first version to include `bundler` as a default gem... :thinking:. I'll try to repro yours again using 2.4.1.

**Comment by deivid-rodriguez** [comment] 2019-02-08 10:51
Note that this issue doesn't only affect `bundler` but all default gems, apparently. At least it also affects the `etc` gem, something I discovered in #6948.

I put together a small ruby script to sanitize an installation by reinstalling all default gems:

```ruby
# frozen_string_literal: true

require "open3"

out, status = Open3.capture2e("gem list | grep default:")

abort "ERROR: #{out}" unless status.success?

out.split("\n").each do |line|
  gem_name, gem_version = line.match(/^(?<gem_name>[[:graph:]]+) \(.*default: (?<gem_version>[0-9\.]+)/).captures

  print "Reinstalling #{gem_name}:#{gem_version} as a default gem... "

  out, status = Open3.capture2e("gem install #{gem_name}:#{gem_version} --default")

  if status.success?
    puts "OK"
  else
    puts out
  end
end
```

It currently fails for the `tracer` and `prime`, which [I reported to the `tracer` repo](https://github.com/ruby/tracer/issues/1).

**Comment by colby-swandale** [comment] 2019-02-14 10:53
Until Ruby 2.6.2 has been posted, the workaround seems to address this problem for now. Closing.

**Closed by colby-swandale** 2019-02-14 10:53 UTC

**Comment by deivid-rodriguez** [comment] 2019-02-16 13:09
Just noting down that my suggested fix in https://github.com/bundler/bundler/issues/6937#issuecomment-461764678 is likely to cause problems because of https://github.com/rubygems/rubygems/issues/2646, so we should cut a release of rubygems with the fix for that, and then recommend both workarounds, `gem update --system` first, and then reinstallations of any affected gems other than `bundler` with the updated rubygems client.

**Comment by deivid-rodriguez** [comment] 2019-02-22 16:57
Just a word of caution about my recommendation here: https://github.com/bundler/bundler/issues/6937#issuecomment-461764678.

I discovered that `gem install --default` currently has issues, like [installing wrong executables](https://github.com/rubygems/rubygems/pull/2649). So until the fix for this is released, the best workaround is `gem update --system`.

**Comment by antonzagorskii** [comment] 2020-01-15 09:33
Just do it

`spring stop`
