### ISSUE TITLE
bundle outdated shows yanked gem

### ISSUE THREAD

**Issue by jaredbeck** [bundler/bundler#3976] opened 2015-09-03 15:33 UTC
Not a big deal, but `bundle outdated` says the newest net-ssh is 2.10.0, though that version was yanked.

```
bundle -v
Bundler version 1.10.6
bundle outdated
# [snip]
  * net-ssh (newest 2.10.0, installed 2.9.2)
# [snip]
```

This screenshot shows that net-ssh 2.10.0 was yanked.

![screen shot 2015-09-03 at 11 29 42 am](https://cloud.githubusercontent.com/assets/380809/9662787/1f2f887a-522f-11e5-92bb-f228212262ce.png)

I see there was an older issue about this (https://github.com/bundler/bundler/issues/2256) but its clearly still an issue. (Though, again, not a big deal)

Thanks for all the work you do on bundler, can't imagine ruby without it!

**Comment by segiddins** [comment] 2015-10-04 18:46
@jaredbeck can you share a Gemfile and Gemfile.lock we can use to reproduce this? It's entirely possible it was a server-side issue (there's some lag puling new / yanked gems)

**Comment by jaredbeck** [comment] 2015-10-06 15:23
> can you share a Gemfile and Gemfile.lock we can use to reproduce this? 

Hmmm, `net-ssh` has released a new version, so even if I could dig up my Gemfile from a month ago, I don't think it would reproduce this issue, sorry.

**Comment by agis-** [comment] 2015-10-22 18:28
Confirmed it's @segiddins's hypothesis.

I've tried this right after yanking the most recent version of the gem. For a couple of minutes the yanked version was showing up in the output of `bundle outdated`.

Closing this since it's not a bundler issue.

**Closed by agis-** 2015-10-22 18:28 UTC
