### ISSUE TITLE
Could not work with bundler on different platforms (Windows and Linux) because of Gemfile.lock different. Re #635.

### ISSUE THREAD

**Issue by alhimicgithub** [bundler/bundler#4620] opened 2016-05-26 10:45 UTC
I have a team where each one works on different platforms (3 on Windows and 2 on Linux) so we are sure our app works good on different platform, our code is the same (it should works on different platforms because clients deploy system on different platforms, this is requirement) and gems are relevant. But because of Gemfile.lock generated differently for Win and Linux platforms we have 2 different Gemfile.lock.win and Gemfile.lock.nix. And have separate script that rename this file before run bundle install, to use appropriate .lock file. And it is important to have lock file on windows, not to delete it before do bundle install like hostings do (Heroku and ...), because it could lead to issues with new gems, what have happened a lot of times before. 

Are you going some how fix issue to able to run bundle on Windows and Linux machine and avoid issues with new gems?  I have read #635 issue and it was closed, but problem still appears, 6 years past. Personally I like solution offered here (issue  #3933 by 'rgb-one' commented on Aug 20, 2015). Or add this issue as fact in known issues, so we will stay with our approach. 
Stick with versions for all gems in Gemfile also not good solution for us.
Sorry for so much text, just to avoid XY problem.

**Comment by LynnCo** [comment] 2016-06-02 09:03
Given that this has been brought up before, it will likely require code changes that won't make it until the Better Platform Support release (ie. not a bugfix release)

**Comment by segiddins** [comment] 2016-06-02 13:20
@alhimicgithub is there any reason the `platforms` DSL option doesn't work for you?

**Comment by alhimicgithub** [comment] 2016-06-02 18:26
@segiddins `platforms` works good from Gemfile file, but isn't taken into account in Gemfile.lock as it should, (f.e. pg gem, has min-gw for windows and will be delete on Linux Gemfile.lock), that is this issue about. So yes kind of solution could be that bundler differentiate and locate gems for each platform in Gemfile.lock, and store them in platforms section for example.

**Comment by segiddins** [comment] 2016-06-02 21:33
The gem file.lock can track multiple platforms, so I'm still unclear on why platform support is insufficient

**Comment by indirect** [comment] 2016-06-02 21:38
@segiddins it doesn't actually work. :( you can't install across the windows/unix boundary with the same lock. this is (depending on how you look at it) either a huge and very old bug, or a planned feature that we never finished.

**Comment by headius** [comment] 2016-06-13 17:22
This also affects anyone committing a Gemfile.lock from MRI and then trying to use JRuby. For example, "pry" under JRuby requires "spoon", while MRI doesn't. Also, "pry" and "ffi" have -java versions, but the lock file can't reflect that AND the non-java exts that MRI uses.

So basically, you can't even switch from MRI to JRuby with a given lock file, if any of the dependencies have extensions (think ffi, nokogiri, racc, json, and a TON of others).

**Comment by headius** [comment] 2016-06-13 17:24
I should also point out that a Gemfile.lock on JRuby would break on MRI, due to incompatible dependencies (usually exts).

**Comment by headius** [comment] 2016-06-13 17:26
See here for the latest case of this: https://travis-ci.org/Calvyn82/oorb/jobs/137291735

Under JRuby, "pry" installs a -java version, which has a dependency on "spoon". MRI does not have such a dependency (and can't install -java platform gems anyway), so --deployment fails.

**Comment by headius** [comment] 2016-06-13 18:43
A simpler fix than reworking how Gemfile.lock is structured would be to emit Gemfile.<platform>.lock, with some fallback to Gemfile.ruby.lock or Gemfile.lock if platform-specific lock files don't exist. We have some users that monkey-patch Bundler now to do exactly that, since they dev in MRI and deploy in JRuby.

**Comment by segiddins** [comment] 2016-08-04 22:11
Is there a reproduction case for this I can test my fixes against?

**Comment by segiddins** [comment] 2016-12-05 16:52
Ping for a reproduction case? Otherwise we'll have to close this issue. Thanks!

**Comment by agross** [comment] 2016-12-05 17:01
`bundle install` this on Linux and see how the lockfile is modified (is was generated on Windows). 

``` 
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    adsf (1.2.1)
      rack (>= 1.0.0)
    archive-zip (0.7.0)
      io-like (~> 0.3.0)
    ast (2.3.0)
    awesome_print (1.7.0)
    babosa (1.0.2)
    builder (3.2.2)
    byebug (9.0.6)
    chromedriver-helper (1.0.0)
      archive-zip (~> 0.7.0)
      nokogiri (~> 1.6)
    chunky_png (1.3.8)
    closure-compiler (1.1.12)
    coderay (1.1.1)
    colored (1.2)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.2)
    configatron (4.5.0)
    crass (1.0.2)
    cri (2.7.0)
      colored (~> 1.2)
    diff-lcs (1.2.5)
    docile (1.1.5)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    eventmachine (1.2.1-x64-mingw32)
    ffi (1.9.14-x64-mingw32)
    formatador (0.2.5)
    guard (2.14.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    guard-haml_lint (0.1.4)
      guard (~> 2.2)
      guard-compat (~> 1.1)
      haml_lint (>= 0.15.2)
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    guard-rack (2.2.0)
      ffi
      guard (~> 2.3)
      spoon
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.2.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    haml (4.0.7)
      tilt
    haml_lint (0.18.4)
      haml (~> 4.0)
      rake (>= 10, < 12)
      rubocop (>= 0.36.0)
      sysexits (~> 1.1)
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    htmlcompressor (0.3.1)
    htmlentities (4.3.4)
    http_parser.rb (0.6.0)
    io-like (0.3.0)
    json (2.0.2)
    kramdown (1.13.1)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    lumberjack (1.0.10)
    method_source (0.8.2)
    mini_portile2 (2.1.0)
    multi_json (1.12.1)
    nanoc (4.4.2)
      cri (~> 2.3)
      hamster (~> 3.0)
      parallel (~> 1.9)
      ref (~> 2.0)
    nanoc-cachebuster (0.4.0)
      nanoc (>= 3.3.0)
    nenv (0.3.0)
    nokogiri (1.6.8.1-x64-mingw32)
      mini_portile2 (~> 2.1.0)
    nokogumbo (1.4.10)
      nokogiri
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oily_png (1.2.1)
      chunky_png (~> 1.3.7)
    parallel (1.10.0)
    parser (2.3.3.0)
      ast (~> 2.2)
    powerpack (0.1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.1)
      byebug (~> 9.0)
      pry (~> 0.10)
    public_suffix (2.0.4)
    r18n-core (2.1.4)
    rack (2.0.1)
    rack-livereload (0.3.16)
      rack
    rainbow (2.1.0)
    rake (11.3.0)
    rake-funnel (0.18.0)
      configatron (~> 4.5)
      rake (>= 10.4, < 12)
      rubyzip (~> 1.0)
      smart_colored
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    ref (2.0.0)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.45.0)
      parser (>= 2.3.1.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    rubocop-checkstyle_formatter (0.3.0)
      rubocop (>= 0.30.1)
    rubocop-rspec (1.8.0)
      rubocop (>= 0.42.0)
    ruby-prof (0.16.2)
    ruby-progressbar (1.8.1)
    ruby_dep (1.5.0)
    ruby_gntp (0.3.4)
    rubyzip (1.2.0)
    sanitize (4.4.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.4.4)
      nokogumbo (~> 1.4.1)
    sass (3.4.22)
    shellany (0.0.1)
    simplecov (0.12.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    simplecov-teamcity-summary (0.1.2)
      simplecov
    slop (3.6.0)
    smart_colored (1.1.1)
    spoon (0.0.6)
      ffi
    sysexits (1.2.0)
    terminal-notifier-guard (1.7.0)
    thor (0.19.4)
    thread_safe (0.3.5)
    tilt (2.0.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    tzinfo-data (1.2016.10)
      tzinfo (>= 1.0.0)
    unicode-display_width (1.1.1)
    wdm (0.1.1)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  addressable
  adsf
  awesome_print
  babosa
  builder
  chromedriver-helper (~> 1.0)
  closure-compiler
  compass (~> 1.0)
  guard-bundler
  guard-haml_lint
  guard-livereload
  guard-rack (~> 2.2)
  guard-rspec
  guard-rubocop
  haml
  htmlcompressor
  htmlentities
  kramdown
  nanoc (~> 4.3)
  nanoc-cachebuster
  nokogiri (~> 1.6)
  oily_png
  pry-byebug
  r18n-core
  rack
  rack-livereload
  rake-funnel
  rb-fsevent
  rb-inotify
  rspec (~> 3.0)
  rubocop
  rubocop-checkstyle_formatter
  rubocop-rspec
  ruby-prof
  ruby_gntp
  sanitize
  simplecov
  simplecov-teamcity-summary
  terminal-notifier-guard
  tzinfo
  tzinfo-data
  wdm

BUNDLED WITH
   1.13.6 
```

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 3158ee5..e5962b7 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -41,7 +41,9 @@ GEM
     em-websocket (0.5.1)
       eventmachine (>= 0.12.9)
       http_parser.rb (~> 0.6.0)
+    eventmachine (1.2.1)
     eventmachine (1.2.1-x64-mingw32)
+    ffi (1.9.14)
     ffi (1.9.14-x64-mingw32)
     formatador (0.2.5)
     guard (2.14.0)
@@ -109,6 +111,8 @@ GEM
     nanoc-cachebuster (0.4.0)
       nanoc (>= 3.3.0)
     nenv (0.3.0)
+    nokogiri (1.6.8.1)
+      mini_portile2 (~> 2.1.0)
     nokogiri (1.6.8.1-x64-mingw32)
       mini_portile2 (~> 2.1.0)
     nokogumbo (1.4.10)
@@ -203,6 +207,7 @@ GEM
     wdm (0.1.1)
 
 PLATFORMS
+  ruby
   x64-mingw32
 
 DEPENDENCIES
```

**Comment by segiddins** [comment] 2016-12-05 18:49
This is intended behavior -- as of 1.13, you could run `bundle lock --add-platform ruby` on Windows to add the ruby platform to your lockfile ahead of time

**Comment by agross** [comment] 2016-12-05 19:25
Interesting, thanks. Is this a remembered option or do I have to run this again? (As well as Linux devs have to `--add-platform x64-mingw32`?) 

Is there a reason why this is not documented? (Just had a look at http://bundler.io/v1.13/man/bundle-lock.1.html)

**Comment by segiddins** [comment] 2016-12-05 20:16
You just have to run it once to get the platform into your lockfile, once it's there it should stay there

**Comment by hackhowtofaq** [comment] 2016-12-28 14:47
Could you please add this to the documentation? OR Is there a reason for not being there as @agross noticed?

Ty

**Comment by segiddins** [comment] 2016-12-28 15:29
It's been added to the bundle lock docs on master

**Comment by hackhowtofaq** [comment] 2016-12-29 07:51
How do we solve the problem, of getting the same gem from different location according to platform?
i.e.
```
gem 'resque', path: "Y://my_gems/resque", platforms: [:mswin, :mingw]
gem 'resque', path: "/media/hdd1/my_gems/resque", platforms: :ruby
```

The above is not working 
I'm getting `There was an error parsing 'Gemfile'.......`



Ty

**Comment by segiddins** [comment] 2016-12-29 13:56
@hackhowtofaq that's not currently supported

**Comment by segiddins** [comment] 2017-06-04 21:22
Closing as I believe `bundle lock` is the correct way to handle the multiple platform situation. Feel free to ping us if something further is need.

**Closed by segiddins** 2017-06-04 21:22 UTC
Labels: type: bug report
