### ISSUE TITLE
dependency solving across multiple sources

### ISSUE THREAD

**Issue by idoa01** [bundler/bundler#3595] opened 2015-04-27 18:17 UTC
I'm currently using bundler 1.9.4 and I'm trying to install a gem from a private repo which depends on gems from rubygems.org

##### Gemfile:
```rb
source 'https://rubygems.org'

source 'http://somerepo/geminabox' do
  gem "gem_a", ">=0.2.0"
end
```
`gem_a` depends on `bunny` and I'm getting the following error:
```
Fetching source index from http://somerepo/geminabox
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bunny":
  In Gemfile:
    gem_a (>= 0.2.0) ruby depends on
      bunny (~> 0.9.0.pre7) ruby
Could not find gem 'bunny (~> 0.9.0.pre7) ruby', which is required by gem 'gem_a (>= 0.2.0) ruby', in any of the sources.
```
using `--full-index` or flattening the gemfile, I get the expected result (all the gems installed), but I prefer to use the new syntax to specify the origin of the gem.
##### (flattened Gemfile):
```rb
source 'https://rubygems.org'
source 'http://somerepo/geminabox'

gem "gem_a", ">=0.2.0"
```

##### bundle env:
```
    Bundler   1.9.4
    Rubygems  2.4.5
    Ruby      2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

    RVM       1.26.9 (latest)
    Git       1.9.1
```

**Comment by idoa01** [comment] 2015-04-27 18:24
hmm... seems like a duplicate of #3537. 
sorry about that.

**Comment by agis-** [comment] 2015-10-21 17:20
Closing as a duplicate of #3537 indeed.

**Closed by agis-** 2015-10-21 17:20 UTC
Labels: duplicate
