### ISSUE TITLE
infinite loop resolving dependencies

### ISSUE THREAD

**Issue by islam-taha** [bundler/bundler#5642] opened 2017-05-05 14:08 UTC
I've created [this gist ](https://gist.github.com/islam-taha/6f7e7b98214790e02185f9faf657a905)which contains my gemfile causing this issue along with the 

`DEBUG_RESOLVER=1 bundle update -VV` command output which is repeated in the infinite loop.

**Note**: this issue is not appearing when removing `gem 'split' `

**bundler version '1.15.0.pre.3'**

**Comment by segiddins** [comment] 2017-05-05 17:26
Please share the output of `bundle env`, thanks!

**Comment by islam-taha** [comment] 2017-05-05 17:30
Here it is [bundlenv.txt](https://github.com/bundler/bundler/files/979835/bundlenv.txt).

**Comment by segiddins** [comment] 2017-05-10 19:25
I cannot reproduce the issue with the given `Gemfile` and `Gemfile.lock`

**Comment by islam-taha** [comment] 2017-05-13 21:15
The issue still exist with ruby 2.3.1!

**Comment by fukayatsu** [comment] 2017-05-18 04:09
I'm in the same situation: [gist: bundle env & log](https://gist.github.com/fukayatsu/7274a2f51c4250cd96870672a9c5be54)

I added `gem 'rack', '~> 1.0'` to my Gemfile as workaround .

**Comment by segiddins** [comment] 2017-07-19 14:55
Confirmed the issue with @fukayatsu's Gemfile, and confirmed that I am _unable_ to reproduce it with @islam-taha's.

**Comment by greysteil** [comment] 2017-09-15 19:52
This is fixed in the 1.16.0 pre-releases by all the resolver work we did. Confirmed both Gemfiles resolve in less than a second.

This can be closed.

**Closed** 2017-09-16 05:38 UTC
Labels: type: bug report
