### ISSUE TITLE
bundle update rdoc

### ISSUE THREAD

**Issue by araujodelucas** [bundler/bundler#6126] opened 2017-10-26 12:52 UTC
```
[perfcenter@ip-172-31-20-13 dashboard]$ bundle update rdoc
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Your lockfile was created by an old Bundler that left some things out.
You can fix this by adding the missing gems to your Gemfile, running bundle instal l, and then removing the gems from your Gemfile.
The missing gems are:
* rdoc depended upon by sdoc
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.4
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.6.2
Using arel 6.0.3
Using execjs 2.6.0
Using htmlentities 4.3.4
Using rubyzip 1.0.0
Using debug_inspector 0.0.2
Using sass 3.4.19
Using thor 0.19.1
Using bundler 1.15.4
Using byebug 8.2.0
Using chunky_png 1.3.5
Using coffee-script-source 1.10.0
Using multi_json 1.11.2
Using rb-fsevent 0.9.6
Using ffi 1.9.10
Using hike 1.2.3
Using tilt 1.4.1
Using http_accept_language 2.0.5
Using libv8 3.16.14.13 (x86_64-linux)
Using oj 2.14.6
Using oj_mimic_json 1.0.1
Using pg 0.18.4
Using ref 2.0.0
Using spring 1.4.3
Using tzinfo 1.2.2
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using mail 2.6.3
Using autoprefixer-rails 6.1.0.1
Using uglifier 2.7.2
Using binding_of_caller 0.7.2
Using compass-import-once 1.0.5
Using coffee-script 2.4.1
Using compass-core 1.0.3
Using rb-inotify 0.9.5
Using sprockets 2.12.4
Fetching therubyracer 0.12.2
Installing therubyracer 0.12.2 with native extensions
Using activesupport 4.2.5
Using loofah 2.0.3
Using axlsx 2.0.1
Using bootstrap-sass 3.3.5.1
Using compass 1.0.3
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5
Using jbuilder 2.3.2
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.5
Using activerecord 4.2.5
Using actionview 4.2.5
Using actionpack 4.2.5
Using actionmailer 4.2.5
Using railties 4.2.5
Using sprockets-rails 2.3.3
Using momentjs-rails 2.10.6
Using coffee-rails 4.1.0
Using font-awesome-rails 4.6.3.0
Using jquery-rails 4.0.5
Using sass-rails 5.0.4
Using rails 4.2.5
Fetching web-console 2.2.1
Installing web-console 2.2.1
Using bootstrap3-datetimepicker-rails 4.17.37
Fetching turbolinks 2.5.3
Installing turbolinks 2.5.3
Using compass-rails 2.0.5
Using dom_routes 1.0.3
```

# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `/usr/local/rvm/gems/ruby-2.3.1/bin/bundle update rdoc`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, st ack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/mas ter/doc/contributing/ISSUES.md?**

  ...

## Backtrace

```
fatal: No live threads left. Deadlock?
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/worker.rb:43:in ` pop'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/worker.rb:43:in ` deq'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer/paralle l_installer.rb:132:in `process_specs'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer/paralle l_installer.rb:103:in `call'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer/paralle l_installer.rb:77:in `call'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer.rb:199: in `install_in_parallel'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer.rb:166: in `install'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer.rb:80:i n `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/installer.rb:24:i n `install'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/cli/update.rb:50: in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/cli.rb:228:in `up date'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/t hor/command.rb:27:in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/t hor/invocation.rb:126:in `invoke_command'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/t hor.rb:387:in `dispatch'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dis patch'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/t hor/base.rb:466:in `start'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `sta rt'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <t op (required)>'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.r b:121:in `with_friendly_errors'
  /usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (requi red)>'
  /usr/local/rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
  /usr/local/rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
  /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

## Environment

```
Bundler   1.15.4
Rubygems  2.6.14
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
GEM_HOME  /opt/perfcenter/dashboard/vendor/bundle/ruby/2.3.0
GEM_PATH
RVM       1.29.3 (latest)
Git       2.13.6
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2k  26 Jan 2017
```

## Bundler settings

```
—local
  Set for the current user (/opt/perfcenter/.bundle/config): "build.pg —with-pg-co nfig=/usr/lib64/pgsql92/bin/pg_config"
frozen
  Set for your local app (/opt/perfcenter/dashboard/.bundle/config): true
path
  Set for your local app (/opt/perfcenter/dashboard/.bundle/config): "vendor/bundl e"
disable_shared_gems
  Set for your local app (/opt/perfcenter/dashboard/.bundle/config): true
```

### Gemfile

```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: http s://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# I18N
gem 'http_accept_language', '~> 2.0'

# Framework CSS
gem 'compass-rails', '~> 2.0.4'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'font-awesome-rails', '~> 4.6.0'
gem 'autoprefixer-rails'

# Framework javascript
gem 'dom_routes', '~> 1.0.3'

# Faster JSON
gem 'oj', '~> 2.14.6'
gem 'oj_mimic_json', '~> 1.0.1'

# SLM - geracao de arquivos xlsx
gem 'axlsx', '~> 2.0.1'

# widgets complementares
gem 'momentjs-rails', '~> 2.10.6'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger consol e
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the backgr ound. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    autoprefixer-rails (6.1.0.1)
      execjs
      json
    axlsx (2.0.1)
      htmlentities (~> 4.3.1)
      nokogiri (>= 1.4.1)
      rubyzip (~> 1.0.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
    bootstrap3-datetimepicker-rails (4.17.37)
      momentjs-rails (>= 2.8.1)
    builder (3.2.2)
    byebug (8.2.0)
    chunky_png (1.3.5)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    compass-rails (2.0.5)
      compass (~> 1.0.0)
      sass-rails (< 5.1)
      sprockets (< 2.13)
    debug_inspector (0.0.2)
    dom_routes (1.0.3)
      rails (>= 3.2)
    erubis (2.7.0)
    execjs (2.6.0)
    ffi (1.9.10)
    font-awesome-rails (4.6.3.0)
      railties (>= 3.2, < 5.1)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    hike (1.2.3)
    htmlentities (4.3.4)
    http_accept_language (2.0.5)
    i18n (0.7.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    libv8 (3.16.14.13)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.2)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    momentjs-rails (2.10.6)
      railties (>= 3.1)
    multi_json (1.11.2)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    oj (2.14.6)
    oj_mimic_json (1.0.1)
    pg (0.18.4)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (11.1.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.0)
    ref (2.0.0)
    rubyzip (1.0.0)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spring (1.4.3)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  autoprefixer-rails
  axlsx (~> 2.0.1)
  bootstrap-sass (~> 3.3.4)
  bootstrap3-datetimepicker-rails (~> 4.17.37)
  byebug
  coffee-rails (~> 4.1.0)
  compass-rails (~> 2.0.4)
  dom_routes (~> 1.0.3)
  font-awesome-rails (~> 4.6.0)
  http_accept_language (~> 2.0)
  jbuilder (~> 2.0)
  jquery-rails
  momentjs-rails (~> 2.10.6)
  oj (~> 2.14.6)
  oj_mimic_json (~> 1.0.1)
  pg (~> 0.15)
  rails (= 4.2.5)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  therubyracer
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.11.2
```

**Comment by segiddins** [comment] 2017-10-26 13:45
This is probably caused by:

```
Your lockfile was created by an old Bundler that left some things out.
You can fix this by adding the missing gems to your Gemfile, running bundle instal l, and then removing the gems from your Gemfile.
The missing gems are:
* rdoc depended upon by sdoc
```

which was at the top of the command output -- did you try adding `doc` to your Gemfile?

**Comment by colby-swandale** [comment] 2017-11-01 11:20
ping @araujodelucas

**Comment by colby-swandale** [comment] 2017-11-19 04:48
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Closed** 2017-11-19 04:48 UTC
Labels: status: user feedback required
