### ISSUE TITLE
Should the `path:` option add gems to LOAD_PATH if they're not included in dependencies?

### ISSUE THREAD

**Issue by deivid-rodriguez** [bundler/bundler#6058] opened 2017-09-23 21:52 UTC
I'm not sure if this is expected behaviour or not. We're might be doing unsupported stuff, but I thought it might be worth asking.

* We have a project structure like the following:

```shell
.
├── decidim.gemspec
├── decidim-assemblies
│   └── decidim-assemblies.gemspec
├── decidim-admin
│   └── decidim-admin.gemspec
├── decidim-participatory_processes
│   └── decidim-participatory_processes.gemspec
... # More similar gems
└── test_app
    ├── Gemfile
    └── Gemfile.lock

3 directories, 5 files
```

* Every `decidim-*` subgem is a runtime dependency of the `decidim` root gem, _except for_ `decidim-assemblies`.

* In the `test_app`'s `Gemfile`, we specifiy `gem "decidim" , path: ".."` so that it uses the local version of our library.

With this setup, I would expect `decidim-assemblies` to be ignored from the test app dependencies. However, this is only partly true since even though `decidim-assemblies` is not included in the test app `Gemfile.lock` file, it _is_ added to the LOAD_PATH.

This is because `decidim-assemblies.gemspec` adds itself to the LOAD_PATH as it's normally done in gemspecs, but I wonder if this gemspec should not be read at all in this situation?

I wrote a test case to better illustrate the situation

```diff
diff --git a/spec/install/gemfile/path_spec.rb b/spec/install/gemfile/path_spec.rb
index f7789e7ea..f0fd38f55 100644
--- a/spec/install/gemfile/path_spec.rb
+++ b/spec/install/gemfile/path_spec.rb
@@ -114,6 +114,51 @@ RSpec.describe "bundle install with explicit source paths" do
     expect(out).to eq("WIN OVERRIDE")
   end
 
+  it "does not add local gems to load path when they're not dependencies" do
+    build_lib "foo", :path => lib_path("nested/foo")
+
+    gemspec = lib_path("nested/foo").join("foo.gemspec").to_s
+    File.open(gemspec, "w") do |f|
+      f.write <<-G
+        # -*- encoding: utf-8 -*-
+        # stub: foo 1.0 ruby lib
+
+        lib = File.expand_path("../lib", __FILE__)
+        $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
+
+        Gem::Specification.new do |s|
+          s.name = "foo".freeze
+          s.version = "1.0"
+
+          s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
+          s.require_paths = ["lib".freeze]
+          s.authors = ["no one".freeze]
+          s.date = "2017-09-23"
+          s.description = "This is a completely fake gem, for testing purposes.".freeze
+          s.email = "foo@bar.baz".freeze
+          s.homepage = "http://example.com".freeze
+          s.licenses = ["MIT".freeze]
+          s.rubygems_version = "2.6.13".freeze
+          s.summary = "This is just a fake gem for testing".freeze
+        end
+      G
+    end
+
+    build_lib "bar", :path => lib_path("nested/bar")
+
+    build_lib "omg", :path => lib_path("nested") do |s|
+      s.add_dependency "bar"
+    end
+
+    install_gemfile <<-G
+      source "file://#{gem_repo1}"
+      gem "omg", :path => "#{lib_path("nested")}"
+    G
+
+    bundle 'exec ruby -e \'puts $LOAD_PATH.any? { |p| p.include?("nested/bar/lib") }\''
+    expect(out).to eq("false")
+  end
+
```

**Comment by colby-swandale** [comment] 2017-09-24 21:33
My initial reaction says this does look like a bug, @segiddins thoughts?

**Comment by colby-swandale** [comment] 2017-09-27 07:01
\cc @indirect

**Comment by indirect** [comment] 2017-09-27 08:05
I'm open to feedback, but I think this is not a bug. Bundler, by definition, needs to read the gemspecs of any gems that are available in a source. Bundler isn't putting this gem in your load path, this gem is adding itself to the load path.

In git gems or packaged gems, Bundler solves this problem by evaluating a gemspec once and then converting it into a YAML gemspec that no longer runs code, including not editing the load path. It seems like if you want a gem to stay out of the load path, its gemspec needs to not add itself to a load path.

**Comment by deivid-rodriguez** [comment] 2017-09-27 08:30
@indirect Thanks for the input!

> I'm open to feedback, but I think this is not a bug. Bundler, by definition, needs to read the gemspecs of any gems that are available in a source. Bundler isn't putting this gem in your load path, this gem is adding itself to the load path.

Yup, I understood that. My expectation though would be that the gemspec should not be read at all, because I'm not telling `bundler` to do it. I think that `path: /my/path` should not read all gemspecs present in `/my/path` (as in `/my/path/**/*.gemspec`). It should only read `/my/path/{Gemfile,*.gemspec}`, resolve it, and then read the gemspecs in subfolders if `Gemfile`'s resolution says so (via `path: /my/path/subpath`).

> In git gems or packaged gems, Bundler solves this problem by evaluating a gemspec once and then converting it into a YAML gemspec that no longer runs code, including not editing the load path. It seems like if you want a gem to stay out of the load path, its gemspec needs to not add itself to a load path.

Not sure I understand this, you mean that every subgem's gemspec is still read once with the `git:` source? If I change my example from `path:` to `git:`, things work as I expect, so I would assume `decidim-assemblies.gemspec` is never read in this case. :thinking:

**Comment by indirect** [comment] 2017-09-27 08:57
@deivid-rodriguez Every gemspec inside a path must be read, to find out if it is a gem that needs to be installed or not. For example, the Rails repo contains many subgems, some or all of which are depended on by the `rails.gemspec`. So if we were to stop evaluating all sub-gem gemspecs, the Rails repo would stop working. Sub-gemfiles are not ever evaluated—that just isn't a thing that Bundler has ever done.

As for the other types of sources, yes, both `gem build foo.gemspec` and using `git: 'url'` in your Gemfile mean that RubyGems or Bundler will evaluate the gemspec once, store the results as YAML, and never eval the gemspec again while reading, installing, or using that gem.

**Comment by deivid-rodriguez** [comment] 2017-09-27 09:07
> @deivid-rodriguez Every gemspec inside a path must be read, to find out if it is a gem that needs to be installed or not. For example, the Rails repo contains many subgems, some or all of which are depended on by the rails.gemspec. So if we were to stop evaluating all sub-gem gemspecs, the Rails repo would stop working. Sub-gemfiles are not ever evaluated—that just isn't a thing that Bundler has ever done.

Yup, I understand that this would be a breaking change indeed, since requiring gems in subpaths would need to be done explicitly as I suggested. And I get that you have no intentions to change it, that's cool :+1:.

> As for the other types of sources, yes, both gem build foo.gemspec and using git: 'url' in your Gemfile mean that RubyGems or Bundler will evaluate the gemspec once, store the results as YAML, and never eval the gemspec again while reading, installing, or using that gem.

I'm still not clear about this. In the case of the `git:` source, if the repo has gems in subpaths but they are not explicited as dependencies of the root gem, I'd say those gemspecs are NEVER read, not even once.

**Comment by colby-swandale** [comment] 2018-01-27 02:23
I'm closing this. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Closed by colby-swandale** 2018-01-27 02:23 UTC

**Comment by deivid-rodriguez** [comment] 2018-01-27 13:00
@colby-swandale Well, yes, it was just not acknowledged as a bug.
