### ISSUE TITLE
bundle exec rspec is not running

### ISSUE THREAD

**Issue by KMadhuSudhan** [bundler/bundler#5618] opened 2017-04-26 16:07 UTC
bundle env
The git source `git://github.com/rweng/jquery-datatables-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/sumoheavy/jira-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Your Gemfile lists the gem faker (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
## Environment

```
Bundler   1.14.6
Rubygems  2.6.10
Ruby      2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
GEM_HOME  /Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0
GEM_PATH  /Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0:/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0@global
RVM       1.29.1 (latest)
Git       2.12.0
Platform  x86_64-darwin-16
```

## Bundler settings

```
jobs
  Set for your local app (/Users/konda.madhusudhan/RailsSpace/jackhammer/web/app/.bundle/config): "4"
without
  Set for your local app (/Users/konda.madhusudhan/RailsSpace/jackhammer/web/app/.bundle/config): "development:test"
```

### Gemfile

```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'coffee-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
#jquery ui
gem 'jquery-ui-rails'
#authentication and roles
gem 'devise'
gem 'cancancan'
gem 'rolify'
#bootstrap
gem 'bootstrap-sass'
# pagination
gem 'will_paginate'
gem 'will_paginate-bootstrap'
#validations
gem "jquery-validation-rails"
# scanning stuff
gem 'owasp-pipeline', '>= 0.8.7'
gem 'whenever'
gem 'chronic'
#github api
gem 'octokit'
#gitlab
gem 'gitlab'
#oauth
gem 'omniauth'
gem 'omniauth-github'
# redis && caching
gem 'redis-rails'
gem 'rails-settings-cached'
gem 'redis-namespace'
#sidekiq
gem 'sidekiq'
gem 'sidekiq-status'
gem 'sinatra', :require => false # for the UI
# ENV Variables
gem 'figaro'
#eager load notification
gem 'bullet'
#file upload
gem "paperclip", "~> 5.0.0"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Unicorn as the app server
# gem 'unicorn'
#file upload
gem 'remotipart', '~> 1.2'
#datatables
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# faker
gem 'faker'
#font awesome
gem "font-awesome-rails"
#nested from
gem "nested_form"
#jira integration
gem 'jira-ruby', github:'sumoheavy/jira-ruby'
gem 'soap4r-ng','2.0.3'
gem 'jira4r'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.42'
gem 'puma'
gem 'foreman'
gem 'actionpack-action_caching'
gem 'spinjs-rails'
gem 'activerecord-session_store'
gem 'crack'
gem 'execjs'
gem 'therubyracer'
gem 'ruby-nmap'
#wp scan
gem 'typhoeus'
gem 'addressable'
gem 'ruby-progressbar'
gem 'terminal-table'
gem 'yajl-ruby'
#string formation
gem 'kramdown'
gem 'rails_autolink'
gem 'RedCloth'
gem 'loofah'
gem 'premailer-rails'
gem 'arachni'
gem 'arachni-reactor'
gem 'sidekiq-scheduler'
gem 'toastr-rails'
gem 'local_time'
gem 'sidekiq-statistic'
gem 'sidekiq-middleware'
gem 'sidekiq-retries'
gem 'god'
#gem 'tagsinput-rails'
gem 'tag-it-rails'
gem 'best_in_place'
group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'
	gem 'rspec'
	gem 'rspec-rails'
	gem 'factory_girl_rails'

end

group :development do
	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'
	gem 'pry-rails'
	gem 'pry-byebug'
	gem 'better_errors'
	gem 'binding_of_caller'
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'
end
group :test do
	gem 'faker'
	gem 'capybara'
	gem 'database_cleaner'
	gem 'webmock', '>=1.17.2'
	gem 'simplecov'
	gem 'rspec-its'
end
```

### Gemfile.lock

```
GIT
  remote: git://github.com/rweng/jquery-datatables-rails.git
  revision: d486b31b192a2924b1913e080ad23460e6b96d31
  specs:
    jquery-datatables-rails (3.4.0)
      actionpack (>= 3.1)
      jquery-rails
      railties (>= 3.1)
      sass-rails

GIT
  remote: git://github.com/sumoheavy/jira-ruby.git
  revision: 90cc2c86cddafb9c84e383fd9da041ec7a6cc261
  specs:
    jira-ruby (1.2.0)
      activesupport
      oauth (~> 0.5, >= 0.5.0)

GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.3.2)
    actionmailer (4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7.1)
      actionview (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-action_caching (1.2.0)
      actionpack (>= 4.0.0, < 6)
    actionview (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7.1)
      activesupport (= 4.2.7.1)
      globalid (>= 0.3.0)
    activemodel (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
    activerecord (4.2.7.1)
      activemodel (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      arel (~> 6.0)
    activerecord-session_store (1.0.0)
      actionpack (>= 4.0, < 5.1)
      activerecord (>= 4.0, < 5.1)
      multi_json (~> 1.11, >= 1.11.2)
      rack (>= 1.5.2, < 3)
      railties (>= 4.0, < 5.1)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.6)
    arachni (1.5.1)
      addressable (= 2.3.6)
      arachni-rpc (~> 0.2.1.4)
      awesome_print (= 1.6.1)
      bundler
      childprocess (= 0.5.3)
      coderay (= 1.1.0)
      concurrent-ruby (= 1.0.2)
      concurrent-ruby-ext (= 1.0.2)
      http_parser.rb (= 0.6.0)
      kramdown (= 1.4.1)
      loofah (= 2.0.3)
      msgpack (= 0.7.0)
      nokogiri (= 1.6.8.1)
      oj (= 2.15.0)
      oj_mimic_json (= 1.0.1)
      ox (= 2.4.11)
      pony (= 1.11)
      puma (= 2.14.0)
      rack (= 1.6.4)
      rb-readline (= 0.5.1)
      rubyzip (= 1.2.1)
      selenium-webdriver (= 3.0.1)
      sinatra (= 1.4.6)
      sinatra-contrib (= 1.4.6)
      terminal-table (= 1.4.5)
      typhoeus (= 1.0.2)
      watir-webdriver (= 0.8.0)
    arachni-reactor (0.1.2)
    arachni-rpc (0.2.1.4)
      arachni-reactor (~> 0.1.2)
    arel (6.0.4)
    autoprefixer-rails (6.7.7.1)
      execjs
    awesome_print (1.6.1)
    backports (3.7.0)
    bcrypt (3.1.11)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    best_in_place (3.1.0)
      actionpack (>= 3.2)
      railties (>= 3.2)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bootstrap3-datetimepicker-rails (4.17.47)
      momentjs-rails (>= 2.8.1)
    brakeman (3.6.1)
    builder (3.2.3)
    bullet (5.5.1)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    bundler-audit (0.5.0)
      bundler (~> 1.2)
      thor (~> 0.18)
    byebug (9.0.6)
    cancancan (1.16.0)
    capybara (2.12.1)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    childprocess (0.5.3)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    climate_control (0.1.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.2)
    concurrent-ruby-ext (1.0.2)
      concurrent-ruby (~> 1.0.2)
    connection_pool (2.2.1)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    css_parser (1.4.10)
      addressable
    curb (0.9.3)
    cvss (0.99.0)
    data_mapper (1.2.0)
      dm-aggregates (~> 1.2.0)
      dm-constraints (~> 1.2.0)
      dm-core (~> 1.2.0)
      dm-migrations (~> 1.2.0)
      dm-serializer (~> 1.2.0)
      dm-timestamps (~> 1.2.0)
      dm-transactions (~> 1.2.0)
      dm-types (~> 1.2.0)
      dm-validations (~> 1.2.0)
    data_objects (0.10.17)
      addressable (~> 2.1)
    database_cleaner (1.5.3)
    dawnscanner (1.6.7)
      cvss
      data_mapper
      dm-sqlite-adapter
      haml
      justify
      logger-colors
      ptools
      ruby_parser
      sqlite3
      sys-uname
      terminal-table
    debug_inspector (0.0.2)
    devise (4.2.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.3)
    dm-aggregates (1.2.0)
      dm-core (~> 1.2.0)
    dm-constraints (1.2.0)
      dm-core (~> 1.2.0)
    dm-core (1.2.1)
      addressable (~> 2.3)
    dm-do-adapter (1.2.0)
      data_objects (~> 0.10.6)
      dm-core (~> 1.2.0)
    dm-migrations (1.2.0)
      dm-core (~> 1.2.0)
    dm-serializer (1.2.2)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      json_pure (~> 1.6)
      multi_json (~> 1.0)
    dm-sqlite-adapter (1.2.0)
      dm-do-adapter (~> 1.2.0)
      do_sqlite3 (~> 0.10.6)
    dm-timestamps (1.2.0)
      dm-core (~> 1.2.0)
    dm-transactions (1.2.0)
      dm-core (~> 1.2.0)
    dm-types (1.2.2)
      bcrypt-ruby (~> 3.0)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      multi_json (~> 1.0)
      stringex (~> 1.4)
      uuidtools (~> 2.1)
    dm-validations (1.2.0)
      dm-core (~> 1.2.0)
    do_sqlite3 (0.10.17)
      data_objects (= 0.10.17)
    docile (1.1.5)
    erubis (2.7.0)
    et-orbi (1.0.2)
      tzinfo
    ethon (0.10.1)
      ffi (>= 1.3.0)
    execjs (2.7.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.8.0)
      factory_girl (~> 4.8.0)
      railties (>= 3.0.0)
    faker (1.7.3)
      i18n (~> 0.5)
    faraday (0.11.0)
      multipart-post (>= 1.2, < 3)
    fastercsv (1.5.5)
    ffi (1.9.18)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.7.0.1)
      railties (>= 3.2, < 5.1)
    foreman (0.84.0)
      thor (~> 0.19.1)
    gitlab (3.7.0)
      httparty (~> 0.13.0)
      terminal-table
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    god (0.13.7)
    haml (4.0.7)
      tilt
    hashdiff (0.3.2)
    hashie (3.5.5)
    highline (1.7.8)
    htmlentities (4.3.4)
    http_parser.rb (0.6.0)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (0.8.1)
    jbuilder (2.6.3)
      activesupport (>= 3.0.0, < 5.2)
      multi_json (~> 1.2)
    jira4r (1.3.0)
      soap4r-ng (~> 2.0)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    jquery-validation-rails (1.16.0)
    json (1.8.6)
    json_pure (1.8.6)
    jsonpath (0.5.8)
      multi_json
    justify (1.0.2)
    jwt (1.5.6)
    kramdown (1.4.1)
    libv8 (3.16.14.19)
    local_time (1.0.3)
      coffee-rails
    logger-application (0.0.2)
    logger-colors (1.0.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    momentjs-rails (2.17.1)
      railties (>= 3.1)
    msgpack (0.7.0)
    multi_json (1.12.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    mysql2 (0.4.5)
    nested_form (0.3.2)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    oauth (0.5.1)
    oauth2 (1.3.1)
      faraday (>= 0.8, < 0.12)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    octokit (4.7.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    oj (2.15.0)
    oj_mimic_json (1.0.1)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-github (1.2.3)
      omniauth (~> 1.5)
      omniauth-oauth2 (>= 1.4.0, < 2.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    owasp-pipeline (0.8.7)
      brakeman (>= 3.0.5)
      bundler-audit (>= 0.3.1)
      curb (>= 0.8.8)
      dawnscanner (>= 1.6.0)
      fastercsv (>= 1.5)
      highline (>= 1.6.20)
      jsonpath (>= 0.5.7)
      multi_json (>= 1.2)
      nokogiri (>= 1.6.6.2)
      rake
      redcarpet
      terminal-table (>= 1.4)
    ox (2.4.11)
    paperclip (5.0.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (~> 0.3.0)
    pony (1.11)
      mail (>= 2.0)
    premailer (1.10.2)
      addressable
      css_parser (>= 1.4.10)
      htmlentities (>= 4.0.0)
    premailer-rails (1.9.5)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.2)
      byebug (~> 9.0)
      pry (~> 0.10)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    ptools (1.3.3)
    puma (2.14.0)
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-settings-cached (0.6.5)
      rails (>= 4.2.0)
    rails_autolink (1.1.6)
      rails (> 3.1)
    railties (4.2.7.1)
      actionpack (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    rb-readline (0.5.1)
    rdoc (4.3.0)
    redcarpet (3.4.0)
    redis (3.3.3)
    redis-actionpack (5.0.1)
      actionpack (>= 4.0, < 6)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 1.4.0)
    redis-activesupport (5.0.1)
      activesupport (>= 3, < 6)
      redis-store (~> 1.2.0)
    redis-namespace (1.5.3)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (1.6.0)
      rack (~> 1.5)
      redis-store (~> 1.2.0)
    redis-rails (5.0.1)
      redis-actionpack (~> 5.0.0)
      redis-activesupport (~> 5.0.0)
      redis-store (~> 1.2.0)
    redis-store (1.2.0)
      redis (>= 2.2)
    ref (2.0.0)
    remotipart (1.3.1)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    rolify (5.1.0)
    rprogram (0.3.2)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-its (1.2.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    ruby-nmap (0.9.2)
      nokogiri (~> 1.3)
      rprogram (~> 0.3)
    ruby-progressbar (1.8.1)
    ruby_parser (3.8.4)
      sexp_processor (~> 4.1)
    rubyzip (1.2.1)
    rufus-scheduler (3.4.0)
      et-orbi (~> 1.0)
    safe_yaml (1.0.4)
    sass (3.4.23)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sawyer (0.8.1)
      addressable (>= 2.3.5, < 2.6)
      faraday (~> 0.8, < 1.0)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    selenium-webdriver (3.0.1)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    sexp_processor (4.8.0)
    sidekiq (4.2.10)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-middleware (0.3.0)
      sidekiq (>= 2.12.4)
    sidekiq-retries (0.4.0)
      sidekiq (>= 3.2.4)
    sidekiq-scheduler (2.1.2)
      hashie (~> 3.4)
      redis (~> 3)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    sidekiq-statistic (1.2.0)
      sidekiq (>= 3.3.4, < 5)
    sidekiq-status (0.6.0)
      sidekiq (>= 2.7)
    simplecov (0.14.1)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sinatra-contrib (1.4.6)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (>= 1.3, < 3)
    slop (3.6.0)
    soap4r-ng (2.0.3)
      httpclient (~> 2.6)
      logger-application (~> 0.0.2)
    spinjs-rails (1.4)
      rails (>= 3.1)
    spring (2.0.1)
      activesupport (>= 4.2)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    stringex (1.5.1)
    sys-uname (1.0.3)
      ffi (>= 1.0.0)
    tag-it-rails (2.0.0)
      jquery-ui-rails
      railties
    terminal-table (1.4.5)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.7)
    toastr-rails (1.0.3)
      railties (>= 3.1.0)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.0)
    typhoeus (1.0.2)
      ethon (>= 0.9.0)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.1.13)
      execjs (>= 0.3.0, < 3)
    uniform_notifier (1.10.0)
    uuidtools (2.1.5)
    warden (1.2.7)
      rack (>= 1.0)
    watir-webdriver (0.8.0)
      selenium-webdriver (>= 2.46.2)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (2.3.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket (1.2.4)
    whenever (0.9.7)
      chronic (>= 0.6.3)
    will_paginate (3.1.5)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)
    xpath (2.0.0)
      nokogiri (~> 1.3)
    yajl-ruby (1.3.0)

PLATFORMS
  ruby

DEPENDENCIES
  RedCloth
  actionpack-action_caching
  activerecord-session_store
  addressable
  arachni
  arachni-reactor
  best_in_place
  better_errors
  binding_of_caller
  bootstrap-sass
  bootstrap3-datetimepicker-rails (~> 4.17.42)
  bullet
  byebug
  cancancan
  capybara
  chronic
  coffee-rails
  crack
  database_cleaner
  devise
  execjs
  factory_girl_rails
  faker
  figaro
  font-awesome-rails
  foreman
  gitlab
  god
  jbuilder (~> 2.0)
  jira-ruby!
  jira4r
  jquery-datatables-rails!
  jquery-rails
  jquery-ui-rails
  jquery-validation-rails
  kramdown
  local_time
  loofah
  momentjs-rails (>= 2.9.0)
  mysql2 (>= 0.3.13, < 0.5)
  nested_form
  octokit
  omniauth
  omniauth-github
  owasp-pipeline (>= 0.8.7)
  paperclip (~> 5.0.0)
  premailer-rails
  pry-byebug
  pry-rails
  puma
  rails (= 4.2.7.1)
  rails-settings-cached
  rails_autolink
  redis-namespace
  redis-rails
  remotipart (~> 1.2)
  rolify
  rspec
  rspec-its
  rspec-rails
  ruby-nmap
  ruby-progressbar
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  sidekiq
  sidekiq-middleware
  sidekiq-retries
  sidekiq-scheduler
  sidekiq-statistic
  sidekiq-status
  simplecov
  sinatra
  soap4r-ng (= 2.0.3)
  spinjs-rails
  spring
  tag-it-rails
  terminal-table
  therubyracer
  toastr-rails
  turbolinks
  typhoeus
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
  webmock (>= 1.17.2)
  whenever
  will_paginate
  will_paginate-bootstrap
  yajl-ruby

BUNDLED WITH
   1.14.6
```

**Comment by KMadhuSudhan** [comment] 2017-04-26 16:07
bundler: failed to load command: rspec (/Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/rspec)
Gem::Exception: can't find executable rspec
  /Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:408:in `block in replace_bin_path'
  /Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:425:in `block in replace_bin_path'
  /Users/konda.madhusudhan/.rvm/gems/ruby-2.3.0/bin/rspec:22:in `<top (required)>'

**Comment by segiddins** [comment] 2017-05-30 00:53
Since you've run `bundle config without test`, this is the intended behavior

**Comment by colby-swandale** [comment] 2017-06-04 10:51
I'm closing this for now. Feel free to reopen this ticket if you have any more questions.

**Closed by colby-swandale** 2017-06-04 10:51 UTC
Labels: status: user feedback required, type: bug report
