### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_file_s_stat - .gitignore

### ISSUE THREAD

**Issue by gsecillano** [bundler/bundler#3704] opened 2015-06-02 17:50 UTC
- What did you do?

I ran the command `/opt/ruby-2.1.3/bin/bundle install --gemfile /var/www/ct/stage/releases/20150602173753/Gemfile --path /var/www/ct/stage/shared/bundle --deployment --quiet --without development test debugging`

- What did you expect to happen?

I expected Bundler to install the gems in my Gemfile

- What happened instead?

Instead, what actually happened was it failed with the error below.

Error details

Errno::ENOENT: No such file or directory @ rb_file_s_stat - .gitignore
/opt/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `stat'
/opt/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `block in validate_permissions'
/opt/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `each'
/opt/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `validate_permissions'
/opt/ruby-2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:2540:in `validate'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `validate'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:369:in `block in load_gemspec_uncached'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `chdir'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/opt/ruby-2.1.3/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:52:in `chdir'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:362:in `load_gemspec_uncached'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:352:in `load_gemspec'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:134:in `block in load_spec_files'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `each'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `load_spec_files'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:91:in `local_specs'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:99:in `specs'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:566:in `block in converge_locked_specs'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:553:in `converge_locked_specs'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:194:in `resolve'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:165:in `missing_specs'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:70:in `block in run'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:67:in `run'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:18:in `install'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli/install.rb:107:in `run'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:158:in `install'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:10:in `start'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/bin/bundle:20:in `block in <top (required)>'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
/opt/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.10.2/bin/bundle:18:in `<top (required)>'
/opt/ruby-2.1.3/bin/bundle:23:in `load'
/opt/ruby-2.1.3/bin/bundle:23:in `<main>'

Environment

Bundler   1.10.2
Rubygems  2.2.2
Ruby      2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
GEM_HOME  /var/www/ct/stage/shared/bundle/ruby/2.1.0
GEM_PATH
Git       1.7.2.5

Bundler settings

frozen
Set for your local app (/var/www/ct/stage/releases/20150602173753/.bundle/config): "1"
path
Set for your local app (/var/www/ct/stage/releases/20150602173753/.bundle/config): "/var/www/ct/stage/shared/bundle"
without
Set for your local app (/var/www/ct/stage/releases/20150602173753/.bundle/config): "development:test:debugging"
disable_shared_gems
Set for your local app (/var/www/ct/stage/releases/20150602173753/.bundle/config): "1"
gemfile
Set via BUNDLE_GEMFILE: "/var/www/ct/stage/releases/20150602173753/Gemfile"

**Comment by segiddins** [comment] 2015-06-02 18:13
Closing as a duplicate of https://github.com/bundler/bundler/issues/3698.

**Closed by segiddins** 2015-06-02 18:13 UTC
