### ISSUE TITLE
Vendored gems require bundle install to be discovered

### ISSUE THREAD

**Issue by volkanunsal** [bundler/bundler#6683] opened 2018-09-01 17:19 UTC
I'm trying to run a Docker container using gems from `vendor/bundle`, but the first time I use a gem such as `rake` bundler complains that it cannot find the library. I need to run `bundle install` again and see the `Using gem XYZ` fly by on my terminal before these libraries become discoverable by bundler. 

Just to be sure, I have `BUNDLE_PATH` set in my environment to `/app/vendor/bundle` and I have also tried modifying `~/.bundle/config` myself to add `BUNDLE_PATH`, but nothing worked. 

Is there something I'm missing here?

**Comment by indirect** [comment] 2018-09-01 18:26
Bundler definitely does not support using gems without having ever run bundle install before. If you feel like this is a bug, can you please provide enough information for us to reproduce it?

**Comment by volkanunsal** [comment] 2018-09-01 18:48
Sure, I can produce a Docker container this weekend. But I didn't realize this behavior was by design. I don't know much about how bundler works internally, so forgive me if this sounds ignorant. Why is `bundle install` necessary if there is already a `BUNDLE_PATH` in the environment that would tell bundler where to find the installed gems?

**Comment by indirect** [comment] 2018-09-01 19:25
the first possibility off the top of my head is compiled gems, but the overall situation of “these files need to be installed in a specific way for this exact machine” is the entire reason why we only support using gems after running bundle installl. gems are not always files you can copy to a new machine and use.

**Comment by volkanunsal** [comment] 2018-09-02 19:41
I can understand that ensuring gems are suitable for the machine is a good rationale, but in this case the gems were built in the same Docker container where they will be used, so it shouldn't be necessary to run `bundle install` again.

Here is the repo where I tried to reproduce this issue. 

https://github.com/volkanunsal/bundler_start_up

**Comment by deivid-rodriguez** [comment] 2018-09-02 20:55
Thanks @volkanunsal! I was 100% percent sure I had seen this recently, so I decided to investigate since you provided a reproductio! :smiley:

I confirmed the issue, and that https://github.com/bundler/bundler/pull/6628 fixes it. So my plan would be to include that PR in the 1.16.5 milestone, and then you can fix the issue by configuring `bundle config global_path_appends_ruby_scope true`.

I think the fact that PR was not backported is uninentional, as per my comment in https://github.com/bundler/bundler/issues/6672#issuecomment-417473266.

**Comment by colby-swandale** [comment] 2018-09-13 11:06
It seems that this issue has been answered. Closing.

**Closed by colby-swandale** 2018-09-13 11:06 UTC

**Comment by deivid-rodriguez** [comment] 2018-09-13 11:34
Yeah, the relevant PR was marked for backporting (to 1.17.0 in the end), so this should get fixed once we released that version!
