### ISSUE TITLE
full_gem_path is invalid for default gems on Ruby 2.5+

### ISSUE THREAD

**Issue by Fryguy** [bundler/bundler#6930] opened 2019-01-24 16:18 UTC
Using both bundler 2.0.1 and 1.17.2, with Ruby 2.5, it seems that if the Gemfile contains a gem that also happens to be a default gem (i.e. those that are packaged with ruby), then rubygems creates a Bundler::StubSpecification instance with an invalid full_gem_path.

Reproducer:

Gemfile:
```ruby
gem 'json'
```

Shell with Ruby 2.5.3:
```sh
> bundle update
> bundle exec irb

irb(main):001:0> s = Bundler.environment.specs.detect { |s| s.full_gem_path.include?("json-2.1.0") }
=> #<Bundler::StubSpecification:0x00007fc78508b548 @name="json", ... >
irb(main):002:0> s.full_gem_path
=> "/Users/jfrey/.rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/json-2.1.0"
irb(main):003:0> Dir.exist?(s.full_gem_path)
=> false
```

Notice the gem path is pointing to the ruby installation directory, but it's a directory that doesn't exist. However, this seems to work on Ruby 2.4.5, as it refers me to the installed gem in the .gem directory.

```sh
irb(main):001:0> s = Bundler.environment.specs.detect { |s| s.full_gem_path.include?("json-2.1.0") }
=> #<Bundler::StubSpecification:0x00007fd4bb8a7a68 @name="json", ... >
irb(main):002:0> s.full_gem_path
=> "/Users/jfrey/.gem/ruby/2.4.5/gems/json-2.1.0"
irb(main):003:0> Dir.exist?(s.full_gem_path)
=> true
```

FWIW, I am using chruby/ruby-install, which installs gems to ~/.gem and rubies to ~/.rubies

Thanks to @NickLaMuro for helping me track this down.

**Comment by Fryguy** [comment] 2019-01-24 16:24
I've tried this with a number of system gems, and it happens only with the "default" ones.  That is, gems like `did_you_mean`, do not exhibit this problem because they are fully extracted and actually exist in the directory:

```sh
> ls -1 /Users/jfrey/.rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/
did_you_mean-1.2.0
minitest-5.10.3
net-telnet-0.1.1
power_assert-1.1.1
rake-12.3.0
rdoc-6.0.1
test-unit-3.2.7
xmlrpc-0.3.0
```

but other default gems like `json`, `psych, and `bigdecimal` do not exist in that directory, even though that have specifications.  These gems are the ones that exhibit the issue.

```sh
> ls -1 /Users/jfrey/.rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/specifications/default
bigdecimal-1.3.4.gemspec
cmath-1.0.0.gemspec
csv-1.0.0.gemspec
date-1.0.0.gemspec
dbm-1.0.0.gemspec
etc-1.0.0.gemspec
fcntl-1.0.0.gemspec
fiddle-1.0.0.gemspec
fileutils-1.0.2.gemspec
gdbm-2.0.0.gemspec
io-console-0.4.6.gemspec
ipaddr-1.2.0.gemspec
json-2.1.0.gemspec
openssl-2.1.2.gemspec
psych-3.0.2.gemspec
rdoc-6.0.1.gemspec
scanf-1.0.0.gemspec
sdbm-1.0.0.gemspec
stringio-0.0.1.gemspec
strscan-1.0.0.gemspec
webrick-1.4.2.gemspec
zlib-1.0.0.gemspec
```

**Comment by Fryguy** [comment] 2019-01-31 18:35
I checked and this also fails on Ruby 2.6

**Comment by deivid-rodriguez** [comment] 2019-02-18 17:33
This seems like a ruby-core bug. On a fresh installation, the folder is indeed missing. But if you reinstall the default gem with `gem install json:2.1.0 --default`, the folder is created. I'm going to have a look at it in ruby-core.

**Comment by deivid-rodriguez** [comment] 2019-02-19 12:38
I proposed a fix for this to ruby-core in ruby/ruby#2085.

**Comment by hsbt** [comment] 2019-02-19 12:39
This is intentional behavior. `did_you_mean` is the bundled gems, But `json` is the default gems.

@Fryguy What's usecase of `full_gem_path` of default gems?

**Comment by deivid-rodriguez** [comment] 2019-02-19 13:44
I understand that `full_gem_path` is not really meaningful for default gems as they are handled now. Also, I have checked on a fresh ruby 2.4 docker image, and `full_gem_path` is also a non existent directory, so I don't think there's been a change in behavior. @Fryguy Maybe `gem install json` had been previously run in the environment where you checked this?

However, I see several issues with the current situation:

* `full_gem_path` still returns a value for default gems in the default ruby distribution, a folder that doesn't exist.

* `rbinstall` and `gem install --default` have inconsistent behavior. Where as rbinstall only creates the `full_gem_path` folder if the default gem provides executables, the rubygems default gem installer always creates the `full_gem_path` folder, and leaves it empty if the default gem provides no executables.

I propose to either:

* Return `nil` or empty string for `full_gem_path` if the gem is a default gem.

or

* Create a empty directory [like `gem install --default` does](https://github.com/rubygems/rubygems/blob/3d27eb01f8ab89a672915ebd56c7b70768739749/lib/rubygems/installer.rb#L312-L316).

And whatever solution we choose, we should make sure the ruby-core installer and rubygems one have a consistent behavior.

**Comment by Fryguy** [comment] 2019-03-05 21:23
> What's usecase of full_gem_path of default gems?

Generally, there isn't a use case as much as I was pointing out that this method returns an invalid value.  For my usage, I would be fine if it returned nil or empty string, because I can handle those cases, but pointing to a non-existent directory seems wrong and confusing.

Specifically, I ran into this because in our application we use Rails engines as plugins, and we have code that pulls out information about the plugins using various Bundler/Gem methods.  I recently added support for symlinked paths, so then I need to `File.realpath` to resolve the symlinks, but `realpath` blows up if the path doesn't actually exist.  The code in question basically ends up calling `.realpath` on every `.full_gem_path`, and the invalid ones blow up.  It took me a while to solve, because I didn't realize that the `.full_gem_path` wasn't a real path.  If it had been nil, I think I would have solved the issue a lot quicker.

Here's the code in question if you're curious: https://github.com/ManageIQ/manageiq/pull/18002/files#diff-2dffee21730102d591f668045fe85db7

**Comment by hsbt** [comment] 2019-03-23 07:44
Hi, I try to modify it like this: https://github.com/rubygems/rubygems/compare/master...hsbt:gem-full-patch-for-default-gems?expand=1

But It has the breaking change with `full_gem_path`.  Unfortunately, We should not apply it.

**Comment by deivid-rodriguez** [comment] 2019-03-23 09:46
@hsbt You don't like https://github.com/ruby/ruby/pull/2085? I know it doesn't really fix the problem in the sense that the returned folder is not correct. But at least it is a folder that exists, and it makes the behavior of rubygems default gem installer and ruby-core's default gem installer consistent.

**Comment by hsbt** [comment] 2019-03-25 00:45
Yes, I dont't like that only fixing inconsistency changes without usecase.

**Comment by deivid-rodriguez** [comment] 2019-04-01 12:09
IMO this PR helps bundler & rubygems developers because it reduces surprises. For me it was confusing to be able to reproduce this only for gems I had not reinstalled through `gem install --default`. But it also fixes the OP issue, so my opinion is why not.

**Closed** 2019-08-23 08:20 UTC
