### ISSUE TITLE
Minitest is not loaded when bundle exec is invoked

### ISSUE THREAD

**Issue by ebenoist** [bundler/bundler#3388] opened 2015-02-11 15:59 UTC
I am attempting to publish a gem and have come across a problem. While minitest should be available, I am forced to declare it as a development dependency in the gem spec if I run `bundle exec rake test` as opposed to `rake test`. When running `rake test` the load path is able to bring in the minitest bundled gem.

I have posted my [bundler env to a public gist](https://gist.github.com/ebenoist/2b54075341f8fc45a80e) and have created a [test project](https://github.com/ebenoist/minitest-bundler-bug) that displays the bug.

#### Without Bundler
```BASH
[master+][~/development/minitest-bundler-bug]❥ rake test
/Users/ebenoist/.rbenv/versions/2.1.2/bin/ruby -I"lib:lib" -I"/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib" "/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/bug_test.rb"
Run options: --seed 39836

# Running:

.

Finished in 0.001396s, 716.3324 runs/s, 716.3324 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

### With Bundler
```BASH
[master][~/development/minitest-bundler-bug]❥ bundle exec rake test
/Users/ebenoist/.rbenv/versions/2.1.2/bin/ruby -I"lib:lib" -I"/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib" "/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/bug_test.rb"
/Users/ebenoist/development/minitest-bundler-bug/test/bug_test.rb:1:in `require': cannot load such file -- minitest (LoadError)
	from /Users/ebenoist/development/minitest-bundler-bug/test/bug_test.rb:1:in `<top (required)>'
	from /Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'
	from /Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib" -I"/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib" "/Users/ebenoist/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/bug_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

Thank you for the amazing project, and let me know if I can provide any other information that would help in fixing this issue.

**Comment by TimMoore** [comment] 2015-02-11 23:01
This is actually Bundler working as intended. What `bundle exec` does is set your load path so that only the gems that were resolved in your bundle are available to load. Adding it as a development dependency (or directly in your `Gemfile`) is the right solution.

**Closed by TimMoore** 2015-02-11 23:01 UTC

**Comment by ebenoist** [comment] 2015-02-12 02:07
Tim, thanks for your reply. I'm still a bit confused. I believe that "minitest" is bundled with the Ruby stdlib in 2.1. I don't have to add json or erb as a declared dependency for the same reason; I can require right away. What am I missing?

**Comment by indirect** [comment] 2015-02-12 02:36
It’s not bundled with the stdlib, it’s simply installed as a gem by default with every new Ruby. JSON and ERB are actually _inside_ the stdlib. Different situations.

**Comment by ebenoist** [comment] 2015-02-12 02:48
André, thank you for the swift reply. This was the distinction I was
missing. I had always assumed that minitest was included in the stdlib
(it's always there!). I see now that it is rather one of the bundled gems
<https://github.com/ruby/ruby/blob/3e818c614d8ab6eef4f53c57148d09c1844efcf4/gems/bundled_gems>.
Thank you for taking the time to clear that up.
