### ISSUE TITLE
Error while restarting puma webserver

### ISSUE THREAD

**Issue by sjayanna** [bundler/bundler#4079] opened 2015-10-28 02:50 UTC
Please see the [gist](https://gist.github.com/sjayanna/5ed1baf175a45cb2509f)
Not sure why this error is happening? is it because of bundler version?

Thanks!

**Comment by segiddins** [comment] 2015-10-28 02:58
It looks like you're trying to do something with bundler in a directory that doesn't have a gem file?

**Comment by sjayanna** [comment] 2015-10-28 03:07
Thank you @segiddins but there is a Gemfile in that folder as shown in the attached image (please ignore the datestamp)
![image](https://cloud.githubusercontent.com/assets/194508/10778761/5eb53a44-7cff-11e5-8308-3b00b8c55a93.png)

**Comment by segiddins** [comment] 2015-10-28 04:03
what's the output of `bundle install --verbose`?

**Comment by sjayanna** [comment] 2015-10-28 04:21
@segiddins I use Ansible to deploy it on the server automatically. This works most of the time but sometimes I get this and i have to run the capasitrano deply script again and then it works.

**Comment by indirect** [comment] 2015-12-07 20:07
Closing because we can't reproduce this issue with the he given data. My guess as to why this problem is happening is that some code inside the web app has run `Dir.chdir`, and puma can no longer find the Gemfile.

**Closed by indirect** 2015-12-07 20:08 UTC
