### ISSUE TITLE
"bundle install" doesn't respect version in Gemfile.lock when using source option/block  (1.7.3)

### ISSUE THREAD

**Issue by mdt** [bundler/bundler#3175] opened 2014-09-16 02:15 UTC
When a gem (let's call it "MyGem") has a specific remote source option set in the Gemfile, and Gemfile.lock specifies an earlier-numbered version for MyGem, then in some cases, "bundle install" incorrectly selects the *latest* version of MyGem and changes Gemfile.lock to specify the latest version of MyGem.  Reproducing this problem seems to require all of the following:
* Gemfile specifies multiple remote sources.
* Gemfile requires a specific source for MyGem.
* The local gem cache (maybe: bundler installation?) knows about a more-recent version of MyGem than the one specified in Gemfile.lock.

If any one of the above isn't true, then "bundle install" correctly installs the locked version of MyGem and leaves Gemfile.lock unchanged.  But if all three bullet-points hold, then "bundle install" always changes Gemfile.lock to grab the latest version of MyGem, even though we could have (should have) used the locked version.  This seems like a bug.

This long script reproduces the problem:

https://gist.github.com/mdt/426195a829c9aa681bf1

**Comment by jezstephens** [comment] 2015-02-16 23:23
Still reproducible in 1.8.2. Surely this is a fairly common use case. Is there a workaround I'm missing?

**Comment by indirect** [comment] 2015-02-17 02:26
Simply refusing to unlock the gem if the source type stays the same is not okay: if the Gemfile moves a gem from one source to another, the version _must_ be unlocked to allow versions that are present in that source even if the locked version is not present in that source.

**Comment by indirect** [comment] 2015-02-17 02:34
@jezstephens if this is a frequent problem for you, you're welcome to fix it and send a pull request.

Also, please keep in mind that when you say "gem 'rake'", that means you are okay with _literally any version of the rake gem_. You got one. If you're not okay with the version you got, please specify versions that you are okay with while we fix this problem entirely for free and in our spare time.

**Comment by jezstephens** [comment] 2015-02-17 12:08
Apologies @indirect, I didn't intend my comment in the ungrateful tone you seem to have felt. I was simply surprised at the lack of people having trouble with this, though now I understand the issue a bit better I see it may not be as common an issue as I first thought.

I actually did look into this further, but didn't make any real progress before turning in to bed. All I've found is that while PR #3301 fixes the second error case in @mdt's script (once updated to reflect the current version of rake), I still see a similar problem in my real application.

My gems are updating when I run `bundle install` not only when I add a new source, but also afterwards if I manually roll back the versions in `Gemfile.lock` then run it again.

> when you say "gem 'rake'", that means you are okay with literally any version of the rake gem [...] please specify versions that you are okay with

I don't think this is really about what my Gemfile says, but what my Gemfile.lock says. Being able to lock to specific versions without giving specific versions in the Gemfile is obviously a key feature. In fact I do have version constraints for the affected gems, just not specific versions.

Specifying exact versions seems like the best workaround for now though, so thanks.

I'll look into this further when I have more free time. I understand it's frustrating when people expect something for nothing, but please don't be so quick to imply laziness if you want to encourage contributions.

**Comment by indirect** [comment] 2015-02-17 20:45
Thanks for clarifying. In general, incredulity that a bug has not been fixed in an open source project is always going to be grating because we are working on this project almost entirely unpaid. As a result, it sounds ungrateful, demanding, or both.

I do believe that it is a bug that versions are unlocked in this case, and we will try to get it fixed. Pull requests are welcome anytime someone has a problem that they genuinely need fixed quickly.

**Comment by TimMoore** [comment] 2015-02-17 21:12
@jezstephens could you please add the details from `bundle env` and reproduction steps (ideally a script)?

> My gems are updating when I run bundle install not only when I add a new source, but also afterwards if I manually roll back the versions in Gemfile.lock then run it again.

Can you clarify what you mean by this? Are you reverting the changes to `Gemfile.lock` entirely? If that's the case, then from Bundler's perspective it's still a new source.

**Comment by jandudulski** [comment] 2015-03-02 09:09
> reproduction steps

Create a new Gemfile, e.g.:

```ruby
source 'https://rubygems.org'

gem 'virtus'

source 'https://rails-assets.org' do
  gem 'rails-assets-angular', '1.3.0'
end
```

and run `bundle install`

Now change `gem 'rails-assets-angular', '1.3.0'` to `gem 'rails-assets-angular', '~> 1.3.0'` and run `bundle` - for me it updates `rails-assets-angular` to the newest accessible locally version.

Or change `gem 'virtus'` to the `gem 'virtus', '1.0.3'` and run bundle:

```bash
[yanoo@hodor]~/Code/gemtest% bundle install
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/.
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Could not find gem 'virtus (= 1.0.3) ruby' in the gems available on this machine.
```

**Comment by moxley** [comment] 2015-03-13 22:54
We reproduced this problem in bundler versions 1.7.12, 1.7.3, and it seems to be fixed in 1.8.3 and 1.8.5.

**Comment by jandudulski** [comment] 2015-03-13 23:29
Just tested as described above with 1.8.5 - bundler still updates to the highest available version locally.

**Comment by pschambacher** [comment] 2015-03-27 08:51
Still happening with Bundler 1.9. From my point of view Bundler is simply broken for 3 minor versions now.

**Comment by indirect** [comment] 2015-03-27 08:56
@pschambacher since users reported this bug as fixed, please open a new ticket for the issue you're seeing in 1.9, following [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) so that we can reproduce the bug and fix it.

**Closed by indirect** 2015-03-27 08:56 UTC

**Comment by pschambacher** [comment] 2015-03-27 09:21
Hi @indirect I've created the issue [here](https://github.com/bundler/bundler/issues/3520) with as much details as possible
