### ISSUE TITLE
Gem.post_install hook is not run during bundle install when a gem is installed from rubygems, but is executed if I point the gem to the github repository

### ISSUE THREAD

**Issue by ramkumar-kr** [bundler/bundler#6071] opened 2017-09-30 18:23 UTC
Using bundler version `1.16.0.pre.2` on Ubuntu 16.04 LTS

Hi,
I have a gem called `hooke` which creates symbolic links for git hooks to a directory in the repository. When I try to install the gem from rubygems, the post install script does not run (the `hooks` directory in `.git` is not symlinked). However, when I install the same gem from github, I'm seeing that the post install script runs successfully.

I wrote a couple of shell scripts to help in reproducing the issue

### Installing the gem using rubygems
```bash
#!/bin/sh

bundler --version
mkdir test
cd test
git init
mkdir git_hooks
bundle init
echo "gem 'hooke'" >> Gemfile
bundle install
ls -al .git/hooks
cd ..
rm -rf test
```
**Output**
```
Bundler version 1.16.0.pre.2
Initialized empty Git repository in /tmp/test/.git/
Writing new Gemfile to /tmp/test/Gemfile
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from https://rubygems.org/..
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.16.0.pre.2
Using hooke 1.0.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
total 48
drwxrwxr-x 2 ramkumar ramkumar 4096 Oct  1 08:27 .
drwxrwxr-x 7 ramkumar ramkumar 4096 Oct  1 08:27 ..
-rwxrwxr-x 1 ramkumar ramkumar  478 Oct  1 08:27 applypatch-msg.sample
-rwxrwxr-x 1 ramkumar ramkumar  896 Oct  1 08:27 commit-msg.sample
-rwxrwxr-x 1 ramkumar ramkumar  189 Oct  1 08:27 post-update.sample
-rwxrwxr-x 1 ramkumar ramkumar  424 Oct  1 08:27 pre-applypatch.sample
-rwxrwxr-x 1 ramkumar ramkumar 1642 Oct  1 08:27 pre-commit.sample
-rwxrwxr-x 1 ramkumar ramkumar 1239 Oct  1 08:27 prepare-commit-msg.sample
-rwxrwxr-x 1 ramkumar ramkumar 1348 Oct  1 08:27 pre-push.sample
-rwxrwxr-x 1 ramkumar ramkumar 4898 Oct  1 08:27 pre-rebase.sample
-rwxrwxr-x 1 ramkumar ramkumar 3610 Oct  1 08:27 update.sample

```

### Installing the gem using github

```bash
#!/bin/sh

bundler --version
mkdir test
cd test
git init
mkdir git_hooks
bundle init
echo "gem 'hooke', github: 'ramkumar-kr/hooke'" >> Gemfile
bundle install
ls -al .git/hooks
cd ..
rm -rf test

```

**Output**
```
Bundler version 1.16.0.pre.2
Initialized empty Git repository in /tmp/test/.git/
Writing new Gemfile to /tmp/test/Gemfile
Fetching https://github.com/ramkumar-kr/hooke
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.16.0.pre.2
Using hooke 1.0.1 from https://github.com/ramkumar-kr/hooke (at master@ebf7fad)
Renaming ./.git/hooks
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from hooke:
You are now hooked
lrwxrwxrwx 1 ramkumar ramkumar 19 Sep 30 23:32 .git/hooks -> /tmp/test/git_hooks
```

I also confirmed that there are no changes in the code between the rubygems version and the github version by doing a diff on the locations of installed directories

**Comment by olleolleolle** [comment] 2017-09-30 18:54
Reading this, I was helped by these two links;

- Docs: [Rubygems Guide: Plugins](http://guides.rubygems.org/plugins/) about _Extensions that use the RubyGems plugin API._
- Hooke's [lib/rubygems_plugin.rb](https://github.com/ramkumar-kr/hooke/blob/master/lib/rubygems_plugin.rb)

**Comment by colby-swandale** [comment] 2017-10-01 04:46
`Gem.post_install` does not get executed on the gem being installed by design (in RubyGems). Git gems in Bundler having their `#post_install` executed is just because of how git & path gems work in Bundler.

**Comment by colby-swandale** [comment] 2017-10-01 04:54
I suggest using a command instead of the install hook

**Comment by ramkumar-kr** [comment] 2017-10-01 07:51
Hi @colby-swandale ,

Correct me if I'm wrong here.
I'm under the assumption that there is no difference in installing a gem in rubygems from either the `gem install` command or using a Gemfile and performing a `bundle install`

However, I observed that `Gem.post_install` gets executed when I install the gem using `gem install`

Here's a shell script containing the commands which I ran
```bash
#!/bin/sh

bundler --version
mkdir test
cd test
git init
mkdir git_hooks
bundle init
gem install "hooke"
ls -al .git/hooks
cd ..
rm -rf test
```

And the output I got was
```
Bundler version 1.16.0.pre.2
Initialized empty Git repository in /tmp/test/.git/
Writing new Gemfile to /tmp/test/Gemfile
You are now hooked
Renaming ./.git/hooks # <-- Printed from Gem.post_install
Successfully installed hooke-1.0.1
Parsing documentation for hooke-1.0.1
Installing ri documentation for hooke-1.0.1
Done installing documentation for hooke after 0 seconds
1 gem installed
lrwxrwxrwx 1 ramkumar ramkumar 19 Oct  1 13:04 .git/hooks -> /tmp/test/git_hooks
```

**Comment by olleolleolle** [comment] 2017-10-01 08:44
(Since, I'm awake, I'll add some of my thoughts, which may make the "try creating this hook-creation step as a Gem plugin _command_" clearer.)

The assumption that you listed (btw: that’s a great way to explain how _you_ see the issue!), I have thoughts about that.

I think of `bundle install` not as mechanically the _same_ as “install each of these”, but rather as “ensure I have all of these, `gem install` them _if needed_“.

Here's an example "conversation":

1. On `bundle install` when Bundler goes “oh, you didn’t have that gem on your machine, I’ll `gem install` it”, it makes a `gem install` (which _will_ fire the `Gem.post_install` hook).
2. The next time `bundle install` is run, Bundler won’t reinstall, but instead just _use_ the existing, installed gem. No `gem install`, and so no `Gem.post_install` is reached.

**Comment by ramkumar-kr** [comment] 2017-10-01 12:02
Hi @olleolleolle ,

Thanks a lot for your explanation. Now I clearly understand why the post_install hook does not run by "design" in rubygems.

I was wondering if there are any life-cycle hooks for bundler (Something like the `after_bundle` in Rails templates) so that I can have behaviour similar to javascript packages  like [husky](https://github.com/typicode/husky)

**Comment by colby-swandale** [comment] 2017-10-03 12:14
I'm closing this for now. If you have any more question don't be afraid to ask.

**Closed by colby-swandale** 2017-10-03 12:14 UTC
