### ISSUE TITLE
Getting errors while installing bundle

### ISSUE THREAD

**Issue by AnandababuGanesan** [bundler/bundler#4613] opened 2016-05-25 11:55 UTC
ananda@ananda-OptiPlex-790:/usr/localdisk/hw/repowrt$ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    ArgumentError: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/home/ananda/.bundle/cache/compact_index/rubygems.org.80.9e8aca59a0c3a407fba89eb64623162d/versions20160525-12967-br4rpy" (parent directory mode 40777)
      /usr/lib/ruby/1.8/fileutils.rb:695:in `remove_entry_secure'
      /usr/lib/ruby/1.8/tmpdir.rb:131:in `mktmpdir'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:65:in `available?'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/fetcher/compact_index.rb:15:in `available?'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/fetcher.rb:154:in `use_api'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `select'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:335:in `remote_specs'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/source/rubygems.rb:82:in `specs'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/lazy_specification.rb:56:in `__materialize__'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/spec_set.rb:91:in `materialize'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/spec_set.rb:88:in `map!'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/spec_set.rb:88:in `materialize'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/definition.rb:140:in `specs'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/definition.rb:129:in `resolve_remotely!'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/installer.rb:195:in `resolve_if_need'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/installer.rb:70:in `run'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/installer.rb:22:in `install'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/cli/install.rb:102:in `run'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/cli.rb:175:in `install'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `__send__'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/1.8/gems/bundler-1.12.4/exe/bundle:27
      /var/lib/gems/1.8/gems/bundler-1.12.4/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /var/lib/gems/1.8/gems/bundler-1.12.4/exe/bundle:19
      /usr/local/bin/bundle:19:in `load'
      /usr/local/bin/bundle:19

Environment
      
  Bundler   1.12.4
  Rubygems  1.8.15
  Ruby      1.8.7 (2011-06-30 patchlevel 352) [i686-linux]
  GEM_HOME  /var/lib/gems/1.8
  GEM_PATH  /var/lib/gems/1.8:/home/ananda/.gem/ruby/1.8
  Git       1.7.9.5
      
      Bundler settings
      
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=parent+directory+is+world+writable%2C+FileUtils%23remove_entry_secure+does+not+work%3B+abort%3A+%22%2Fhome%2Fananda%2F.bundle%2Fcache%2Fcompact_index%2Frubygems.org.80.9e8aca59a0c3a407fba89eb64623162d%2Fversions20160525-12967-br4rpy%22+%28parent+directory+mode+40777%29&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by LynnCo** [comment] 2016-06-08 00:15
Closing as a duplicate of https://github.com/bundler/bundler/issues/4630, we'll work on resolving it there!

**Closed by LynnCo** 2016-06-08 00:15 UTC
Labels: status: triage
