### ISSUE TITLE
`bundle viz` fails with `NoMethodError`

### ISSUE THREAD

**Issue by hauleth** [bundler/bundler#3217] opened 2014-10-18 17:10 UTC
After running `bundle viz` I get this:

```
/home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/graph.rb:38:in `block in _populate_relations': undefined method `runtime_dependencies' for nil:NilClass (NoMethodError)
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/graph.rb:37:in `_populate_relations'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/graph.rb:19:in `initialize'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/cli/viz.rb:11:in `new'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/cli/viz.rb:11:in `run'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/cli.rb:321:in `viz'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/cli.rb:9:in `start'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/bin/bundle:20:in `block in <top (required)>'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /home/hauleth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/bin/bundle:18:in `<top (required)>'
	from /home/hauleth/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
	from /home/hauleth/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'
```

Any idea what is wrong?

**Comment by aprescott** [comment] 2015-05-06 15:10
I have this issue. I'm not quite sure I follow why this is happening, but is there a reliable workaround?

**Comment by fotanus** [comment] 2015-05-06 16:19
@aprescott Can you fill an [issue](https://github.com/bundler/bundler/blob/master/ISSUES.md) ? It is the easiest way to have all requirements to reproduce it and possibly fix it.

**Comment by aprescott** [comment] 2015-05-06 18:25
My issue is basically exactly as described here, with potentially different versions. ruby 2.2.2p95, rubygems 2.4.6, bundler 1.9.5, rails 4.2.1. I can open another issue, though, if the duplication is fine. (I'd just be linking to this issue anyway.)

**Comment by indirect** [comment] 2015-05-06 18:29
The file https://github.com/bundler/bundler/blob/master/ISSUES.md has specific instructions for what we need to know in order to try to reproduce your problem. Please read the file and follow the instructions.

**Comment by aprescott** [comment] 2015-05-06 18:47
Apologies for the noise. I dug into this some more and I can't provide more than what you already know with the commit linked in this issue. It's a similar problem with an `rc1` pre-release dependency and `dependency.to_spec` returning `nil` within `_populate_relations`. Specifically, `backbone-on-rails` 0.9.9.0 using `eco` 1.0.0, which uses `eco-source` 1.1.0.rc.1 (whose `to_spec` returns `nil`). I'll shut up!

**Comment by aprescott** [comment] 2015-05-12 02:45
I believe this is fixed now and can be closed.

**Closed** 2015-05-12 02:48 UTC

**Comment by andywenk** [comment] 2015-07-05 14:20
just for the record and it may help someone. I had this output:

    bundle viz                                                                                  ✭
    ――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
    - What did you do?
    - What did you expect to happen?
    - What happened instead?

    Error details

        NoMethodError: undefined method `runtime_dependencies' for nil:NilClass
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/graph.rb:39:in `block in _populate_relations'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/graph.rb:38:in `_populate_relations'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/graph.rb:20:in `initialize'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli/viz.rb:11:in `new'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli/viz.rb:11:in `run'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli.rb:336:in `viz'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/cli.rb:10:in `start'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/bin/bundle:20:in `block in <top (required)>'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
        /Users/andwen/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/bin/bundle:18:in `<top (required)>'
        /Users/andwen/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
        /Users/andwen/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'

    Environment

        Bundler   1.9.4
        Rubygems  2.4.5
        Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
        GEM_HOME  /Users/andwen/project/sumcumo/ace/vendor/ruby/2.2.0
        GEM_PATH
        Git       2.4.5

    Bundler settings

        path
          Set for your local app (/Users/andwen/project/sumcumo/ace/.bundle/config): "vendor"
        disable_shared_gems
          Set for your local app (/Users/andwen/project/sumcumo/ace/.bundle/config): "1"
        cache_all
          Set for your local app (/Users/andwen/project/sumcumo/ace/.bundle/config): "true"
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    Unfortunately, an unexpected error occurred, and Bundler cannot continue.

    First, try this link to see if there are any existing issue reports for this error:
    https://github.com/bundler/bundler/search?q=undefined+method+%60runtime_dependencies%27+for+nil%3ANilClass&type=Issues

    If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
    https://github.com/bundler/bundler/issues/new

After upgrading to bundler 1.10.5, the problem was gone and the graphic was created.

Cheers

Andy
