### ISSUE TITLE
bundle package --all-platforms does not save other platform's gems

### ISSUE THREAD

**Issue by calebthompson** [bundler/bundler#5863] opened 2017-07-13 16:44 UTC
According to [bundle-package.1](https://bundler.io/v1.15/man/bundle-package.1.html#SUPPORT-FOR-MULTIPLE-PLATFORMS), the `--all-platforms` argument to `bundle package` should include gems from all platforms. This is corroborated by this issue https://github.com/bundler/bundler/issues/4517.

Here's what I've done:

```
❯ ls
Gemfile
❯ cat Gemfile
source "https://rubygems.org"

gem "image_optim_pack"       
❯ bundle lock --add-platform x86_64-linux
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/.
Writing lockfile to /Users/caleb.thompson/code/salary-social/foobar/Gemfile.lock
❯ bundle lock --add-platform x86_64-darwin-16
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Writing lockfile to /Users/caleb.thompson/code/salary-social/foobar/Gemfile.lock
❯ bundle package --all-platforms
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Fetching fspath 3.1.0
Installing fspath 3.1.0
Fetching exifr 1.3.1
Installing exifr 1.3.1
Fetching image_size 1.5.0
Installing image_size 1.5.0
Fetching in_threads 1.4.0
Installing in_threads 1.4.0
Fetching progress 3.3.1
Installing progress 3.3.1
Using bundler 1.15.1
Fetching image_optim 0.25.0
Installing image_optim 0.25.0
Fetching image_optim_pack 0.5.0.20170712 (x86_64-darwin)
Installing image_optim_pack 0.5.0.20170712 (x86_64-darwin)
Bundle complete! 1 Gemfile dependency, 8 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from image_optim:
Rails image assets optimization is extracted into image_optim_rails gem
You can safely remove `config.assets.image_optim = false` if you are not going to use that gem
Updating files in vendor/cache
Fetching fspath 3.1.0
  * fspath-3.1.0.gem
Fetching exifr 1.3.1
  * exifr-1.3.1.gem
Fetching image_size 1.5.0
  * image_size-1.5.0.gem
Fetching in_threads 1.4.0
  * in_threads-1.4.0.gem
Fetching progress 3.3.1
  * progress-3.3.1.gem
Fetching image_optim 0.25.0
  * image_optim-0.25.0.gem
Fetching image_optim_pack 0.5.0.20170712 (x86_64-darwin)
  * image_optim_pack-0.5.0.20170712-x86_64-darwin.gem
                        
❯ tree 
.
├── Gemfile
├── Gemfile.lock
└── vendor
    └── cache
        ├── exifr-1.3.1.gem
        ├── fspath-3.1.0.gem
        ├── image_optim-0.25.0.gem
        ├── image_optim_pack-0.5.0.20170712-x86_64-darwin.gem
        ├── image_size-1.5.0.gem
        ├── in_threads-1.4.0.gem
        └── progress-3.3.1.gem

2 directories, 9 files
❯ cat .bundle/config
---
BUNDLE_CACHE_ALL_PLATFORMS: "true"
```

I'd expect the tree output to include a linux version for image_optim_pack, which I can use when deploying to production. It doesn't, so my cache isn't valid when I'm deploying on a linux machine.

## Environment

```
Bundler   1.15.1
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
GEM_HOME  /Users/caleb.thompson/code/salary-social/foobar/.gem/ruby/2.4.1
GEM_PATH  /Users/caleb.thompson/code/salary-social/foobar/.gem/ruby/2.4.1:/Users/caleb.thompson/code/salary-social/test/.gem/ruby/2.4.1:/Users/caleb.thompson/code/heroku-buildpack-ruby/.gem/ruby/2.4.1:/Users/caleb.thompson/.gem/ruby/2.4.1
Git       2.13.2
Platform  x86_64-darwin-16
```

## Bundler settings

```
git.allow_insecure
  Set for the current user (/Users/caleb.thompson/.bundle/config): "true"
cache_all_platforms
  Set for your local app (/Users/caleb.thompson/code/salary-social/foobar/.bundle/config): "true"
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "image_optim_pack"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    exifr (1.3.1)
    fspath (3.1.0)
    image_optim (0.25.0)
      exifr (~> 1.2, >= 1.2.2)
      fspath (~> 3.0)
      image_size (~> 1.5)
      in_threads (~> 1.3)
      progress (~> 3.0, >= 3.0.1)
    image_optim_pack (0.5.0.20170712)
      fspath (>= 2.1, < 4)
      image_optim (~> 0.19)
    image_size (1.5.0)
    in_threads (1.4.0)
    progress (3.3.1)

PLATFORMS
  ruby

DEPENDENCIES
  image_optim_pack

BUNDLED WITH
   1.15.1
```

**Comment by bkoski** [comment] 2017-07-14 01:47
Ran into [similar troubles with google-protobuf](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1592).

Traced the issue back to [this line in `Bundler::LazySpecification#__materialize__`](https://github.com/bundler/bundler/blob/b0883924ee284d2d2f6e8848ac2994085c95035a/lib/bundler/lazy_specification.rb#L71) which omits the details of  alternative platforms provided with `bundle lock --add-platform` unless `Bundler.feature_flag.specific_platform?` is true.

Here's what worked for me with bundler 1.15.1:

```
bundle config specific_platform true
bundle lock --add-platform x86_64-linux
bundle package --all-platforms
```

Not sure if this is a code bug, or a documentation issue? At the very least seems like the docs should advise setting this feature flag.

**Comment by calebthompson** [comment] 2017-07-17 14:21
@bkoski great find! I wasn't able to get it to work, did you end up with additional gems packed when you ran that?

```
❯ bundle config --local specific_platform true
❯ bundle lock --add-platform x86_64-linux
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Writing lockfile to /Users/caleb.thompson/code/salary-social/foobar/Gemfile.lock
❯ rm -rf .gem vendor
❯ cat Gemfile.lock
# omitted
PLATFORMS
  ruby
  x86_64-darwin-16
  x86_64-linux
# omitted
❯ bundle package --all-platforms
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/.
Fetching fspath 3.1.0
Installing fspath 3.1.0
Fetching exifr 1.3.1
Installing exifr 1.3.1
Fetching image_size 1.5.0
Installing image_size 1.5.0
Fetching in_threads 1.4.0
Installing in_threads 1.4.0
Fetching progress 3.3.1
Installing progress 3.3.1
Using bundler 1.15.1
Fetching image_optim 0.25.0
Installing image_optim 0.25.0
Fetching image_optim_pack 0.5.0.20170712
Installing image_optim_pack 0.5.0.20170712
Bundle complete! 1 Gemfile dependency, 8 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from image_optim:
Rails image assets optimization is extracted into image_optim_rails gem
You can safely remove `config.assets.image_optim = false` if you are not going to use that gem
Updating files in vendor/cache
Fetching image_optim_pack 0.5.0.20170712
  * image_optim_pack-0.5.0.20170712.gem
Fetching image_optim_pack 0.5.0.20170712
Fetching image_optim_pack 0.5.0.20170712
Fetching fspath 3.1.0
  * fspath-3.1.0.gem
Fetching image_optim 0.25.0
  * image_optim-0.25.0.gem
Fetching fspath 3.1.0
Fetching image_optim 0.25.0
Fetching fspath 3.1.0
Fetching image_optim 0.25.0
Fetching exifr 1.3.1
  * exifr-1.3.1.gem
Fetching fspath 3.1.0
Fetching image_size 1.5.0
  * image_size-1.5.0.gem
Fetching in_threads 1.4.0
  * in_threads-1.4.0.gem
Fetching progress 3.3.1
  * progress-3.3.1.gem
Fetching exifr 1.3.1
Fetching fspath 3.1.0
Fetching image_size 1.5.0
Fetching in_threads 1.4.0
Fetching progress 3.3.1
Fetching exifr 1.3.1
Fetching fspath 3.1.0
Fetching image_size 1.5.0
Fetching in_threads 1.4.0
Fetching progress 3.3.1
❯ tree
.
├── Gemfile
├── Gemfile.lock
└── vendor
    └── cache
        ├── exifr-1.3.1.gem
        ├── fspath-3.1.0.gem
        ├── image_optim-0.25.0.gem
        ├── image_optim_pack-0.5.0.20170712.gem
        ├── image_size-1.5.0.gem
        ├── in_threads-1.4.0.gem
        └── progress-3.3.1.gem
```

**Comment by segiddins** [comment] 2017-07-17 16:10
I don't think we can make this work without `specific_platform` (which will be enabled by default in 2.0)

**Comment by colby-swandale** [comment] 2017-07-22 08:36
I'm closing this for now. If you have any more questions don't be afraid to re-open this ticket.

**Closed by colby-swandale** 2017-07-22 08:36 UTC

**Comment by ylg** [comment] 2017-07-25 14:26
@colby-swandale I'm likely missing the obvious here, why's this closed "for now"? Is there a roadmap to reopen it, was an answer to the question provided privately, or is it considered a duplicate of something in 2.0?

**Comment by segiddins** [comment] 2017-07-25 15:19
The answer is to use the `specific_platform` setting

**Comment by calebthompson** [comment] 2017-07-25 15:22
@segiddins @colby-swandale Unless I misunderstand the feature, that setting isn't causing all platform versions to be packed: https://github.com/bundler/bundler/issues/5863#issuecomment-315770111

**Comment by calebthompson** [comment] 2017-07-25 15:26
@segiddins @colby-swandale Yup, `specific_platform` worked for me in 1.15.3. Thank you!

**Comment by ylg** [comment] 2017-07-26 19:08
Great, thanks all, I was thrown by the last comment on specific_platform being a negative finding.

**Comment by xam7247** [comment] 2017-08-30 15:24
I still face this issue with bundler 1.15.1. 

The only thing that worked was bkoski's comment above (to most extent). Would this be added to bundler's documentation ?
