### ISSUE TITLE
Multiple source warning when using the block and a Gemfile.lock exists

### ISSUE THREAD

**Issue by jbarreneche** [bundler/bundler#4058] opened 2015-10-15 22:16 UTC
Hi, we found an inconsistency with the warning for indirect dependencies in multiple sources, when using the `source` declaration with a block.

The first time you add the source (ie. the Gemfile.lock doesn't have the source) the installation doesn't issue a warning (like this spec suggests https://github.com/bundler/bundler/blob/master/spec/install/gems/sources_spec.rb#L170-L185). Which is what we expected.

But, after the Gemfile.lock is generated (and, if you don't have the gem in your system) if you run `bundle install` the warning is issued. I generated a failing test by extending the previous test #4059.

I think this inconsistency arises from the fact that the Gemfile.lock puts both sources together, and doesn't indicate which source was used to install which gem. eg:

for:
```ruby
source 'https://rubygems.org'

source 'https://blocksource.com/' do
  gem 'depends_on_rack'
end
```

```
GEM
  remote: https://rubygems.org/
  remote: https://blocksource.com/
  specs:
     depends_on_rack
     rack
```
which is the same Gemfile.lock that is generated when you use 2 sources without a block.

I tried to debug it further down, but I got a bit lost :stuck_out_tongue:  If you give me some pointers I can try to fix it.

**Comment by agis-** [comment] 2015-10-26 19:17
This seems like a duplicate of #3671.

**Closed** 2016-01-04 06:09 UTC
