### ISSUE TITLE
Bundle viz deprecation

### ISSUE THREAD

**Issue by fatkodima** [bundler/bundler#7414] opened 2019-11-01 15:38 UTC
```
$ bundle viz
[DEPRECATED] The `viz` command has been moved to the `bundle-viz` gem, see https://github.com/bundler/bundler-viz
Resolving dependencies...
...
```

`https://github.com/bundler/bundler-viz` - returns 404.

So, was this already extracted or is there work in progress or is there a need for someone to do this?

**Comment by deivid-rodriguez** [comment] 2019-11-04 12:19
Closing as a duplicate of https://github.com/bundler/bundler/issues/7041. You can find the information in there.

**Closed by deivid-rodriguez** 2019-11-04 12:19 UTC
