### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by biow0lf** [bundler/bundler#6220] opened 2017-12-22 11:55 UTC
Hello,

```
$ bundle
Fetching https://github.com/plataformatec/devise.git
Traceback (most recent call last):
	10: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/bin/bundle:23:in `<main>'
	 9: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/bin/bundle:23:in `load'
	 8: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
	 7: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	 6: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_errors'
	 5: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `log_error'
	 4: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:45:in `error'
	 3: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:105:in `tell_me'
	 2: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `say'
	 1: from /Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `!~'
/Users/biow0lf/.rbenv/versions/2.5.0-rc1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
$ 
```

ENV:

```
$ ruby -v
ruby 2.5.0rc1 (2017-12-14 trunk 61243) [x86_64-darwin16]
$ bundle -v
Bundler version 1.16.1
$
```

```
$ cat Gemfile 
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'devise', git: 'https://github.com/plataformatec/devise.git', branch: 'master'

$ 
```

Looks like is set LANG= to something like "ru_RU.UTF-8" (or "en_US.UTF-8") problem go away.

**Comment by shevegen** [comment] 2017-12-23 10:25
I've had a similar error with rubygems "gem" itself, in a non-ruby file, when trying to upload a project. Culprit in my case were german umlauts (such as ä ö ü ), in a filename, I think. I ended up renaming these files from german to english and then the problem went away, but I remember reporting this back then. Not sure if rubygems itself fixed that problem.

Those errors are in general quite tedious, IMO.

**Comment by rosenfeld** [comment] 2017-12-28 19:38
I had this problem running bundle from inside a Docker container and even after configuring the Linux locale properly it wouldn't work. So I committed the changes to fix the locale, stopped and removed the container and recreated it and this time it worked. Just in case someone else is struggling to fix this from a `docker exec container bash` session.

**Comment by segiddins** [comment] 2017-12-30 11:41
Thanks, we should probably fix this. Can you try running with `DEBUG=1` so we can see what the underlying error being raised is? Thanks!

**Comment by rosenfeld** [comment] 2017-12-31 12:17
Since I have already fixed the container and no longer have access to the old container (it's a build container, not based in a Dockerfile) I can no longer easily reproduce it. I could probably try if I had more free time but currently there are so many items in my backlog that it's hard for me to set up some time to look at this. I remember the problem happened in some file from the "thor" gem. If I recall correctly it was a regular expression containing some space on it. I wasn't able to find any non ASCII char, so I guess that space wasn't a regular one. Unfortuntately that's all I can remember for the time being. As soon as I find some free time I'll try to reproduce it.

**Comment by rosenfeld** [comment] 2017-12-31 12:22
Actually I just tried unsetting LANG and LANGUAGE in my development machine and was able to reproduce it. Here's the stacktrace:

```
        10: from /home/rodrigo/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
         9: from /home/rodrigo/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
         8: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
         7: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
         6: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_errors'
         5: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `log_error'
         4: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:45:in `error'
         3: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/ui/shell.rb:105:in `tell_me'
         2: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `say'
         1: from /home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `!~'
/home/rodrigo/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:88:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
```

Here's the output before the Traceback when running with DEBUG=1:

```
DEBUG=1 bundle --deployment
Running `bundle install --deployment` with bundler 1.16.1
The git source `git://github.com/plataformatec/devise.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Frozen, using resolution from the lockfile
The definition is missing ["rake-12.3.0", "concurrent-ruby-1.0.5", "i18n-0.9.1", "minitest-5.10.3", "thread_safe-0.3.6", "tzinfo-1.2.4", "activesupport-5.1.4", "builder-3.2.3", "erubi-1.7.0", "mini_portile2-2.3.0", "nokogiri-1.8.1", "rails-dom-testing-2.0.3", "crass-1.0.3", "loofah-2.1.1", "rails-html-sanitizer-1.0.3", "actionview-5.1.4", "rack-2.0.3", "rack-test-0.8.2", "actionpack-5.1.4", "nio4r-2.2.0", "websocket-extensions-0.1.3", "websocket-driver-0.6.5", "actioncable-5.1.4", "globalid-0.4.1", "activejob-5.1.4", "mini_mime-1.0.0", "mail-2.7.0", "actionmailer-5.1.4", "arbre-1.1.1", "coffee-script-source-1.12.2", "execjs-2.7.0", "coffee-script-2.4.1", "method_source-0.9.0", "thor-0.20.0", "railties-5.1.4", "coffee-rails-4.2.2", "formtastic-3.1.5", "formtastic_i18n-0.6.0", "has_scope-0.7.1", "responders-2.4.0", "inherited_resources-1.8.0", "jquery-rails-4.3.1", "kaminari-core-1.1.1", "kaminari-actionview-1.1.1", "activemodel-5.1.4", "arel-8.0.0", "activerecord-5.1.4", "kaminari-activerecord-1.1.1", "kaminari-1.1.1", "polyamorous-1.3.1", "ransack-1.8.4", "rb-fsevent-0.10.2", "ffi-1.9.18", "rb-inotify-0.9.10", "sass-listen-4.0.0", "sass-3.5.4", "sprockets-3.7.1", "activeadmin-1.2.0", "bcrypt-3.1.11", "orm_adapter-0.5.0", "warden-1.2.7", "devise-encryptable-0.2.0", "libv8-3.16.14.19", "pg-0.21.0", "puma-3.11.0", "sprockets-rails-3.2.1", "rails-5.1.4", "rails_compatible_cookies_utils-0.1.2", "ref-2.0.0", "tilt-2.0.8", "sass-rails-5.0.7", "therubyracer-0.12.3", "uglifier-4.0.2"]
HTTP GET https://index.rubygems.org/versions
HTTP 206 Partial Content https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Looking up gems ["rake", "concurrent-ruby", "i18n", "minitest", "thread_safe", "tzinfo", "activesupport", "builder", "erubi", "mini_portile2", "nokogiri", "rails-dom-testing", "crass", "loofah", "rails-html-sanitizer", "actionview", "rack", "rack-test", "actionpack", "nio4r", "websocket-extensions", "websocket-driver", "actioncable", "globalid", "activejob", "mini_mime", "mail", "actionmailer", "arbre", "coffee-script-source", "execjs", "coffee-script", "method_source", "thor", "railties", "coffee-rails", "formtastic", "formtastic_i18n", "has_scope", "responders", "inherited_resources", "jquery-rails", "kaminari-core", "kaminari-actionview", "activemodel", "arel", "activerecord", "kaminari-activerecord", "kaminari", "polyamorous", "ransack", "rb-fsevent", "ffi", "rb-inotify", "sass-listen", "sass", "sprockets", "activeadmin", "bcrypt", "orm_adapter", "warden", "devise", "devise-encryptable", "libv8", "pg", "puma", "sprockets-rails", "rails", "rails_compatible_cookies_utils", "ref", "tilt", "sass-rails", "therubyracer", "uglifier"]
Looking up gems ["functional-ruby", "rails-deprecated_sanitizer", "celluloid", "em-hiredis", "faye-websocket", "redis", "atomic", "erubis", "rack-mount", "rack-cache", "journey", "hoe", "camping", "fcgi", "memcache-client", "mongrel", "ruby-openid", "test-spec", "thin", "json", "multi_json", "activemodel-globalid", "activerecord-deprecated_finders", "ruby_parser", "mime-types", "treetop", "tlsmail", "racc", "rake-compiler", "rexical", "tenderlove-frex", "weakling", "mini_portile", "pkg-config", "text-format", "bcrypt-ruby", "rack-ssl", "rdoc", "inherited_views", "meta_search", "will_paginate", "haml", "fastercsv", "bourbon", "jquery-ui-rails", "listen", "bones", "hike", "activeresource", "actionwebservice", "bundler", "activestorage"]
HTTP GET https://index.rubygems.org/info/treetop
HTTP 304 Not Modified https://index.rubygems.org/info/treetop
Looking up gems ["timers", "facter", "celluloid-essentials", "celluloid-extras", "celluloid-fsm", "celluloid-pool", "celluloid-supervision", "dotenv", "nenv", "rspec-logsplit", "rubyforge", "RubyInline", "gemcutter", "markaby", "metaid", "mab", "ZenTest", "rspec", "eventmachine", "daemons", "eventmachine-le", "http_parser.rb", "preforker", "flexmock", "mocha", "archive-tar-minitar", "rcov", "mime-types-data", "rb-fchange", "rb-kqueue", "celluloid-io", "ruby_dep", "little-plugger", "loquacious", "bones-extras", "bones-git", "ruby-yadis", "ParseTree", "sexp_processor", "rails-observers", "activemodel-serializers-xml", "abstract", "maruku", "yard", "temple", "cgi_multipart_eof_fix", "fastthread", "gem_plugin", "multimap", "hiredis", "text-hyphen", "facets", "polyglot"]
Looking up gems ["celluloid-gems", "coveralls", "rubocop", "CFPropertyList", "sys-admin", "win32-api", "win32console", "win32-dir", "windows-api", "windows-pr", "win32-security", "json_pure", "hitimes", "dotenv-deployment", "metaclass", "syntax", "minitar", "minitar-cli", "net-scp", "SexpProcessor", "git", "cucumber", "diff-lcs", "spicycode-rcov", "rspec-core", "rspec-expectations", "rspec-mocks", "bones-rcov", "bones-rspec", "bones-rubyforge", "bones-zentest"]
Looking up gems ["test-unit", "term-ansicolor", "rainbow", "parser", "backports", "powerpack", "ruby-progressbar", "astrolabe", "tins", "unicode-display_width", "parallel", "ffi-win32-extensions", "rspec-support", "net-ssh", "colorize", "rest-client", "simplecov", "powerbar", "libxml-ruby", "gherkin", "multi_test", "cucumber-core", "gherkin3", "cucumber-wire", "event-bus", "cucumber-expressions", "configuration", "mkrf", "spruz"]
Looking up gems ["ast", "slop", "netrc", "http-cookie", "http-accept", "ansi", "hashie", "power_assert", "cucumber-tag_expressions", "simplecov-html", "docile", "lockfile", "trollop", "echoe", "needle", "jruby-pageant", "bcrypt_pbkdf", "rbnacl", "rbnacl-libsodium"]
Looking up gems ["curses", "pattern-match", "highline", "allison", "domain_name", "sqlite3"]
Looking up gems ["unf", "termios"]
Looking up gems ["unf_ext"]
```

It's an admin app built on top of `active_admin`. There's nothing really special about it. The main app is a separate non Rails project (built on top of Roda instead).

**Comment by rosenfeld** [comment] 2017-12-31 12:24
Just to make it easier for you, here's the offending line: https://github.com/bundler/bundler/blob/master/lib/bundler/vendor/thor/lib/thor/shell/basic.rb#L88

**Comment by rosenfeld** [comment] 2017-12-31 12:29
I opened it in Vim and couldn't actually find any non ASCII char in that file, so maybe that is caused by some bug in Ruby 2.5.0.

**Comment by rposborne** [comment] 2018-01-12 03:38
I had been able to isolate this down outside our app,   and wrapped it up in a repo https://github.com/rposborne/bundler-ruby-2-5 

Hopefully this helps solve the issue

**Comment by segiddins** [comment] 2018-01-13 05:31
https://github.com/plataformatec/devise/pull/4753 should fix this!

**Comment by rposborne** [comment] 2018-01-13 06:05
@segiddins Thank for the quick follow up on this!  Glad the repor steps helped!

**Comment by colby-swandale** [comment] 2018-07-17 10:04
It seems like this issue has been resolved, feel free to ping if otherwise.

**Closed by colby-swandale** 2018-07-17 10:04 UTC
Labels: type: bug report
