### ISSUE TITLE
Valid config in 1.6.2 is no longer valid in 1.9.2

### ISSUE THREAD

**Issue by punkle** [bundler/bundler#3557] opened 2015-04-10 10:59 UTC
I recently updated bunder to version 1.9.2. Config that was valid in the previous version 1.6.2 is no longer valid.

    ---
    BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG: https://redacted_url/
    BUNDLE_MIRROR__HTTP://RUBYGEMS.ORG: https://redacted_url/

 

      ruby-1.9.3-p484@dd 11:53:38-brian.fletcher~/project$ bundle install
      ――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
      - What did you do?
      - What did you expect to happen?
      - What happened instead?

      Error details

          ArgumentError: Gem sources must be absolute. You provided '/'.
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/settings.rb:196:in `normalize_uri'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/settings.rb:63:in `block in gem_mirrors'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/settings.rb:60:in `each'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/settings.rb:60:in `inject'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/settings.rb:60:in `gem_mirrors'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source.rb:11:in `mirror_for'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/fetcher.rb:400:in `configured_uri_for'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/fetcher.rb:109:in `initialize'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:201:in `new'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:201:in `block in fetchers'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:200:in `map'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:200:in `fetchers'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:306:in `block in remote_specs'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/index.rb:9:in `build'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:305:in `remote_specs'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/source/rubygems.rb:79:in `specs'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:204:in `block (2 levels) in index'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:202:in `each'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:202:in `block in index'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/index.rb:9:in `build'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:199:in `index'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:193:in `resolve'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/definition.rb:121:in `resolve_remotely!'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/installer.rb:79:in `run'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/installer.rb:18:in `install'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/cli/install.rb:80:in `run'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/cli.rb:157:in `install'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/cli.rb:10:in `start'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/bin/bundle:20:in `block in <top (required)>'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/gems/bundler-1.9.2/bin/bundle:18:in `<top (required)>'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/bin/bundle:23:in `load'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/bin/bundle:23:in `<main>'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/bin/ruby_executable_hooks:15:in `eval'
          /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd/bin/ruby_executable_hooks:15:in `<main>'

      Environment

          Bundler   1.9.2
          Rubygems  2.4.5
          Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin12.5.0]
          GEM_HOME  /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd
          GEM_PATH  /Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@dd:/Users/brian.fletcher/.rvm/gems/ruby-1.9.3-p484@global
          RVM       1.25.24 (stable)
          Git       1.9.5 (Apple Git-50.3)
          rubygems-bundler (1.4.2)

      Bundler settings

          mirror.https://rubygems.org
            You have not configured a value for `mirror.https://rubygems.org`
          mirror.http://rubygems.org
            You have not configured a value for `mirror.http://rubygems.org`
      ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

      Unfortunately, an unexpected error occurred, and Bundler cannot continue.

      First, try this link to see if there are any existing issue reports for this error:
      https://github.com/bundler/bundler/search?q=Gem+sources+must+be+absolute.+You+provided+%27%2F%27.&type=Issues

      If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
      https://github.com/bundler/bundler/issues/new

**Comment by indirect** [comment] 2015-04-10 19:24
Ugh, I thought we had fixed this. :( Thanks for the report!

**Comment by punkle** [comment] 2015-04-10 19:31
no probs

**Comment by fantasticfears** [comment] 2015-04-24 15:12
This problem remains in 1.9.4

Environment

    Bundler   1.9.4
    Rubygems  2.4.6
    Ruby      2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
    GEM_HOME  /Users/fantasticfears/.rvm/gems/ruby-2.2.2
    GEM_PATH  /Users/fantasticfears/.rvm/gems/ruby-2.2.2:/Users/fantasticfears/.rvm/gems/ruby-2.2.2@global
    RVM       1.26.11 (latest)
    Git       2.3.1
    rubygems-bundler (1.4.4)

**Comment by Strech** [comment] 2015-05-07 04:57
@punkle @fantasticfears can you provide config example?

**Comment by fantasticfears** [comment] 2015-05-07 06:05
I can't reproduce this anymore after fresh reinstall the RVM.

Anyway, my config:

    ---
    BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/: https://ruby.taobao.org/

**Comment by punkle** [comment] 2015-05-13 14:04
@fantasticfears the issue occurs where you use an old config with a later bundler.

@Strech her is a config example
    ---
    BUNDLE_MIRROR__HTTPS://RUBYGEMS.ORG: https://redacted_url/
    BUNDLE_MIRROR__HTTP://RUBYGEMS.ORG: https://redacted_url/

**Comment by Strech** [comment] 2015-05-13 21:04
I think, i can fix it :wrench:

**Comment by indirect** [comment] 2015-05-16 22:36
This should be fixed in the 1.9.9 release, coming out as soon as the CI build passes.

**Closed by indirect** 2015-05-16 22:36 UTC
Labels: bug

**Comment by fantasticfears** [comment] 2015-05-17 02:34
👍
