### ISSUE TITLE
Remove dependency from git in new gemspec template

### ISSUE THREAD

**Issue by jolting** [bundler/bundler#6281] opened 2018-01-31 20:46 UTC
This is fine if git is installed, but that might not always be the case for systems that are running Alpine Linux.

This line has made tons of gems dependent on git.
https://github.com/bundler/bundler/blob/fe9d6989a11443dbfe1840cc07f89918e3d7b37d/lib/bundler/templates/newgem/newgem.gemspec.tt#L32

As this article suggests there is a far simpler solution that doesn't require shelling out to git.
http://www.codinginthecrease.com/news_article/show/350843-using-git-in-your-gemspec

Specifically:
```
spec.files = Dir.glob("{bin,lib}/**/*") + %w(LICENSE README.md)
```

**Comment by jolting** [comment] 2018-01-31 20:58
#2287 mentions that bundler caches the result of the gemspec, but if you're using private_gems you'll need to install git on the production system.

**Comment by colby-swandale** [comment] 2018-01-31 21:34
Duplicate of #5810

**Closed by colby-swandale** 2018-01-31 21:34 UTC
