### ISSUE TITLE
nested bundle exec, not working in Ruby trunk/head

### ISSUE THREAD

**Issue by MSP-Greg** [bundler/bundler#7244] opened 2019-07-10 20:01 UTC
Only on Ruby trunk/head, there's a Travis CI test issue with Puma that generates a `LoadError`, where a `bundle exec` command is generated within a process started via `bundle exec`.

So, I used the following command:
```
bundle exec "bundle exec 'ruby -v'"
```

Works fine with Ruby 2.6.3, RG 3.0.3, & bundler 2.0.1.

With Ruby trunk/master/head/2.7.0 (RG 3.1.0.pre1, bundler 2.1.0.pre.1), it fails on the line in the bin stub:
```ruby
load Gem.activate_bin_path('bundler', 'bundle', version)
```
Correct value is:
```
lib/ruby/gems/2.7.0/gems/bundler-2.1.0.pre.1/exe/bundle
```
nested value is the following, which doesn't exist, and generates the LoadError:
```
lib/bin/bundle
```

**EDIT:**

Sorry for not making it explicitly clear, but `bundle exec "ruby -v"` works fine in both.  The only issue is nested `bundle exec`'s, which may be common in testing started with 'bundle exec rake \<test\>`...

**Comment by deivid-rodriguez** [comment] 2019-07-10 21:27
I tried this on current master and it seems to work, so this should probably be fixed once a newer bundler commit is used in ruby-core. I did this on current master, not sure if it fully represents the case you're seeing:

```
~/Code/bundler $ touch Gemfile
~/Code/bundler $ RUBYOPT=-Ilib exe/bundle exec 'bundle exec "ruby -v"'
Resolving dependencies...
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

**Comment by MSP-Greg** [comment] 2019-07-10 21:27
Fixed in https://github.com/ruby/ruby/pull/2285

**Comment by MSP-Greg** [comment] 2019-07-10 21:29
@deivid-rodriguez

You have to use Ruby trunk/master/2.7.0.  Explanation in the above ruby PR...

**Comment by deivid-rodriguez** [comment] 2019-07-10 21:44
You don't make PRs to ruby-core for bundler. You make PRs to the bundler repo, and then they are backported to ruby.

Currently the ruby repo is using and older reference than current bundler's master, and the issue you mention is not reproducible on bundler's master. Once ruby-core is updated to the latest bundler, the issue should be fixed since I can't reproduce it here.

**Comment by deivid-rodriguez** [comment] 2019-07-10 21:51
Sorry @MSP-Greg, I read your PR now. No idea whether it is correct or not, but the case for a regular bundler installation shouldn't be affected, so I guess if that fixes some failures in core, it's fine? @hsbt will know best... :man_shrugging:

**Comment by MSP-Greg** [comment] 2019-07-10 21:57
@deivid-rodriguez

Thanks.  I saw your previous response, and assumed you hadn't read the PR.

Yes and yes.  I'm not sure if `Gem.dir` always points to the 'internal' gem folder where default and bundled gems/specs are stored.  There's too many OS's out there, but it's an improvement on the current, which breaks some CI testing (Ruby trunk only) that uses nested `bundle exec`'s.

I'm kind of sensitive about trunk failures...

**Comment by MSP-Greg** [comment] 2019-07-11 15:21
> so I guess if that fixes some failures in core

Actually, the failure is a result of bundler being installed as a default gem, so that really isn't a 'Ruby core' issue, it's just that core/trunk is the only place that happens.

I don't know what exactly the 'integration plans' are, but if RG and Bundler will be separate default gems as they are in trunk...

Regardless, this breaks trunk CI, and considering that a few times when I've suggested that repos test against it, they complain about failures, issues like this should get fixed in a prompt manner, regardless of upstream, downstream, or a body of water.

Lastly, I have no idea how to write a test for this, as the failure happens when the bundler exe folder is in its installed location...

**Comment by MSP-Greg** [comment] 2019-07-13 13:40
@deivid-rodriguez

Just looked into this a little further (as opposed to while taking a break from a mess), and the issue is a result of a PR of yours.  Not being critical, as this is an edge case.  See https://github.com/bundler/bundler/commit/e742c3d5f458a4a59cf0eaab2567eca844f956d1 and #7100.  

See PR #7248.

I may add a test for this in ruby-loco, as I've already got several 'CLI' tests...

**Closed** 2019-07-19 05:14 UTC
