### ISSUE TITLE
Conflicting platform dependencies still not resolving.

### ISSUE THREAD

**Issue by nomoon** [bundler/bundler#5349] opened 2017-01-23 04:59 UTC
Re #5340 closed as fixed in 1.14.2, I'm still getting the same error.

I seem to still be getting this error with Bundler 1.14.2 and JRuby (ruby-concurrency/thread_safe#29)

## Environment

```
Bundler   1.14.2
Rubygems  2.6.8
Ruby      2.3.1p0 (2016-11-09 revision 54768) [java]
GEM_HOME  /Users/nomoon/.rvm/gems/jruby-9.1.6.0@thread_safe
GEM_PATH  /Users/nomoon/.rvm/gems/jruby-9.1.6.0@thread_safe:/Users/nomoon/.rvm/gems/jruby-9.1.6.0@global
RVM       1.28.0 (latest)
Git       2.11.0
Platform  universal-java-1.8
rubygems-bundler (1.4.4)
```

## Bundler settings

```
build.eventmachine
  Set for the current user (/Users/nomoon/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
gem.test
  Set for the current user (/Users/nomoon/.bundle/config): "rspec"
gem.coc
  Set for the current user (/Users/nomoon/.bundle/config): "true"
gem.mit
  Set for the current user (/Users/nomoon/.bundle/config): "true"
local.readthis
  Set for the current user (/Users/nomoon/.bundle/config): "/Users/nomoon/LocalDev/readthis"
force_ruby_platform
  Set for the current user (/Users/nomoon/.bundle/config): "false"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'rspec', '~> 3.2.0'
  gem 'simplecov', '~> 0.9.2', :require => false
  if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.0.0')
    gem 'term-ansicolor', '~> 1.3.2', :require => false
    gem 'tins', '~> 1.6.0', :require => false
  end
  gem 'coveralls', '~> 0.7.11', :require => false
end

group :documentation do
  gem 'countloc', '~> 0.4.0', :platforms => :mri, :require => false
  gem 'yard', '~> 0.8.7.6', :require => false
  gem 'inch', '~> 0.5.10', :platforms => :mri, :require => false
  gem 'redcarpet', '~> 3.2.2', platforms: :mri # understands github markdown
end
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    thread_safe (0.3.5-java)

GEM
  remote: https://rubygems.org/
  specs:
    atomic (1.1.16-java)
    coveralls (0.7.12)
      multi_json (~> 1.10)
      rest-client (>= 1.6.8, < 2)
      simplecov (~> 0.9.1)
      term-ansicolor (~> 1.3)
      thor (~> 0.19.1)
    diff-lcs (1.3)
    docile (1.1.5)
    domain_name (0.5.20161129)
      unf (>= 0.0.5, < 1.0.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    mime-types (2.99.3)
    multi_json (1.12.1)
    netrc (0.11.0)
    rake (11.3.0)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rspec (3.2.0)
      rspec-core (~> 3.2.0)
      rspec-expectations (~> 3.2.0)
      rspec-mocks (~> 3.2.0)
    rspec-core (3.2.3)
      rspec-support (~> 3.2.0)
    rspec-expectations (3.2.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-mocks (3.2.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-support (3.2.2)
    simplecov (0.9.2)
      docile (~> 1.1.0)
      multi_json (~> 1.0)
      simplecov-html (~> 0.9.0)
    simplecov-html (0.9.0)
    term-ansicolor (1.4.0)
      tins (~> 1.0)
    thor (0.19.4)
    tins (1.13.0)
    unf (0.1.4-java)
    yard (0.8.7.6)

PLATFORMS
  java

DEPENDENCIES
  atomic (= 1.1.16)
  countloc (~> 0.4.0)
  coveralls (~> 0.7.11)
  inch (~> 0.5.10)
  rake (< 12.0)
  redcarpet (~> 3.2.2)
  rspec (~> 3.2.0)
  simplecov (~> 0.9.2)
  thread_safe!
  yard (~> 0.8.7.6)

BUNDLED WITH
   1.14.2
```

### thread_safe.gemspec

```ruby
# -*- encoding: utf-8 -*-
$:.push File.expand_path('../lib', __FILE__) unless $:.include?('lib')
require 'thread_safe/version'

Gem::Specification.new do |gem|
  gem.authors       = ["Charles Oliver Nutter", "thedarkone"]
  gem.email         = ["headius@headius.com", "thedarkone2@gmail.com"]
  gem.summary       = %q{Thread-safe collections and utilities for Ruby}
  gem.description   = %q{A collection of data structures and utilities to make thread-safe programming in Ruby easier}
  gem.homepage      = "https://github.com/ruby-concurrency/thread_safe"

  gem.files         = `git ls-files`.split($\)
  gem.files        += ['lib/thread_safe/jruby_cache_backend.jar'] if defined?(JRUBY_VERSION)
  gem.files        -= ['.gitignore'] # see https://github.com/headius/thread_safe/issues/40#issuecomment-42315441
  gem.platform      = 'java' if defined?(JRUBY_VERSION)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.name          = "thread_safe"
  gem.require_paths = ["lib"]
  gem.version       = ThreadSafe::VERSION
  gem.license       = "Apache-2.0"

  gem.add_development_dependency 'atomic', '= 1.1.16'
  gem.add_development_dependency 'rake', '< 12.0'
  gem.add_development_dependency 'rspec', '~> 3.2'
end
```

```
$ bundle install
The dependency countloc (~> 0.4.0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform mri`.
The dependency inch (~> 0.5.10) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform mri`.
The dependency redcarpet (~> 3.2.2) will be unused by any of the platforms Bundler is installing for. Bundler is installing for java but the dependency is only for ruby. To add those platforms to the bundle, run `bundle lock --add-platform mri`.
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing rake 11.3.0
Installing atomic 1.1.16 (java)
Installing multi_json 1.12.1
Installing unf 0.1.4 (java)
Installing mime-types 2.99.3
Installing netrc 0.11.0
Installing docile 1.1.5
Installing simplecov-html 0.9.0
Installing tins 1.13.0
Installing thor 0.19.4
Installing diff-lcs 1.3
Installing rspec-support 3.2.2
Using thread_safe 0.3.5 (java) from source at `.`
Installing yard 0.8.7.6
Using bundler 1.14.2
Installing domain_name 0.5.20161129
Installing simplecov 0.9.2
Installing term-ansicolor 1.4.0
Installing rspec-core 3.2.3
Installing rspec-expectations 3.2.1
Installing rspec-mocks 3.2.1
Installing http-cookie 1.0.3
Installing rspec 3.2.0
Installing rest-client 1.8.0
Installing coveralls 0.7.12
Bundle complete! 10 Gemfile dependencies, 25 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle exec rake -T
Bundler could not find compatible versions for gem "unf":
  In snapshot (Gemfile.lock):
    unf (= 0.1.4) java

  In Gemfile:
    coveralls (~> 0.7.11) java was resolved to 0.7.12, which depends on
      rest-client (< 2, >= 1.6.8) java was resolved to 1.8.0, which depends on
        http-cookie (< 2.0, >= 1.0.2) java was resolved to 1.0.3, which depends on
          domain_name (~> 0.5) java was resolved to 0.5.20161129, which depends on
            unf (< 1.0.0, >= 0.0.5) java

    coveralls (~> 0.7.11) java was resolved to 0.7.12, which depends on
      rest-client (< 2, >= 1.6.8) java was resolved to 1.8.0, which depends on
        http-cookie (< 2.0, >= 1.0.2) java was resolved to 1.0.3, which depends on
          domain_name (~> 0.5) java was resolved to 0.5.20161129, which depends on
            unf (< 1.0.0, >= 0.0.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

If I revert to Bundler 1.13.7, everything works as expected.

**Comment by jsvd** [comment] 2017-01-23 10:02
I also confirm this is failing:

```
/tmp/bundler_test % ruby -v 
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14 +jit [darwin-x86_64]
/tmp/bundler_test % bundler -v
Bundler version 1.14.2
/tmp/bundler_test % ls
Gemfile     bundler.gemspec
/tmp/bundler_test % cat Gemfile
gemspec
/tmp/bundler_test % cat bundler.gemspec
Gem::Specification.new do |s|

  s.name            = 'bundler_spec'
  s.version         = '0.0.1'
  s.licenses        = ['Apache License (2.0)']
  s.summary         = ""
  s.description     = ""
  s.authors         = [""]
  s.email           = ''
  s.homepage        = ""
  s.require_paths = [""]

  s.add_runtime_dependency "http_parser.rb"
  s.add_development_dependency "rake"
end

/tmp/bundler_test % bundle install
Resolving dependencies...
Using rake 12.0.0
Using http_parser.rb 0.6.0 (java)
Using bundler 1.14.2
Using bundler_spec 0.0.1 from source at `.`
Bundle complete! 2 Gemfile dependencies, 4 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
j/tmp/bundler_test % bundle install
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on
your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "http_parser.rb":
  In snapshot (Gemfile.lock):
    http_parser.rb (= 0.6.0) java

  In Gemfile:
    bundler_spec java was resolved to 0.0.1, which depends on
      http_parser.rb java

    bundler_spec java was resolved to 0.0.1, which depends on
      http_parser.rb

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by jcoyne** [comment] 2017-01-23 15:43
I'm also getting this with nokogiri:

```
Bundler could not find compatible versions for gem "nokogiri":
  In snapshot (Gemfile.lock):
    nokogiri (= 1.7.0.1) java
  In Gemfile:
    simple_solr_client java was resolved to 0.1.2, which depends on
      nokogiri java
    simple_solr_client java was resolved to 0.1.2, which depends on
      nokogiri
```

**Comment by segiddins** [comment] 2017-01-23 16:02
If anyone is interested in running a git bisect, that might make it clearer what caused the regression -- I don't know when I'll be able to look into the issue myself.

**Comment by jsvd** [comment] 2017-01-23 16:27
The result of my bisect points to 4233b7329e2cfd15f907d9abc69940330fbb1b00

see gist for full run and files used: https://gist.github.com/jsvd/4e0e66b666600a67bc0077df2e913e46

**Comment by segiddins** [comment] 2017-01-23 17:53
Thanks! That gives me some idea of what the problem is (the resolver not having context around what all of the available platforms of locked specs are)

**Comment by segiddins** [comment] 2017-01-23 20:00
This seems to fix at least one of the reproduction cases, going to run against the bundler tests suite to see if it causes any regressions. Verifying if it also fixes the issue for you would also be very helpful

```diff
diff --git a/lib/bundler/definition.rb b/lib/bundler/definition.rb
index 15383a22c..934e12689 100644
--- a/lib/bundler/definition.rb
+++ b/lib/bundler/definition.rb
@@ -691,7 +691,7 @@ module Bundler
           dep.platforms.concat(@platforms.map {|p| Dependency::REVERSE_PLATFORM_MAP[p] }.flatten(1)).uniq!
         end
       end
-      Set.new(@dependencies) != Set.new(@locked_deps)
+      Set.new(@dependencies.map {|d| Gem::Dependency.new(d.name, *d.requirement.as_list)}) != Set.new(@locked_deps.map {|d| Gem::Dependency.new(d.name, *d.requirement.as_list)})
     end
 
     # Remove elements from the locked specs that are expired. This will most
```

**Comment by segiddins** [comment] 2017-01-23 20:48
Seems like the real resolver fix is the following:

```diff
diff --git a/lib/bundler/resolver.rb b/lib/bundler/resolver.rb
index 2eff76d..2cd5720 100644
--- a/lib/bundler/resolver.rb
+++ b/lib/bundler/resolver.rb
@@ -308,7 +308,9 @@ module Bundler
 
     def requirement_satisfied_by?(requirement, activated, spec)
       return false unless requirement.matches_spec?(spec) || spec.source.is_a?(Source::Gemspec)
-      spec.activate_platform!(requirement.__platform) || spec.for?(requirement.__platform)
+      # spec.activate_platform!(requirement.__platform) if Bundler.definition.platforms.include?(requirement.__platform)
+      spec.activate_platform!(requirement.__platform) if Bundler.definition.platforms.include?(requirement.__platform)
+      true
     end
 
     def sort_dependencies(dependencies, activated, conflicts)
```

**Comment by segiddins** [comment] 2017-01-23 23:50
https://github.com/bundler/bundler/pull/5355 _should_ be the real fix for this issue, if y'all want to try it out

**Comment by nomoon** [comment] 2017-01-24 03:36
@segiddins Seems to be working for me.

**Comment by jsvd** [comment] 2017-01-24 09:02
I confirm https://github.com/bundler/bundler/pull/5355 also works for me 👍

**Closed** 2017-01-24 17:26 UTC
Labels: type: bug report
