### ISSUE TITLE
errors bundle

### ISSUE THREAD

**Issue by jeffersonmena** [bundler/bundler#5160] opened 2016-11-08 23:51 UTC
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Permission+denied+%40+rb_sysopen+-+%2Ftmp%2Fbundler-compact-index-20161108-4734-1m88uhi%2Fversions&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new

**Comment by segiddins** [comment] 2016-11-08 23:55
Please fill out the information requested in https://github.com/bundler/bundler/blob/master/ISSUES.md#reporting-unresolved-problems, including the error report you encountered. thanks!

**Comment by lynnco** [comment] 2016-11-12 06:03
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) `Permission denied` issues. A suite of permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14. Until 1.14 releases, the team doesn't have the capacity to deal with, or deploy more fixes for, the quantity of permissions errors we receive.

I'm sorry you are experiencing issues and I hope you can get them resolved!!!

**Closed by lynnco** 2016-11-12 06:03 UTC
