### ISSUE TITLE
RubyGems post-install hook not triggering

### ISSUE THREAD

**Issue by brandonweiss** [bundler/bundler#5429] opened 2017-02-14 06:25 UTC
I see a lot of talk about Bundler install hooks on different issues/PRs that (like this thread) mentions that Bundler respects RubyGems post install hooks, but I'm testing it out and that doesn't seem to be the case… if I install via `gem install` the hook runs, but if I add the gem to a Gemfile and install it doesn't seem to be triggering the hook. Is that unexpected?

**Comment by brandonweiss** [comment] 2017-02-14 06:29
The easiest way I found to test this out is to create a new gem. Add a file at `lib/rubygems_plugin.rb` with something like this:

```ruby
Gem.post_install do
  File.write("~/test.txt", "it worked!")
end
```

If you do `rake install` you should see the gem install and then that file will be written to your home directory.

But if you create a new folder, add a Gemfile, and reference your gem via `path: "path/to/your/gem"`, and then `bundle install`, the file won't be written.

**Comment by indirect** [comment] 2017-02-14 07:06
Thanks for reporting this! Running `bundle install` with `path` gems does not install those gems. The `path` feature is a shortcut to add the path to $LOAD_PATH, and does not do any of the usual gen installation procedures. Please create a gem if you need to run a post-install hook during `bundle install`.

**Comment by brandonweiss** [comment] 2017-02-14 07:07
Hmm, if memory serves I also tried that because I suspected `path` might be bypassing this… but I can't remember. Let me try that now.

**Comment by brandonweiss** [comment] 2017-02-14 07:16
Yeah, I just tried it with a private gem on GitHub… oh wait, does that not work either? Does it only trigger the install hook if the source is RubyGems?

**Comment by indirect** [comment] 2017-02-14 11:28
@brandonweiss I honestly don't know about git gems, but I would only expect a post-install hook to run from an actual .gem file coming from a gem server, yeah.

**Comment by brandonweiss** [comment] 2017-02-14 15:08
No wait, that doesn't make any sense, because if I `rake install` it gets run. It definitely shouldn't matter where it gets installed from.

**Comment by brandonweiss** [comment] 2017-02-14 15:20
OK, my theory is that it has something to do that I install gems with `bundle install --path`. That sorts of makes sense, in that if it's just being dumped in a directory and Bundler is doing some magic to load the gem, and if what's actually causing the post install hook to fire is Rubygems, then maybe Rubygems never gets the chance to trigger it?

I tried to test this out by removing the path, although… that's weird, I don't see the gem when I do `gem list`. And when I run `bundle show gem_name` it's in:

`/Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/gem_name`

Shouldn't it be in the outer-level gem directory? Did Bundler change at some point to nest it inside the Bundler gem?

**Comment by segiddins** [comment] 2017-02-15 17:59
Bundler only should be running the install hooks when it runs an actual gem installer, which definitely doesn't happen for path gems

**Comment by brandonweiss** [comment] 2017-02-15 19:53
By “path gems” do you mean a gem that is referenced in a Gemfile via the `path` option or when gems are installed via Bundler to a local path via the `path` flag? The former I guess makes sense, although the latter is not what I'd expect… I would not expect a gem to install differently simply because gems are being put in a specific directory.

**Comment by segiddins** [comment] 2017-02-15 20:12
Via the `:path` option in the Gemfile

**Comment by indirect** [comment] 2017-02-17 06:32
@brandonweiss to answer your earlier question, I believe that gems in `bundler/gems` are `:git` gems? If a `.gem` built gem is installed via `bundle install`, it shouldn't go into a directory named `bundler`. Maybe you have some environment variable or bundler setting changing the `--path` still?

**Comment by brandonweiss** [comment] 2017-02-18 03:27
@indirect Oh, well I am installing it via GitHub at the moment, so that would make sense why it's being installed there. OK, so maybe it's _still_ bypassing the RubyGems install process and thus not triggering the post-install hook. Let me try publishing a gem to RubyGems and see if installing via bundler triggers the post-install hook.

**Comment by colby-swandale** [comment] 2017-03-06 12:04
ping @brandonweiss

**Comment by colby-swandale** [comment] 2017-03-23 10:35
I'm closing this for now but feel free to open this again if needed

**Comment by glebm** [comment] 2017-06-03 19:07
The install from path not triggering `lib/rubygems_plugin.rb`-registered hooks issue still exists.

**Comment by segiddins** [comment] 2017-06-03 19:22
Please share a gemfile that we can use to reproduce the issue

**Comment by glebm** [comment] 2017-06-03 19:35
Remove the workaround here:

https://github.com/glebm/critical-path-css-rails/blob/penthouse-npm/Gemfile#L7-L10

The run `bundle`: https://github.com/glebm/critical-path-css-rails/tree/penthouse-npm

(note that `gemspec` is effectively a `path` gem)

**Comment by segiddins** [comment] 2017-06-03 20:00
Ah now I understand, thanks!

**Comment by indirect** [comment] 2017-06-03 20:09
@glebm gems from paths are never installed, and that's why the post install hook is not firing. can you describe what you would expect to happen with a post install hook for gems that aren't installed? what's the goal you're trying to accomplish?

**Comment by segiddins** [comment] 2017-06-03 20:11
@indirect it's just that the plugin file should be loaded, if I'm understanding correctly. I have a patch nearly done

**Comment by brandonweiss** [comment] 2017-06-03 20:18
Sorry I haven't followed up with a repro 😞 Distracted by two many things.

It's possible the term “installation” might have a particular meaning here that I'm not getting, but if I made a gem, someone might “install” it a number of ways.

## Manually to global gems
`gem install gem_name`

## From a Gemfile with Bundler to global gems
```ruby
source "http://rubygems.org"

gem "gem_name"
```

`bundle install`

## From a Gemfile via path with Bundler to global gems
```ruby
source "http://rubygems.org"

gem "gem_name", path: "~/Code/gem_name"
```

`bundle install`

## From a gemfile with Bundler to local path
```ruby
source "http://rubygems.org"

gem "gem_name"
```

`bundle install --path vendor`

---

It's possible there are some other permutations I'm not thinking of, but from my perspective, running `bundle install` is installing all of these. I get technically in some cases it's probably not (like specifying the gem via path), but I would expect every single one of these to trigger the post-install hook. Does that seem reasonable?

**Comment by segiddins** [comment] 2017-06-03 20:21
> From a Gemfile via path with Bundler to global gems

This case doesn't actually _install_ `gem_name`, it just puts its require paths on the `load_path`

**Comment by glebm** [comment] 2017-06-03 20:27
@segiddins True but that's an implementation detail. The expection is that `rubygems_plugins` are loaded.

**Comment by segiddins** [comment] 2017-06-03 20:35
Loading the plugins is separate from post install hooks, and I think loading them is totally reasonable

**Comment by glebm** [comment] 2017-06-03 22:01
If you load the plugins, their post-install hooks will run, right?

**Comment by glebm** [comment] 2017-06-03 22:02
*post- and pre-install hooks

**Comment by brandonweiss** [comment] 2017-06-03 22:13
I guess I don't really understand the terminology… I would assume loading the plugin would then trigger a pre/post-install hook (if one exists) because they're defined in `lib/rubygems_plugin.rb` in a gem?

**Comment by glebm** [comment] 2017-06-03 23:58
Yes, that's what I think as well. Just checking as I am a bit confused by @segiddins's last comment

**Comment by glebm** [comment] 2017-06-04 10:20
Looks like hooks will not trigger during the gems installation (by design): http://help.rubygems.org/discussions/problems/378-gempre_install-does-not-working-as-it-named

**Closed** 2017-06-16 01:11 UTC
Labels: status: user feedback required

**Comment by brandonweiss** [comment] 2017-07-25 17:38
Damn. That is really disappointing. `npm` has this ability and it's super-useful. 😞

**Comment by brandonweiss** [comment] 2017-07-27 14:30
OK, I sort of got it working, actually. Here's the repo: https://github.com/brandonweiss/git-hookshot

Instead of using `rubygems_plugin.rb` to define an install hook, I just defined it in the gemspec. The reason I thought it worked and shipped it is because when I was testing this I was using the GitHub repo as the source in my Gemfile. And when I bundle installed the first time, or any time I bundle updated the install hook would run and generate the directory and symlinks.

But someone just noticed that if they use RubyGems as a source then it doesn't work. Is that expected? That pre/post install hooks would run if the source is from GitHub but not RubyGems?
