### ISSUE TITLE
v1.15.4 - Different LOAD_PATH when bundle config local.GEMFILE used

### ISSUE THREAD

**Issue by apsoto** [bundler/bundler#6070] opened 2017-09-30 00:32 UTC
I have a gem I develop locally.  The gemspec's require paths are:

      s.require_paths = Dir['{app,app/models,config,db,lib}']

I have for years used `bundle config local.GEMNAME PATH_TO_LOCAL` to point my project's to my local checkout of the gem.

I recently upgraded to bundler v1.15.4 and I'm seeing a different $LOAD_PATH than when I used v1.14.3

I expect to the see following directories from my gem in the $LOAD_PATH:
```
/Users/asoto/projects/wurl_show_data/app
/Users/asoto/projects/wurl_show_data/app/models
/Users/asoto/projects/wurl_show_data/config
/Users/asoto/projects/wurl_show_data/db
/Users/asoto/projects/wurl_show_data/lib
```

but instead, when using `bundle config local.GEMNAME PATH_TO_LOCAL` I only see:
```
/Users/asoto/projects/wurl_show_data/config
/Users/asoto/projects/wurl_show_data/db
/Users/asoto/projects/wurl_show_data/lib
```

If I delete the bundle config setting, I then see the paths I expected.

Sample outputs of v1.15.4 and v1.14.3 below

v1.15.4:
```
$ bundle --version
Bundler version 1.15.4
$ bundle config local.wurl_show_data /Users/asoto/projects/wurl_show_data
$ bundle exec ruby -e "puts $:.sort.select {|path| path.match('wurl_show_data') }"
/Users/asoto/projects/wurl_show_data/config
/Users/asoto/projects/wurl_show_data/db
/Users/asoto/projects/wurl_show_data/lib
$ bundle config --delete local.wurl_show_data
$ bundle exec ruby -e "puts $:.sort.select {|path| path.match('wurl_show_data') }"
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/app
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/app/models
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/config
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/db
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/lib
```

In v1.14.3
```
$ bundle --version
Bundler version 1.14.3
$ bundle config local.wurl_show_data /Users/asoto/projects/wurl_show_data
$ bundle exec ruby -e "puts $:.sort.select {|path| path.match('wurl_show_data') }"
/Users/asoto/projects/wurl_show_data/app
/Users/asoto/projects/wurl_show_data/app/models
/Users/asoto/projects/wurl_show_data/config
/Users/asoto/projects/wurl_show_data/db
/Users/asoto/projects/wurl_show_data/lib
$ bundle config --delete local.wurl_show_data
$ bundle exec ruby -e "puts $:.sort.select {|path| path.match('wurl_show_data') }"
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/app
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/app/models
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/config
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/db
/Users/asoto/projects/wurl-event-processors/vendor/bundler/bundler/gems/wurl_show_data-9c76dd535074/lib
```

**Comment by apsoto** [comment] 2017-09-30 00:34
I also see the same broken behavior in `1.16.0.pre.2`

**Comment by segiddins** [comment] 2017-10-20 18:36
Can you share a project we can use to reproduce the issue? Thanks!

**Comment by colby-swandale** [comment] 2017-11-01 11:19
ping @apsoto

**Comment by apsoto** [comment] 2017-11-06 17:18
sorry, I've been swamped an unable to get this back to you.  I worked around by reverting to an older version of bundler.

**Comment by segiddins** [comment] 2017-12-30 11:59
Closing due to the of a project that reproduces the issue.

**Closed by segiddins** 2017-12-30 11:59 UTC
Labels: status: user feedback required
