### ISSUE TITLE
if an installed gem is missing from the global gem cache, "bundle (install | package)" fails to update vendor/cache

### ISSUE THREAD

**Issue by bughit** [bundler/bundler#4432] opened 2016-04-11 20:26 UTC
Could not find {gem file} for installation

if something is missing from the cache, it should download it, not fail

**Comment by RochesterinNYC** [comment] 2016-04-11 22:15
Can you please provide a `Gemfile` or an error report? More explicit steps to reproduce this issue? More description of the issue itself? More information is needed.

**Comment by bughit** [comment] 2016-04-12 17:43
if you have a local vendor cache ({project_root}/vendor/cache), both bundle install and bundle package, will try to update it.  If you add a gem to the Gemfile, which is already gem installed but happens to missing from the global gem cache (delete the gem file from the global cache to repro), both commands will fail with "Could not find {gem file} for installation"

A cache should be refillable on demand form upstream.

**Comment by segiddins** [comment] 2017-06-04 19:33
Closing because we never got a Gemfile nor a `bundle env` to be able to reproduce.

**Closed by segiddins** 2017-06-04 19:33 UTC
Labels: status: triage
