### ISSUE TITLE
Add a setting for default update level

### ISSUE THREAD

**Issue by chrismo** [bundler/bundler#5994] opened 2017-08-31 22:40 UTC
https://github.com/bundler/bundler/blob/57f5ef656bb1845079225dde42b2d91ecb07ee2b/lib/bundler/cli.rb#L256-L257

These lines show the options, we may need to do a little more work to make this happen - but I think it's just one location to do this. 

I can take this one on (if we agree we still want to do this - @indirect @segiddins)

**Comment by indirect** [comment] 2017-08-31 22:42
@chrismo I'm not sure if I'm qualified to weigh in here... for me, what to update is a gem-by-gem thing. I don't even want Rails patch level changes unless I change my Gemfile. I (usually) watch minor releases from gems that are 1.0+. I (usually) want only patch releases from gems that are < 1.0. What are the use cases motivating the change in defaults?

**Comment by indirect** [comment] 2017-08-31 23:00
After some discussion, we arrived at a loose consensus: we will implement this change as a configuration setting, allowing users who want a default of `--patch` to opt-in. In the future, based on usage and other feedback, we may eventually default that setting to `on` rather than `off`. 👍

**Comment by ankitkataria** [comment] 2019-01-14 20:10
@indirect @segiddins Can I work on this issue?

**Comment by segiddins** [comment] 2019-01-16 16:32
Go for it!

**Comment by ankitkataria** [comment] 2019-01-17 05:06
What I understood from the issue is that we have to implement a configuration option for patch level changes. It'll be off by default and can be turned to on if required.
Am I correct? @segiddins

**Comment by colby-swandale** [comment] 2019-02-15 22:36
Feature has been merged. Closing.

**Closed by colby-swandale** 2019-02-15 22:36 UTC
Labels: good first issue, help wanted, type: feature-request
