### ISSUE TITLE
bundle error

### ISSUE THREAD

**Issue by wsgdrfz** [bundler/bundler#5120] opened 2016-10-24 08:05 UTC
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/Users/wsgdrfz/.rvm/gems/ruby-2.3.1/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what happened was...

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/var/folders/c7/mg3plhhn5_s4410mf9g192qm0000gn/T/bundler-compact-index-20161024-27840-2g1f5e/versions, /Users/wsgdrfz/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:60:in `block in update'
      /Users/wsgdrfz/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
      /Users/wsgdrfz/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Environment

  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  GEM_HOME  /Users/wsgdrfz/.rvm/gems/ruby-2.3.1
  GEM_PATH  /Users/wsgdrfz/.rvm/gems/ruby-2.3.1:/Users/wsgdrfz/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       2.10.1
  rubygems-bundler (1.4.4)

**Comment by lynnco** [comment] 2016-10-26 05:00
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93) `Permission denied @ dir_s_mkdir` issues. Permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14

**Closed** 2016-10-26 05:00 UTC
