### ISSUE TITLE
/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require': cannot load such file

### ISSUE THREAD

**Issue by saroar** [bundler/bundler#4906] opened 2016-08-22 09:38 UTC
/Users/alif/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require': cannot load such file -- irbtools/binding (LoadError)

It was working two days ago i think its bundle issue please check if it is thanks 

here my gem and config

```
group :development do
  gem 'irbtools', require: 'irbtools/binding'
end
```

.irbrc inside this file
require 'irbtools'

**Comment by segiddins** [comment] 2016-08-22 16:05
What's the output of `bundle env`? What's required to reproduce the issue?

**Comment by saroar** [comment] 2016-08-22 16:06
``` [alif@ oz_digital]$ (meta-tags) bundle env
Environment

    Bundler   1.12.5
    Rubygems  2.6.6
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    Git       2.8.4

Bundler settings

    without
      Set for your local app (/Developer/OzDigital/oz_digital/.bundle/config): "production:development:test"
    orig_path
      Set via BUNDLE_ORIG_PATH: "/Users/alif/.rbenv/versions/2.3.1/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/alif/.rbenv/shims:/Users/alif/.rbenv/bin:/usr/local/bin:./bin:/Users/alif/.rbenv/shims:/Users/alif/.rbenv/bin:/Users/alif/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/alif/.rvm/bin"

Gem file
```

**Comment by indirect** [comment] 2016-08-26 05:06
please follow [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md) so that we can reproduce the problem.

**Comment by segiddins** [comment] 2016-09-21 15:52
Closing since we don't have a Gemfile we can use to reproduce the issue.

**Closed by segiddins** 2016-09-21 15:52 UTC
