### ISSUE TITLE
Cold install tries writing Atomic gem to system Ruby directory

### ISSUE THREAD

**Issue by lucaspiller** [bundler/bundler#3062] opened 2014-06-11 12:20 UTC
When trying to deploy cold I get the following error:

``` shell
$ bundle install --path=/<app-path>/shared/bundle --without development test
Unfortunately, a fatal error has occurred. Please see the Bundler troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
/opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/atomic-1.1.15 (Errno::EACCES)
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:210:in `write_gem_make_out'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:132:in `build_error'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:171:in `rescue in build_extension'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:156:in `build_extension'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `each'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems.rb:185:in `try_activate'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/net/http/persistent.rb:12:in `<top (required)>'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendored_persistent.rb:3:in `<top (required)>'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/fetcher.rb:1:in `<top (required)>'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli/install.rb:70:in `run'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli.rb:146:in `install'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/command.rb:27:in `run'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in `start'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
    from /opt/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
    from /usr/local/bin/bundle:23:in `load'
    from /usr/local/bin/bundle:23:in `<main>'
```

I originally had this with 1.5.3, but even after upgrading to 1.6.2 I got the same. I installed the atomic gem manually (`sudo gem install atomic -v 1.1.15`), and after that everything else worked fine.

Why is Bundler trying to install this gem there?

Bundler version 1.6.2
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux](installed from source)
Ubuntu 12.04.4 LTS

**Comment by segiddins** [comment] 2017-01-14 23:41
Failed to reproduce this, closing due to age.

**Closed by segiddins** 2017-01-14 23:41 UTC
Labels: status: triage, type: bug report
