### ISSUE TITLE
bundle package copies .svn directories into vendor/cache

### ISSUE THREAD

**Issue by pboling** [bundler/bundler#2749] opened 2013-12-06 18:22 UTC
I have a bit of a strange setup.  I have local gems that are in my project Gemfile like so:

```
gem 'ctable', :path => '../gems/ctable'
```

The project at '../gems/ctable' is an svn working copy.

Then when I run bundle package it copies the working copy into my project at vendor/cache.  My intention is to commit the vendor/cache to svn, however the .svn directories are also copied into the vendor/cache:

```
$ bundle package --all
$ cd vendor/cache
$ find . -type d -name .svn
./ctable/spec/.svn
./ctable/lib/ctable/.svn
./ctable/lib/.svn
./ctable/old_tests/.svn
./ctable/.svn
```

```
svn add vendor
A         vendor
A         vendor/cache
svn: warning: 'vendor/cache/ctable' is already under version control
```

I don't think this is the desired (default) behavior.  I, for one, do not desire it.

**Comment by agis-** [comment] 2015-10-21 15:59
@indirect So should we close this or?

**Comment by indirect** [comment] 2015-10-26 03:32
I think we'll close this as "package includes all the files in a directory by design, and you are free to script something that makes needed changes based on that expectation"

**Closed by indirect** 2015-10-26 03:32 UTC
