### ISSUE TITLE
No such file or directory @ rb_file_s_stat - .gemtest

### ISSUE THREAD

**Issue by tank-bohr** [bundler/bundler#3700] opened 2015-06-02 11:12 UTC
```
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/opt/ruby-2.1.6/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOENT: No such file or directory @ rb_file_s_stat - .gemtest
      /opt/ruby-2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `stat'
      /opt/ruby-2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2673:in `block in validate_permissions'
      /opt/ruby-2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `each'
      /opt/ruby-2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2672:in `validate_permissions'
      /opt/ruby-2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2540:in `validate'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `block in validate'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/rubygems_integration.rb:51:in `validate'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:369:in `block in load_gemspec_uncached'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `chdir'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:53:in `block in chdir'
      /opt/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/shared_helpers.rb:52:in `chdir'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:362:in `load_gemspec_uncached'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler.rb:352:in `load_gemspec'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:134:in `block in load_spec_files'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `each'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:133:in `load_spec_files'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/git.rb:189:in `load_spec_files'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/path.rb:91:in `local_specs'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/source/git.rb:159:in `specs'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/lazy_specification.rb:53:in `__materialize__'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:88:in `block in materialize'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:85:in `map!'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/spec_set.rb:85:in `materialize'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/definition.rb:165:in `missing_specs'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:70:in `block in run'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/ui/shell.rb:76:in `silence'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:67:in `run'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/installer.rb:18:in `install'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/cli/install.rb:107:in `run'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:158:in `install'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/cli.rb:10:in `start'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/bin/bundle:20:in `block in <top (required)>'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /home/jenkins/.gem/ruby/2.1.0/gems/bundler-1.10.2/bin/bundle:18:in `<top (required)>'
      /opt/ruby-2.1.6/bin/bundle:23:in `load'
      /opt/ruby-2.1.6/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.2
    Rubygems  2.2.3
    Ruby      2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]
    GEM_HOME  /opt/ruby-2.1.6/lib/ruby/gems/2.1.0
    GEM_PATH  /opt/ruby-2.1.6/lib/ruby/gems/2.1.0:/home/jenkins/.gem/ruby/2.1.0
    Git       1.8.3.1
--- TEMPLATE END ----------------------------------------------------------------
```

**Comment by segiddins** [comment] 2015-06-02 15:14
Closing as a duplicate of https://github.com/bundler/bundler/issues/3698.

**Closed by segiddins** 2015-06-02 15:14 UTC
