### ISSUE TITLE
Allow passing additional options to `bundle console`

### ISSUE THREAD

**Issue by postmodern** [bundler/bundler#3209] opened 2014-10-10 00:18 UTC
I really want the ability to pass irb options to `bundle console`:

    bundle console -Ilib

**Comment by agis-** [comment] 2015-10-21 16:43
Closing this since it's not a bug and there is #3210 around which could just be reopened.

If you want this to be tracked as a feature request it should be submitted to https://github.com/bundler/bundler-features instead.

Thanks!

**Closed by agis-** 2015-10-21 16:43 UTC
