### ISSUE TITLE
Regression in disable_shared_gems behavior

### ISSUE THREAD

**Issue by miros** [bundler/bundler#4974] opened 2016-09-13 09:15 UTC
Between the versions `v1.13.0.pre.1` and `v1.13.0.rc1` the behavior of `bundle install --deployment` has changed concerning the `disable_shared_gems` flag. Gems that are present in system rubygems are no longer installed into the local gems folder (`vendor/bundle`).

This behavior seems to be caused by change in `Bundler#configure_gem_path` of

    ENV["GEM_PATH"] = ""

to

    env["GEM_PATH"] = nil

introduced in commit 9a8ab67da6567c767307e8861893761542483ba0

I tested under 2.4.5.1 rubygems version.

I am sorry If that new behavior is an intended one and not a regression.

**Comment by segiddins** [comment] 2016-09-13 11:03
I believe this might be intended? I think the idea of disable shared gems is to completely decouple bundler from the set of gems rubygems has

**Comment by miros** [comment] 2016-09-13 11:12
@segiddins

> the idea of disable shared gems is to completely decouple bundler from the set of gems  rubygems has

Yes. But after fix it does not seem to work that way. 
Sorry, I was not clear enough. By local gem folder i meant `--path` param (`/vendor/bundle` by default). When I run `bundle install` with `--deployment` flag, I expect to see all gems from my Gemfile instalIed there regardless of their existence in rubygems set. But currently system gems are skipped.

**Comment by segiddins** [comment] 2016-09-13 12:47
Can you share a Gemfile we can use to reproduce the issue? Thanks!

**Comment by miros** [comment] 2016-09-13 13:43
I see this problem with all Gemfiles really.

```
➜  bundler -v
Bundler version 1.13.0
➜  bundler cat Gemfile
source 'https://rubygems.org'

gem 'awesome_print'

➜  bundle install
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using awesome_print 1.7.0
Using bundler 1.13.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

➜  bundle install --deployment
Using awesome_print 1.7.0
Using bundler 1.13.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./vendor/bundle.

➜  ls -al vendor/bundle/ruby/2.2.0
total 0
drwxr-xr-x  2 miros  staff   68 13 сен 16:38 .
drwxr-xr-x  3 miros  staff  102 13 сен 16:38 ..
```

**Comment by segiddins** [comment] 2016-09-13 13:51
I cannot produce the issue with the given Gemfile

**Comment by miros** [comment] 2016-09-13 19:46
I am using rbenv. That might be significant.

```
rbenv --version
rbenv 1.0.0-31-gd0779fc
```

```
➜  bundle env
Environment

    Bundler   1.13.1
    Rubygems  2.5.1
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    Git       2.3.3

Gemfile

    source 'https://rubygems.org'

    gem "awesome_print"

Gemfile.lock

    <No /Users/miros/.rbenv/plugins/test/bundler/Gemfile.lock found>
```

```
➜  gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/miros/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/miros/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/miros/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/miros/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/miros/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/miros/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/miros/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /Users/miros/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc --no-yard"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/miros/.rbenv/versions/2.3.1/bin
     - /Users/miros/.rbenv/libexec
     - /Users/miros/.rbenv/plugins/ruby-build/bin
     - /Users/miros/.rbenv/shims
     - /Users/miros/.rbenv/bin
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/miros/bin
```

**Comment by chrismo** [comment] 2016-09-13 23:05
i can recreate. had to make sure awesome_print was first in my system gems.

**Comment by chrismo** [comment] 2016-09-14 22:41
I can confirm that https://github.com/bundler/bundler/commit/9a8ab67da6567c767307e8861893761542483ba0 is the culprit. Since we made that change to accommodate new 1.12 behavior which had broken some `bundle exec` and have now broken this instead ... not to mention being a little surprised there's _no_ tests that failed as a result of breaking `disable_shared_gems` in this way ... I dunno what to do. 

The best thing would be to see if a fix can be made to make both cases happy ... but I may not have time to do that in the near future.

**Comment by chrismo** [comment] 2016-09-15 05:24
<img width="164" alt="screen shot 2016-09-15 at 12 23 40 am" src="https://cloud.githubusercontent.com/assets/8092/18539161/ba1baeac-7ada-11e6-8fa8-9797db878c5e.png">

**Comment by chrismo** [comment] 2016-09-15 15:03
Not terribly cunning actually, just perhaps how this should have been fixed in the first place? #4992

**Comment by litch** [comment] 2016-09-16 15:22
FWIW, this has caused us to revert to bundler 1.12.5 as well.

**Comment by miros** [comment] 2016-09-16 19:11
@chrismo Thanks for quick fix

**Comment by chrismo** [comment] 2016-09-20 05:38
The fix is neither quick nor a fix: It doesn't work. See this [new comment](https://github.com/bundler/bundler/pull/4992#issuecomment-248206307) on the PR #4992.

**Comment by pibako** [comment] 2016-09-20 12:41
I think I just run into this issue as well on 1.13.1 . Below is the minimal example, note that `vendor/bundle/ruby/2.2.0` is empty after I run `bundle install --deployment`:

```
pi@mac:~/company/poc-bundler$ cat Gemfile
source 'https://rubygems.org'

gem 'rest-client',                      '~>1.6.7'
pi@mac:~/company/poc-bundler$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    mime-types (1.25.1)
    rest-client (1.6.9)
      mime-types (~> 1.16)

PLATFORMS
  ruby

DEPENDENCIES
  rest-client (~> 1.6.7)
pi@mac:~/company/poc-bundler$ bundle install --deployment
Using mime-types 1.25.1
Using bundler 1.13.1
Using rest-client 1.6.9
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into ./vendor/bundle.
pi@mac:~/company/poc-bundler$ ls -R
Gemfile		Gemfile.lock	vendor

./vendor:
bundle

./vendor/bundle:
ruby

./vendor/bundle/ruby:
2.2.0

./vendor/bundle/ruby/2.2.0:
pi@mac:~/company/poc-bundler$ bundle env
Environment

    Bundler   1.13.1
    Rubygems  2.4.5.1
    Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    Git       2.9.0

Bundler settings

    build.iconv
      Set for the current user (/Users/pi/.bundle/config): "--with-opt-dir=/usr/local"
    build.mysql
      Set for the current user (/Users/pi/.bundle/config): "--with-mysql-config=/usr/local/mysql/bin/mysql_config"
    jobs
      Set for the current user (/Users/pi/.bundle/config): "6"
    build.libv8
      Set for the current user (/Users/pi/.bundle/config): "--with-system-v8"
    frozen
      Set for your local app (/Users/pi/company/poc-bundler/.bundle/config): "1"
    path
      Set for your local app (/Users/pi/company/poc-bundler/.bundle/config): "vendor/bundle"
    disable_shared_gems
      Set for your local app (/Users/pi/company/poc-bundler/.bundle/config): "true"

Gemfile

    source 'https://rubygems.org'

    gem 'rest-client',                      '~>1.6.7'

Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        mime-types (1.25.1)
        rest-client (1.6.9)
          mime-types (~> 1.16)

    PLATFORMS
      ruby

    DEPENDENCIES
      rest-client (~> 1.6.7)
pi@mac:~/company/poc-bundler$
```

**Comment by chrismo** [comment] 2016-09-20 14:40
@pibako yes, this looks like the same problem. Presumably you have mime-types, rest-client installed in system rubies. Thx for the report, sorry for the trouble.

**Comment by pibako** [comment] 2016-09-20 14:46
@chrismo, right, I though I included this in my previous comment:
```
pi@mac:~/company/poc-bundler$ bundle show --paths
/Users/pi/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.13.1
/Users/pi/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mime-types-1.25.1
/Users/pi/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.6.9
pi@mac:~/company/poc-bundler$
```

**Comment by segiddins** [comment] 2016-09-20 16:28
I cannot reproduce this, but I don't use rbenv

**Closed** 2016-09-27 20:54 UTC
Labels: status: working, type: bug report
