### ISSUE TITLE
Bundler won't update to 1.16.1

### ISSUE THREAD

**Issue by tomatohammado** [bundler/bundler#6290] opened 2018-02-07 14:52 UTC
Hello, I am trying to run `gem install bundler`, and update my current `1.16.0` version to `1.16.1`

0) I start with this
```bash
~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )
```

1) I attempt to update bundler
```bash
~
$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 8 seconds
1 gem installed
```

2) I try running `bundle version` again to confirm bundler has been updated, and get the same response I did in step 0)
```bash
~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )
```

3) when I try `gem install --default bundler`, I get even an even stranger result
```bash
~
$ gem install --default bundler
Successfully installed bundler-1.16.1 as a default gem
Done installing documentation for bundler after 0 seconds
1 gem installed

~
$ bundle version
/Users/ga/.rbenv/versions/2.4.2/bin/bundle:23:in `load': cannot load such file -- /Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle (LoadError)
	from /Users/ga/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
```

4) I can resolve the error and get back to where I started by running `gem install bundler` again
```bash
~
$ gem install  bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1 gem installed

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )
```

---
Here is some additional information to help troubleshoot the issue:
```bash
~
$ bundle env
fatal: Not a git repository (or any of the parent directories): .git
## Environment

\```
Bundler       1.16.0
  Platforms   ruby, x86_64-darwin-16
Ruby          2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
  Full Path   /Users/ga/.rbenv/versions/2.4.2/bin/ruby
  Config Dir  /Users/ga/.rbenv/versions/2.4.2/etc
RubyGems      2.7.2
  Gem Home    /Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  Gem Path    /Users/ga/.gem/ruby/2.4.0:/Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  User Path   /Users/ga/.gem/ruby/2.4.0
  Bin Dir     /Users/ga/.rbenv/versions/2.4.2/bin
Tools
  Git         2.15.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
\```

## Bundler Build Metadata

\```
Built At          2018-02-07
Git SHA
Released Version  false
\```
```

```bash
~
$ gem query --local

*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activesupport (5.1.4)
arel (8.0.0)
bcrypt (3.1.11)
bigdecimal (default: 1.3.0)
bindex (0.5.0)
builder (3.2.3)
bundler (default: 1.16.1, default: 1.16.0)
byebug (9.1.0)
coderay (1.1.2)
concurrent-ruby (1.0.5)
crass (1.0.2)
did_you_mean (1.1.0)
diff-lcs (1.2.5)
erubi (1.7.0)
ffi (1.9.18)
globalid (0.4.1)
i18n (0.9.1)
io-console (default: 0.4.6)
json (default: 2.0.4)
loofah (2.1.1)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.10.1)
net-telnet (0.1.1)
nio4r (2.1.0)
nokogiri (1.8.1)
openssl (default: 2.0.5)
pg (0.21.0)
pkg-config (1.2.8)
power_assert (0.4.1)
pry (0.11.3)
psych (default: 2.2.2)
puma (3.10.0)
rack (2.0.3)
rack-test (0.7.0)
rails (5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.4)
rake (12.0.0)
rdoc (default: 5.0.0)
rspec (3.7.0, 3.3.0)
rspec-core (3.7.1, 3.3.2)
rspec-expectations (3.7.0, 3.3.1)
rspec-mocks (3.7.0, 3.3.2)
rspec-support (3.7.1, 3.3.0)
rubygems-update (2.7.2)
sprockets (3.7.1)
sprockets-rails (3.2.1)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tzinfo (1.2.4)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.2.1)
```

**Comment by lilmonix3** [comment] 2018-02-07 21:24
temporary problem.
you can manunally `git clone` bundler into "/Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/" and change name file bundler into bundler latest version

**Comment by tomatohammado** [comment] 2018-02-07 23:55
@segiddins I tried it, doesn't seem to have worked
```bash
Last login: Wed Feb  7 17:41:47 on ttys000

~
$ gem install rubygems-update -v 2.7.4
Fetching: rubygems-update-2.7.4.gem (100%)
Successfully installed rubygems-update-2.7.4
Parsing documentation for rubygems-update-2.7.4
Installing ri documentation for rubygems-update-2.7.4
Done installing documentation for rubygems-update after 48 seconds
1 gem installed

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )

~
$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1 gem installed

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )

~
$ bundle env
fatal: Not a git repository (or any of the parent directories): .git
## Environment

\```
Bundler       1.16.0
  Platforms   ruby, x86_64-darwin-16
Ruby          2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
  Full Path   /Users/ga/.rbenv/versions/2.4.2/bin/ruby
  Config Dir  /Users/ga/.rbenv/versions/2.4.2/etc
RubyGems      2.7.2
  Gem Home    /Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  Gem Path    /Users/ga/.gem/ruby/2.4.0:/Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  User Path   /Users/ga/.gem/ruby/2.4.0
  Bin Dir     /Users/ga/.rbenv/versions/2.4.2/bin
Tools
  Git         2.15.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
\```

## Bundler Build Metadata

\```
Built At          2018-02-07
Git SHA
Released Version  false
\```

~
$ gem query --local

*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activesupport (5.1.4)
addressable (2.5.2)
arel (8.0.0)
bcrypt (3.1.11)
bigdecimal (default: 1.3.0)
bindex (0.5.0)
builder (3.2.3)
bundler (default: 1.16.1, default: 1.16.0)
byebug (10.0.0, 9.1.0)
capybara (2.17.0)
childprocess (0.8.0)
coderay (1.1.2)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
crass (1.0.3, 1.0.2)
did_you_mean (1.1.0)
diff-lcs (1.3, 1.2.5)
erubi (1.7.0)
execjs (2.7.0)
ffi (1.9.21, 1.9.18)
globalid (0.4.1)
i18n (0.9.3, 0.9.1)
io-console (default: 0.4.6)
jbuilder (2.7.0)
json (default: 2.0.4)
listen (3.1.5)
loofah (2.1.1)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.1)
multi_json (1.13.1)
net-telnet (0.1.1)
nio4r (2.2.0, 2.1.0)
nokogiri (1.8.2, 1.8.1)
nyan-cat-formatter (0.12.0)
openssl (default: 2.0.5)
pg (0.21.0)
pkg-config (1.2.8)
power_assert (0.4.1)
pry (0.11.3)
psych (default: 2.2.2)
public_suffix (3.0.1)
puma (3.11.2, 3.10.0)
rack (2.0.4, 2.0.3)
rack-test (0.8.2, 0.7.0)
rails (5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.4)
rake (12.3.0, 12.0.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
rspec (3.7.0, 3.3.0)
rspec-core (3.7.1, 3.3.2)
rspec-expectations (3.7.0, 3.3.1)
rspec-mocks (3.7.0, 3.3.2)
rspec-support (3.7.1, 3.3.0)
ruby_dep (1.5.0)
rubygems-update (2.7.4, 2.7.2)
rubyzip (1.2.1)
sass (3.5.5)
sass-listen (4.0.0)
sass-rails (5.0.7)
selenium-webdriver (3.9.0)
spring (2.0.2)
spring-watcher-listen (2.0.1)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
turbolinks (5.1.0)
turbolinks-source (5.1.0)
tzinfo (1.2.5, 1.2.4)
uglifier (4.1.5)
web-console (3.5.1)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.2.1)
xpath (3.0.0)

~
$ gem uninstall rubygems-update -v 2.7.2
Successfully uninstalled rubygems-update-2.7.2

~
$ gem query --local

*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activesupport (5.1.4)
addressable (2.5.2)
arel (8.0.0)
bcrypt (3.1.11)
bigdecimal (default: 1.3.0)
bindex (0.5.0)
builder (3.2.3)
bundler (default: 1.16.1, default: 1.16.0)
byebug (10.0.0, 9.1.0)
capybara (2.17.0)
childprocess (0.8.0)
coderay (1.1.2)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
crass (1.0.3, 1.0.2)
did_you_mean (1.1.0)
diff-lcs (1.3, 1.2.5)
erubi (1.7.0)
execjs (2.7.0)
ffi (1.9.21, 1.9.18)
globalid (0.4.1)
i18n (0.9.3, 0.9.1)
io-console (default: 0.4.6)
jbuilder (2.7.0)
json (default: 2.0.4)
listen (3.1.5)
loofah (2.1.1)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.1)
multi_json (1.13.1)
net-telnet (0.1.1)
nio4r (2.2.0, 2.1.0)
nokogiri (1.8.2, 1.8.1)
nyan-cat-formatter (0.12.0)
openssl (default: 2.0.5)
pg (0.21.0)
pkg-config (1.2.8)
power_assert (0.4.1)
pry (0.11.3)
psych (default: 2.2.2)
public_suffix (3.0.1)
puma (3.11.2, 3.10.0)
rack (2.0.4, 2.0.3)
rack-test (0.8.2, 0.7.0)
rails (5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.4)
rake (12.3.0, 12.0.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
rspec (3.7.0, 3.3.0)
rspec-core (3.7.1, 3.3.2)
rspec-expectations (3.7.0, 3.3.1)
rspec-mocks (3.7.0, 3.3.2)
rspec-support (3.7.1, 3.3.0)
ruby_dep (1.5.0)
rubygems-update (2.7.4)
rubyzip (1.2.1)
sass (3.5.5)
sass-listen (4.0.0)
sass-rails (5.0.7)
selenium-webdriver (3.9.0)
spring (2.0.2)
spring-watcher-listen (2.0.1)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
turbolinks (5.1.0)
turbolinks-source (5.1.0)
tzinfo (1.2.5, 1.2.4)
uglifier (4.1.5)
web-console (3.5.1)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.2.1)
xpath (3.0.0)

~
$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1 gem installed

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-07 commit )
```

I also uninstalled the previous 2.7.2 version after installing the 2.7.4, but still no luck

**Comment by hsbt** [comment] 2018-02-08 00:18
Can you try to upgrade rubygems by `gem update --system`? It install RubyGems 2.7.5 to your environment.

**Comment by tomatohammado** [comment] 2018-02-08 00:22
@hsbt yep, I just realized I didn't update RubyGems correctly the first time 😅

here's what I got. Still seem to have the same issue, but `bundle env` correctly reflects the latest version of RubyGems (2.7.5)

I did get an error near the end of the installation: `Permission denied @ rb_sysopen - /`

```bash
~
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.5.gem (100%)
Successfully installed rubygems-update-2.7.5
Parsing documentation for rubygems-update-2.7.5
Installing ri documentation for rubygems-update-2.7.5
Installing darkfish documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 50 seconds
Parsing documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.5
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/ga/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/source.rb

~
$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1 gem installed

~
$ bundler version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-08 commit )

~
$ bundle env
fatal: Not a git repository (or any of the parent directories): .git
## Environment

\```
Bundler       1.16.0
  Platforms   ruby, x86_64-darwin-16
Ruby          2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
  Full Path   /Users/ga/.rbenv/versions/2.4.2/bin/ruby
  Config Dir  /Users/ga/.rbenv/versions/2.4.2/etc
RubyGems      2.7.5
  Gem Home    /Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  Gem Path    /Users/ga/.gem/ruby/2.4.0:/Users/ga/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0
  User Path   /Users/ga/.gem/ruby/2.4.0
  Bin Dir     /Users/ga/.rbenv/versions/2.4.2/bin
Tools
  Git         2.15.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
\```

## Bundler Build Metadata

\```
Built At          2018-02-08
Git SHA
Released Version  false
\```

~
$ gem query --local

*** LOCAL GEMS ***

actioncable (5.1.4)
actionmailer (5.1.4)
actionpack (5.1.4)
actionview (5.1.4)
activejob (5.1.4)
activemodel (5.1.4)
activerecord (5.1.4)
activesupport (5.1.4)
addressable (2.5.2)
arel (8.0.0)
bcrypt (3.1.11)
bigdecimal (default: 1.3.0)
bindex (0.5.0)
builder (3.2.3)
bundler (default: 1.16.1, default: 1.16.0)
byebug (10.0.0, 9.1.0)
capybara (2.17.0)
childprocess (0.8.0)
coderay (1.1.2)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.0.5)
crass (1.0.3, 1.0.2)
did_you_mean (1.1.0)
diff-lcs (1.3, 1.2.5)
erubi (1.7.0)
execjs (2.7.0)
ffi (1.9.21, 1.9.18)
globalid (0.4.1)
i18n (0.9.3, 0.9.1)
io-console (default: 0.4.6)
jbuilder (2.7.0)
json (default: 2.0.4)
listen (3.1.5)
loofah (2.1.1)
mail (2.7.0)
method_source (0.9.0)
mini_mime (1.0.0)
mini_portile2 (2.3.0)
minitest (5.11.3, 5.10.1)
multi_json (1.13.1)
net-telnet (0.1.1)
nio4r (2.2.0, 2.1.0)
nokogiri (1.8.2, 1.8.1)
nyan-cat-formatter (0.12.0)
openssl (default: 2.0.5)
pg (0.21.0)
pkg-config (1.2.8)
power_assert (0.4.1)
pry (0.11.3)
psych (default: 2.2.2)
public_suffix (3.0.1)
puma (3.11.2, 3.10.0)
rack (2.0.4, 2.0.3)
rack-test (0.8.2, 0.7.0)
rails (5.1.4)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
railties (5.1.4)
rake (12.3.0, 12.0.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 5.0.0)
rspec (3.7.0, 3.3.0)
rspec-core (3.7.1, 3.3.2)
rspec-expectations (3.7.0, 3.3.1)
rspec-mocks (3.7.0, 3.3.2)
rspec-support (3.7.1, 3.3.0)
ruby_dep (1.5.0)
rubygems-update (2.7.5, 2.7.4)
rubyzip (1.2.1)
sass (3.5.5)
sass-listen (4.0.0)
sass-rails (5.0.7)
selenium-webdriver (3.9.0)
spring (2.0.2)
spring-watcher-listen (2.0.1)
sprockets (3.7.1)
sprockets-rails (3.2.1)
sqlite3 (1.3.13)
test-unit (3.2.3)
thor (0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
turbolinks (5.1.0)
turbolinks-source (5.1.0)
tzinfo (1.2.5, 1.2.4)
uglifier (4.1.5)
web-console (3.5.1)
websocket-driver (0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.2.1)
xpath (3.0.0)

~
$ gem uninstall rubygems-update -v 2.7.4
Successfully uninstalled rubygems-update-2.7.4

~
$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 6 seconds
1 gem installed

~
$ bundler version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.0 (2018-02-08 commit )
```

**Comment by hsbt** [comment] 2018-02-08 00:25
> ERROR:  While executing gem ... (Errno::EACCES)
>     Permission denied @ rb_sysopen - /Users/ga/.rbenv/versions/2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/source.rb

It seems to NOT the same issue. I think it was caused by RubyGems 2.7.2 that was broken version. If you have a few time, Can you try to re-install Ruby 2.4.2 and upgrade RubyGems 2.7.5.

**Comment by tomatohammado** [comment] 2018-02-08 01:02
@hsbt I actually just updated to Ruby v 2.5.0 and then upgrade my RubyGems

Good new is that I was successfully updated bundler to version 1.16.1

Bad news is that I still get the error `fatal: Not a git repository (or any of the parent directories): .git`, even when I'm in a git repo.

This is actually the issue I was trying to solve by updating bundler. Yesterday I was able to update to 1.16.1 and it got rid of the error, but then I must have done something because I had the problem I originally made this issue for.

Does anybody have any insight as why why I am getting the "Not a git repository" error?

```bash
~
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

~
$ rbenv install 2.5.0
ruby-build: use openssl from homebrew
Downloading ruby-2.5.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.0.tar.bz2
Installing ruby-2.5.0...
Installed ruby-2.5.0 to /Users/ga/.rbenv/versions/2.5.0


~
$ rbenv init
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"


~
$ rbenv global 2.5.0

~
$ source ~/.bash_profile

~
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

~
$ gem install rubygems-update bundler
Fetching: rubygems-update-2.7.5.gem (100%)
Successfully installed rubygems-update-2.7.5
Parsing documentation for rubygems-update-2.7.5
Installing ri documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 47 seconds
Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Installing ri documentation for bundler-1.16.1
Done installing documentation for bundler after 5 seconds
2 gems installed

~
$ gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.7.5
Parsing documentation for rubygems-update-2.7.5
Installing darkfish documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 54 seconds
Parsing documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.5
Bundler 1.16.1 installed
RubyGems 2.7.5 installed
Regenerating binstubs
Parsing documentation for rubygems-2.7.5
Installing ri documentation for rubygems-2.7.5



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/Users/ga/.rbenv/versions/2.5.0/bin/gem
	/Users/ga/.rbenv/versions/2.5.0/bin/bundle

Ruby Interactive (ri) documentation was installed. ri is kind of like man
pages for Ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

RubyGems system software updated

~
$ source ~/.bash_profile

~
$ bundle env
fatal: Not a git repository (or any of the parent directories): .git
## Environment

\```
Bundler       1.16.1
  Platforms   ruby, x86_64-darwin-17
Ruby          2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  Full Path   /Users/ga/.rbenv/versions/2.5.0/bin/ruby
  Config Dir  /Users/ga/.rbenv/versions/2.5.0/etc
RubyGems      2.7.5
  Gem Home    /Users/ga/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
  Gem Path    /Users/ga/.gem/ruby/2.5.0:/Users/ga/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
  User Path   /Users/ga/.gem/ruby/2.5.0
  Bin Dir     /Users/ga/.rbenv/versions/2.5.0/bin
Tools
  Git         2.16.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
\```

## Bundler Build Metadata

\```
Built At          2018-02-08
Git SHA
Released Version  false
\```

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.1 (2018-02-08 commit )
```

**Comment by hsbt** [comment] 2018-02-08 01:15
I couldn't reproduce it. ( I'm also maintainer of rbenv/ruby-biild)

```
~ > rbenv uninstall 2.5.0; and rbenv install 2.5.0
rbenv: remove /Users/hsbt/.rbenv/versions/2.5.0? [yN] y
ruby-build: use openssl from homebrew
Downloading ruby-2.5.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.0.tar.bz2
Installing ruby-2.5.0...
ruby-build: use readline from homebrew
Installed ruby-2.5.0 to /Users/hsbt/.rbenv/versions/2.5.0

~ > rbenv shell 2.5.0 
~ > ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
~ > gem update --system 
Updating rubygems-update
Fetching: rubygems-update-2.7.5.gem (100%)
Successfully installed rubygems-update-2.7.5
Installing RubyGems 2.7.5
Bundler 1.16.1 installed
RubyGems 2.7.5 installed
Regenerating binstubs



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/Users/hsbt/.rbenv/versions/2.5.0/bin/gem
	/Users/hsbt/.rbenv/versions/2.5.0/bin/bundle

RubyGems system software updated
~ > bundle version
Bundler version 1.16.1 (2018-02-08 commit b943955)
~ > 
```

**Comment by tomatohammado** [comment] 2018-02-08 01:59
@hsbt I just went through the same steps you did, and yes it seems that the problem is probably something to do with my machine as I still get the same error.

The big difference I see is that I do not get a commit version when I run `bundle version` - mine is blank while yours is `b943955`

Looking at the bottom of the `bundle env` output, it says that the 'Release Version' is false, and I don't know what `Git SHA` is supposed to say next to it but it's possible that it shouldn't be blank.

In researching the `fatal: Not a git repository (or any of the parent directories): .git` came up with [this previous bundler issue #2039](https://github.com/bundler/bundler/issues/2039) so I don't know if that helps. Looking at my Gem Path/Home it could also have to do with my `~/.gem` or `~/.rbenv` directories (I don't have a `~/.gemrc` file)

```bash
Last login: Wed Feb  7 20:18:27 on ttys002

~
$ rbenv uninstall 2.5.0; and rbenv install 2.5.0
rbenv: remove /Users/ga/.rbenv/versions/2.5.0? [yN] y
-bash: and: command not found

~
$ rbenv install 2.5.0
ruby-build: use openssl from homebrew
Downloading ruby-2.5.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.0.tar.bz2
Installing ruby-2.5.0...
Installed ruby-2.5.0 to /Users/ga/.rbenv/versions/2.5.0


~
$ rbenv shell 2.5.0

~
$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

~
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.5.gem (100%)
Successfully installed rubygems-update-2.7.5
Parsing documentation for rubygems-update-2.7.5
Installing ri documentation for rubygems-update-2.7.5
Installing darkfish documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 61 seconds
Parsing documentation for rubygems-update-2.7.5
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.5
Bundler 1.16.1 installed
RubyGems 2.7.5 installed
Regenerating binstubs
Parsing documentation for rubygems-2.7.5
Installing ri documentation for rubygems-2.7.5



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/Users/ga/.rbenv/versions/2.5.0/bin/gem
	/Users/ga/.rbenv/versions/2.5.0/bin/bundle

Ruby Interactive (ri) documentation was installed. ri is kind of like man
pages for Ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

RubyGems system software updated

~
$ bundle version
fatal: Not a git repository (or any of the parent directories): .git
Bundler version 1.16.1 (2018-02-08 commit )

~
$ bundle env
fatal: Not a git repository (or any of the parent directories): .git
## Environment

\```
Bundler       1.16.1
  Platforms   ruby, x86_64-darwin-17
Ruby          2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  Full Path   /Users/ga/.rbenv/versions/2.5.0/bin/ruby
  Config Dir  /Users/ga/.rbenv/versions/2.5.0/etc
RubyGems      2.7.5
  Gem Home    /Users/ga/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
  Gem Path    /Users/ga/.gem/ruby/2.5.0:/Users/ga/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
  User Path   /Users/ga/.gem/ruby/2.5.0
  Bin Dir     /Users/ga/.rbenv/versions/2.5.0/bin
Tools
  Git         2.16.1
  RVM         not installed
  rbenv       rbenv 1.1.1

  chruby      not installed
\```

## Bundler Build Metadata

\```
Built At          2018-02-08
Git SHA
Released Version  false
\```

$ ls -la ~
total 224
drwxr-xr-x+  47 ga    staff   1504 Feb  6 15:41 .
drwxr-xr-x    6 root  admin    192 Nov 13 23:17 ..
-rw-r--r--    1 ga    staff    266 Dec 15 13:49 .502478.padl
-r--------    1 ga    staff      7 Nov  8 11:42 .CFUserTextEncoding
-rw-r--r--@   1 ga    staff  24580 Feb  5 14:21 .DS_Store
drwx------    2 ga    staff     64 Feb  7 17:23 .Trash
drwxr-xr-x   11 ga    staff    352 Nov 15 09:48 .atom
-rw-------    1 ga    staff   6298 Feb  7 20:25 .bash_history
-rw-r--r--@   1 ga    staff   3958 Jan 24 11:09 .bash_profile
drwx------  104 ga    staff   3328 Dec 19 08:57 .bash_sessions
drwxr-xr-x    3 ga    staff     96 Feb  6 15:41 .bundle
drwxr-xr-x    4 ga    staff    128 Jan 26 15:47 .config
drwx------    3 ga    staff     96 Jan 26 23:03 .cups
-rw-------    1 ga    staff   9196 Jan 30 16:05 .dbshell
drwx------   12 ga    staff    384 Nov 13 12:03 .dropbox
drwxr-xr-x    3 ga    staff     96 Feb  5 10:25 .gem
-rw-r--r--    1 ga    staff  16223 Nov 28 13:09 .git-prompt.sh
-rw-r--r--    1 ga    staff    309 Jan 25 16:26 .gitconfig
-rw-r--r--    1 ga    staff    687 Nov 13 10:56 .gitignore_global
-rw-r--r--    1 ga    staff   3349 Nov 13 10:18 .installfest
drwxr-xr-x    3 ga    staff     96 Dec 15 13:49 .lightpaper
drwxr-xr-x    3 ga    staff     96 Jan  5 14:58 .local
-rw-------    1 ga    staff      0 Dec 18 11:11 .mongorc.js
drwxr-xr-x    8 ga    staff    256 Jan  7 23:00 .mume
-rw-------    1 ga    staff    197 Jan  5 14:59 .netrc
drwxr-xr-x    4 ga    staff    128 Jan 23 15:11 .node-gyp
-rw-------    1 ga    staff    427 Feb  1 10:55 .node_repl_history
drwxr-xr-x    6 ga    staff    192 Dec  8 15:58 .npm
-rw-------    1 ga    staff   5529 Feb  6 16:22 .pry_history
drwxr-xr-x    5 ga    staff    160 Nov 13 10:33 .rbenv
drwx------    5 ga    staff    160 Nov 28 11:46 .ssh
drwxr-xr-x    6 ga    staff    192 Nov 13 10:29 .subversion
-rw-------    1 ga    staff   1426 Nov 29 17:24 .viminfo
drwxr-xr-x    3 ga    staff     96 Nov 13 10:56 .vscode
drwxr-xr-x    3 ga    staff     96 Dec 13 17:50 .vscode-insiders
-rw-r--r--    1 ga    staff    116 Jan 31 17:23 .yarnrc
drwx------@   5 ga    staff    160 Nov 29 08:46 Applications
drwx------+  11 ga    staff    352 Feb  7 17:23 Desktop
drwx------+  17 ga    staff    544 Dec  8 14:11 Documents
drwx------+  30 ga    staff    960 Feb  6 17:15 Downloads
drwx------@  21 ga    staff    672 Dec 14 08:34 Dropbox
drwx------@  70 ga    staff   2240 Feb  4 14:26 Library
drwx------+   3 ga    staff     96 Nov  8 11:42 Movies
drwx------+   4 ga    staff    128 Nov 14 08:43 Music
drwx------+   9 ga    staff    288 Jan 24 15:16 Pictures
drwxr-xr-x+   5 ga    staff    160 Nov  8 11:42 Public
drwxr-xr-x@   8 ga    staff    256 Feb  4 13:42 dev
```

**Comment by melvyn-sopacua** [comment] 2018-05-14 19:00
I had any combination of these errors, except the git one and "cured" it with the following sequence:

```!sh
$ sudo apt-get remove ruby
$ sudo rm -rf /var/lib/gems/2.3.0
$ sudo apt-get install vim-nox # pulls in ruby and gives me $EDITOR back
$ sudo gem install bundler
$ sudo apt-get install ruby-dev # for native gems
```
Something Ubuntu did (best guess) kept linking / referencing bundler 1.15.3 in my case resulting in a plethora of different failures. Hope this helps other, even though it's killing a fly with an axe.

**Comment by colby-swandale** [comment] 2018-12-12 23:51
This issue has been fixed in recent releases of Bundler. You should be able to `gem install bundler` and run `bundle env`/`bundle version` without any issues.

**Closed by colby-swandale** 2018-12-12 23:51 UTC
