### ISSUE TITLE
Bundler attempts to load gems in "without" groups

### ISSUE THREAD

**Issue by folgerc** [bundler/bundler#6312] opened 2018-02-27 00:37 UTC
Hi,

First some context: I'm using Rails and running into an issue where I'm trying to remove test dependencies from my production environment. The problem is that these dependencies are defined in their own 'test' group in my Gemfile [1], but they are still being loaded on startup. I know this because I get 'could not find gem X' when viewing the Rails site. I tried setting the 'without' setting but this seems to have no effect.

Looking further that appears to be because in this initialize block, the 'without' settings are not taken into account due to the direct call to expand_dependencies [2], where the code path that removes the 'without' groups is different [3].

Is this expected behavior? I'm fairly new to Ruby/Rails so would love to know this is my fault.

[1] gemfile contents
```ruby
group :test do
  # ... bunch of stuff
  # this is the test dependency I want to keep out
  gem 'teaspoon-jasmine'
end
```

[2] https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L123
[3] seems to start here https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L223

**Comment by segiddins** [comment] 2018-02-27 13:37
Please share the output of `bundle env`, thanks!

**Comment by folgerc** [comment] 2018-02-27 17:53
Here you go,

``` 
 report is Bundler 1.3.5
 Ruby 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
 Rubygems 2.5.1
 GEM_HOME /placeholder/ruby2.3.x/lib/ruby/gems/2.3.0
 GEM_PATH /placeholder/ruby2.3.x/lib/ruby/gems/2.3.0:/.gem/ruby/2.3.0

 Bundler settings
   without
     Set for your local app (/placeholder/rails-root/.bundle/config): "test"
   bin_path
     Set via BUNDLE_BIN_PATH: "/placeholder/ruby2.3.x/lib/ruby/gems/2.3.0/gems/bundler-1.3.5/bin/bundle"
   gemfile
     Set via BUNDLE_GEMFILE: "/placeholder/rails-root/Gemfile"

 Gemfile
 gem 'rails'
 gem 'haml'

 group :test do
   gem 'haml-rails'
   gem 'rspec-rails'
   gem 'simplecov'
   gem 'simplecov-cobertura'
   gem 'teaspoon-jasmine'
 end


 Gemfile.lock
 <No Gemfile.lock found>
```

**Comment by segiddins** [comment] 2018-02-27 23:14
Looks like you’re running a super old version of Bundler! 1.3.5 must be about 4 years old, the latest is 1.16.1. Can you try again with the latest Bundler? Thanks!

**Comment by folgerc** [comment] 2018-02-28 00:51
Sorry about that, it's a little challenging to upgrade. In any case I can reproduce the same problem after testing with the newest version. FWIW I can resolve this by changing expand_dependencies to apply the same filtering as is done in requested_dependencies.

Here's some more env output (I've excluded a few things specific to my environment).
```
 Bundler       1.16.1
   Platforms   ruby, x86_64-linux
 Ruby          2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
   Full Path   /placeholder/ruby2.3.x/bin/ruby
   Config Dir  /placeholder/ruby2.3.x/etc
 RubyGems      2.5.1
   Gem Home    /placeholder/ruby2.3.x/lib/ruby/gems/2.3.0
   Gem Path    /placeholder/ruby2.3.x/lib/ruby/gems/2.3.0:/.gem/ruby/2.3.0
   User Path   /.gem/ruby/2.3.0
   Bin Dir     /placeholder/ruby2.3.x/bin
 ```
```
 ## Bundler Build Metadata
```
 ```
 Built At          2017-12-21
 Git SHA           0034ef341
 Released Version  true

 ## Bundler settings
 without
   Set for your local app (/placeholder/rails-root/.bundle/config): [:test]
 bin_path
   Set via BUNDLE_BIN_PATH: "/placeholder/ruby2.3.x/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle"
 gemfile
   Set via BUNDLE_GEMFILE: "/placeholder/rails-root/Gemfile"

 ## Gemfile

 ### Gemfile

 gem 'rails'
 gem 'haml'

 group :test do
   gem 'haml-rails'
   gem 'rspec-rails'
   gem 'simplecov'
   gem 'simplecov-cobertura'
   gem 'teaspoon-jasmine'
 end

 ### Gemfile.lock

 <No /placeholder/rails-root/Gemfile.lock found>
 ```

**Comment by colby-swandale** [comment] 2018-03-01 08:33
I cannot reproduce this issue with the given information. Can you create a test repository that we can use to replicate this issue you're having.

**Comment by indirect** [comment] 2018-03-04 23:44
I'm not completely sure if this is related to your problem, but I believe that Bundler can only exclude `without` gems if you have a Gemfile.lock. It seems like you are trying to deploy to production without a lockfile, and I would very much recommend against that.

**Comment by folgerc** [comment] 2018-03-05 20:43
Here's a test repo: https://github.com/folgerc/repro-6312. It's pretty minimal and is what I believe is happening in Rails land.

@indirect to your point, there is more to the story here in that there is some custom dependency management happening in addition to bundler, and I'm trying to get them to play nice together. Is there any way to honor the without groups, or really just ignore specific groups, without the Gemfile.lock being populated?

**Comment by segiddins** [comment] 2018-03-06 05:50
You can try running `bundle lock`, and then `bundle config without test`, and then finally `bundle install`, but I can't promise that will work

**Comment by folgerc** [comment] 2018-03-07 00:15
Thanks, seems like ```bundle lock``` itself attempts to download the gems though, even with the without group already specified in the config.

**Comment by segiddins** [comment] 2018-03-07 03:57
Hmm, it shouldn't need to download them at all (since there aren't any `git` gems in those groups. But that should at least solve the issue (for now) of it attempting to load those gems?

**Comment by segiddins** [comment] 2018-03-07 04:05
The following test passes, bundler is not trying to download any gems using `bundle lock`:

```ruby
it "can lock without downloading gems when using without" do
    gemfile <<-G
      source "file://#{gem_repo1}"
      
      gem "thin"
      gem "rack_middleware", :group => "test"
    G
    bundle! "config set without test"
    bundle! "config set path .bundle"
    bundle! "lock"
    expect(bundled_app(".bundle")).not_to exist
  end
```

**Comment by folgerc** [comment] 2018-03-07 18:13
Alright, I tried via the CLI but maybe it's different once trying to do it in an actual rails website. I'll try it and see if that works out.

(Starting from the same repo)
```
bundle lock
Could not find gem 'invalid-gem' in any of the gem sources listed in your Gemfile.
```

**Comment by colby-swandale** [comment] 2018-05-20 03:14
ping @folgerc were you able to resolve this issue?

**Comment by colby-swandale** [comment] 2018-07-10 14:36
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Closed by colby-swandale** 2018-07-10 14:36 UTC
Labels: status: user feedback required
