### ISSUE TITLE
when sudo is required and rubygems is < 2.7.5, tmpdir/bin is created with wrong permissions

### ISSUE THREAD

**Issue by glenjamin** [bundler/bundler#6555] opened 2018-05-25 22:44 UTC
I suspect this will be marked as wontfix due to the affected version, but I figured I'd report it anyway since i've established the exact issue and it does affect the default OS X ruby.

```
bundler (1.16.2)

RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [universal.x86_64-darwin17]
```

OS X High Sierra 10.13.4, default ruby install, bundler installed with `sudo gem install bundler`.

-----------

When running `bundle install` on a project, I correctly get prompted for sudo credentials. Then I get an error like this:

```
Fetching rspec-core 3.7.1
Installing rspec-core 3.7.1
Gem::FilePermissionError: You don't have write permissions for the
/var/folders/dl/n48gsdsadsd137spc0000gn/T/bundler20180525-69405-1rsaznkrspec-core-3.7.1/bin directory.
An error occurred while installing rspec-core (3.7.1), and Bundler cannot continue.
Make sure that `gem install rspec-core -v '3.7.1' --source 'https://rubygems.org/'` succeeds before bundling.
```

I looked into this futher, and found that the temporary directory is correctly created with my user as the owner, but the `bin` directory inside is owned by root.

I dug around in the code and established the reason why:
https://github.com/bundler/bundler/blob/197ef090950cc379c0c131564154d06fdd1b9a04/lib/bundler/source/rubygems.rb#L138-L147

The tempdir is created using `Bunder.tmp`, this works fine.
Then if rubygems is <2.7.5 the `bin` dir is created using `Bundler.mkdir_p`.
I presume this is because as of version 2.7.5 rubygems itself creates the bin dir if it doesn't exist already.

The problem occurs because mkdir_p tries to be helpful:
https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L376-L384
if `requires_sudo?` is true, the directory is always created with root ownership - which is not the desired behaviour in this case.

**Comment by segiddins** [comment] 2018-05-28 21:57
Can you see if @colby-swandale's PR in https://github.com/bundler/bundler/pull/6542 will fix this?

**Comment by glenjamin** [comment] 2018-05-29 06:40
Yep, that’ll do it!

**Comment by colby-swandale** [comment] 2018-05-30 09:14
Marking ss duplicate of #6535

**Closed by colby-swandale** 2018-05-30 09:14 UTC
