### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by luminousdot** [bundler/bundler#5208] opened 2016-11-26 16:56 UTC
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bin/bundle install`

- What did you expect to happen?

  I expected Bundler to... install

- What happened instead?

  Instead, what happened was...
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

Error details

    Errno::EACCES: Permission denied @ rb_sysopen - /home/vladimir/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions
      /usr/lib/ruby/2.3.0/fileutils.rb:1393:in `initialize'
      /usr/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
      /usr/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
      /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
      /usr/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
      /usr/lib/ruby/2.3.0/fileutils.rb:1360:in `copy'
      /usr/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
      /usr/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
      /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
      /usr/lib/ruby/2.3.0/fileutils.rb:530:in `rescue in block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:527:in `block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /var/lib/gems/2.3.0
  GEM_PATH  /var/lib/gems/2.3.0:/home/vladimir/.gem/ruby/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
  Git       2.7.4
--- TEMPLATE END ----------------------------------------------------------------

**Comment by colby-swandale** [comment] 2016-11-28 00:57
Check the permissions of `/home/vladimir/.bundle` and `/home/vladimir` to make sure that Bundler has permissions to write to that directory. 

Did you run bundler with `sudo` or as another user at any point?

**Comment by sfarheen** [comment] 2016-11-28 15:35
@colby-swandale ,

I am facing the same issue. I am new to Unix. Can you please tell me what I need to change in bundle file?

**Comment by colby-swandale** [comment] 2016-11-28 20:30
@sfarheen If you're getting an error similar to above, it means that Bundler doesn't have the required permissions for the given directory. Here is a quick resource on file permissions in unix: http://linuxcommand.org/lts0070.php which shows how to manipulate file permissions. Although it's probably easier to just delete the `.bundle` directory and start again.

**Comment by luminousdot** [comment] 2016-11-28 20:46
Hi Colby, thanks for answering. I did just that.  Deleted the .bundle directory and started again. sudo didn't work for some reason. I'm new to Rails, just started with learing. Maybe I did something.

**Comment by lynnco** [comment] 2016-12-01 08:01
(pre-written response)

Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) `Permission denied` issues. A suite of permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14. Until 1.14 releases, the team doesn't have the capacity to deal with, or deploy more fixes for, the quantity of permissions errors we receive.

I'm sorry you are experiencing issues and I hope you can get them resolved!!! Feel free to continue commenting on this issue in the meantime.

**Closed by lynnco** 2016-12-01 08:01 UTC
