### ISSUE TITLE
Incorrect message when changing bundler settings

### ISSUE THREAD

**Issue by katgironpe** [bundler/bundler#5174] opened 2016-11-15 08:46 UTC
![alt text](https://s12.postimg.org/8hwt60mlp/Screen_Shot_2016_11_15_at_4_43_37_PM.png "Incorrect message")

This is really odd:

```
kath@Katherines-MacBook-Air ~ $ bundle config --global jobs 7                                                                                                                          [2.3.1]
Your application has set jobs to "3". This will override the global value you are currently setting
```

When I check the config file, it is set to 7. But the message is incorrect.

**Comment by indirect** [comment] 2016-11-15 09:01
Thanks for reporting this! Can you also tell us the output from `bundle env`?

**Comment by katgironpe** [comment] 2016-11-15 09:29
@indirect Here it is:

```
    DEPENDENCIES
      byebug
      coffee-rails (~> 4.2)
      jbuilder (~> 2.5)
      jquery-rails
      listen (~> 3.0.5)
      pg (~> 0.18)
      puma (~> 3.0)
      rails (~> 5.0.0, >= 5.0.0.1)
      sass-rails (~> 5.0)
      spring
      spring-watcher-listen (~> 2.0.0)
      turbolinks (~> 5)
      tzinfo-data
      uglifier (>= 1.3.0)
      web-console

    BUNDLED WITH
       1.13.6
```

**Comment by indirect** [comment] 2016-11-15 18:43
@katgironpe thanks! unfortunately that's only the end. can you include the beginning, too?

**Comment by katgironpe** [comment] 2016-11-15 19:55
@indirect BTW, the message is entirely different on Ubuntu which is strange. I only get this odd message on Mac OS X.

**Comment by segiddins** [comment] 2016-11-19 03:58
Could you still please share the entire output of `bundle env`? Thanks!

**Comment by katgironpe** [comment] 2016-11-21 05:35
@segiddins Here it is.

```
Environment

    Bundler   1.13.6
    Rubygems  2.5.1
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    Git       2.10.2

Bundler settings

    jobs
      Set for the current user (/Users/kath/.bundle/config): "12"
    git.allow_insecure
      Set for the current user (/Users/kath/.bundle/config): "true"

Gemfile

    source 'https://rubygems.org'


    gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
    gem 'devise', github: 'plataformatec/devise'
    gem 'ffaker'
    gem 'friendly_id', '~> 5.1.0'
    gem 'pg', '~> 0.18'
    gem 'puma', '~> 3.0'
    gem 'responders', '2.3.0'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.2'

    gem 'jquery-rails'
    gem 'turbolinks', '~> 5'
    gem 'jbuilder', '~> 2.5'

    group :development, :test do
      gem 'awesome_print'
      gem 'byebug', platform: :mri
    end

    group :development do
      gem 'better_errors'
      gem 'web-console'
      gem 'listen', '~> 3.0.5'
      gem 'spring'
      gem 'spring-watcher-listen', '~> 2.0.0'
    end

    group :test do
      gem 'capybara'
      gem 'database_cleaner'
      gem 'email_spec'
      gem 'factory_girl_rails', '~> 4.7.0'
      gem 'launchy'
      gem 'rails-controller-testing'
      gem 'rspec-rails', '~> 3.6.0.beta1'
      gem 'selenium-webdriver'
      gem 'shoulda-matchers', require: false
    end

Gemfile.lock

    GIT
      remote: git://github.com/plataformatec/devise.git
      revision: d2ea28b3dbbf3e11dc9e800179fb89c53d61fc71
      specs:
        devise (4.2.0)
          bcrypt (~> 3.0)
          orm_adapter (~> 0.1)
          railties (>= 4.1.0, < 5.1)
          responders
          warden (~> 1.2.3)

    GEM
      remote: https://rubygems.org/
      specs:
        actioncable (5.0.0.1)
          actionpack (= 5.0.0.1)
          nio4r (~> 1.2)
          websocket-driver (~> 0.6.1)
        actionmailer (5.0.0.1)
          actionpack (= 5.0.0.1)
          actionview (= 5.0.0.1)
          activejob (= 5.0.0.1)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 2.0)
        actionpack (5.0.0.1)
          actionview (= 5.0.0.1)
          activesupport (= 5.0.0.1)
          rack (~> 2.0)
          rack-test (~> 0.6.3)
          rails-dom-testing (~> 2.0)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (5.0.0.1)
          activesupport (= 5.0.0.1)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 2.0)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        activejob (5.0.0.1)
          activesupport (= 5.0.0.1)
          globalid (>= 0.3.6)
        activemodel (5.0.0.1)
          activesupport (= 5.0.0.1)
        activerecord (5.0.0.1)
          activemodel (= 5.0.0.1)
          activesupport (= 5.0.0.1)
          arel (~> 7.0)
        activesupport (5.0.0.1)
          concurrent-ruby (~> 1.0, >= 1.0.2)
          i18n (~> 0.7)
          minitest (~> 5.1)
          tzinfo (~> 1.1)
        addressable (2.5.0)
          public_suffix (~> 2.0, >= 2.0.2)
        arel (7.1.4)
        awesome_print (1.7.0)
        bcrypt (3.1.11)
        better_errors (2.1.1)
          coderay (>= 1.0.0)
          erubis (>= 2.6.6)
          rack (>= 0.9.0)
        builder (3.2.2)
        byebug (9.0.6)
        capybara (2.10.1)
          addressable
          mime-types (>= 1.16)
          nokogiri (>= 1.3.3)
          rack (>= 1.0.0)
          rack-test (>= 0.5.4)
          xpath (~> 2.0)
        childprocess (0.5.9)
          ffi (~> 1.0, >= 1.0.11)
        coderay (1.1.1)
        coffee-rails (4.2.1)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.2.x)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.10.0)
        concurrent-ruby (1.0.2)
        database_cleaner (1.5.3)
        debug_inspector (0.0.2)
        diff-lcs (1.2.5)
        email_spec (2.1.0)
          htmlentities (~> 4.3.3)
          launchy (~> 2.1)
          mail (~> 2.6.3)
        erubis (2.7.0)
        execjs (2.7.0)
        factory_girl (4.7.0)
          activesupport (>= 3.0.0)
        factory_girl_rails (4.7.0)
          factory_girl (~> 4.7.0)
          railties (>= 3.0.0)
        ffaker (2.2.0)
        ffi (1.9.14)
        friendly_id (5.1.0)
          activerecord (>= 4.0.0)
        globalid (0.3.7)
          activesupport (>= 4.1.0)
        htmlentities (4.3.4)
        i18n (0.7.0)
        jbuilder (2.6.0)
          activesupport (>= 3.0.0, < 5.1)
          multi_json (~> 1.2)
        jquery-rails (4.2.1)
          rails-dom-testing (>= 1, < 3)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        launchy (2.4.3)
          addressable (~> 2.3)
        listen (3.0.8)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.4)
          mime-types (>= 1.16, < 4)
        method_source (0.8.2)
        mime-types (3.1)
          mime-types-data (~> 3.2015)
        mime-types-data (3.2016.0521)
        mini_portile2 (2.1.0)
        minitest (5.9.1)
        multi_json (1.12.1)
        nio4r (1.2.1)
        nokogiri (1.6.8.1)
          mini_portile2 (~> 2.1.0)
        orm_adapter (0.5.0)
        pg (0.19.0)
        public_suffix (2.0.4)
        puma (3.6.0)
        rack (2.0.1)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (5.0.0.1)
          actioncable (= 5.0.0.1)
          actionmailer (= 5.0.0.1)
          actionpack (= 5.0.0.1)
          actionview (= 5.0.0.1)
          activejob (= 5.0.0.1)
          activemodel (= 5.0.0.1)
          activerecord (= 5.0.0.1)
          activesupport (= 5.0.0.1)
          bundler (>= 1.3.0, < 2.0)
          railties (= 5.0.0.1)
          sprockets-rails (>= 2.0.0)
        rails-controller-testing (1.0.1)
          actionpack (~> 5.x)
          actionview (~> 5.x)
          activesupport (~> 5.x)
        rails-dom-testing (2.0.1)
          activesupport (>= 4.2.0, < 6.0)
          nokogiri (~> 1.6.0)
        rails-html-sanitizer (1.0.3)
          loofah (~> 2.0)
        railties (5.0.0.1)
          actionpack (= 5.0.0.1)
          activesupport (= 5.0.0.1)
          method_source
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (11.3.0)
        rb-fsevent (0.9.8)
        rb-inotify (0.9.7)
          ffi (>= 0.5.0)
        responders (2.3.0)
          railties (>= 4.2.0, < 5.1)
        rspec-core (3.6.0.beta1)
          rspec-support (= 3.6.0.beta1)
        rspec-expectations (3.6.0.beta1)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (= 3.6.0.beta1)
        rspec-mocks (3.6.0.beta1)
          diff-lcs (>= 1.2.0, < 2.0)
          rspec-support (= 3.6.0.beta1)
        rspec-rails (3.6.0.beta1)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          railties (>= 3.0)
          rspec-core (= 3.6.0.beta1)
          rspec-expectations (= 3.6.0.beta1)
          rspec-mocks (= 3.6.0.beta1)
          rspec-support (= 3.6.0.beta1)
        rspec-support (3.6.0.beta1)
        rubyzip (1.2.0)
        sass (3.4.22)
        sass-rails (5.0.6)
          railties (>= 4.0.0, < 6)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        selenium-webdriver (3.0.1)
          childprocess (~> 0.5)
          rubyzip (~> 1.0)
          websocket (~> 1.0)
        shoulda-matchers (3.1.1)
          activesupport (>= 4.0.0)
        spring (2.0.0)
          activesupport (>= 4.2)
        spring-watcher-listen (2.0.1)
          listen (>= 2.7, < 4.0)
          spring (>= 1.2, < 3.0)
        sprockets (3.7.0)
          concurrent-ruby (~> 1.0)
          rack (> 1, < 3)
        sprockets-rails (3.2.0)
          actionpack (>= 4.0)
          activesupport (>= 4.0)
          sprockets (>= 3.0.0)
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.5)
        turbolinks (5.0.1)
          turbolinks-source (~> 5)
        turbolinks-source (5.0.0)
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (3.0.3)
          execjs (>= 0.3.0, < 3)
        warden (1.2.6)
          rack (>= 1.0)
        web-console (3.4.0)
          actionview (>= 5.0)
          activemodel (>= 5.0)
          debug_inspector
          railties (>= 5.0)
        websocket (1.2.3)
        websocket-driver (0.6.4)
          websocket-extensions (>= 0.1.0)
        websocket-extensions (0.1.2)
        xpath (2.0.0)
          nokogiri (~> 1.3)

    PLATFORMS
      ruby

    DEPENDENCIES
      awesome_print
      better_errors
      byebug
      capybara
      coffee-rails (~> 4.2)
      database_cleaner
      devise!
      email_spec
      factory_girl_rails (~> 4.7.0)
      ffaker
      friendly_id (~> 5.1.0)
      jbuilder (~> 2.5)
      jquery-rails
      launchy
      listen (~> 3.0.5)
      pg (~> 0.18)
      puma (~> 3.0)
      rails (~> 5.0.0, >= 5.0.0.1)
      rails-controller-testing
      responders (= 2.3.0)
      rspec-rails (~> 3.6.0.beta1)
      sass-rails (~> 5.0)
      selenium-webdriver
      shoulda-matchers
      spring
      spring-watcher-listen (~> 2.0.0)
      turbolinks (~> 5)
      uglifier (>= 1.3.0)
      web-console

    BUNDLED WITH
       1.13.6
```

**Comment by lynnco** [comment] 2016-12-01 08:14
@chrismo do you have any particular thoughts on have to resolve this, or are you still investigating?

**Comment by chrismo** [comment] 2016-12-19 05:24
Sorry I dropped the ball here - no I haven't been investigating. :-/

**Comment by lynnco** [comment] 2016-12-22 20:14
That's fine!

This issue is now available for anyone to pick up

**Comment by segiddins** [comment] 2017-01-15 01:52
I can't reproduce this issue locally

**Comment by Shekharrajak** [comment] 2017-02-02 12:06
I get this msg, : 
```
You are replacing the current global value of jobs, which is currently "7"
```

when I did `bundle config --global jobs 12`( after running `bundle config --global jobs 7`)

**Comment by katgironpe** [comment] 2017-02-02 13:48
Is it really just me? I still get a similar issue on MacOS Sierra. I use Rbenv. 

![Incorrect message](https://s24.postimg.org/49ql4ge0l/Screen_Shot_2017_02_03_at_12_44_28_AM.png)

Note: I have set this for the first time because I have a newly install MacOS Sierra. On Ubuntu, it's just fine. Very weird.

**Comment by segiddins** [comment] 2017-09-06 22:10
Closing because no one besides the original reporter could reproduce, but if someone runs into this again, and can reproduce it reliably, please open a new issue!

**Closed by segiddins** 2017-09-06 22:10 UTC
Labels: status: triage, type: bug report

**Comment by katgironpe** [comment] 2017-09-06 22:25
@segiddins The message is better now, and I could no longer reproduce this issue with the current stable version of bundler.

**Comment by segiddins** [comment] 2017-09-06 23:37
Cool, glad to hear!
