### ISSUE TITLE
Unexpected behaviour resolving rails 5.0.1 and paperclip 5.1.0

### ISSUE THREAD

**Issue by benpickles** [bundler/bundler#5493] opened 2017-03-03 12:17 UTC
With rails 5.0.1 and paperclip 5.1.0 installed locally if I do a `bundle install --local` everything is fine but with access to the network it can't resolve versions because of a conflict with activesupport 5.0.2 - which doesn't seem correct to me.

This is reproducible by performing the following:

```shell
gem install paperclip --version 5.1.0
gem install rails --version 5.0.1
rails _5.0.1_ new myapp --skip-action-cable --skip-action-mailer --skip-active-record --skip-bundle --skip-gemfile --skip-git --skip-javascript --skip-keeps --skip-listen --skip-puma --skip-spring --skip-sprockets --skip-test --skip-turbolinks
cd myapp
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'rails', '5.0.1'" >> Gemfile 
echo "gem 'paperclip', '5.1.0'" >> Gemfile 
bundle install --local
# ...snip...
bundle update paperclip
# Fetching gem metadata from https://rubygems.org/..........
# Fetching version metadata from https://rubygems.org/..
# Fetching dependency metadata from https://rubygems.org/.
# Resolving dependencies...
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    paperclip (= 5.1.0) was resolved to 5.1.0, which depends on
      activemodel (>= 4.2.0) was resolved to 5.0.2, which depends on
        activesupport (= 5.0.2)

    paperclip (= 5.1.0) was resolved to 5.1.0, which depends on
      activesupport (>= 4.2.0)

    rails (= 5.0.1) was resolved to 5.0.1, which depends on
      activesupport (= 5.0.1)
```

Here's the output from `bundle env`:

## Environment

```
Bundler   1.14.5
Rubygems  2.6.8
Ruby      2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
GEM_HOME  /Users/ben/.rvm/gems/ruby-2.4.0
GEM_PATH  /Users/ben/.rvm/gems/ruby-2.4.0:/Users/ben/.rvm/gems/ruby-2.4.0@global
RVM       1.27.0 (latest)
Git       2.12.0
Platform  x86_64-darwin-16
```

## Bundler settings

```
jobs
  Set for the current user (/Users/ben/.bundle/config): "4"
gem.coc
  Set for the current user (/Users/ben/.bundle/config): "false"
gem.mit
  Set for the current user (/Users/ben/.bundle/config): "false"
gem.test
  Set for the current user (/Users/ben/.bundle/config): "rspec"
build.libv8
  Set for the current user (/Users/ben/.bundle/config): "--with-system-v8"
build.therubyracer
  Set for the current user (/Users/ben/.bundle/config): "--with-system-v8"
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'rails', '5.0.1'
gem 'paperclip', '5.1.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.1)
      actionpack (= 5.0.1)
      nio4r (~> 1.2)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.1)
      actionpack (= 5.0.1)
      actionview (= 5.0.1)
      activejob (= 5.0.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.1)
      actionview (= 5.0.1)
      activesupport (= 5.0.1)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.1)
      activesupport (= 5.0.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (5.0.1)
      activesupport (= 5.0.1)
      globalid (>= 0.3.6)
    activemodel (5.0.1)
      activesupport (= 5.0.1)
    activerecord (5.0.1)
      activemodel (= 5.0.1)
      activesupport (= 5.0.1)
      arel (~> 7.0)
    activesupport (5.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.1.4)
    builder (3.2.3)
    climate_control (0.1.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    concurrent-ruby (1.0.5)
    erubis (2.7.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    i18n (0.8.1)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    nio4r (1.2.1)
    nokogiri (1.7.0.1)
      mini_portile2 (~> 2.1.0)
    paperclip (5.1.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (~> 0.3.0)
    rack (2.0.1)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.1)
      actioncable (= 5.0.1)
      actionmailer (= 5.0.1)
      actionpack (= 5.0.1)
      actionview (= 5.0.1)
      activejob (= 5.0.1)
      activemodel (= 5.0.1)
      activerecord (= 5.0.1)
      activesupport (= 5.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.2)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.0.1)
      actionpack (= 5.0.1)
      activesupport (= 5.0.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.4)
    thread_safe (0.3.6)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  paperclip (= 5.1.0)
  rails (= 5.0.1)

BUNDLED WITH
   1.14.5
```

**Comment by segiddins** [comment] 2017-03-08 20:02
I'm unable to reproduce this with Bundler 1.14.6

**Comment by segiddins** [comment] 2017-03-08 20:05
Yup, this was fixed by https://github.com/bundler/bundler/commit/a65e81d938e014fcb1c9176f24af4b5d0881b91e!

**Closed by segiddins** 2017-03-08 20:05 UTC
Labels: type: bug report

**Comment by benpickles** [comment] 2017-03-13 16:40
Brilliant, thanks :D
