### ISSUE TITLE
Bundler v1.10.0+ suppresses output from `gem` under `bundle exec`

### ISSUE THREAD

**Issue by fancyremarker** [bundler/bundler#3699] opened 2015-06-01 22:16 UTC
```
$ bundle -v
Bundler version 1.10.2
$ gem -v
2.0.14
$ bundle exec gem -v
(No ouptut)
$ 
```

This behavior was introduced in v1.10.0, and it breaks `bundle exec rake install`, since `rake install` [looks for a specific string in the output](https://github.com/bundler/bundler/blob/e41edd1/lib/bundler/gem_helper.rb#L87) of `gem install`.

**Comment by fancyremarker** [comment] 2015-06-01 22:39
This issue began with 3ac4215617aca867f33f1b4e46c29421001bb07a — I see how to fix the behavior I'm observing, but I'm wondering what the original intention of that commit was. Happy to submit a PR, but want to ensure that I'm not breaking anything.

**Comment by segiddins** [comment] 2015-06-01 23:06
ah, the issue here is probably that we're `exec`ing -- might want to reset that in `bundle exec`, right before we call `Kernel#exec`

**Comment by segiddins** [comment] 2015-06-02 03:55
I cannot reproduce this...

**Comment by segiddins** [comment] 2015-06-03 23:47
Should be fixed by https://github.com/bundler/bundler/pull/3707, which will be released soon.

**Closed by segiddins** 2015-06-03 23:47 UTC
Labels: bug

**Comment by fancyremarker** [comment] 2015-06-04 04:13
Thanks @segiddins! I've confirmed that #3707 fixes the issue I was seeing.
