### ISSUE TITLE
Gem resolution different in 1.16.0 (starting with pre 1)

### ISSUE THREAD

**Issue by chrisarcand** [bundler/bundler#6139] opened 2017-11-01 15:30 UTC
We started experiencing Travis build failures in a project suddenly (https://github.com/ManageIQ/manageiq-smartstate) and noticed that an ancient version of a gem we own (https://github.com/ManageIQ/azure-armrest) was now being installed unexpectedly. We also noticed that the newest version of Bundler (1.16.0) started being used on Travis, and discovered that this ancient version of our gem is installed using the first prerelease of 1.16.0 and on (and works fine on 1.15.4). 

I've included the two resulting lockfiles (note the BUNDLED WITHs) in [this gist](https://gist.github.com/chrisarcand/5f6fce99ce4158d55cf86510e2e5f943)

Note that `azure-armrest` has (or had) no version constraint as a dependency of `manageiq-smartstate`, and that adding a constraint (as should be done) seems to resolve properly. That's a fine solution to my problem, but I figured I'd open this anyway in case the fact that Bundler appears to be resolving things differently and pulling this extremely old dependency by default also seems a little concerning to the Bundler team :)

Here's the diff, for posterity in this issue:

```diff
diff --git a/Users/carcand/ss_good.txt b/Users/carcand/ss_bad.txt
index e635baa..154c466 100644
--- a/Users/carcand/ss_good.txt
+++ b/Users/carcand/ss_bad.txt
@@ -71,22 +71,20 @@ GEM
       i18n (~> 0.7)
       minitest (~> 5.1)
       tzinfo (~> 1.1)
-    addressable (2.4.0)
+    addressable (2.5.2)
+      public_suffix (>= 2.0.2, < 4.0)
     arel (8.0.0)
     ast (2.3.0)
     awesome_spawn (1.4.1)
-    azure-armrest (0.9.2)
-      activesupport (>= 4.2.2)
-      addressable (~> 2.4.0)
-      azure-signature (~> 0.2.3)
-      json (~> 2)
-      memoist (~> 0.15.0)
-      parallel (~> 1.12.0)
-      rest-client (~> 2.0.0)
-    azure-signature (0.2.3)
-      addressable
+    azure-armrest (0.0.3)
+      cache_method (~> 0.2.7)
+      json
+      rest-client
     binary_struct (2.1.0)
     builder (3.2.3)
+    cache (0.4.1)
+    cache_method (0.2.7)
+      cache (>= 0.2.1)
     camcorder (0.0.5)
     codeclimate-test-reporter (1.0.8)
       simplecov (<= 0.13)
@@ -131,7 +129,6 @@ GEM
     loofah (2.1.1)
       crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
-    memoist (0.15.0)
     memory_buffer (0.1.0)
     mime-types (3.1)
       mime-types-data (~> 3.2015)
@@ -272,4 +269,4 @@ DEPENDENCIES
   webmock (~> 2.3.1)
 
 BUNDLED WITH
-   1.15.4
+   1.16.0
```

## Environment

```
Bundler   1.16.0.pre.1
RubyGems  2.6.14
Ruby      2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
Git       2.14.1
Platform  x86_64-darwin-16
OpenSSL   OpenSSL 1.0.2l  25 May 2017
```

**Comment by greysteil** [comment] 2017-11-02 01:00
Thanks for the report @chrisarcand. Can you also include a copy of your `Gemfile`? It looks to me like Bundler 1.16.0 is prioritising the latest version of `adressable` over the latest version of `azure-armrest`, which isn't an unreasonable thing for it to do (despite the fact it's a change).

**Comment by chrisarcand** [comment] 2017-11-02 01:05
@greysteil 

https://github.com/ManageIQ/manageiq-smartstate/blob/f545c35aebfc56d3ecfb8b7dcd715a29672093b2/Gemfile

which uses also uses the gemspec:

https://github.com/ManageIQ/manageiq-smartstate/blob/f545c35aebfc56d3ecfb8b7dcd715a29672093b2/manageiq-smartstate.gemspec

**Comment by greysteil** [comment] 2017-11-02 09:33
Argh. OK, yeah, this is happening because your Gemfile imports the gemspec, so Bundler doesn't consider `azure-armrest` as explicitly required dependency (it's a sub-dependency of your gem). As a result the fix in #6128 doesn't apply, and the downgrade you're seeing is possible.

Thanks masses for the report. I *think* the behaviour Bundler's displaying here is fine, even though it's a little surprising. The setup it's installing is a valid one that doesn't have any pareto improvements, even though it includes downgrades. It's also worth noting that those downgrades, and this change in equilibrium, wouldn't happen in Bundler 2.0 (when released) since it will disallow downgrades by default.

I suggest we keep this issue open for a bit to see if similar stories are causing people problems, but close it in mid-November if not.

**Comment by MarioCarrion** [comment] 2017-11-02 14:17
We are experiencing a similar issue when running our tests (for our internal gem). It started to happen with `1.16.0`; it was working fine with `1.15.4`.

What we see is that after the `bundle install` and the `bundle exec`; the gem seems to be loaded twice because we get a bunch of waraning similar to _warning: already initialized constant_.

Sadly our code is proprietary, but I'll try to come up with something that exposes the same behavior.

**Comment by dlukman** [comment] 2017-11-02 14:27
Same issue here. Travis builds started failing since bundler `1.16.0` was introduced. The dependency resolution seems to be different. We are also have a Gemfile which imports gemspec. 

To be more specific, `1.15.4` installs `ffi-yajl 2.3.1`, whereas `1.16.0` tries to install `ffi-yajl 1.4.0` https://travis-ci.org/criteo/cookbook-release/builds/296266246

**Comment by nathanpalmer** [comment] 2017-11-06 17:49
We're running into a similar issue (I can't say if it's the same.) But our builds started failing as soon as 1.16.0 was released without any other changes to our code. We can now take a previous successful build, run it again and it fails.

For us it seems the problem is that we have several rails engines inside the app with their own Gemfiles. When you run a bundle install inside those directories it no longer picks up the local Gemfile but uses the main apps Gemfile. Because of this some of the gems aren't getting installed and the tests won't run.

Our solution so far is to make a completely custom Dockerfile build that targets the same ruby version but with a 1.15.4 as the bundler version.

**Comment by greysteil** [comment] 2017-11-06 18:53
@nathanpalmer - that sounds like a different issue (this one is about how the Gemfile is resolved, not which Gemfile is resolved). Can you create a separate issue for it, ideally with steps for us to reproduce?

**Comment by greysteil** [comment] 2017-11-07 10:58
@segiddins - how would you feel about turning on the `only_update_to_newer_versions` option for updates where all gems are unlocked? All of the issues are are from doing `bundle update` with no arguments, or doing `bundle install` with no `Gemfile.lock` present. We can't easily fix the later, but we can fix the former...

**Comment by segiddins** [comment] 2017-11-10 19:57
`only_update_to_newer_versions` is only enabled on 2.0 I believe? You should ask @indirect though, he's the one who wanted the feature

**Comment by indirect** [comment] 2017-11-11 00:23
@greysteil we definitely want to turn that on, but we have been avoiding it so far because of backwards compatibility 😬 it is slated to be on without an option to disable it starting in 2.0.0. are you suggesting that we might want to turn it on by default before 2.0? won't that be a breaking change?

**Comment by indirect** [comment] 2017-11-11 00:25
@sesam unfortunately bundler very frequently has to choose between upgrading one package and downgrading another or vice versa. without specific input from a user, there's no way for Bundler to know if the intention is to upgrade package X (at the cost of downgrading Y) or not upgrade X. Both options produce bug reports from angry users. :/

**Comment by sesam** [comment] 2017-11-11 02:45
@indirect thanks for your ideas. I saw downgrades of several major versions. Looked like jumping from highest possible to lowest possible. Feels buggy.
Possible defences?
- Resolver detects this, does a new attempt with the big-downgrade packages more prioritized to not be downgraded >1 major version. Maybe also avoid going from 1.x to 0.x, or jumping >1 year backwards.
- Or if current algo has a "linear response" to versions/age, make it non-linear to more strongly disincentivize resolver from bigger downgrades vs smaller downgrade jumps.

**Comment by indirect** [comment] 2017-11-11 05:05
@sesam understood, thanks for the feedback. In the meantime, you can work around this by setting a version constraint in your Gemfile, or by using the [pessimize](https://github.com/joonty/pessimize) gem to add version constraints to your gems automatically.

**Comment by colby-swandale** [comment] 2017-11-19 04:47
This looks answered

**Closed by colby-swandale** 2017-11-19 04:47 UTC
