### ISSUE TITLE
Installing Bundler using redmine instructions

### ISSUE THREAD

**Issue by ekulbyrnes** [bundler/bundler#5205] opened 2016-11-25 01:48 UTC
- What did you do?

  I ran the command `/usr/local/bin/bundler install --without development test postgresql sqlite`

(as instructed using these install process for Redmine: http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_25x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_and_Subversion)

- What did you expect to happen?

  I expected Bundler to...

Install correctly. Note that when the instruction is executed under SUDO, it recommends not doing so because it will affect non-root users.

- What happened instead?

  Instead, what happened was...

It failed.

"Unfortunately, an unexpected error occurred, and Bundler cannot continue."

Error details

    Errno::EACCES: Permission denied - (/tmp/bundler-compact-index-20161125-3026-18qn8w8/versions, /home/lbyrnes/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /usr/lib/ruby/1.9.1/fileutils.rb:519:in `rename'
      /usr/lib/ruby/1.9.1/fileutils.rb:519:in `block in mv'
      /usr/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
      /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
      /usr/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
      /usr/lib/ruby/1.9.1/fileutils.rb:508:in `mv'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:261:in `block (2 levels) in index'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `each'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:259:in `block in index'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:256:in `index'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:250:in `resolve'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/exe/bundler:4:in `load'
      /var/lib/gems/1.9.1/gems/bundler-1.13.6/exe/bundler:4:in `<top (required)>'
      /usr/local/bin/bundler:23:in `load'
      /usr/local/bin/bundler:23:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  1.8.23
  Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
  GEM_HOME  /var/lib/gems/1.9.1
  GEM_PATH  /var/lib/gems/1.9.1:/home/lbyrnes/.gem/ruby/1.9.1
  Git       1.9.1
      
      Bundler settings
      
  without
    Set for your local app (/usr/share/redmine/.bundle/config): "development:test:postgresql:sqlite"

**Comment by colby-swandale** [comment] 2016-11-25 02:46
Please review the permissions at `/home/lbyrnes/.bundle/` and make sure that Bundler and the user has permissions to write to that location. 

Did you run bundler as `root` or any other user at any stage?

**Comment by ekulbyrnes** [comment] 2016-11-25 03:48
thanks - must be an issue with install, that directory doesn't exist... will recheck if i've missed a step.

Yes, I did attempt to install as root a few times to see if that resolved the permissions issue, but to no avail.

**Comment by lynnco** [comment] 2016-12-01 07:57
(pre-written response)

Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?utf8=%E2%9C%93&q=Permission+denied&type=Issues) `Permission denied` issues. A suite of permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14. Until 1.14 releases, the team doesn't have the capacity to deal with, or deploy more fixes for, the quantity of permissions errors we receive.

I'm sorry you are experiencing issues and I hope you can get them resolved!!! Feel free to continue commenting on this issue in the meantime.

**Closed by lynnco** 2016-12-01 07:57 UTC
