### ISSUE TITLE
no implicit conversion of nil into String (fix patch)

### ISSUE THREAD

**Issue by e2** [bundler/bundler#3728] opened 2015-06-06 15:39 UTC
(NOTE: On Bundler 1.10.3, RubyGems 2.4.7, RVM, 'foobar' is nonexisting example)

While running something like this:

```
RUBYOPT=-rbundler/setup gem install -V --backtrace pkg/foobar-0.0.3.gem
```

I started getting this:

```
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=foobar
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=guard-compat,puppet
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=facter,hiera,json_pure
200 OK
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:21:in `exist?'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:21:in `present?'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:136:in `new'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:130:in `initialize'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:162:in `new'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:162:in `block in install'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `each'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `install'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:249:in `install_gem'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/home/me/.rvm/rubies/ruby-2.2.1/bin/gem:21:in `<main>'
```

It's because RubyGems is trying to download an installed gem (`guard-compat`) that wasn't detected as installed.

`guard-compat` is installed, but wasn't detected as installed (`#installed?`) ...

... basically because the following fails:

```ruby
require 'bundler'
Bundler::StubSpecification.new("foobar", "0.0.3", "ruby", nil) == Gem::Specification.new('foobar', '0.0.3')
#=> false
```

I'm not sure I can help reproduce the overall use case (thus the debugging).

**Comment by segiddins** [comment] 2015-06-06 15:58
This isn't a bug -- once you've done `-rbundler/setup`, you've given control over your gems in the current process to Bundler, and interacting with RubyGems in the same process isn't guaranteed to work.

**Comment by e2** [comment] 2015-06-06 19:27
@segiddins - what I'm actually running is `bundle exec rake install` - the `RUBYOPT= (...)` is just a more minimalistic way to reproduce the exact same issue.

I'm not doing any magic, just running `bundle exec rake install` and getting this error.

**Comment by ff-rboutotte** [comment] 2015-06-13 03:33
I too get this error all the time, and have gotten it on many versions of bundler. My use case is that I have a rake file with build tasks that run tests on my gem, then at the very end if all passed I run system("gem uninstall mygem") and system ("gem install .pkg/mygem-*.gem"). I've tried every varient I could think of trying to uninstall/install a gem from within a rake file and struggle to get it to work. Occasionally I get a combo that works, but then breaks. Even more odd if I run 'gem list mygem' before/after it always shows as existing. Here is the output:

mygem 22.0.0.0 built to pkg/mygem-22.0.0.0.gem.
Uninstalling existing mygem gem...
ERROR:  While executing gem ... (Gem::InstallError)
    gem "mygem" is not installed
Installing updated mygem gem...
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

**Comment by ff-rboutotte** [comment] 2015-06-13 03:38
So if I prepend my command with 'RUBYOPT= ' then this all works now within a rake file. Perhaps I have finally found a solution.

**Comment by notwilson** [comment] 2015-06-18 21:38
I'm also getting this error starting from Bundler 1.10.0. It occurs when I do 'bundle exec gem install gemfile.' I found that if I exclude 'mechanize' and 'ruby-progressbar' gems from runtime_dependency in my gemspec file, everything works. There is no issue with the versions prior to v1.10.0 (ie. <= v1.9.9).

**Comment by segiddins** [comment] 2015-06-18 21:48
@notwilson could you please share a script that reproduces the issue so we can investigate? Thanks!

**Comment by notwilson** [comment] 2015-06-18 22:10
Sure, @segiddins. Simply create a gemspec file, for instance, "hello.gemspec" as follows: 

````
spec = Gem::Specification.new do |s|
  s.name = "notwilson"
  s.version = "0.0.1"
  s.summary = "Sample Gem"
  s.description = %{Just a sample gem}
	s.license = "GPL-2"
  s.authors = "notwilson"
  s.email = "notwilson@xxxxx.com"
  s.homepage = "http://github.com"
  s.add_runtime_dependency 'mechanize', '~> 2.7.3', '>= 2.7.3'
  s.add_runtime_dependency 'ruby-progressbar', '~> 1.7.5', '>= 1.7.5'
end
````
Then run `gem build hello.gemspec`:

````
# gem build hello.gemspec
  Successfully built RubyGem
  Name: hello
  Version: 0.0.1
  File: hello-0.0.1.gem
````
At this point, if you do `gem install hello-0.0.1.gem`, it would work fine.

````
# gem install hello-0.0.1.gem
Successfully installed hello-0.0.1
1 gem installed
````

However, if you tried to do `bundle exec gem install hello-0.0.1.gem`, it will spits out the error:

````
# bundle exec gem install hello-0.0.1.gem --backtrace
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:21:in `exist?'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:21:in `present?'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:136:in `new'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:130:in `initialize'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:162:in `new'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:162:in `block in install'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `each'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `install'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:249:in `install_gem'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
	/Users/wilson/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
	/Users/wilson/.rbenv/versions/2.2.2/bin/gem:21:in `<main>'
````

Reverting to Bundler v1.9.9 works fine.

````
# gem uninstall bundler
Successfully uninstalled bundler-1.10.4
# gem install bundler -v 1.9.9
Fetching: bundler-1.9.9.gem (100%)
Successfully installed bundler-1.9.9
1 gem installed
# bundle exec gem install hello-0.0.1.gem
Successfully installed hello-0.0.1
1 gem installed
````

**Comment by segiddins** [comment] 2015-06-18 22:11
Right, but I don't see how `bundle exec gem install`even makes sense?

**Comment by indirect** [comment] 2015-06-18 22:17
It's sometimes convenient to use bundle exec gem to manipulate installed gems, especially for the pristine command. It also means that something in Bundler's rubygems compatibility layer is broken, and we need to fix the regression.

**Comment by notwilson** [comment] 2015-06-18 22:18
I originally have a Rakefile whose 'install' task does a gem install.

````
desc 'Builds and installs the gem'
task :install => :build do
  sh "gem install hello.gem"
end
````

When doing a `rake install`, the issue pops out.

**Comment by comutt** [comment] 2015-06-20 17:55
I've just been stuck in this problem and thanks @notwilson your procedure solved it.

@segiddins 
> Right, but I don't see how bundle exec gem installeven makes sense?

I'm using Redmine with bundler and unicorn-rails.
Redmine's Gemfile does not provide unicorn, so I need to install unicon-rails with `bundle exec gem install unicorn-rails`, because I do not want to install unicorn-rails not to system-wide but .bundle.
Also Gemfile is provided under version-control, so it's not good idea to modify Gemfile.

**Comment by comutt** [comment] 2015-06-20 18:01
Oops sorry, I've just identified that I've been forgotten that I need add unicorn to Gemfile to run unicorn by `bundle exec`.
My previous comment is just a garbage, sorry...

**Comment by notwilson** [comment] 2015-07-02 16:51
My issue has been resolved in Bundler v1.10.5. Thank you.

**Closed** 2015-07-02 17:07 UTC

**Comment by alishantesch** [comment] 2016-07-07 19:25
I can't reinstall bundler too. Same error!

**Comment by indirect** [comment] 2016-07-07 19:45
@alishantesch this issue is fixed and closed. If you're having a new issue, please see [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md).
