### ISSUE TITLE
Permission denied @ rb_file_s_rename - (/tmp/bundler-compact-index-20161029-13674-1fo83pg/versions,~/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)

### ISSUE THREAD

**Issue by alekzxd** [bundler/bundler#5137] opened 2016-10-29 18:25 UTC
I'm following "Deploying web application with Heroku" Udaicty's course and at Setting up database lesson I need to run `bundle install` command, but when I did it this error did appear at terminal.

Error details

    Errno::EACCES: Permission denied @ rb_file_s_rename - (/tmp/bundler-compact-index-20161029-13674-1fo83pg/versions, /home/alxu/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions)
      /usr/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
      /usr/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
      /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
      /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
      /usr/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:55:in `block in update'
      /usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:65:in `update'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:56:in `update_and_parse_checksums!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:67:in `available?'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `call'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/fetcher.rb:157:in `use_api'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `block in api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `select'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:332:in `api_fetchers'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:337:in `block in remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/index.rb:10:in `build'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:336:in `remote_specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/source/rubygems.rb:83:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/lazy_specification.rb:61:in `__materialize__'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:91:in `block in materialize'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `map!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:88:in `materialize'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/definition.rb:162:in `resolve_remotely!'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:225:in `resolve_if_need'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:78:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/installer.rb:24:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/install.rb:71:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:189:in `install'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
      /var/lib/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

Environment
      
  Bundler   1.13.6
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
  GEM_HOME  /var/lib/gems/2.3.0
  GEM_PATH  /var/lib/gems/2.3.0:~/.gem/ruby/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
  Git       2.7.4

**Comment by lynnco** [comment] 2016-10-30 22:27
Closing as a duplicate of [the other](https://github.com/bundler/bundler/search?q=Permission+denied+%40+dir_s_mkdir&type=Issues&utf8=%E2%9C%93) `Permission denied @ dir_s_mkdir` issues. Permission errors have been addressed by https://github.com/bundler/bundler/pull/5007 which will release in Bundler 1.14

**Closed by lynnco** 2016-10-30 22:27 UTC

**Comment by Craig1f** [comment] 2017-03-15 17:19
I'm still having this problem on Bundler 1.14.6. My issue is consistent with this post in that the issue happens in /tmp/bundler-compact-index-***, and not in the other directories referenced by other people having permissions issues.
