### ISSUE TITLE
Bundler swallong `LoadError`?

### ISSUE THREAD

**Issue by alexaltair** [bundler/bundler#4910] opened 2016-08-24 01:02 UTC
I have a gem named `something-like-this`. During the loading process in a rails app, [this line](https://github.com/bundler/bundler/blob/c1e168d/lib/bundler/runtime.rb#L104) turns it into `something/like/this`. It's actually located at `something/like_this`, so the next line raises again. Then the `LoadError` gets rescued again. But then the guard clause on [this line](https://github.com/bundler/bundler/blob/c1e168d/lib/bundler/runtime.rb#L108), evades the reraise, and then the error is silently swallowed. Bundler continues with loading the next gem.

Is this the intended behavior? Am I doing something else wrong? (Other than not naming the gem `something-like_this`.)

**Comment by segiddins** [comment] 2016-08-24 05:26
I'll take a look at the particulars in the morning, but a quick fix would be to change your gemfile to include `gem "something-like-this", require: "something/like_this"`

**Comment by alexaltair** [comment] 2016-09-01 20:15
@segiddins Ping on this.

**Comment by segiddins** [comment] 2016-09-06 16:24
Do you have a gemfile we can use to reproduce the issue? That would help in creating a test case. Thanks!

**Comment by segiddins** [comment] 2016-09-06 16:29
Actually, bundler swallowing the error is the intended behavior unless you manually specify `require: {true,name}` in your Gemfile

**Comment by segiddins** [comment] 2016-09-21 15:51
@indirect can we close this as "behaves as intended"?

**Comment by segiddins** [comment] 2017-01-15 00:59
Closing as behaves as intended.

**Closed by segiddins** 2017-01-15 00:59 UTC
