### ISSUE TITLE
Rubinius bundler problem

### ISSUE THREAD

**Issue by Ybrin** [bundler/bundler#5115] opened 2016-10-23 15:59 UTC
- What did you do?
  
  I ran the command `bundle install` after installing the latest rubinius (rbx-3.60)
- What did you expect to happen?
  
  I expected Bundler to install my gems
- What happened instead?
  
  Instead, I saw this error report. Nothing at all happened and not a single gem was installed.

Error details

```
Rubinius::ObjectBoundsExceededError: Tuple::copy_from: index 14 out of bounds for size 13
  core/hash.rb:216:in `insert'
  core/hash.rb:411:in `[]='
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:229:in `add'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/rubysl-set-2.0.1/lib/rubysl/set/set.rb:240:in `add?'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:73:in `update_info'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:44:in `dependencies'
  core/proc.rb:20:in `call'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/fetcher/compact_index.rb:86:in `compact_index_client'
  core/proc.rb:20:in `call'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:65:in `apply_func'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:60:in `process_queue'
  core/kernel.rb:585:in `loop'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:57:in `process_queue'
  /Users/koray/.rbenv/versions/rbx-3.60/gems/gems/bundler-1.13.6/lib/bundler/worker.rb:29:in `initialize'
  core/proc.rb:20:in `call'
```

Environment

  Bundler   1.13.6
  Rubygems  2.6.6
  Ruby      2.3.1p0 (2016-09-21 revision 0) [x86_64-darwin16.0.0]
  GEM_HOME  /Users/koray/.rbenv/versions/rbx-3.60/gems
  GEM_PATH  /Users/koray/.rbenv/versions/rbx-3.60/gems:/Users/koray/.gem/rbx/2.3
  Git       2.8.4 (Apple Git-73)

**Comment by segiddins** [comment] 2016-10-23 17:32
I'm not sure how `add?` is causing an `ObjectBoundsExceededError`, so my first guess might be that this is an issue with the `Set` implementation in rbx?

**Comment by abnud1** [comment] 2016-11-04 14:36
I had this problem too, but after I installed rubysl-set gem(via `rbx -S gem install rubysl-set`) the problem disappeared , I got `NoMethodError '>' for nil:NilClass` but the fether retried and succeeded.  

I think that bundler assumes the ruby standard library to be available where rubinius factored out some of it into external gems.  

The solution to this in my opinion is to add the missing parts of the standard library in bundler's gemspec only for platform rubinius.

**Comment by segiddins** [comment] 2016-11-19 04:12
Bundler can't have gem dependencies, and I feel that assuming the standard library is available isn't unreasonable?

**Comment by abnud1** [comment] 2016-11-19 18:38
@segiddins  hmmm I'm not sure but I don't think there is any problem with Bundler having dependencies (it's a gem after all) .  

The availability of standard library is for sure reasonable and this is a somewhat unfortunate fact about rubinius :)

**Comment by segiddins** [comment] 2016-11-28 19:19
This is a duplicate of https://github.com/bundler/bundler/issues/5142, which will be fixed by https://github.com/bundler/bundler/pull/5213

**Closed by segiddins** 2016-11-28 19:19 UTC
Labels: platform: rubinius, status: triage
