### ISSUE TITLE
Add an error message about pre-release dependencies

### ISSUE THREAD

**Issue by lynncyrin** [bundler/bundler#4657] opened 2016-06-09 08:57 UTC
From https://github.com/bundler/bundler/issues/4340, https://github.com/bundler/bundler/issues/2938, https://github.com/bundler/bundler/issues/4337

It would help reduce user confusion if the error message generated in that case explicitly stated that pre-release dependencies need to be explicitly listed in the gemfile

**Comment by segiddins** [comment] 2016-06-09 15:42
Checkin whether the conflicting gem has pre-release versions that satisfy all dependencies when rescuing the `VersionConflict` should be sufficient for this

**Comment by b-ggs** [comment] 2016-06-25 17:01
Working on this.

**Comment by b-ggs** [comment] 2016-06-29 05:45
@segiddins Could you perhaps explain further what you mean by `Checkin whether the conflicting gem has pre-release versions that satisfy all dependencies`

I've managed to reproduce the issue and rescue the `VersionConflict` exception from one of the cases in the issues linked above. Still not clear to me what to do moving forward though.

**Comment by greysteil** [comment] 2017-09-15 19:32
This should be fixed / unnecessary now - https://github.com/bundler/bundler/pull/6014 ensures we get the right behaviour for pre-releases.

**Comment by GBH** [comment] 2018-02-08 22:11
So I just wasted few hours because Bundler was doing dumb stuff. Discovered that was because one dependency has its own dependency on a pre-release gem. I had to define that dependency in my own Gemfile to `bundle install` successfully. Error message produced by bundler was completely useless of course. It was rails 5.2.0.rc1 btw.

Is there a reason why bundler won't fetch pre-release dependencies like that when they are defined in gemspecs?

I'm not even sure that's even an issue as it seems to work fine until I forced version on one of the gems. See: https://github.com/rails/rails-controller-testing/issues/37 Very confusing.

**Comment by colby-swandale** [comment] 2018-02-08 22:36
@GBH You're attitude in your comment is coming off as very rude and unfair to everyone that works on something you literally get for free. We have a [Code of Conduct](https://github.com/bundler/bundler/blob/master/CODE_OF_CONDUCT.md) that applies to everyone participating in the Bundler repository and i recommend you review it before commenting here again. You've been warned.

**Comment by GBH** [comment] 2018-02-08 22:57
@colby-swandale Sorry, didn't mean to come off rude, just frustrated. Edited. Cheers.

**Comment by greysteil** [comment] 2018-02-09 01:31
I’m on holiday without much internet for the next few days, but if you post a copy of a `Gemfile` and `Gemfile.lock` that’s failing to resolve as expected I’ll take a look into it when I’m back.

#6014 should have fixed this, so I’m a little confused.

**Comment by GBH** [comment] 2018-02-09 01:53
@greysteil I can do even better. 

Here's repo state when `bundle install` wont work: https://github.com/comfy/comfy-blog/tree/0ea3307e3fa86dd68edd8b8b62208c2e26a71c3c 

Following commit added `gem "rails", "~> 5.2.0.rc1"` to Gemfile that got everything working. 

Issue seems to be with:

- A depends on B 
- B depends on C.rc1

Yet this got triggered by a gem that seems to be unrelated. Here's the error in full:

```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails-controller-testing (~> 1.0.2) was resolved to 1.0.2, which depends on
      actionpack (>= 5.0.1, ~> 5.x)

    web-console (~> 3.5.1) was resolved to 3.5.1, which depends on
      railties (>= 5.0) was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0)

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    rails-controller-testing (~> 1.0.2) was resolved to 1.0.2, which depends on
      actionpack (>= 5.0.1, ~> 5.x) was resolved to 5.0.1, which depends on
        activesupport (= 5.0.1)

    web-console (~> 3.5.1) was resolved to 3.5.1, which depends on
      activemodel (>= 5.0) was resolved to 5.0.2, which depends on
        activesupport (= 5.0.2)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    web-console (~> 3.5.1) was resolved to 3.5.1, which depends on
      railties (>= 5.0)

Could not find gem 'railties (>= 5.0)', which is required by gem 'web-console (~> 3.5.1)', in any of the sources.
```

**Comment by greysteil** [comment] 2018-03-18 19:37
Sorry for taking so long to come back on this. I couldn't replicate it when I tried a couple of weeks ago and have just tried again and still can't - checking out https://github.com/comfy/comfy-blog/commit/95f3e677c62db1444a0ed4e0f574ab887c99daae I'm getting resolution after a couple of seconds. I'm on Bundler 1.16.1, Ruby 2.5.0, and Rubygems 2.7.6 - @GBH can you try updating Rubygems and let me know if the problem persists?

**Comment by deivid-rodriguez** [comment] 2019-11-11 20:27
@GBH Ping

**Comment by GBH** [comment] 2019-11-12 17:22
I won't be able to replicate error I got 1.5 years ago. Feel free to close 🤷‍♂

**Comment by deivid-rodriguez** [comment] 2019-11-12 18:12
It sounds like this got fixed, just wanted to check with you just in case. Thanks.

**Closed by deivid-rodriguez** 2019-11-12 18:12 UTC
Labels: status: user feedback required, type: feature-request
