### ISSUE TITLE
Double exec failure under weird circumstances

### ISSUE THREAD

**Issue by coderanger** [bundler/bundler#4402] opened 2016-03-26 23:20 UTC
With latest RubyGems (2.6.2) and Bundler (1.11.2) and installing with `bundle install --path`, you can't use `bundle exec` inside itself.

My minimal repro case:

```
$ docker run -it ubuntu:15.10 bash
# apt-get install -y ruby
# gem update --system
# gem install bundler
# cd /tmp
# echo "source 'https://rubygems.org/'" >Gemfile
# bundle install --path=vendor
# bundle exec bundle exec ruby --version
/usr/local/bin/bundle:22:in `load': cannot load such file -- /var/lib/gems/2.1.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)
    from /usr/local/bin/bundle:22:in `<main>'
```

Using anything other than the latest RubyGems or Bundler seems to not trigger it, and ditto leaving off the `--path`. The repeated `gems/bundler-1.11.2` ending up in the path is probably the issue in the end, but I'm having trouble figuring out what is causing that.

**Comment by coderanger** [comment] 2016-03-26 23:37
I get a different error on Bundler 1.12.0.rc (after adding `gem 'bundler'` to the Gemfile to be safe):

```
root@ee54eb8eddd5:/tmp# bundle exec bundle exec ruby --version
bundler: failed to load command: bundle (/usr/local/bin/bundle)
Gem::Exception: can't find executable bundle
  /var/lib/gems/2.1.0/gems/bundler-1.12.0.rc/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path'
  /usr/local/lib/site_ruby/2.1.0/rubygems.rb:278:in `activate_bin_path'
  /usr/local/bin/bundle:22:in `<top (required)>'
```

**Comment by indirect** [comment] 2016-03-26 23:43
I think this is related to the RubyGems binstub issue that @segiddins is currently looking into.

**Comment by coderanger** [comment] 2016-03-26 23:44
:+1: as an addendum I think I was wrong about the version of Bundler mattering, it happens all the way back to 1.5 so just related to the RubyGems version and `--path`.

**Comment by coderanger** [comment] 2016-03-26 23:50
And I can confirm that it works fine with RubyGems 2.6.1 and before.

**Comment by sosedoff** [comment] 2016-03-28 18:24
Just hit the same issue and can confirm that downgrading to rubygems 2.6.1 fixed the issue.
```gem update --system 2.6.1```

**Comment by segiddins** [comment] 2016-03-28 19:10
This ought to be fixed with RubyGems master?

**Comment by razor-x** [comment] 2016-04-04 19:45
Just ran into this issue with a wercker build that was passing and then started failing because of this. The docker image pointed at `ruby:2.2.4` across both builds.

Last passing build:

```
Pulling from library/ruby: 2.2.4
Digest: sha256:76e2edb051ed50edb03cdb84890dc7e8f22a8bd2303f07a80a8f8b6241129dac
Status: Image is up to date for ruby:2.2.4
```

First failing build:

```
Pulling from library/ruby: 2.2.4
Digest: sha256:069b0a70135f2bc676c089a88cef464c2f668f91ab7aacf5842c16327124b854
Status: Image is up to date for ruby:2.2.4
```

**Comment by radar** [comment] 2016-04-16 07:49
Does anyone have the link to the Rubygems issue where this is discussed?

**Comment by segiddins** [comment] 2016-04-16 16:58
Can people please try with rubygems 2.6.3 and/or bundler 1.12.0.rc.2? Thanks!

**Comment by razor-x** [comment] 2016-04-16 17:04
@segiddins I was trying to get this to work by trying a few different combinations of ruby, rubygems, and bundler versions. I [ended up with](https://github.com/makenew/chef-cookbook/blob/f31702c945a7bbeda1b2f99d0dc2302b43fbe05e/wercker.yml) Ruby 2.3.0, rubygems 2.6.1, and bundler 1.12.0.rc.

**Comment by radar** [comment] 2016-04-16 21:44
@segiddins I am unable to install the capybara 2.7.0 gem. Here is my Gemfile: https://gist.github.com/radar/b07f0860695a22d1bcc825694670ad31. The error I get is simply:

```
Could not find capybara-2.7.0 in any of the sources
```

The command I'm running to get this error is:

```
bundle install --path vendor/bundle
```

If you'd like to see the app where I am seeing the error, checkout the `ci` branch of https://github.com/radar/twist. It's currently at radar/twist@9b13f3a8a5b6c5b07bffd707f0d30c0721f7467f.

**Comment by segiddins** [comment] 2016-04-16 21:53
@radar can you also try adding the `--full-index` flag? I think not finding capybara is a separate server-side error

**Comment by radar** [comment] 2016-04-17 04:45
@segiddins That looks like it fixed the problem. Still want me to test the `rc2` release with RubyGems 2.6.3?

**Comment by radar** [comment] 2016-04-17 05:00
I'm now seeing this error on RG 2.6.3 and that RC release of Bundler:

```
/var/lib/gems/2.3.0/gems/bundler-1.12.0.rc.2/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
	from /usr/local/bin/bundle:22:in `<main>'
```

Looks to be a variant of the original bug.

**Comment by razor-x** [comment] 2016-04-30 18:43
Can confirm this is still broken on Ruby 2.3.0, rubygems 2.6.4, and bundler 1.12.1 (for example: https://app.wercker.com/#buildstep/5724fbed742fcc85460e74bc).

**Comment by chulkilee** [comment] 2016-05-02 05:25
FYI I could avoid this problem from the official ruby image by installing bundler again.

See https://github.com/docker-library/ruby/issues/73#issuecomment-215095772

**Comment by tk8817** [comment] 2016-05-16 16:39
This problem sucks the big one. Thankful for this thread - I have also downgraded to 2.6.1 and am back up and running.

**Comment by tk8817** [comment] 2016-05-20 02:27
Does anyone have any info the ruby gems issue for this matter? I can not find anything in my own searches.

**Comment by chrismo** [comment] 2016-11-04 19:25
This does appear to be a duplicate of #4602. If anyone on this thread is still stuck by this problem, report in, and we'll take a look. I'm going to update some thoughts on #4602. If there's nothing unique/outstanding on this ticket, we should close this one.

I also feel like building a tool that will graphviz issue references :)

**Comment by janahue** [comment] 2016-11-21 22:41
@chrismo, this problem still affects me:

```
$ bundle exec foreman start
17:29:15 web.1  | started with pid 91692
17:29:15 web.1  | I, [2016-11-21T17:29:15.903974 #91692]  INFO -- : Refreshing Gem list
17:29:18 web.1  | bundler: failed to load command: unicorn (/Users/janahue/.gem/ruby/2.3.1/bin/unicorn)
17:29:18 web.1  | Gem::LoadError: Specified 'mysql' for database adapter, but the gem is not loaded. Add `gem 'mysql'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

$ cat Procfile
web: bundle exec unicorn -o "$HOST" -p "$PORT" -c ./config/unicorn.rb
```

I'm using:

- Bundler: 1.13.6
- Rubygems: 2.5.1
- Ruby: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
- GEM_HOME: /Users/janahue/.gem/ruby/2.3.1
- GEM_PATH: /Users/janahue/.gem/ruby/2.3.1:/opt/rubies/2.3.1/lib/ruby/gems/2.3.0
- Git: 2.9.0

**Comment by segiddins** [comment] 2016-11-21 23:10
@janahue please also share the output of `bundle env `

**Comment by janahue** [comment] 2016-11-22 16:56
@segiddins this is the output of `bundle env`. I'm not able to share all of the output from my `Gemfile` and `Gemfile.lock` due to the private nature of this repo. Are there specific pieces that would be helpful for debugging this?

```
Environment

    Bundler   1.13.6
    Rubygems  2.5.1
    Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    GEM_HOME  /Users/janahue/.gem/ruby/2.3.1
    GEM_PATH  /Users/janahue/.gem/ruby/2.3.1:/opt/rubies/2.3.1/lib/ruby/gems/2.3.0
    Git       2.9.0

Bundler settings

    jobs
      Set for your local app (/Users/janahue/src/github.com/Shopify/growth_tools/.bundle/config): "4"
    mirror.https://rubygems.org/
      Set for your local app (/Users/janahue/src/github.com/Shopify/growth_tools/.bundle/config): "https://gem-proxy.shopify.io"
    mirror.http://rubygems.org/
      Set for your local app (/Users/janahue/src/github.com/Shopify/growth_tools/.bundle/config): "https://gem-proxy.shopify.io"
    mirror.https://rubygems.org.fallback_timeout/
      Set for your local app (/Users/janahue/src/github.com/Shopify/growth_tools/.bundle/config): "1"
    mirror.http://rubygems.org.fallback_timeout/
      Set for your local app (/Users/janahue/src/github.com/Shopify/growth_tools/.bundle/config): "1"
```

**Comment by chrismo** [comment] 2016-11-22 17:12
Can you confirm `mysql` gem is in the Gemfile and Gemfile.lock?

**Comment by segiddins** [comment] 2016-11-22 18:11
@janahue reproducing the issue with a Gemfile you can share would be the best for us

**Comment by janahue** [comment] 2016-11-22 19:15
@chrismo Yeah, both reference the mysql gem:

`Gemfile` includes

```
group :development, :test do
  gem 'mysql'
```

`Gemfile.lock` includes

```
mysql (2.9.1)
```

**Comment by chrismo** [comment] 2016-12-19 05:20
@janahue if you get back to this, let's open a new issue. Could be related to the OP, but it's not an exact match AFAIK (doesn't appear to be due to nested bundle execs). Let me know if I can help in any other way.

**Closed by chrismo** 2016-12-19 05:20 UTC
Labels: status: user feedback required, type: bug report
