### ISSUE TITLE
Unexpected resolve failure

### ISSUE THREAD

**Issue by fcheung** [bundler/bundler#5494] opened 2017-03-03 15:27 UTC
I'm encountering some weird behaviour, which I can boil down to this shell script

```
echo "
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.4.0'
" > Gemfile

bundle

echo "
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.5.0'
" > Gemfile

bundle update rspec-rails
```

When I run, the first bundle succeeds, the update fails with

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        actionpack (= 3.2.6) was resolved to 3.2.6, which depends on
          rails-dom-testing (~> 2.0) was resolved to 2.0.2, which depends on
            activesupport (< 6.0, >= 4.2.0)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 5.0.2)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 5.0.2)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 3.2.6)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 3.2.6)

    rspec-rails (~> 3.5.0) was resolved to 3.5.2, which depends on
      activesupport (>= 3.0)
```

If I add `gem 'activesupport', '4.2.7.1'` to my Gemfile, then the bundle updates just fine.

If I change the dependency on rails to be on railties instead, then I don't get any errors. I also don't get any errors in 1.13.6 however  it is also happening to me in 1.13.6 with a more complicated gemfile - I came to the example above trying to reduce my problem to a minimal example

bundle env:

## Environment

```
Bundler   1.14.5
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
Git       2.10.2
Platform  x86_64-darwin-16
```

## Bundler settings

```
--jobs
  Set for the current user (/Users/fred/.bundle/config): "8"
build.eventmachine
  Set for the current user (/Users/fred/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
gem.test
  Set for the current user (/Users/fred/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/fred/.bundle/config): "true"
gem.coc
  Set for the current user (/Users/fred/.bundle/config): "false"
```

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.5.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7.1)
      actionview (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7.1)
      activesupport (= 4.2.7.1)
      globalid (>= 0.3.0)
    activemodel (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
    activerecord (4.2.7.1)
      activemodel (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      arel (~> 6.0)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.4)
    bcrypt (3.1.11)
    builder (3.2.3)
    concurrent-ruby (1.0.5)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.3)
    erubis (2.7.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    i18n (0.8.1)
    json (1.8.6)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    nokogiri (1.7.0.1)
      mini_portile2 (~> 2.1.0)
    orm_adapter (0.5.0)
    rack (1.6.5)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.7.1)
      actionpack (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    rspec-core (3.4.4)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.2)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.4)
    thread_safe (0.3.6)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    warden (1.2.7)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  devise (~> 3.5.0)
  rails (~> 4.2.7.1)
  rspec-rails (~> 3.4.0)

BUNDLED WITH
   1.14.5
```

**Comment by fcheung** [comment] 2017-03-03 16:04
oops, had the 'new issue' window open long enough that #5493 got created while i was writing this. #5457 also seems related, but the commit that closed that issue is in 1.14.5 already

**Comment by colby-swandale** [comment] 2017-03-03 23:08
@fcheung can you try `master` and let us know the results. Thanks!

**Comment by fcheung** [comment] 2017-03-06 10:34
Still failing with 1.14.6 (which i think is the same code as master), but a different set of error messages. It is now complaining about multiple gems, not just activesupport

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        actionpack (= 3.2.6) was resolved to 3.2.6, which depends on
          activesupport (= 5.0.1)

    rspec-rails (~> 3.5.0) was resolved to 3.5.2, which depends on
      actionpack (>= 3.0) was resolved to 3.2.6, which depends on
        rails-dom-testing (~> 2.0) was resolved to 2.0.2, which depends on
          activesupport (< 6.0, >= 4.2.0)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 3.2.6)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        activesupport (= 3.2.6)

    rspec-rails (~> 3.5.0) was resolved to 3.5.2, which depends on
      activesupport (>= 3.0)
Bundler could not find compatible versions for gem "minitest":
  In Gemfile:
    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 4.0.0, which depends on
        actionpack (= 4.0.0) was resolved to 4.0.0, which depends on
          activesupport (= 5.0.1) was resolved to 4.0.0, which depends on
            minitest (~> 5.1)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 4.0.0, which depends on
        activesupport (= 4.0.0) was resolved to 4.0.0, which depends on
          minitest (~> 4.2)
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.16, which depends on
        actionpack (= 3.2.16) was resolved to 3.2.16, which depends on
          rack (~> 1.4.5)

    rspec-rails (~> 3.5.0) was resolved to 3.5.2, which depends on
      actionpack (>= 3.0) was resolved to 3.2.16, which depends on
        rack (~> 2.0)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 3.2.16, which depends on
        actionpack (= 3.2.16) was resolved to 3.2.16, which depends on
          rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
            rack (>= 1.0)
Bundler could not find compatible versions for gem "tzinfo":
  In Gemfile:
    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 4.0.5, which depends on
        actionpack (= 4.0.5) was resolved to 4.0.5, which depends on
          activesupport (= 5.0.1) was resolved to 4.0.5, which depends on
            tzinfo (~> 1.1)

    devise (~> 3.5.0) was resolved to 3.5.10, which depends on
      railties (< 5, >= 3.2.6) was resolved to 4.0.5, which depends on
        activesupport (= 4.0.5) was resolved to 4.0.5, which depends on
          tzinfo (~> 0.3.37)
```

**Comment by colby-swandale** [comment] 2017-03-06 11:22
@segiddins

**Comment by fcheung** [comment] 2017-03-06 12:15
Some of that stuff in there looks really weird, e.g. 

```
railties (< 5, >= 3.2.6) was resolved to 3.2.6, which depends on
        actionpack (= 3.2.6) was resolved to 3.2.6, which depends on
          activesupport (= 5.0.1)
```

whereas the rails gems always have an exact version requirement for the other active/action-foo gems

**Comment by segiddins** [comment] 2017-03-06 17:36
Looks like a bug ¯\_(ツ)_/¯

**Comment by colby-swandale** [comment] 2017-03-10 02:53
I can't reproduce this on the latest release @fcheung

**Comment by fcheung** [comment] 2017-03-10 12:00
@colby-swandale with 1.14.6?

The bash script i put in the issue reliably reproduces the issue for me. It doesn't fail however if I change all the calls to bundler to be --local. I will try to reproduce from a clean environment

**Comment by segiddins** [comment] 2017-03-28 19:54
This is working on 1.14.6 for me as well

**Comment by fcheung** [comment] 2017-03-30 11:03
I still get exactly the same error.

I can also reproduce with this script
```
mkdir -p gems
export GEM_HOME=gems
export GEM_PATH=gems
gem install bundler
bundle config --local build.nokogiri --use-system-libraries
echo "
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.4.0'
" > Gemfile

bundle

echo "
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.5.0'
" > Gemfile

bundle update rspec-rails
```

which sets GEM_HOME/PATH to a clean folder just in case the list of installed gems was somehow relevant.

What other environmental details might be relevant?

## Environment

```
Bundler   1.14.6
Rubygems  2.5.2
Ruby      2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
GEM_HOME  gems
Git       2.10.2
Platform  x86_64-darwin-16
```

## Bundler settings

```
--jobs
  Set for the current user (/Users/fred/.bundle/config): "8"
build.eventmachine
  Set for the current user (/Users/fred/.bundle/config): "--with-cppflags=-I/usr/local/opt/openssl/include"
gem.test
  Set for the current user (/Users/fred/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/fred/.bundle/config): "true"
gem.coc
  Set for the current user (/Users/fred/.bundle/config): "false"
build.nokogiri
  Set for your local app (/Users/fred/repto2/.bundle/config): "--use-system-libraries"
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7.1'
gem 'devise', '~> 3.5.0'
gem 'rspec-rails', '~> 3.5.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7.1)
      actionview (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7.1)
      activesupport (= 4.2.7.1)
      globalid (>= 0.3.0)
    activemodel (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
    activerecord (4.2.7.1)
      activemodel (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      arel (~> 6.0)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.4)
    bcrypt (3.1.11)
    builder (3.2.3)
    concurrent-ruby (1.0.5)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.3)
    erubis (2.7.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    i18n (0.8.1)
    json (1.8.6)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.10.1)
    nokogiri (1.7.1)
      mini_portile2 (~> 2.1.0)
    orm_adapter (0.5.0)
    rack (1.6.5)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.7.1)
      actionpack (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    rspec-core (3.4.4)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-rails (3.4.2)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.4)
    thread_safe (0.3.6)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    warden (1.2.7)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  devise (~> 3.5.0)
  rails (~> 4.2.7.1)
  rspec-rails (~> 3.4.0)

BUNDLED WITH
   1.14.6
```

**Comment by segiddins** [comment] 2017-03-30 22:12
Thanks, that reproduced it! Turns out this is already fixed on master, and will be fixed in either `2.0` or `1.15`.

**Closed by segiddins** 2017-03-30 22:12 UTC
Labels: status: user feedback required, type: bug report

**Comment by magedmakled** [comment] 2017-12-22 06:15
I have `bundler (1.16.1, default: 1.16.0, 1.15.3)` and seems to have the same error

**Comment by segiddins** [comment] 2017-12-22 12:03
@magedmakled please open a new issue, thanks!
