### ISSUE TITLE
Bundle init failed when ancestor directory has Gemfile

### ISSUE THREAD

**Issue by kyoshidajp** [bundler/bundler#6205] opened 2017-12-08 11:32 UTC
# Steps to reproduce

```
% tree sample
sample
├── Gemfile
└── hoge
% cd sample/hoge
% bundle init
/Users/kyoshida/work/sample/Gemfile already exists at /Users/kyoshida/work/sample/Gemfile
```

# Expected behavior

Gemfile is generated in `hoge` directory.

Because [bundle init document](http://bundler.io/v1.16/man/bundle-init.1.html) says the following.

> bundle-init - Generates a Gemfile into the current working directory

I believe that current woking is the same as `$PWD`'s value.

However, the code is intentionally looking for ancestor directories.
1. https://github.com/bundler/bundler/blob/v1.16.0/lib/bundler/cli/init.rb#L40
1. https://github.com/bundler/bundler/blob/v1.16.0/lib/bundler/shared_helpers.rb#L240

This behavior is in the specifications?

# Version

Bundler version 1.16.0

**Comment by colby-swandale** [comment] 2017-12-09 01:12
Thanks for the report. I have a fix for this.

**Comment by kibitan** [comment] 2017-12-09 09:25
I also get same problem of this. @colby-swandale can you fix it soon? I searched the cause a bit, can i give a pull-request for it?

**Comment by segiddins** [comment] 2017-12-11 21:15
https://github.com/bundler/bundler/pull/6207 will fix this

**Comment by kibitan** [comment] 2017-12-11 21:22
super! thanks 😄

**Closed** 2017-12-12 00:04 UTC
Labels: type: bug report
